### ISSUE TITLE
NPM package does not include build files

### ISSUE THREAD

**Issue by felipeochoa** [dolanmiu/docx#1]
This package is exactly what I was looking for! Apologies that I'm about to file a handful of little issues.

If I `npm install` this package, I only get the typescript files. Not sure what your process is for releasing, for some reason the `build` directory is not included in the NPM package. Node complains of not finding `docx`

**Comment by felipeochoa** [comment]
Not sure if it's related, but here are the NPM warnings when running `npm install`:

```
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
npm WARN prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
```

**Comment by felipeochoa** [comment]
I think  `package.json` is missing a `"files"` section. Something like: `"files": ["ts", "build"],` (Incidentally, I think "lib" is a more common name for this)

**Comment by felipeochoa** [comment]
Also, I think to resolve the warnings you have to rename the "prepublish" to "prepublishOnly". [This](https://iamakulov.com/notes/all/npm-4-prepublish/) is a concise source describing the resolution to npm/npm#10074

**Comment by dolanmiu** [comment]
I am thinking whether or not prepublish is even nessesary

perhaps a `postinstall` is enough?

files, i agree should be needed though

and yes, not sure why I called is `ts`, `lib` or `src` (I prefer that), is maybe better
