### ISSUE TITLE
How to remove defaultTabStop from Word

### ISSUE THREAD

**Issue by ricardograna** [dolanmiu/docx#1022]
Hello, thanks for the great work with this package.

I am using Numbering, but the result is being affected by the defaultTabStop from Word and I couldn't find a way to remove it.

**Comment by dolanmiu** [comment]
I believe you can set your own tab stops like so:

https://docx.js.org/#/usage/tab-stops

**Comment by ricardograna** [comment]
Yes, I can. But Word has an attribute called Default Tab Stop that affects the Tab Stops. Even when I set Left Tab Stop to zero, Word uses the Default Tab Stop.

**Comment by ricardograna** [comment]
Does the package have a method to insert an extra xml to the result file? This actually would help

**Comment by dolanmiu** [comment]
Need to implement:

https://c-rex.net/samples/ooxml/e1/Part4/OOXML_P4_DOCX_defaultTabStop_topic_ID0EIXSX.html
