### ISSUE TITLE
Add API for specifying individual column widths/spacing

### ISSUE THREAD

**Issue by askoufis** [dolanmiu/docx#1030]
# Issue

Currently the API has a way to specify whether or not columns have an [equal width](https://github.com/dolanmiu/docx/blob/master/src/file/document/body/section-properties/properties/columns.ts#L37) or not. However, there is no way to specify the space after and width of the individual columns if you want them to be different widths.

Columns spec: http://officeopenxml.com/WPsectionCols.php

# Proposed API
To avoid a breaking change, an extension to the existing `column` section property seems like the best approach. I was thinking an optional field `columns` that takes a list of objects containing a `space` and `width`.

E.g.
```ts
const document = new Document({
  sections: [
    {
      properties: {
        column: {
          equalWidth: false,
          columns: [
            {
              width: 2835,
              space: 516,
            },
            {
              width: 5669,
            },
          ],
        },
      },
    },
  ],
});

```

I don't mind trying to implement this once a nice API is decided on.

**Comment by dolanmiu** [comment]
I like this approach yes, looks clean

Could you make a pull request? @askoufis
