### ISSUE TITLE
Cannot get ExpressPacker to work

### ISSUE THREAD

**Issue by kharmonycentral** [dolanmiu/docx#104]
Great tool so far and look forward to future progress! 

I have an AngularJS application where I am making a routing call to a server-side file which implements docx. When I use the LocalPacker(doc) approach, it works just fine. The file is created on the server and I can open it as expected. However when I try to use the ExpressPacker as implemented below, it does not work. No file download starts from the exporter.pack call and when I use the client side to open the res data passed, the file is corrupted although there does seem to be some data passed back which resembles a docx file. Here is my approach:

From the client:

```
$http({
  method: 'POST',
  url: '/guidance-generate',
  dataType: 'json',
  data: { data: data },
  headers: {
    'Content-Type': 'application/json'
  }
}).then(function(result){
  var file = new Blob([result.data], {type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'});
  let a = document.createElement("a");
  a.style = "display: none";
  document.body.appendChild(a);
  //Create a DOMString representing the blob
  //and point the link element towards it
  let url = window.URL.createObjectURL(file);
  a.href = url;
  a.download = 'EMS Guidance.docx';
  //programatically click the link to trigger the download
  a.click();
  //release the reference to the file by revoking the Object URL
  window.URL.revokeObjectURL(url);
},
function(error) {
  //error handler
  console.error("Error occured::",error);
});
```

Then the server-side file (/guidance-generate) creates the docx document object based on the data passed in (which is JSON)...again the document looks fine when using the LocalPacker. The server-side file:

```
const express = require('express');
const docx = require('docx');
//create the document as doc
var exporter = new docx.ExpressPacker(doc, res);
exporter.pack('new file');
```
No download starts after running the code. I have gone through the docx source code and see that the ExpressPacker puts the file into res.attachment but when it comes back to the client side (using Chrome debugger), I do not see an attachment element for the res object. There is data.data which resembles a docx jumble of text but when I open the downloaded file (resulting from the faux <a> link download) it says the file is corrupted both in LibreOffice and Word. 

Any guidance would be greatly appreciated. I am not getting any other errors that I know of. Thank you!

**Comment by dolanmiu** [comment]
Deprecated

ExpressPacker is gone. As of `4.0.0`, it exports to buffers, blobs and base64 strings!

It is up to you to pass the buffer to `res.attachment` in Express

It means it also works for sails and other similar frameworks other than Express.
