### ISSUE TITLE
alignment: AlignmentType.CENTER does not work

### ISSUE THREAD

**Issue by Julycc41** [dolanmiu/docx#1072]
I did a little test, and somehow this property doesn't seem to work, right  

 
![1627960244(1)](https://user-images.githubusercontent.com/80231740/127951650-3172d03c-197f-4705-8447-fd3bedc551a0.png)

![1627960346(1)](https://user-images.githubusercontent.com/80231740/127951774-f4128de1-29e4-4603-bfc3-96f3e1aa687f.png)

**Comment by dolanmiu** [comment]
I believe it is actually center, but its just that the table is `max width`?

Correct me if im wrong

**Comment by Julycc41** [comment]
> 我相信它实际上是中心，但它只是桌子`max width`？
> 
> 如果我错了纠正我

Thank you very much.  I put the properties into the render text and I got the effect I wanted
