### ISSUE TITLE
Restart numbering not working with lowerLetter

### ISSUE THREAD

**Issue by TheDarkStrix** [dolanmiu/docx#1077]
Code :  
``` javascript
  {
    levels: [
      {
        level: 2,
        format: LevelFormat.LOWER_LETTER,
        text: "%3)",
        alignment: AlignmentType.START,
        style: {
          paragraph: {
            indent: {
              left: convertInchesToTwip(0.5),
              hanging: convertInchesToTwip(0.18),
            },
          },
        },
      },
    ],
    reference: "optionsLowerCase",
  },
}
```
``` javascript
  new Paragraph({
              text: sanitizeData(question.choices[choice].text),
              numbering: {
                reference: "optionsLowerCase",
                level: 2,
                instance: 3,
              },
            })
```
The current Output : 
1. some random question
   a) option 1
   b) option 2
   c) option 3
   d) option 4

2. some other question
  e) option 5
  f) option 6
  g) option 7
  h) option 8

**Comment by anti-the-social** [comment]
@TheDarkStrix You might want to use numbering just like it ment to be used, see the following code.
Even the instance numbers aren't needed in this case.
```const fs = require('fs');
const { Document, Packer, Paragraph, PageNumberFormat} = require('docx');

const doc = new Document({
  numbering:{
    config:[{
      reference: 'ref1',
      levels: [
        {
          level: 0,
          format: PageNumberFormat.DECIMAL,
          text: '%1)'
        },
        {
          level: 1,
          format: PageNumberFormat.LOWER_LETTER,
          text: '%2)'
        }
      ],
    }]
  },
  sections: [{
    children: [
      new Paragraph({
        text: "some random question",
        numbering : {
          reference: 'ref1',
          level: 0,
        }
      }),
      new Paragraph({
        text: "option 1",
        numbering : {
          reference: 'ref1',
          level: 1,
        }
      }),
      new Paragraph({
        text: "option 2",
        numbering : {
          reference: 'ref1',
          level: 1,
        }
      }),
      new Paragraph({
        text: "option 3",
        numbering : {
          reference: 'ref1',
          level: 1,
        }
      }),
      new Paragraph({
        text: "Some other random question",
        numbering : {
          reference: 'ref1',
          level: 0,
        }
      }),
      new Paragraph({
        text: "option 1",
        numbering : {
          reference: 'ref1',
          level: 1,
        }
      }),
      new Paragraph({
        text: "option 2",
        numbering : {
          reference: 'ref1',
          level: 1,
        }
      }),
      new Paragraph({
        text: "option 2",
        numbering : {
          reference: 'ref1',
          level: 1,
        }
      }),
    ],
  }]
});

// Used to export the file into a .docx file
Packer.toBuffer(doc).then((buffer) => {
    fs.writeFileSync("restart_lowrer_case_numbering.docx", buffer);
});
```
![image](https://user-images.githubusercontent.com/69673750/128600400-6679822f-a3c5-4bf5-987f-1c223cf1e38f.png)

**Comment by shajji1** [comment]
I'm not getting this result in web js, here is my code, indentation is not working as expected.

`
<!DOCTYPE html>
<html>
<head>
    <script src="https://unpkg.com/docx@6.0.0/build/index.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.8/FileSaver.js"></script>
</head>
<body>
    <h1>DOCX browser Word document generation</h1>
    <button type="button" onclick="generate()">Click to generate document</button>
    <script>
        function generate() {
            const doc = new docx.Document({
                numbering:{
                    config:[{
                      reference: 'ref1',
                      levels: [
                        {
                          level: 0,
                          format: docx.PageNumberFormat.DECIMAL,
                          text: '%1)'
                        },
                        {
                          level: 1,
                          format: docx.PageNumberFormat.LOWER_LETTER,
                          text: '%2)'
                        }
                      ],
                    }]
                  },
                  sections: [{
                    children: [
                      new docx.Paragraph({
                        text: "some random question",
                        numbering : {
                          reference: 'ref1',
                          level: 0,
                        }
                      }),
                      new docx.Paragraph({
                        text: "option 1",
                        numbering : {
                          reference: 'ref1',
                          level: 1,
                        }
                      }),
                      new docx.Paragraph({
                        text: "option 2",
                        numbering : {
                          reference: 'ref1',
                          level: 1,
                        }
                      }),
                      new docx.Paragraph({
                        text: "option 3",
                        numbering : {
                          reference: 'ref1',
                          level: 1,
                        }
                      }),
                      new docx.Paragraph({
                        text: "Some other random question",
                        numbering : {
                          reference: 'ref1',
                          level: 0,
                        }
                      }),
                      new docx.Paragraph({
                        text: "option 1",
                        numbering : {
                          reference: 'ref1',
                          level: 1,
                        }
                      }),
                      new docx.Paragraph({
                        text: "option 2",
                        numbering : {
                          reference: 'ref1',
                          level: 1,
                        }
                      }),
                      new docx.Paragraph({
                        text: "option 2",
                        numbering : {
                          reference: 'ref1',
                          level: 1,
                        }
                      }),
                    ],
                  }]
            });
            docx.Packer.toBlob(doc).then(blob => {
                saveAs(blob, "example.docx");
            });
        }
    </script>
</body>
</html>
`

can anyone help ???
