### ISSUE TITLE
Inserting text in paragraph before page break

### ISSUE THREAD

**Issue by tarceaoana** [dolanmiu/docx#1078]
We are currently using paragraphs with keepNext enabled so that the label for a paragraph is always with some text from the paragraph, and if a paragraph needs to be split, we always leave at least 2 rows on the next page.

Now our question is: Can we somehow insert a text/label/comment/textRun something, before the page break, in case a paragraph is split? something like '(Text is continued on the next page)' or is there some way to detect where the page splits the paragraph without calculating the size of the page or something similar?

```

export const contentText = (text, first) =>
  new TextRun({
    ...(!first && { break: 1 }),
    font: 'IBM Plex Sans',
    color: '000000',
    text,
    size: 20,
  });

const paragraphSettings = (isValue, addTopBorder = false) => ({
  keepNext: true,
  shading,
  border: getBorder(isValue, addTopBorder),
  indent: {
    left: convertMillimetersToTwip(5),
    right: convertMillimetersToTwip(5),
  },
});

export const textField = ({ before, content, keepNext, addTopBorder }) => {
  const beforeChildren = getFormattedBefore(before);

  return [
    new Paragraph({
      ...paragraphSettings(false, addTopBorder),
      children: beforeChildren,
    }),
    new Paragraph({
      ...paragraphSettings(true),
      keepNext,
      children:
        content && content.map((line, idx) => contentText(line, idx === 0)),
    }),
  ];
};
```

**Comment by dolanmiu** [comment]
Did some research, I don't think its possible no. I don't even think its possible with Word. I have found a plugin called `FS Pro` which allows this feature in Word, it seems really cool:

https://www.youtube.com/watch?v=cUyHPqXnXOk

However it's costly: https://informationmapping.com/products/fs-pro-for-word

Essentially to have this feature, `docx` needs to copy this plugin
