### ISSUE TITLE
Express packer - ERR_HTTP_HEADERS_SENT

### ISSUE THREAD

**Issue by jamesthecat7** [dolanmiu/docx#108]
When using express packer to download the doc in the browser I get the following error: 

> Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

My code:

```
router.get('/docx/document.docx', function(req,res) {
	var doc = new docx.Document();
	var paragraph = new docx.Paragraph("Some cool text here.");
	paragraph.addRun(new docx.TextRun("Lorem Ipsum Foo Bar"));
	doc.addParagraph(paragraph);

	var exporter = new docx.ExpressPacker(doc, res);
	exporter.pack("My First Document"); 
});
```

**Comment by dolanmiu** [comment]
you are most likely calling res.end(), or using the res somewhere else after

**Comment by jamesthecat7** [comment]
Yeah I figure that I must be but the endpoint has no next argument, it is literally what I posted.

**Comment by dolanmiu** [comment]
Very odd,

refer to https://runkit.com/dolanmiu/docx-demo1

If you press `endpoint`, it will download the file. It is all in express

**Comment by dolanmiu** [comment]
Deprecated now

Express packer is no longer
