### ISSUE TITLE
Multiple text alignments on same line ?

### ISSUE THREAD

**Issue by missill** [dolanmiu/docx#1082]
Hi, it's possible to have two texts on same line with different alignments?
One on left and the other on right?
Thanks.

**Comment by anti-the-social** [comment]
Personally I don't think so, since one paragraph in Word can be aligned only to one side.
BUT one workaround is frame (https://docx.js.org/#/usage/text-frames?id=intro) It works very similar to images and text could float around that block.

**Comment by anti-the-social** [comment]
I should add, that frame aligning is currently a little bit broken see here: https://github.com/dolanmiu/docx/issues/933

**Comment by missill** [comment]
Thanks for response.

**Comment by CedYF** [comment]
Can we revisit this? it should be possible with tabs

**Comment by anti-the-social** [comment]
Hi @CedYF 

Very much depends on what is the use case. Yes, tabs might work for one line text. Nevertheless in many cases text is user-generated and length isn't known and right text (e.g. page numbering) should stay right-top at the footer. Spacing around page numbering also quite often required. To sum up, frames are much more flexible and usable in most of the cases. So if you start using that approach you might see less problems once your service grows. (like always, earlier or later someone would ask for these things...)

<img width="740" alt="image" src="https://user-images.githubusercontent.com/69673750/184077071-1476ed86-ae5f-4881-abde-8747ff4ca2c9.png">

<img width="740" alt="image" src="https://user-images.githubusercontent.com/69673750/184077142-fd9e2b0c-4637-4279-a160-c354819f37a3.png">

Also, Word itself uses frames when you insert page numbers via UI.
<img width="740" alt="image" src="https://user-images.githubusercontent.com/69673750/184078622-4053b179-4b31-4c6c-916d-f7894fe8a617.png">

**Comment by anti-the-social** [comment]
And if we are talking about just standard text on both sides I would've suggested table. It is more predictable and universal.
But that is all up to you ofc :)
