### ISSUE TITLE
add last footer option

### ISSUE THREAD

**Issue by tarceaoana** [dolanmiu/docx#1096]
i know that currently for a section we have default, first and even footers. ( and headers ) 
is it possible to add also an option for the last page footer? or is there a way to determine if you are on the last page and changing the content of the footer? 
adding a condition to check if       PageNumber.CURRENT != PageNumber.TOTAL_PAGES doesn't work . or can i make this check in a way that i can add a element there only if these 2 are different?

**Comment by dolanmiu** [comment]
I don't think this feature is in the OOXML spec, so it has to be done yourself manually unfortunately.

Correct me if im wrong. If it is part of the OOXML spec, then I guess this is a feature request

Thanks

**Comment by tarceaoana** [comment]
Or do you know of a way if i can inject somewhere something like this  '{IF {PAGE} < {NUMPAGES} "custom flow"}' somewhere in a footer, or in a wrapper?

http://www.addbalance.com/usersguide/fields.htm#last_page

**Comment by dolanmiu** [comment]
Closing as this isn't part of the OOXML spec
