### ISSUE TITLE
Downloading files using wechat to send ,  froms will be squeezed

### ISSUE THREAD

**Issue by chenpeizhen** [dolanmiu/docx#1099]
下载出来的文件，微信打开 new Table columnWidths  或  width 不起作用(使用办公软件打开，以及使用微信打开的效果）
![image](https://user-images.githubusercontent.com/56821026/129677734-55baf476-1fa5-4e34-9b14-c530bbd3e985.png)
****

![image](https://user-images.githubusercontent.com/56821026/129677891-f66d1346-4cea-43d3-8ff7-3c5711a25a3d.png)

**Comment by dolanmiu** [comment]
Try specifing a width for the table cells
