### ISSUE TITLE
Have anyone tried to map HTML (CKEditor to docx.js objects)? 

### ISSUE THREAD

**Issue by ninode97** [dolanmiu/docx#1100]
Hello. 

I have a ckeditor (Rich text) field  and I need to map it to the docx.js.

Any suggestions how could this be done?

Just wanted to ask maybe someone have done similar thing and can give some suggestions (maybe there is a prebuilt solutions). Any information would be appreciated on (**html to docxjs**).

**Comment by anti-the-social** [comment]
To my knowledge there isn't such a solution. You can build one :)

**Comment by Joshua-Flores** [comment]
By the way, for anyone looking for a solution to the above problem I tried doing the same and it's pretty involved to take dynamic html and build this. Another solution is to use [html-docx-js-typescript](https://www.npmjs.com/package/html-docx-js-typescript)
