### ISSUE TITLE
Mistake in "Table Row" docs

### ISSUE THREAD

**Issue by Morsey** [dolanmiu/docx#1101]
I think this is a quick fix in the docs, but I'm not experienced enough in github to know how to fix, or I might be misunderstanding.

In the docs, for Table Row we have an optional property for the row height:

{ **height**: number, rule: HeightRule }

should this be:

{ **value**: numbery, rule: HeightRule }

as that is what worked for me?

**Comment by dolanmiu** [comment]
In V7, it will be height going forward
