### ISSUE TITLE
Is there any way I can set background to document rather than mere color and tint?

### ISSUE THREAD

**Issue by deko-39** [dolanmiu/docx#1103]
I look through @type and see the IDocumentBackgroundOptions but seem like its do not have the complex data type as I search for. Like: 
`interface IDocumentBackgroundOptions {
    readonly color?: string;
    readonly themeColor?: string;
    readonly themeShade?: string;
    readonly themeTint?: string;
    readonly  data: <Buffer | string(svg or sth)>
}`
This would be great. If there's another way for this moment, please teach me. Thank in advanced!

**Comment by dolanmiu** [comment]
So you want a background image rather than background color?

**Comment by dolanmiu** [comment]
I think this is not possible

I am following the spec here, it does not mention background image at all:

http://www.datypic.com/sc/ooxml/e-w_background-1.html
