### ISSUE TITLE
Remove the "leading dots" from entries to page numbers at table of content

### ISSUE THREAD

**Issue by NguyennDuyyThaii** [dolanmiu/docx#1108]
I want to Remove the "leading dots" from entries to page numbers: a.......1 to   a                 1, 
plz, help me

**Comment by dolanmiu** [comment]
Can you show me your code?

I dont really understand what you mean

**Comment by NguyennDuyyThaii** [comment]
This issue is the same as the problem I need to complete, many thanks
https://stackoverflow.com/questions/64383132/modifying-style-of-docx-toc-using-javascript-docx-js
