### ISSUE TITLE
ExternalHyperlink with multiple children

### ISSUE THREAD

**Issue by rowanc1** [dolanmiu/docx#1119]
I am trying to have multiple `TextRun` children be in the same ExternalHyperlink. The way that the API is designed, there is only a single `child`. This means that if there is formatting inside of a link (e.g. bold or other markup) you have to put the link on every single `TextRun`, this isn't ideal when creating links which people will then edit and/or remove in Word.

Single Hyperlink around two TextRuns:
![image](https://user-images.githubusercontent.com/913249/131196501-630fbbf5-f644-488c-a3c0-a6f905a64ef3.png)

It looks like the spec can support multiple children in a Hyperlink, it would be great if we could expose that in `docx`! I will put a draft PR together to show where the approximate changes are.

**Comment by anti-the-social** [comment]
Just some example on what happens when you choose differently styled text and convert it to a link in Word
![image](https://user-images.githubusercontent.com/69673750/131467755-815182ed-fe0d-4885-b5ff-1cc1d1900932.png)
![image](https://user-images.githubusercontent.com/69673750/131467441-aad35570-7517-472f-83b1-d611f57aa6cd.png)

**Comment by rowanc1** [comment]
Thanks @anti-the-social, I should have been more clear that the screenshot that I posted was from word, and created through the linked PR, applying the `Hyperlink` style as well as a few others in a different text run! Thanks for posting the code screenshot as well!

**Comment by rowanc1** [comment]
We can likely close this issue now that #1120 has been merged in!

**Comment by dolanmiu** [comment]
Closing as fixed by #1120
