### ISSUE TITLE
Can't add an image paragraph to the header

### ISSUE THREAD

**Issue by ForsakenHarmony** [dolanmiu/docx#112]
I always get an error saying "The image cannont be displayed"
![image](https://user-images.githubusercontent.com/8845940/43529531-cd006312-95ab-11e8-9de0-2acd4717550b.png)

is there another way to add a right aligned scaled image to it?

**Comment by dolanmiu** [comment]
This will be addressed in `4.0.0`

**Comment by dolanmiu** [comment]
4.0.0 Released and addressed this.
