### ISSUE TITLE
how can I find out that I have moved to a new page?

### ISSUE THREAD

**Issue by emincanmercan** [dolanmiu/docx#1133]
I have an array and the length of this array is different each time. so the page length of my word file is changing. I need this. I have to write one sentence before the end of each page. How can I do that. I can't use footer. Because when there is half a page, the sentence I want to add should be added at the end of the page.
In summary, how can I find out that I have moved to a new page?

Thanks.

**Comment by dolanmiu** [comment]
Not possible im afraid
The page is kind of figured out after the document has finished compiling together
