### ISSUE TITLE
Table Cell Width Problem

### ISSUE THREAD

**Issue by emincanmercan** [dolanmiu/docx#1139]
![Ekran Görüntüsü (5)](https://user-images.githubusercontent.com/82031884/132259478-23ec5764-69b6-432b-a3fe-2d2a2eb0b285.png)
![Ekran Görüntüsü (6)](https://user-images.githubusercontent.com/82031884/132259485-d60e4ea6-3c34-4848-98a7-1e82bf2a837d.png)
![Ekran Görüntüsü (7)](https://user-images.githubusercontent.com/82031884/132259487-5bd5d0f4-6ea8-498b-98d1-3fce708ddf26.png)
![Ekran Görüntüsü (8)](https://user-images.githubusercontent.com/82031884/132259491-6eed207f-1fec-43c6-a99e-34db43fafb81.png)

Hello, I want to consult you about something. As you can see in the photos I have attached, I get different outcomes in the two results, although they have the same code sequence. Even though I just changed the text line, in the first result a new line is created for the long text. On the other hand, in the second result, the long text causes the first column to contract. I want the "example" cells in both results to have the same width. Thanks in advance.

**Comment by anti-the-social** [comment]
``layout: TableLayoutType.FIXED`` is what you are looking for :) 

Try it out:

```
const fs = require('fs');
const { Document, Packer, TextRun, TableCell, Paragraph, TableRow, Table, WidthType, TableLayoutType} = require('docx');

const doc = new Document({
  sections: [{
    children: [
      new Table({ 
        layout: TableLayoutType.FIXED,
        rows: [
          new TableRow({ children: [
            new TableCell({
              width:{
                size: 2000,
                type: WidthType.DXA
              },
              children:[
                new Paragraph({ children: [
                  new TextRun({ text: 'Lovely text for lovely paragraph'})
                ] })
              ]
            }),
            new TableCell({
              width:{
                size: 1005,
                type: WidthType.DXA
              },
              children:[
                new Paragraph({ children: [
                  new TextRun({ text: 'longlonglonglonglonglonglonglonglonglonglonglongloonglonglong'})
                ] })
              ]
            })
          ]})
        ]
      })
    ]
  }],
});

// Used to export the file into a .docx file
Packer.toBuffer(doc).then((buffer) => {
    fs.writeFileSync("table_width.docx", buffer);
});
```

**Comment by emincanmercan** [comment]
Thanks for your help :)

**Comment by anti-the-social** [comment]
@emincanmercan close an issue if that helped you :)
