### ISSUE TITLE
Custom style with numbering attached wanted

### ISSUE THREAD

**Issue by anti-the-social** [dolanmiu/docx#1147]
Recently got noticed that in the word document you can have style where you can have not only style but also numbering attached.
Did go through the lib, but I didn't find `w:numPr` implementation for `paragraphStyles`.

Somewhat related issue: https://github.com/dolanmiu/docx/issues/119 

And also this
https://docx.js.org/api/interfaces/iparagraphstyleoptions.html

And some source related code
https://github.com/dolanmiu/docx/blob/de145e062360b3d26328c6fe2da77f8e8a1838f2/src/file/styles/style/paragraph-style.ts#L5-L8

https://github.com/dolanmiu/docx/blob/de145e062360b3d26328c6fe2da77f8e8a1838f2/src/file/styles/style/style.ts#L42-L51

What word has in styles.xml if such numbering is attached:
![image](https://user-images.githubusercontent.com/69673750/132684429-c9b1aed2-a054-4638-be12-8098d3ff87fb.png)

**Comment by dolanmiu** [comment]
Oh ok nice, should be a simple fix!

**Comment by anti-the-social** [comment]
I'll go for it on Monday :) 
I also found it quite critical for the project I do so would be nice to have release some time soon after implementing this feature if possible

**Comment by dolanmiu** [comment]
nice, yes a v7 release is coming very soon

**Comment by anti-the-social** [comment]
Took quite a while to follow all the chains between the files, but there it is. :) 
https://github.com/dolanmiu/docx/pull/1163
