### ISSUE TITLE
docx editor

### ISSUE THREAD

**Issue by perfectwebtech** [dolanmiu/docx#1148]
hello

i can use free of cost this library ? 

any help example code for my exiting docx ?  i can edit ?

**Comment by anti-the-social** [comment]
This library is under ordinary MIT license: https://github.com/dolanmiu/docx/blob/master/LICENSE

This library is for creating .docx files, not for editing an existing one.
Some hint: .docx file is .zip if you change an extension you'll see the content of it.
Some hint 2: if you need edit .docx file with gui then use Word or some free options as OpenOffice or similar

Just to be clear, issues in github is rather questions about code of the lib and it's problems or improvements.
