### ISSUE TITLE
Publish 4.0.0 to NPM

### ISSUE THREAD

**Issue by michaelmyers** [dolanmiu/docx#115]
I see a tag for 4.0.0 but it isn't available on NPM.  Curious about the timeline to making it available or if there are any blockers I can help with.

**Comment by dolanmiu** [comment]
it was an accident, 4.0.0 is not ready yet!

a few more issues, then I will publish

ETA is 2 weeks

Thanks

**Comment by michaelmyers** [comment]
Thanks for the info, closing and will check back in a couple of weeks.
