### ISSUE TITLE
issues in exporting from 'docx' on aws ecs when using with VueJS

### ISSUE THREAD

**Issue by sjengg06** [dolanmiu/docx#1155]
Hi @dolanmiu,

I'm facing issue in building code that has 'docx' module over aws ecs in a VueJS project. The code runs fine on local but throws following error on AWS ECS (in codebuild). Please let me know if you've any ideas of the reason and fix.

WARNING Compiled with 15 warnings11:15:27 PM

warning in ./src/components/Test/TestSummary.vue?vue&type=script&lang=js&
"export 'AlignmentType' was not found in 'docx'

**Comment by anti-the-social** [comment]
Hi!
I wonder if this helps you in any way:
https://stackblitz.com/edit/vuejs-docx?file=cv-generator.ts
If such example doesn't help then could you bring more of a code you did so it is possible to reproduce the bug.
If it helps then close an issue :)

**Comment by sjengg06** [comment]
Hi!,

The issue was with the Vue version and docx version compatibility on aws. The solution is upgrade the application Vue version to 4.5 and use latest docx version.
