### ISSUE TITLE
Error adding a image to a table

### ISSUE THREAD

**Issue by AladMocu** [dolanmiu/docx#116]
i got `docx.Media.addImage is not a function` everytime I try to add a image to a table or the media

```
docx.Media.addImage is not a function
    at Interface.rl.on.on `(D:\testdocs\main.js:32:30)`
    at Interface.emit (events.js:187:15)
```

im following the example 

```js
const docx = require('docx');

var doc = new docx.Document();

const table = doc.createTable(4, 4);
table.getCell(2, 2).addContent(new docx.Paragraph('Hello'));

const image = docx.Media.addImage(doc, "./demo/images/image1.jpeg");
table.getCell(1, 1).addContent(image);

var exporter = new docx.LocalPacker(doc);
exporter.pack('My Document');

console.log('Document created successfully at project root!');
```

**Comment by dolanmiu** [comment]
This isnt released yet, will be available in 4.0.0

**Comment by AladMocu** [comment]
Thanks for fast response, meanwhile, is there any way to use the ```doc.createImage``` whitout the line break after the image?

**Comment by dolanmiu** [comment]
That is a good question, and the answer is no

This is because an "Image" in `docx` is actually a paragraph, which explains the line break

I will address this in `4.0.0`

Thanks for pointing this out
