### ISSUE TITLE
How to add text/paragraph over image?

### ISSUE THREAD

**Issue by bogmihut8** [dolanmiu/docx#1179]
I am trying to have a paragraph over a full-page image, but I am not able to do it.
Been trying zindex, but that looks like it is a property only for image.

```
new Paragraph({
  children: [
    new ImageRun({
      data: fs.readFileSync("./assets/first.png"),
      transformation: {
        width: 800,
        height: 1100
      },
      floating: {
        horizontalPosition: {
          align: HorizontalPositionAlign.LEFT
        },
        verticalPosition: {
          align: VerticalPositionAlign.CENTER
        }
      }
    }),
    new Paragraph({
      text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.`,
      style: "aside"
    })
  ]
}),
```

**Comment by deko-39** [comment]
So, you want a background image right? Using zindex = 0 and allowOverLap = true, if needed, behindDocument = true on the ImageRun

**Comment by bogmihut8** [comment]
Yes, worked great. Thanks a lot!

**Comment by aviral282** [comment]
Hello Guys, I am trying the same thing trying to write over the image as background. I am getting errors related to the declaration, Can you point out what I am doing wrong ?


![image](https://user-images.githubusercontent.com/27973847/188701157-c182a27a-99b4-4f3e-9c30-72078714cfa6.png)
