### ISSUE TITLE
Live Document site updated more recently than recent release

### ISSUE THREAD

**Issue by mpolichette** [dolanmiu/docx#1186]
Thank you so much for your work on this project.

As I've been working w/ the documentation site, I noticed there was a discrepancy between what is in the docs vs what is available in the latest published package.

Specifically:
[This commit](https://github.com/dolanmiu/docx/commit/dd6d1bc039606791d1aa959ff07296d0e81fdc04) from May adds the `indent` property to tables, and documents it. 

However, the most recent release is from March.  This will probably lead to confusion (it did for me). 

Seems like we would just need to publish a release?  Is that something that is easy and/or happening soon?

Is there a blocker that needs help?

**Comment by dolanmiu** [comment]
Version 7 is released! Docs now up to date with version

**Comment by mpolichette** [comment]
❤️
