### ISSUE TITLE
Do you support adding a paragraph at the top of each page?

### ISSUE THREAD

**Issue by jack-pearson** [dolanmiu/docx#1187]
Do you support adding a paragraph at the top of each page?
![image](https://user-images.githubusercontent.com/42231507/134858239-0f764ccd-13cd-462c-9a13-f9c30ea2070a.png)

**Comment by dolanmiu** [comment]
A header? Then yes:

https://github.com/dolanmiu/docx/blob/master/demo/8-header-footer.ts
