### ISSUE TITLE
Table width units in v7

### ISSUE THREAD

**Issue by anti-the-social** [dolanmiu/docx#1197]
Hello there! very happy to see v7 released, thank you :)

I was testing the lib and found out one unlisted breaking change:
At the 6.0.3 version table width meant to be determined using number and then if width units are set to "pct" passing "100" converted to "100%" via 
`this.root.push(new TableWidthAttributes({ type: type, size: type === WidthType.PERCENTAGE ? `${size}%` : size }));`
Look here: https://github.com/dolanmiu/docx/commit/dd6d1bc039606791d1aa959ff07296d0e81fdc04#diff-1e76230095cf1d1a1da146ebdd9b3b80c5465b76fd2c4c946a2ff6b70ed94340

As for the v7 "100" with unit "pct" leads to this:
![image](https://user-images.githubusercontent.com/69673750/135076628-294289be-9a6b-4b1f-91ce-2695e9f302c6.png)
Which shrinks table to the smallest size possible:
![image](https://user-images.githubusercontent.com/69673750/135077355-3737cd80-3067-4db4-aea3-46d592e79946.png)

I assume we would like to put that feature back in use since why to put units twice into table options? Or what do you think?
... or at least put it into release notes

**Comment by dolanmiu** [comment]
Could you make a fix? I will release `7.0.1` patch

**Comment by dolanmiu** [comment]
But `WithType.PERCENTAGE = 'pct'`? so it should work right?

```ts
type === WidthType.PERCENTAGE ? ${size}% : size
```

**Comment by anti-the-social** [comment]
Yeah, I just created similar thing in my branch (no tests yet)
![image](https://user-images.githubusercontent.com/69673750/135091577-171441de-2e24-4917-9734-dbc32abab7d9.png)
https://github.com/anti-the-social/docx/tree/table-width-percent-unit-handling

**Comment by anti-the-social** [comment]
I wonder why this test does not fail on having in either of outcomes: "100" or "100%"?  (Percents would work only with "100%" in tables I tested)
![image](https://user-images.githubusercontent.com/69673750/135092718-af563482-8424-4bdd-9606-9cf008e1e2f4.png)

**Comment by anti-the-social** [comment]
Here is PR for this
https://github.com/dolanmiu/docx/pull/1199
