### ISSUE TITLE
Missing docs

### ISSUE THREAD

**Issue by donalatorre** [dolanmiu/docx#1206]
I was looking for the `IStylesOptions` documentation in https://docx.js.org/api/, which redirected me to a 404 link https://docx.js.org/api/interfaces/istylesoptions.html.

Idk if it's the only broken link.

**Comment by anti-the-social** [comment]
Could you specify the place where the link is?
If I click "IStylesOptions" at https://docx.js.org/api/, then it leads to working page: https://docx.js.org/api/interfaces/IStylesOptions.html

**Comment by donalatorre** [comment]
Weird, I refreshed the api docs page and now it sends me to the correct link. Closing.
