### ISSUE TITLE
Can't resolve 'dgram' and 'dns'

### ISSUE THREAD

**Issue by joaovictortinoco** [dolanmiu/docx#121]
Hi,

When i try to run docx in Angular 5, i get the following error during build with `ng serve`: 

`ERROR in ./node_modules/docx/build/index.js Module not found: Error: Can't resolve 'dgram' in '../node_modules/docx/build'`

`ERROR in ./node_modules/docx/build/index.js
Module not found: Error: Can't resolve 'dns' in '../node_modules/docx/build'`

**Comment by dolanmiu** [comment]
Yes

`docx` is only supported in a node environment, browsers are not supported

One of the reasons is because of the `archiver`  dependency, which uses `fs`

May be other reasons too, if you can get it working for Angular, it would be awesome

**Comment by dolanmiu** [comment]
Very proud to announce that docx `4.0.0` now supports Angular, React and normal html!

https://codepen.io/anon/pen/dqoVgQ
https://jsfiddle.net/3xhezb5w/3/
