### ISSUE TITLE
Best way to write tests when using docx.js

### ISSUE THREAD

**Issue by sergiofm** [dolanmiu/docx#122]
Hi.  I am converting a document to docx format, and I need a way to test if my conversion methods are doing ok without opening the document in Word all the time.
Is there any way to do that?

**Comment by dolanmiu** [comment]
Glad you asked,

I am actually working on that soon:

https://docs.microsoft.com/en-us/office/open-xml/how-to-validate-a-word-processing-document

**Comment by sergiofm** [comment]
Nice! I would be glad to help with that feature!

**Comment by dolanmiu** [comment]
I am in the middle of writing an Azure cloud function to do this now
