### ISSUE TITLE
Example 28-table-of-contents.ts is not working

### ISSUE THREAD

**Issue by caotrongtin99** [dolanmiu/docx#1225]
Hi,
I run example code but index block do not show.

**Comment by huzaifa3115** [comment]
Same here with me.

**Comment by huzaifa3115** [comment]
Did you get any solution?

**Comment by dolanmiu** [comment]
Duplicate of:

https://github.com/dolanmiu/docx/issues/748

**Comment by hahaXiaoxin** [comment]
Have one get any solution?I use example [of 28-table-contents.ts](https://github.com/dolanmiu/docx/issues/1225#top) but no catalogue On November 23 2023,the docx version is @8.2.4
