### ISSUE TITLE
Performance drop from 6.0.3 to V7

### ISSUE THREAD

**Issue by Morsey** [dolanmiu/docx#1250]
(Firstly, thank you for all your work on this, it is amazing!)

I have a javascript which makes a large document (~50 pages) with 4 tables per page.  In v6.0.3 this is completed and ready within about 4-5 seconds. On any v7 the same code takes in excess of 18 seconds.

I'm fairly new to javascript, so am not very experienced with any type of profiling. However I have the following from chrome which seems to show that main function calling finishing after the normal time, but then something else taking the rest of the time up to 18 seconds.

Any ideas?

<img width="747" alt="Screenshot 2021-10-23 at 19 43 14" src="https://user-images.githubusercontent.com/288440/138567912-083daf47-54f7-4397-acaa-b742e989eb1a.png">

**Comment by Morsey** [comment]
It is all a little complex to share, I'll try and reduce it down and see if I can replicate the issue.

**Comment by Morsey** [comment]
I've discovered the issue is with:

Packer.toBlob(doc).then((blob) => {
    // saveAs from FileSaver will download the file
    saveAs(blob, "example.docx");
});

This is taking a very long time (~20 seconds) with any v7 and above. The document has 4 tables and pictures per page, with 50+ pages. I'll try and make a sample tonight without the confidential information in it.

**Comment by Allatir** [comment]
Hi, 

i've noticed the same issue as well. It is indeed stuck on the same code snippet above. Can confirm it takes always 20 - 25 seconds no matter the amount of pages and content to generate docx.

**Comment by Slash214** [comment]
你好，目前这个问题，你们解决了嘛？

**Comment by Slash214** [comment]
Hello, have you solved this problem so far?

**Comment by dolanmiu** [comment]
Did some profiling work, seems fine as of `v8.3.0`

342ms:

![image](https://github.com/dolanmiu/docx/assets/2917613/a175bd5b-e5e0-400c-bb5f-7f964b1ecc2d)
