### ISSUE TITLE
Nodebuffer is not supported by this platform while using docxjs with javascript (not nodejs/react/vuejs).

### ISSUE THREAD

**Issue by GauravAshara** [dolanmiu/docx#1272]
I am trying to integrate docxjs to my website /browser. To Read the local file I use the below code. 

```  var xhr1= new XMLHttpRequest();
  xhr1.open('GET', 'template.dotx', true);
  if (xhr1.overrideMimeType) {
    xhr1.overrideMimeType('text/plain; charset=x-user-defined');
  }

  xhr1.onreadystatechange = function(e) {
    if (this.readyState == 4 && this.status == 200) {

      window.docData=this.response;
      }
  };
  xhr1.send();
```

**Called below function**
```
function generate() {

    const importDotx = new docx.ImportDotx();
     importDotx.extract(window.docData).then((templateDocument) => {
        const doc = new docx.Document({
            sections: [
                {
                    children: [
                        new docx.Paragraph({
                            children: [
                                new docx.TextRun("Hello World"),
                                new docx.TextRun({
                                    text: "Foo Bar",
                                    bold: true,
                                }),
                                new docx.TextRun({
                                    text: "\tGithub is the best",
                                    bold: true,
                                }),
                            ],
                        }),
                    ],
                },
            ],
        },                    
        {
            template: templateDocument,
        });
        
        
        
        docx.Packer.toBlob(doc).then((blob) => {
            console.log(blob);
            saveAs(blob, "example.docx");
            console.log("Document created successfully");
        });
        
    });
     

    }
```

I got below error Uncaught (in promise) Error: nodebuffer is not supported by this platform

**Comment by dolanmiu** [comment]
The template feature is not properly supported right now, its not too documented. Thinking of removing

If you are looking for a templating solution, consider docx-templater

https://docxtemplater.com/

**Comment by simonbrunel** [comment]
@GauravAshara Probably too late for you but in case other users try to use templates - that [contain images](https://github.com/dolanmiu/docx/blob/master/src/import-dotx/import-dotx.ts#L160) - in the browser, here is how I setup webpack in a vue-cli project to get rid of this error ([based on this article](https://viglucci.io/how-to-polyfill-buffer-with-webpack-5)). Though, **you will probably also experience issues described in #489**.

```sh
npm install -S buffer
```

```js
// vue.config.js
const { ProvidePlugin } = require('webpack');

module.exports = {
  configureWebpack: {
    resolve: {
      fallback: {
        buffer: require.resolve('buffer/'),
      },
    },
    plugins: [
      new ProvidePlugin({
        Buffer: ['buffer', 'Buffer'],
      }),
    ],
  },
};
```

**Comment by dolanmiu** [comment]
`docx` now has this feature out of the box! As of `v8.0.0`:

https://github.com/dolanmiu/docx/blob/master/demo/85-template-document.ts

This library can now read and write docx files.

**Comment by Kaishley** [comment]
> `docx` now has this feature out of the box! As of `v8.0.0`:
> 
> https://github.com/dolanmiu/docx/blob/master/demo/85-template-document.ts
> 
> This library can now read and write docx files.

I am getting `Error: nodebuffer is not supported by this platform` when using in a browser.
