### ISSUE TITLE
lineRule preperty of ISpacingProperty not working on paragraph style

### ISSUE THREAD

**Issue by R-D-D-D** [dolanmiu/docx#1277]
Thanks for the amazing library!

I want to ask if the `lineRule` property of `ISpacingProperty` working right now? In this [demo](https://github.com/dolanmiu/docx/blob/master/demo/62-paragraph-spacing.ts) after replacing the `lineRule` with `LineRuleType.EXACTLY` did not change the rendering at all.

### lineRule: LineRuleType.AUTO
<img width="1536" alt="Screenshot 2021-11-06 at 11 35 00 AM" src="https://user-images.githubusercontent.com/45935526/140615181-7963132a-8200-4877-abdd-710bd3325f04.png">

### lineRule: LineRuleType.EXACTLY
<img width="1536" alt="Screenshot 2021-11-06 at 11 35 55 AM" src="https://user-images.githubusercontent.com/45935526/140615185-71ce49a8-1acb-4a36-9931-6bacd93e30e8.png">

As seen in the two screenshot, the line spacing are all multiple although I have changed it to exactly.

**Comment by anti-the-social** [comment]
Hello :) 

I can confirm the issue, but it sort of fancy.
According to OOXML we have to use **"exactly"** or "atLeast"
![image](https://user-images.githubusercontent.com/69673750/140721174-9f83221d-dc77-428f-89bd-53630c436344.png)
http://officeopenxml.com/WPspacing.php

At the same time Word itself uses **"exact"** or "atLeast"
![image](https://user-images.githubusercontent.com/69673750/140721260-d4474f2d-27ff-410d-b932-c1ba52fd914a.png)

Now so sure what do we do with such fancy situations

**MORE OVER**
Python library has this issue risen already also.
https://github.com/python-openxml/python-docx/issues/598

If you wanna test docx js library, then here is the code:
```
// Sections with multiple columns
// Import from 'docx' rather than '../build' if you install from npm
const fs = require('fs');
const { Document, Packer, Paragraph, LineRuleType, TextRun }  = require('docx');

const doc = new Document({
    sections: [
        {
            children: [
                new Paragraph({
                    spacing:{
                        line: 120,
                        lineRule: LineRuleType.EXACTLY
                    },
                    children: [
                        ew TextRun(`Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
                        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
                        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
                        Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. 
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
                        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
                        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
                        Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. 
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
                        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
                        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
                        Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. 
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
                        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
                        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
                        Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                        `),
                    ],
                }),
            ],
        },
    ],
});

Packer.toBuffer(doc).then((buffer) => {
    fs.writeFileSync("lineSize.docx", buffer);
});
```

**Comment by anti-the-social** [comment]
And yeah, in your case I'd suggest just use LineRuleType.AT_LEAST and you'll be fine :)

**Comment by R-D-D-D** [comment]
Hi thanks so much for the reply! I just have one follow up question. Setting it to `LineRuleType.AT_LEAST` worked like a charm. But from your explanation, I still do not really understand why  `LineRuleType.EXACTLY` does not work, according to OOXML it actually means both should work somewhat in a similar way right?

Thank you!

**Comment by R-D-D-D** [comment]
Sorry `LineTuleType.AT_LEAST` does not work for my case actually. I am working on a project where I am taking text from the web in HTML CSS to MS Word which follows the exact measurement. So I do need EXACT line-height that cannot grow. For AT_LEAST, it grows beyond the set value when font is larger.

**Comment by anti-the-social** [comment]
@R-D-D-D 
What I was trying to say is that Word program by Microsoft doesn't follow the rules it should (OOXML)

I understand that `LineTuleType.AT_LEAST` is not exactly what you are looking, but as long as font-size is smaller then it does. It sort of weird use of line height if it is exact and smaller, than font size.

If, theoretically we change docxjs library to use values what use Word, then 3d party .docx software editors could break just like word did now.

**Comment by R-D-D-D** [comment]
Ahhh got it thank you for your help!
