### ISSUE TITLE
\t not being recognized in google docs

### ISSUE THREAD

**Issue by fcpaulmndza** [dolanmiu/docx#1281]
### Code: 
```
footers: {
          default: new Footer({
            children: [
              new Paragraph({
                style: 'footer',
                children: [
                  new TextRun("Test\t"),
                  new TextRun({
                    children: ['Page ', PageNumber.CURRENT, ' of ', PageNumber.TOTAL_PAGES],
                  }),
                ],
                tabStops: [
                  {
                    type: TabStopType.RIGHT,
                    position: TabStopPosition.MAX,
                  }
                ],
              })
            ],
          }),
        }
```

### Result:
<img width="1080" alt="Screen Shot 2021-11-09 at 10 31 51 PM" src="https://user-images.githubusercontent.com/86214325/140942975-b4ba4b54-7d55-4982-91f1-0343e1ce1ff7.png">

Checking the `docx` file in Google Docs

**Comment by anti-the-social** [comment]
Hi there!
I think the understanding of tabs should be so that `\t` affects only one textRun, so this works for me:
```
const fs = require('fs');
const { Document, Packer, Paragraph, TextRun, Footer, TabStopType, TabStopPosition, PageNumber}  = require('docx');

const doc = new Document({
    sections: [
        {
            children: [
                new Paragraph({
                    children: [
                        new TextRun('Lorem \t ipsum dolor sit amet'),
                    ],
                }),
            ],
            footers: {
                default: new Footer({
                    children: [
                    new Paragraph({
                        style: 'footer',
                        children: [
                            new TextRun({
                              children: ['Test \t', 'Page ', PageNumber.CURRENT, ' of ', PageNumber.TOTAL_PAGES],
                            }),
                        ],
                        tabStops: [{
                            type: TabStopType.RIGHT,
                            position: TabStopPosition.MAX,
                        }],
                    })
                    ],
                }),
            }
        },
    ],
});

Packer.toBuffer(doc).then((buffer) => {
    fs.writeFileSync("tabTest.docx", buffer);
});
```

![image](https://user-images.githubusercontent.com/69673750/141070168-15d3eca9-bdfb-43bb-adcf-13d0905dea6b.png)

**Comment by anti-the-social** [comment]
And just in case, if you try to produce page number on the right via tabs then the footer text length has to be smaller, than page size otherwise it goes fancy looking 
![image](https://user-images.githubusercontent.com/69673750/141070867-d7a6ee48-9943-46c9-bf00-a6ee41e56e5d.png)

**Comment by fcpaulmndza** [comment]
Thanks @anti-the-social! but I'm still getting the same result

**Comment by fcpaulmndza** [comment]
Seems like a compatibility issue. It works in MS Word but not in Google docs @anti-the-social

**Comment by anti-the-social** [comment]
I think this issue should be sort of risen to the google docs, not to this particular library.
And for you, I'd suggest using iframe for page numbering https://docx.js.org/#/usage/text-frames?id=intro

**Comment by CedYF** [comment]
I still can't get the right tab to be recognized in google docs

**Comment by dolanmiu** [comment]
Fixed in a PR

Now there is a dedicated `Tab` object which has perfect compatability

https://github.com/dolanmiu/docx/blob/master/demo/1-basic.ts
