### ISSUE TITLE
Line spacing

### ISSUE THREAD

**Issue by caotrongtin99** [dolanmiu/docx#1282]
I have a long sentence and put it on TextRun constructor and I want to line spacing but it seems it's not mentioned in the document.

**Comment by anti-the-social** [comment]
Line spacing is a part of paragraph settings...
https://docx.js.org/#/usage/paragraph?id=spacing

**Comment by caotrongtin99** [comment]
Hi @anti-the-social, can i set font family for paragraph (not TextRun) and set line spacing for Text Run? Thanks

**Comment by anti-the-social** [comment]
1) I think you should start using declarative styles for font family at least
https://docx.js.org/#/usage/styling-with-js?id=declaritive-styles-similar-to-external-css
You define font family for text run once and it becomes default for all textRuns that you have within one paragraph where declarative style is set.
2) line spacing is not possible to create for particular TextRun (this is limitation of docx documents in general)

**Comment by caotrongtin99** [comment]
> Hi :)
> 
> 1. I think you should start using declarative styles for the font family at least
>    https://docx.js.org/#/usage/styling-with-js?id=declaritive-styles-similar-to-external-css
>    You define font family for text run once and it becomes default for all textRuns that you have within one paragraph where declarative style is set.
> 2. line spacing is not possible to create for particular TextRun (this is limitation of docx documents in general)

My problem is that i want set font family for paragraph with many words:
new Paragraph({
    text: long_sentence,
    alignment: AlignmentType.LEFT
 })
so i use Text Run:
new Paragraph({
    children: [ new TextRun({ text: long_sentence, font: 'Courier' })]
    alignment: AlignmentType.LEFT
 })
but using TextRun make line spacing not correct

**Comment by anti-the-social** [comment]
I am guessing, that you see the difference not in line height, but the font differences.
Different fonts have different letters height in the same font size...
If got it wrong can you make example so we can run and see together what you mean? 

```
const fs = require('fs');
const { Document, Packer, Paragraph, LineRuleType, TextRun }  = require('docx');

const doc = new Document({
    sections: [
        {
            children: [
                new Paragraph({
                    spacing:{
                        line: 1.3 * 240
                    },
                    children: [
                        new TextRun({
                            text:`Times text `,
                            font: 'Times'
                        }),
                        new TextRun({
                            text:`Tahoma Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.  Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.  Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.`,
                            font: 'Tahoma'
                        })
                    ], 
                }),
                new Paragraph({
                    text: `Separation paragraph`
                }),
                new Paragraph({
                    spacing:{
                        line: 1.3 * 240
                    },
                    text: `Default Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.  Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.  Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.` 
                }),
            ],
        },
    ],
});

Packer.toBuffer(doc).then((buffer) => {
    fs.writeFileSync("lineSize.docx", buffer);
});
```

**Comment by caotrongtin99** [comment]
hi @anti-the-social an
what is 1.3 * 240? Can you explain in more detail? Thanks

**Comment by anti-the-social** [comment]
Hi @caotrongtin99 !
Here, I'd prefer to reference the documentation:

> spacing({before=0, after=0, line=0}): Set the line and before/after on the paragraph. Before/after is measured in TWIPs, line is measured in 240ths of a line

What I represented as if I like to have line of 1.3 (css lineHeight property) then formula is 240*lineHeight; In my particular example 1.3 is lineHeight.

https://docx.js.org/#/usage/styling-with-js?id=available-options
