### ISSUE TITLE
Customize Header & Footer

### ISSUE THREAD

**Issue by huzaifa3115** [dolanmiu/docx#1290]
Hello,
I want to use the header & footer as an external template through XML, below are my code & header I am looking to add but didn't succeed yet.

![image](https://user-images.githubusercontent.com/38154499/141804823-0107db22-4c60-424b-b7a6-be7cb270fde7.png)
![image](https://user-images.githubusercontent.com/38154499/141804966-78ce4474-e253-4a13-a2d7-905860aa3901.png)

**Comment by dolanmiu** [comment]
Sorry, this is not a supported feature and will not be!
