### ISSUE TITLE
Multiple tabstops in a paragraph does not work properly with LibreOffice

### ISSUE THREAD

**Issue by mathoi** [dolanmiu/docx#1300]
Hi, 
I use version 7.1.2 of this library.

The documents I generate with this library looks really good in Microsoft Word, but in other editors the results are not always as good. One of the main issues seems to be multiple tabstops in a single paragraph (which I use a lot.)

I'm adding multiple tabstops to a paragraph using the property
 
 tabStops?: { leader?: LeaderType; position: number; type: TabStopType }[]

of IParagraphOptions, but in Libre Office (7.2.2.2) it only uses the last tabstop of the array, i.e. the first tab i add to the paragraph will use that tabstop and every tab after the first will be a default tabstop.

To make a quick test if Libre Office have difficulties with multiple tabstops, I have manually made a simple document with multiple tabstops in Microsoft Word and then opened it i Libre Office. It did not have any problems with the tabstops - the problems only occurs when I use this library to generate documents.

In the following is an example of document, that I've made with this library and how it looks in Microsoft Word 2010 vs Libre Office (7.2.2.2)

Here is how the document looks in Microsoft Word 2010 and how it is supposed to look:

![tabStops-word](https://user-images.githubusercontent.com/10826024/142600783-4d245d33-4285-429e-9441-66d92229e48c.png)

Here is how it looks in Libre office:

![tabStops-libreOffice](https://user-images.githubusercontent.com/10826024/142600802-13585a2a-c45f-470b-894e-a12c12aae59d.png)

**Comment by anti-the-social** [comment]
Hi!
1) It would be much appreciated if you provide code to run to show the issue
2) 95% chance that issue isn't in the docx js library since LibreOffice does have its own logic which is not 100% following OOXML.
3) You can try to create file straight in LibreOffice in a way you like - then you'll test if LibreOffice is capable. Then save it as docx and try to open in Word. If outlook would be the same then problem is in docxjs.

My guess is that LibreOffice doesn't match Word logic and you would not be able to create same looking double tab stop in both of those programs.

**Comment by mathoi** [comment]
Hi,
Thanks for the reply. Here are my comments for your 3 bullets

### Regarding 3 (and 2)
If I manually make a document i LibreOffice and then open it in Microsoft Word then it looks fine. The same is true for the other direction.
This suggests that it is possible to make tabstops that works correctly and similarly in both Mircrosoft Word and LibreOffice. This even seems to be the default case when making a document in either Microsoft Word or LibreOffice.
 

**Document made in LibreOffice:** 
![LibreOffice](https://user-images.githubusercontent.com/10826024/144389243-da3e3d14-8d62-4dd4-837c-77d0d10482b6.png)


**Document made in LibreOffice - open in Microsoft Word:**
![LibreOffice - open in word](https://user-images.githubusercontent.com/10826024/144389253-d83fc514-54ae-4d12-986c-17b1c9f594fc.png)


**Document made in Microsoft Word:**
![Word](https://user-images.githubusercontent.com/10826024/144389297-dad77288-e19f-40d1-b0cb-9a5a5dd28392.png)

**Document made in Microsoft Word - open in LibreOffice:**
![Word - open in LibreOffice](https://user-images.githubusercontent.com/10826024/144389309-81618709-ef74-41c5-901f-42f6bb17e6a1.png)


### Regarding 1
I'm writing my code in Kotlin, so I'm not sure if the following code will help or not.

**Header file:**
To use the library in Kotlin I've made a header file with the top-level annotation:
@file:JsModule("docx") 

Here is the definition of IPropertiesOptions:
![IParagraphOptions](https://user-images.githubusercontent.com/10826024/144391569-35d05b68-cad5-4ee7-a42a-4f64317659f2.png)

And here is the one for tabstops:
![TabStops](https://user-images.githubusercontent.com/10826024/144391628-92cc04d6-dda1-4f8f-b2a8-44a2417a1312.png)

Similarly, I have definitions of IRunOptions, Run, TextRun, ISectionOptions, ISectionPropertiesOptions, Document, IPropertiesOptions etc. 

**Some auxiliary fuctions**
I have then made a couple of auxiliary fuctions:

For creating a paragraph:
![ParagraphOptions](https://user-images.githubusercontent.com/10826024/144392363-651cfe34-7518-4b9b-b592-3a7613c6e93e.png)
![Paragraph](https://user-images.githubusercontent.com/10826024/144392368-58cf354a-7dae-4d54-8216-d8ce4c735e79.png)

For adding tabstops to a paragraph:
![AddTabstop](https://user-images.githubusercontent.com/10826024/144392520-110afb18-4fc3-45d3-8d6a-0ce22937dc9c.png)

Similarly, I have auxiliary functions for handling TextRun, Section and Document 


**The code that generates the example in the original post** 
![actualCode1](https://user-images.githubusercontent.com/10826024/144393452-b6ed58b9-3981-4f1e-9051-8963f4d4aa0c.png)
![actualCode2](https://user-images.githubusercontent.com/10826024/144393464-1f86163e-eaaa-45f7-8dcb-db87eb06f1cf.png)
![actualCode3](https://user-images.githubusercontent.com/10826024/144393472-1f05272d-94f7-49b2-9f64-567f1073e74b.png)
![actualCode4](https://user-images.githubusercontent.com/10826024/144393488-33c10c8c-0c1d-46c6-9c8c-89460e587269.png)
![actualCode5](https://user-images.githubusercontent.com/10826024/144393498-e82e9080-c261-40a8-9da2-31cce0991c7c.png)

**Comment by mathoi** [comment]
Hi again,

I was wondering what the status is regarding this question/issue?

- Do you still think the issue is with LibreOffice and not docx js? 
   To me, the fact that when I make a document i Microsoft Word and subsequently open the document in LibreOffice, it looks fine and the fact that this is true for the other direction as well, clearly demonstrates that even though LibreOffice might not follow the OOXML 100%, then the default/canonical way that Microsoft Word generates the document works fine with LibreOffice. 
I don't know, if the docx js library outputs valid OOXML or not, but I can conclude, that it does not produce OOXML in the same canonical way as Microsoft Word and that if the docx js library did produce OOXML in the same canonical way as Microsoft Word, then my issue would be solved.

- Is the code and the examples sufficient, or do you need something more?

Best regards

**Comment by dolanmiu** [comment]
`docx` mostly follows the ooxml standard, I have written tests to verify this for most of the demos:

https://github.com/dolanmiu/docx/runs/4802228317?check_suite_focus=true

This PR gave support for docx to follow OOXML:

https://github.com/dolanmiu/docx/pull/948

Maybe there are more checks that can be done? if you know of any more we can do, write it here or make a suggestion

**Comment by mathoi** [comment]
I'm not entirely sure what checks you are asking me to provide.

- Is it a test-case like the demos?
  I can do this. Before submitting such a test-case/demo I would like to try validating the document it produces. 
  I have downloaded the folder ooxml-schemas, such that I can use xmllint to validate the document against wml-2010.xsd as you do in your test-code, but I'm not sure how to convert/extract the xml file from the docx file. 

- Is it some checks regarding the produced OOXML?
  If this is the case, then I'm afraid I can't be of much help, as don't know the specifics of OOXML. I can just observe, that the behavior of the documents generated by respectively docx js and Microsoft Word differs and that the behavior of the document generated by Microsoft Word seems to be superior in the following way: both documents looks great and the same when viewed i Microsoft Word, but only the document generated by Microsoft Word looks great when viewed in LibreOffice

**Comment by mathoi** [comment]
Hi @dolanmiu @anti-the-social ,

**The xml file from the example in the first post of this issue, is not valid ooxml according to the  wml-2010.xsd:**

I have extracted the xml file from the docx file by changing the file extension from .docx to .zip. The xml file is then located at  word/document.xml in the zip. 

The file is here (I have changed it to a txt file as github will not allow me to upload a xml file):
[document.txt](https://github.com/dolanmiu/docx/files/8512315/document.txt)

I have then downloaded all the files from the folder ooxml-shemas. 

When running xmllint document.xml --schema wml-2010.xsd I get a result, where it is worth noticing the following:
 - document.xml fails to validate (last line)
 - Element '{http://schemas.openxmlformats.org/wordprocessingml/2006/main}tabs': This element is not expected. 
   This error occurs 8 times: Noting that there are 8 paragraphs with multiple tabStops (2 in each) and 2 lines with a single tabStop, it seems reasonable to assume, that your library fails to generate valid ooxml, when multiple tabStops are used in a single paragraph, but that i produces valid ooxml, when just a single tabStop is present in a paragraph.
    

Here is the result:

C:\Users\Mathias\Desktop\docx\docx-master\docx-master\ooxml-schemas\microsoft>xmllint document.xml --schema wml-2010.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:w15="http://schemas.microsoft.com/office/word/2012/wordml" xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk" xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml" xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape" mc:Ignorable="w14 w15 wp14"><w:background w:color="FFFFFF"/><w:body><w:p><w:r><w:t xml:space="preserve">1 Tabstop per paragraph:</w:t></w:r></w:p><w:p><w:pPr><w:tabs><w:tab w:val="left" w:pos="2976" w:leader="none"/></w:tabs></w:pPr><w:r><w:tab/><w:t xml:space="preserve"> </w:t></w:r><w:r><w:t xml:space="preserve">Left tab stop</w:t></w:r></w:p><w:p><w:pPr><w:tabs><w:tab w:val="right" w:pos="2976" w:leader="none"/></w:tabs></w:pPr><w:r><w:tab/><w:t xml:space="preserve"> </w:t></w:r><w:r><w:t xml:space="preserve">Right tab stop</w:t></w:r></w:p><w:p/><w:p/><w:p><w:r><w:t xml:space="preserve">2 Tabstops - leftmost tabstop added first</w:t></w:r></w:p><w:p><w:pPr><w:tabs><w:tab w:val="left" w:pos="2976" w:leader="none"/></w:tabs><w:tabs><w:tab w:val="right" w:pos="5952" w:leader="none"/></w:tabs></w:pPr><w:r><w:tab/><w:t xml:space="preserve"> </w:t></w:r><w:r><w:t xml:space="preserve">Left</w:t></w:r><w:r><w:tab/><w:t xml:space="preserve"> </w:t></w:r><w:r><w:t xml:space="preserve">Right</w:t></w:r></w:p><w:p><w:pPr><w:tabs><w:tab w:val="right" w:pos="2976" w:leader="none"/></w:tabs><w:tabs><w:tab w:val="left" w:pos="5952" w:leader="none"/></w:tabs></w:pPr><w:r><w:tab/><w:t xml:space="preserve"> </w:t></w:r><w:r><w:t xml:space="preserve">Right</w:t></w:r><w:r><w:tab/><w:t xml:space="preserve"> </w:t></w:r><w:r><w:t xml:space="preserve">Left</w:t></w:r></w:p><w:p><w:pPr><w:tabs><w:tab w:val="left" w:pos="2976" w:leader="none"/></w:tabs><w:tabs><w:tab w:val="left" w:pos="5952" w:leader="none"/></w:tabs></w:pPr><w:r><w:tab/><w:t xml:space="preserve"> </w:t></w:r><w:r><w:t xml:space="preserve">Left</w:t></w:r><w:r><w:tab/><w:t xml:space="preserve"> </w:t></w:r><w:r><w:t xml:space="preserve">Left</w:t></w:r></w:p><w:p><w:pPr><w:tabs><w:tab w:val="right" w:pos="2976" w:leader="none"/></w:tabs><w:tabs><w:tab w:val="right" w:pos="5952" w:leader="none"/></w:tabs></w:pPr><w:r><w:tab/><w:t xml:space="preserve"> </w:t></w:r><w:r><w:t xml:space="preserve">Right</w:t></w:r><w:r><w:tab/><w:t xml:space="preserve"> </w:t></w:r><w:r><w:t xml:space="preserve">Right</w:t></w:r></w:p><w:p/><w:p/><w:p><w:r><w:t xml:space="preserve">2 Tabstops - rightmost tabstop added first</w:t></w:r></w:p><w:p><w:pPr><w:tabs><w:tab w:val="right" w:pos="5952" w:leader="none"/></w:tabs><w:tabs><w:tab w:val="left" w:pos="2976" w:leader="none"/></w:tabs></w:pPr><w:r><w:tab/><w:t xml:space="preserve"> </w:t></w:r><w:r><w:t xml:space="preserve">Left</w:t></w:r><w:r><w:tab/><w:t xml:space="preserve"> </w:t></w:r><w:r><w:t xml:space="preserve">Right</w:t></w:r></w:p><w:p><w:pPr><w:tabs><w:tab w:val="left" w:pos="5952" w:leader="none"/></w:tabs><w:tabs><w:tab w:val="right" w:pos="2976" w:leader="none"/></w:tabs></w:pPr><w:r><w:tab/><w:t xml:space="preserve"> </w:t></w:r><w:r><w:t xml:space="preserve">Right</w:t></w:r><w:r><w:tab/><w:t xml:space="preserve"> </w:t></w:r><w:r><w:t xml:space="preserve">Left</w:t></w:r></w:p><w:p><w:pPr><w:tabs><w:tab w:val="left" w:pos="5952" w:leader="none"/></w:tabs><w:tabs><w:tab w:val="left" w:pos="2976" w:leader="none"/></w:tabs></w:pPr><w:r><w:tab/><w:t xml:space="preserve"> </w:t></w:r><w:r><w:t xml:space="preserve">Left</w:t></w:r><w:r><w:tab/><w:t xml:space="preserve"> </w:t></w:r><w:r><w:t xml:space="preserve">Left</w:t></w:r></w:p><w:p><w:pPr><w:tabs><w:tab w:val="right" w:pos="5952" w:leader="none"/></w:tabs><w:tabs><w:tab w:val="right" w:pos="2976" w:leader="none"/></w:tabs></w:pPr><w:r><w:tab/><w:t xml:space="preserve"> </w:t></w:r><w:r><w:t xml:space="preserve">Right</w:t></w:r><w:r><w:tab/><w:t xml:space="preserve"> </w:t></w:r><w:r><w:t xml:space="preserve">Right</w:t></w:r></w:p><w:sectPr><w:pgSz w:w="11906" w:h="16838" w:orient="portrait"/><w:pgMar w:top="1in" w:right="1in" w:bottom="1in" w:left="1in" w:header="708" w:footer="708" w:gutter="0"/><w:pgNumType/><w:docGrid w:linePitch="360"/></w:sectPr></w:body></w:document>
Element '{http://schemas.openxmlformats.org/wordprocessingml/2006/main}tabs': This element is not expected. Expected is one of ( {http://schemas.openxmlformats.org/wordprocessingml/2006/main}suppressAutoHyphens, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}kinsoku, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}wordWrap, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}overflowPunct, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}topLinePunct, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}autoSpaceDE, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}autoSpaceDN, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}bidi, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}adjustRightInd, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}snapToGrid ).
Element '{http://schemas.openxmlformats.org/wordprocessingml/2006/main}tabs': This element is not expected. Expected is one of ( {http://schemas.openxmlformats.org/wordprocessingml/2006/main}suppressAutoHyphens, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}kinsoku, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}wordWrap, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}overflowPunct, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}topLinePunct, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}autoSpaceDE, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}autoSpaceDN, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}bidi, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}adjustRightInd, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}snapToGrid ).
Element '{http://schemas.openxmlformats.org/wordprocessingml/2006/main}tabs': This element is not expected. Expected is one of ( {http://schemas.openxmlformats.org/wordprocessingml/2006/main}suppressAutoHyphens, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}kinsoku, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}wordWrap, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}overflowPunct, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}topLinePunct, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}autoSpaceDE, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}autoSpaceDN, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}bidi, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}adjustRightInd, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}snapToGrid ).
Element '{http://schemas.openxmlformats.org/wordprocessingml/2006/main}tabs': This element is not expected. Expected is one of ( {http://schemas.openxmlformats.org/wordprocessingml/2006/main}suppressAutoHyphens, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}kinsoku, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}wordWrap, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}overflowPunct, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}topLinePunct, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}autoSpaceDE, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}autoSpaceDN, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}bidi, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}adjustRightInd, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}snapToGrid ).
Element '{http://schemas.openxmlformats.org/wordprocessingml/2006/main}tabs': This element is not expected. Expected is one of ( {http://schemas.openxmlformats.org/wordprocessingml/2006/main}suppressAutoHyphens, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}kinsoku, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}wordWrap, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}overflowPunct, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}topLinePunct, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}autoSpaceDE, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}autoSpaceDN, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}bidi, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}adjustRightInd, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}snapToGrid ).
Element '{http://schemas.openxmlformats.org/wordprocessingml/2006/main}tabs': This element is not expected. Expected is one of ( {http://schemas.openxmlformats.org/wordprocessingml/2006/main}suppressAutoHyphens, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}kinsoku, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}wordWrap, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}overflowPunct, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}topLinePunct, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}autoSpaceDE, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}autoSpaceDN, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}bidi, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}adjustRightInd, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}snapToGrid ).
Element '{http://schemas.openxmlformats.org/wordprocessingml/2006/main}tabs': This element is not expected. Expected is one of ( {http://schemas.openxmlformats.org/wordprocessingml/2006/main}suppressAutoHyphens, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}kinsoku, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}wordWrap, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}overflowPunct, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}topLinePunct, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}autoSpaceDE, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}autoSpaceDN, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}bidi, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}adjustRightInd, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}snapToGrid ).
Element '{http://schemas.openxmlformats.org/wordprocessingml/2006/main}tabs': This element is not expected. Expected is one of ( {http://schemas.openxmlformats.org/wordprocessingml/2006/main}suppressAutoHyphens, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}kinsoku, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}wordWrap, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}overflowPunct, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}topLinePunct, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}autoSpaceDE, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}autoSpaceDN, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}bidi, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}adjustRightInd, {http://schemas.openxmlformats.org/wordprocessingml/2006/main}snapToGrid ).
document.xml fails to validate

**Comment by anti-the-social** [comment]
Hi @mathoi 

So is this document.txt you attach broken for some of the docx editors? (Looked pretty valid tags vise)
You can do it yourself or I can do it for you:
1) Attach broken document.xml here (via .txt like you did)
2) Open this broken document via word 
3) Add one character and re-save(after re-saving word usually fixes problem it finds)
4)  compare the document.xml to the previous version to see what is actually a difference between broken tabs and non-broken tabs. 
5) Check if your findings fit an actual OOXML standard. http://officeopenxml.com/WPtab.php

**Comment by mathoi** [comment]
Hi @anti-the-social ,

Yes, as explained in the first post, the document is broken in LibreOffice. 


I have just done what you asked, and I will detail my findings below.

In the following 
- document.xml is the xml file generated by the library
- document2.xml is the document saved by word after one character is added (a 0 is added after the very first 1)
 
Here are the two documents:
[document.txt](https://github.com/dolanmiu/docx/files/8514472/document.txt)
[document2.txt](https://github.com/dolanmiu/docx/files/8514473/document2.txt)


**Findings:**
**1) document.xml is not valid, but document2.xml is valid**
    When validating the documents against wml-2010.xsd the document.xml generated by the library fails to validate, whereas the document2.xml saved by word does validate. 
    wml-2010.xsd is the schema that all the demos in this library is validated against. This can be seen by inspecting the test-code that  Dolanmiu links to in his post above.

Here is the output from trying to validate document.xml (it's the same as in the previous post)
[xmllintDocument1.txt](https://github.com/dolanmiu/docx/files/8514521/xmllintDocument1.txt)

   Here is the output from the validation of document2.xml
[xmllintDocument2.txt](https://github.com/dolanmiu/docx/files/8514522/xmllintDocument2.txt)


**2) document.xml looks wrong in LibreOffice, document2.xml looks correct in LibreOffice**

**document.xml is broken in LibreOffice:**
In my first post, I described, that the document generated by the library is broken in LibreOffice in the following way:
When multiple tabStops are present in a single paragraph, then LibreOffice will only use the definition (position and type) of the first tabStop, that is added to the list. The following tabStop will then be a default tabStop, i.e. it will ignore the specified position and type (left- or right-tabstop).

Here is a screenshot of document when opened in LibreOffice:
![tabStops](https://user-images.githubusercontent.com/10826024/164046578-c5153ef0-a7e0-4507-bd17-f0e66f4d3097.png)

**document2.xml is correct in LibreOffice:**
The document saved by word respects the definitions(position and type) of all the tabstops.

Here is a screenshot of document2 when opened in LibreOffice:
![tabStops2](https://user-images.githubusercontent.com/10826024/164046589-38474234-0a52-4afc-98c2-3ecc0476bfe1.png)

**3) The diff between document.xml and document2.xml is large and in multiple places**  
There are multiple differences between document.xml and document2.xml. I think, it is better if you compare the two files yourself because the defferences is not contained to a single place.

**Comment by mathoi** [comment]
Hi @anti-the-social @dolanmiu ,

**Good news :D** 

If i sort the tabStops in ascending order before using the docx.js lib then generated document is valid according to the wml-2010.xsd and it looks perfect in LibreOffice.  (@anti-the-social thanks a lot for the suggestion)
I did not expect this, as even the paragraps where, the tabStops are in ascending order looks wrong in the original example. 


For now I'll sort the tabStops before using the library, but I think that the docx.js lib should sort them - it seems like a rather minor inconvinience in order to make sure that the generated output i valid OOXML and looks good in both Word and LibreOffice

**Comment by mathoi** [comment]
Sorry, I was so happy hat it worked that i closed the issue a bit to early.

As mentioned above: The problem is circumvented by sorting the tabstops before using the docx.js lib -  but for the problem to be properly solved, I think that the docx.js lib should do the sorting

**Comment by anti-the-social** [comment]
Good that it helped :)

Should we mark this issue as feature request, what do you think @dolanmiu ?

**Comment by mathoi** [comment]
Hi @anti-the-social @dolanmiu 

I don't know how to explain this:
- I have the same problem again
- I can't reproduce the success from before - not by rollback or anything

I have studied the xml produced by the library and noticed something suspicius: When adding multiple tabStops to a single paragraph, then the library creates seveal singleton-lists instead of creating one list with several tabstops.

Here is a snippet of the xml produced by the library:
![document1](https://user-images.githubusercontent.com/10826024/165541947-1f131a70-8dce-4dc3-90a0-cb03c18c1df9.png)

I think, that this should be a single list like this: 
![document2](https://user-images.githubusercontent.com/10826024/165544227-29e93359-ec38-4be5-9aad-83339c369a78.png)

I have tried to do that manually for alle the relevant places in the xml. The resulting document validates according to the wml-2010.xsd and looks proper in both LibreOffice and Word when converted back to a docx file.

 **Here is the xml before the manual editing (It is not valid):**
[document1.txt](https://github.com/dolanmiu/docx/files/8572928/document1.txt)

**Here is the xml after the manmual editing (It is valid)**
[document2.txt](https://github.com/dolanmiu/docx/files/8572929/document2.txt)




**Source code** 
Here is your sorce code handling multiple tabStops in paragraphs:

From the file [properties.ts](https://github.com/dolanmiu/docx/blob/master/src/file/paragraph/properties.ts):

![paragraphProperties](https://user-images.githubusercontent.com/10826024/165541978-30e63103-4a64-4f2b-a0b8-9209f233765d.png)

And from the file [tab-stop.ts](https://github.com/dolanmiu/docx/blob/master/src/file/paragraph/formatting/tab-stop.ts):

![TabStop](https://user-images.githubusercontent.com/10826024/165548340-bce9ca01-ab6b-4a3f-ad1e-741120fd6898.png)


It seems 
- That the library creates a new list (the tabs element) each time the TabStop constructor is called  (Line 6 in [tab-stop.ts](https://github.com/dolanmiu/docx/blob/master/src/file/paragraph/formatting/tab-stop.ts))
- That the TabStop constructor is called for each tabStop in the tabStops attribute of the paragraph property (Line 140 in [properties.ts](https://github.com/dolanmiu/docx/blob/master/src/file/paragraph/properties.ts))

I think that the tabs element should not be pushed in the TabStop constructor but before the for-loop such that only one list is generated.


I am so sorry about my confusing feedback from ealier, I truely don't know what happened.

**Comment by Icaro-Lima** [comment]
I am having the same problems mentioned by @mathoi. I was using tables in my code. Then, I switched to tab stops. After struggling when using multiple tab stops in the same paragraph, I decided to rollback to using tables.

**Comment by mathoi** [comment]
@anti-the-social @dolanmiu  Please, what do you think about my suggested explanation and solution? Is there somehing I have misunderstood or did not consider?

**Comment by ronram5126** [comment]
I have fixed it in my fork, have requested pull.
[Pull Request](https://github.com/dolanmiu/docx/pull/1709)

**Comment by ronram5126** [comment]
#1709 Have made the fix in my fork. Am performing the pull request.
