### ISSUE TITLE
Does the lib support line numbers?

### ISSUE THREAD

**Issue by caotrongtin99** [dolanmiu/docx#1301]
<img width="548" alt="Screen Shot 2021-11-19 at 5 16 56 PM" src="https://user-images.githubusercontent.com/35460708/142606221-065225f6-1305-48e8-815f-37611f19c5ad.png">

How do we display line numbers for each line? Thanks

**Comment by caotrongtin99** [comment]
@anti-the-social 
Can you help me, bro? 😄 Thanks

**Comment by anti-the-social** [comment]
Hi, @caotrongtin99 :)
You might have seen it in demo folder actually:
70-line-numbers-suppression.ts (https://github.com/dolanmiu/docx/blob/6ede7000fa22fea3706d782bc06e35dcb297eaee/demo/70-line-numbers-suppression.ts)

More about possible options in docx js : 
https://docx.js.org/api/interfaces/ILineNumberAttributes.html

OOXML reference: 
http://officeopenxml.com/WPsectionLineNumbering.php

**Comment by caotrongtin99** [comment]
Thanks a lot @anti-the-social 👍

**Comment by anti-the-social** [comment]
@caotrongtin99 don't forget closing issues once they are resolved 😉

**Comment by caotrongtin99** [comment]
Hi @anti-the-social , it doesn't seem to work on LibreOffice
`  const firstSection = {
    children: [
      new Paragraph({
        text: 'Hello',
        heading: HeadingLevel.HEADING_1
      }),
      new Paragraph(
        'Himenaeos duis luctus nullam fermentum lobortis potenti vivamus non dis, sed facilisis ultricies scelerisque aenean risus hac senectus. Adipiscing id venenatis justo ante gravida placerat, ac curabitur dis pellentesque proin bibendum risus, aliquam porta taciti vulputate primis. Tortor ipsum fermentum quam vel convallis primis nisl praesent tincidunt, lobortis quisque felis vitae condimentum class ut sem nam, aenean potenti pretium ac amet lacinia himenaeos mi. Aliquam nisl turpis hendrerit est morbi malesuada, augue interdum mus inceptos curabitur tristique, parturient feugiat sodales nulla facilisi. Aliquam non pulvinar purus nulla ex integer, velit faucibus vitae at bibendum quam, risus elit aenean adipiscing posuere.'
      ),
      new Paragraph({
        text:
          'Enim mollit nostrud ut dolor eiusmod id sit occaecat dolore culpa amet. Veniam dolor consequat dolor labore ullamco laborum dolore eiusmod qui adipisicing. Elit nulla cupidatat et magna. Id eiusmod tempor non laborum ipsum. Veniam et aliqua excepteur duis officia enim elit excepteur fugiat duis. Sit sunt ullamco non dolor est qui deserunt consequat magna. Esse pariatur esse dolor ut excepteur dolor nisi nisi non est cupidatat mollit.',
        suppressLineNumbers: true
      }),
      new Paragraph(
        'Sed laoreet id mattis egestas nam mollis elit lacinia convallis dui tincidunt ultricies habitant, pharetra per maximus interdum neque tempor risus efficitur morbi imperdiet senectus. Lectus laoreet senectus finibus inceptos donec potenti fermentum, ultrices eleifend odio suscipit magnis tellus maximus nibh, ac sit nullam eget felis himenaeos. Diam class sem magnis aenean commodo faucibus id proin mi, nullam sodales nec mus parturient ornare ad inceptos velit hendrerit, bibendum placerat eleifend integer facilisis urna dictumst suspendisse.'
      )
    ]
  }

  const secondSection = {
    properties: {
      lineNumbers: {
        countBy: 1,
        restart: LineNumberRestartFormat.CONTINUOUS
      }
    },
    children: [
      new Paragraph({
        text: 'Hello',
        heading: HeadingLevel.HEADING_1
      }),
      new Paragraph(
        'Himenaeos duis luctus nullam fermentum lobortis potenti vivamus non dis, sed facilisis ultricies scelerisque aenean risus hac senectus. Adipiscing id venenatis justo ante gravida placerat, ac curabitur dis pellentesque proin bibendum risus, aliquam porta taciti vulputate primis. Tortor ipsum fermentum quam vel convallis primis nisl praesent tincidunt, lobortis quisque felis vitae condimentum class ut sem nam, aenean potenti pretium ac amet lacinia himenaeos mi. Aliquam nisl turpis hendrerit est morbi malesuada, augue interdum mus inceptos curabitur tristique, parturient feugiat sodales nulla facilisi. Aliquam non pulvinar purus nulla ex integer, velit faucibus vitae at bibendum quam, risus elit aenean adipiscing posuere.'
      ),
      new Paragraph({
        text:
          'Enim mollit nostrud ut dolor eiusmod id sit occaecat dolore culpa amet. Veniam dolor consequat dolor labore ullamco laborum dolore eiusmod qui adipisicing. Elit nulla cupidatat et magna. Id eiusmod tempor non laborum ipsum. Veniam et aliqua excepteur duis officia enim elit excepteur fugiat duis. Sit sunt ullamco non dolor est qui deserunt consequat magna. Esse pariatur esse dolor ut excepteur dolor nisi nisi non est cupidatat mollit.',
        suppressLineNumbers: true
      }),
      new Paragraph(
        'Sed laoreet id mattis egestas nam mollis elit lacinia convallis dui tincidunt ultricies habitant, pharetra per maximus interdum neque tempor risus efficitur morbi imperdiet senectus. Lectus laoreet senectus finibus inceptos donec potenti fermentum, ultrices eleifend odio suscipit magnis tellus maximus nibh, ac sit nullam eget felis himenaeos. Diam class sem magnis aenean commodo faucibus id proin mi, nullam sodales nec mus parturient ornare ad inceptos velit hendrerit, bibendum placerat eleifend integer facilisis urna dictumst suspendisse.'
      )
    ]
  }

  const doc = new Document({
    sections: [firstSection, secondSection]
  })`

I only want display line numbers at section 2, but it still displays line numbers at section 1

**Comment by anti-the-social** [comment]
Hi @caotrongtin99 :)
Welcome to awesome LibreOffice that can add line numbering only to whole document:
![image](https://user-images.githubusercontent.com/69673750/142860051-dabd6d5b-0d07-4546-9cf1-84bdba425460.png)
![image](https://user-images.githubusercontent.com/69673750/142860148-e644e651-01c1-421a-92ba-39d618b28c49.png)
https://help.libreoffice.org/3.3/Writer/Line_Numbering

**Comment by caotrongtin99** [comment]
Thanks for your help @anti-the-social

**Comment by caotrongtin99** [comment]
Hi @anti-the-social , there are some pages with 24 lines, others with 25 lines even though they are formatted the same. Why? Please help me!

<img width="382" alt="Screen Shot 2021-11-30 at 10 45 15 AM" src="https://user-images.githubusercontent.com/35460708/143982225-4fa3ba2e-501c-4
<img width="381" alt="Screen Shot 2021-11-30 at 10 47 37 AM" src="https://user-images.githubusercontent.com/35460708/143982405-272689d5-ec4a-4718-871e-f6cda9e17d2c.png">
d06-89e9-8f5fbc4fed61.png">

**Comment by anti-the-social** [comment]
@caotrongtin99 how about footer and header? Are they same, do they exist on both of those pages? 

P.s. page margin and page height might also affect, but that is unlikely in your case I think, but worth to check too

**Comment by caotrongtin99** [comment]
Hi @anti-the-social , I have code example about my case
```
const fs = require("fs")
const { Document, Packer, Paragraph, TextRun, Header, LineNumberRestartFormat } = require("docx")


const transcriptLines = [
  'Line 1',
  'Line 2',
  'Line 3',
  'Line 4',
  'Line 5',
  'Line 6',
  'Line 7',
  'Line 8',
  'Line 9',
  'Line 10',
  'Line 11',
  'Line 12',
  'Line 13',
  'Line 14',
  'Line 15',
  'Line 16',
  'Line 17',
  'Line 18',
  'Line 19',
  'Line 20',
  'Line 21',
  'Line 22',
  'Line 23',
  'Line 24',
  'Line 25: It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout',
  'Line 1',
  'Line 2',
  'Line 3',
  'Line 4',
  'Line 5',
  'Line 6',
  'Line 7',
  'Line 8',
  'Line 9',
  'Line 10',
  'Line 11',
  'Line 12',
  'Line 13',
  'Line 14',
  'Line 15',
  'Line 16',
  'Line 17',
  'Line 18',
  'Line 19',
  'Line 20',
  'Line 21',
  'Line 22',
  'Line 23',
  'Line 24',
  'Line 25'
]
const doc = new Document({
    sections: [
        {
          properties: {
            lineNumbers: {
              countBy: 1,
              restart: LineNumberRestartFormat.NEW_PAGE
            }
          },
            headers: {
              default: new Header({
                children: [
                  new Paragraph('Header 1'),
                  new Paragraph('Header 2'),
                  new Paragraph('Header 3')
                ]
              })
            },
            footers: {
              default: new Header({
                children: [
                  new Paragraph('Footer 1'),
                  new Paragraph('Footer 2'),
                  new Paragraph('Footer 3'),
                  new Paragraph('Footer 4')
                ]
              })
            },
            children: transcriptLines.map(line => new Paragraph({
                spacing: {
                  line: 2 * 240
                },
                children: [
                  new TextRun({
                    text: `${line}`,
                    font: 'Courier New',
                    size: 24
                  }),
                ]
            })),
        },
    ],
});

Packer.toBuffer(doc).then((buffer) => {
    fs.writeFileSync("document.docx", buffer);
});
```

Transcript line 25 has 3 lines, so transcript line 25 will move to next page. Please take a look on it. Thanks a lot.

**Comment by caotrongtin99** [comment]
I have just tried with another transcript lines
```
const transcriptLines = [
  'Line 1',
  'Line 2',
  'Line 3',
  'Line 4',
  'Line 5',
  'Line 6',
  'Line 7',
  'Line 8',
  'Line 9',
  'Line 10',
  'Line 11',
  'Line 12',
  'Line 13',
  'Line 14',
  'Line 15',
  'Line 16',
  'Line 17',
  'Line 18',
  'Line 19',
  'Line 20',
  'Line 21',
  'Line 22',
  'Line 23',
  'Line 24 It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout It is a long established fact',
  'Line 25: It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout',
  'Line 1',
  'Line 2',
  'Line 3',
  'Line 4',
  'Line 5',
  'Line 6',
  'Line 7',
  'Line 8',
  'Line 9',
  'Line 10',
  'Line 11',
  'Line 12',
  'Line 13',
  'Line 14',
  'Line 15',
  'Line 16',
  'Line 17',
  'Line 18',
  'Line 19',
  'Line 20',
  'Line 21',
  'Line 22',
  'Line 23',
  'Line 24',
  'Line 25'
]
```

<img width="512" alt="Screen Shot 2021-12-02 at 3 08 30 PM" src="https://user-images.githubusercontent.com/35460708/144382442-6931578f-8e70-464b-8e66-706c4167e2d6.png">
And only get 23 lines at first page, Do you have any solution to resolve the problem 🤪 @anti-the-social ?

**Comment by anti-the-social** [comment]
@caotrongtin99 Great code examples, thank you!

Solution is pretty simple here: don't use paragraph thingy, but rather textRun
Paragraph means that lines of the long sentence would go together on the same page, while textRuns long sentences can be broken into parts with the page break.

```
const fs = require("fs")
const { Document, Packer, Paragraph, TextRun, Header, LineNumberRestartFormat } = require("docx")


const transcriptLines = [
  'Line 1',
  'Line 2',
  'Line 3',
  'Line 4',
  'Line 5',
  'Line 6',
  'Line 7',
  'Line 8',
  'Line 9',
  'Line 10',
  'Line 11',
  'Line 12',
  'Line 13',
  'Line 14',
  'Line 15',
  'Line 16',
  'Line 17',
  'Line 18',
  'Line 19',
  'Line 20',
  'Line 21',
  'Line 22',
  'Line 23',
  'Line 24',
  'Line 25: It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout',
  'Line 1',
  'Line 2',
  'Line 3',
  'Line 4',
  'Line 5',
  'Line 6',
  'Line 7',
  'Line 8',
  'Line 9',
  'Line 10',
  'Line 11',
  'Line 12',
  'Line 13',
  'Line 14',
  'Line 15',
  'Line 16',
  'Line 17',
  'Line 18',
  'Line 19',
  'Line 20',
  'Line 21',
  'Line 22',
  'Line 23',
  'Line 24',
  'Line 25'
]

const pChildren = []
for(let i=0; i<transcriptLines.length; i++){
  const line = transcriptLines[i]
  pChildren.push(
    new TextRun({
      text: `${line}`,
      font: 'Courier New',
      size: 24
    })
  )
  pChildren.push(
    new TextRun({ break: 1 })
  )
}

const doc = new Document({
    sections: [
        {
          properties: {
            lineNumbers: {
              countBy: 1,
              restart: LineNumberRestartFormat.NEW_PAGE
            }
          },
            headers: {
              default: new Header({
                children: [
                  new Paragraph('Header 1'),
                  new Paragraph('Header 2'),
                  new Paragraph('Header 3')
                ]
              })
            },
            footers: {
              default: new Header({
                children: [
                  new Paragraph('Footer 1'),
                  new Paragraph('Footer 2'),
                  new Paragraph('Footer 3'),
                  new Paragraph('Footer 4')
                ]
              })
            },
            children: [ 
              new Paragraph({
                spacing: {
                  line: 2 * 240
                },
                children: pChildren
            }),
          ]
        },
    ],
});

Packer.toBuffer(doc).then((buffer) => {
    fs.writeFileSync("numbered_lines2.docx", buffer);
});
```

**Comment by caotrongtin99** [comment]
> 

Cool! I try it now. Thank you so much!

**Comment by caotrongtin99** [comment]
Can we set haging indent for each transcript line @anti-the-social ?

**Comment by caotrongtin99** [comment]
Do you have any idea @anti-the-social  :((

**Comment by caotrongtin99** [comment]
Hi @anti-the-social , I have a sample code in my case (indent paragraph and align text center)
```
const fs = require("fs")
const { Document, Packer, Paragraph, TextRun, Header, LineNumberRestartFormat, convertInchesToTwip, AlignmentType } = require("docx")


const transcriptLines = [
  'Line 1',
  'Line 2',
  'Line 3',
  'Line 4',
  'Line 5',
  'Line 6',
  'Line 7',
  'Line 8',
  'Line 9',
  'Line 10',
  'Line 11',
  'Line 12',
  'Line 13',
  'Line 14',
  'Line 15',
  'Line 16',
  'Line 17',
  'Line 18',
  'Line 19',
  'Line 20',
  'Line 21',
  'Line 22',
  'Line 24 It is a long established fact that a reader will be distracted.',
  'Line 25: It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout',
  'Line 1',
  'Line 2',
  'Line 3',
  'Line 4',
  'Line 5',
  'Line 6',
  'Line 7',
  'Line 8',
  'Line 9',
  'Line 10',
  'Line 11',
  'Line 12',
  'Line 13',
  'Line 14',
  'Line 15',
  'Line 16',
  'Line 17',
  'Line 18',
  'Line 19',
  'Line 20',
  'Line 21',
  'Line 22',
  'Line 23',
  'Line 24',
  'Line 25'
]
const doc = new Document({
    sections: [
        {
          properties: {
            lineNumbers: {
              countBy: 1,
              restart: LineNumberRestartFormat.NEW_PAGE
            }
          },
            headers: {
              default: new Header({
                children: [
                  new Paragraph('Header 1'),
                  new Paragraph('Header 2'),
                  new Paragraph('Header 3')
                ]
              })
            },
            footers: {
              default: new Header({
                children: [
                  new Paragraph('Footer 1'),
                  new Paragraph('Footer 2'),
                  new Paragraph('Footer 3'),
                  new Paragraph('Footer 4')
                ]
              })
            },
            children: transcriptLines.map((line, index) => {
              if ([1,2,3].includes(index)) {
                return new Paragraph({
                  alignment: AlignmentType.CENTER,
                  children: [
                    new TextRun({
                      text: line,
                      bold: true,
                      font: 'Courier New'
                    })
                  ],
                  spacing: {
                    after: 200,
                    line: 2 * 240
                  }
                }) 
              }
              return new Paragraph({
                spacing: {
                  line: 2 * 240
                },
                indent: {
                  left: convertInchesToTwip(0.3),
                  hanging: convertInchesToTwip(0.3),
                  start: convertInchesToTwip(0.3)
                },
                children: [
                  new TextRun({
                    text: `${line}`,
                    font: 'Courier New',
                    size: 24
                  }),
                ]
            })
          }),
        },
    ],
});

Packer.toBuffer(doc).then((buffer) => {
    fs.writeFileSync("document.docx", buffer);
});

```
Please take a loot on it. Thank you so much!
