### ISSUE TITLE
Edit and add sections, paragraphs on the fly after creating Doc

### ISSUE THREAD

**Issue by Allatir** [dolanmiu/docx#1308]
Is there a way to add sections and paragraphs and/or edit them on the fly? 
is it possible to do something like this: 

var doc = new docx.Document(); 
var paragraph = new docx.Paragraph();

and then later add the text and set the properties?
For my use case, there is no pre-designed document. The users should be able to add these themselves. So it always depends on the users how the document is constructed. 

with kind regards
Bradley

**Comment by anti-the-social** [comment]
Hi @Allatir !

It was like that some times ago, but now it is not possible in this library.
You should rethink logic of your code e.g. 

```
// keep sections as array till it is filled with sections and then create document out of it.
const mySections = []

mySections.push(firstSection)
mySections.push(secondSection)

const doc = new docx.Document({sections: mySections});
```

Similar approach to the paragraphs, tables, rows and other such elements.

**Comment by Allatir** [comment]
Hi thank you, 
this might indeed be the way to go then. 

thank you :)
