### ISSUE TITLE
Docs way newer than released npm module

### ISSUE THREAD

**Issue by schneyer** [dolanmiu/docx#131]
Hi Dolan,

First off, amazing module, well done and thank you!! I was able to render an entire complex doc structure to a docx in about 1 day of work thanks to you.

I hit a snag on adding images, and after digging around in your docs, discovered that you're overhauling image rendering but the library hasn't been updated on npm in quite a while, so I think the version I'm running isn't using all your fixes. (Specifically, I can't get the new Buffer-based image loading to work -- it ALWAYS expects a file path).

Are you planning to release soon?

Thanks,
Evan

**Comment by dolanmiu** [comment]
Released 4.0.0 now

**Comment by schneyer** [comment]
Awesome, thanks for the quick turnaround! FYI, the docs are still not really accurate or clear. Two main issues:

1. It says that image creation takes a Buffer, but that's not true (Buffer fails no matter what) -- I was only able to get it to work once I converted my Buffer to a base64 string.
2. It's not clear how to create an Image prior to adding it to the doc. (doc.createImage creates and adds an ImageParagraph) -- is this intentional?

**Comment by dolanmiu** [comment]
Are you sure?

The example here shows using a buffer and base64 string

Are you using node or browser?

**Comment by schneyer** [comment]
Wow, I don't know what changed but it's working now with the plain buffer (in node). My mistake, and again great work!!

Oh btw, I can open a separate issue for this if it's non-trivial, but question: is there a good way to store a piece of (invisible) meta-data along with a Paragraph? I want to store track an ID of my own sections, so that if a user exports a docx, then makes changes and re-imports I have a way to match up sections. Any ideas?

**Comment by dolanmiu** [comment]
Forgot to post the link:

https://github.com/dolanmiu/docx/blob/master/demo/demo5.ts

> is there a good way to store a piece of (invisible) meta-data along with a Paragraph

Currently thats not supported. Is this a microsoft word feature?

**Comment by dolanmiu** [comment]
Good idea, let me know
