### ISSUE TITLE
Add limit to numbering depth

### ISSUE THREAD

**Issue by jamesmontalvo3** [dolanmiu/docx#1342]
MS Word and Google Docs both have a limit on how deep numbering and bullets can be. Here's a screenshot demonstrating that limit in Word

![image](https://user-images.githubusercontent.com/716482/146392361-05bed10f-ea17-463e-92ea-3a28ebf04fd8.png)

The same limit applies in Google Docs. This library allows creating numbering of arbitrary depth, but upon attempting to open the resulting document you get this error:

![image](https://user-images.githubusercontent.com/716482/146392137-62180342-b4e3-47a2-b91b-7a16a606bf54.png)

It took some time to figure out where the error was coming from, so it would be better if this library added a warning to the user that they've exceeded the maximum depth.

**Comment by dolanmiu** [comment]
Could you send me the code for this? Will be quicker for me to reproduce, then fix

**Comment by dolanmiu** [comment]
Found some material with this:

https://answers.microsoft.com/en-us/msoffice/forum/all/does-word-support-more-than-9-list-levels/d130fdcd-1781-446d-8c84-c6c79124e4d7
