### ISSUE TITLE
ImageRun couldnt work

### ISSUE THREAD

**Issue by ddhearly** [dolanmiu/docx#1356]
### Discussed in https://github.com/dolanmiu/docx/discussions/1350

<div type='discussions-op-text'>

<sup>Originally posted by **ddhearly** December 23, 2021</sup>
Im using <script src="https://unpkg.com/docx@5.0.2/build/index.js"></script> working to create docx using browser but ImageRun could not worked. Please help me to display image in docx. Thankyou</div>

**Comment by anti-the-social** [comment]
There isn't enough information to say why you cannot succeed. Please paste code for us that shows the issue so it is possible to reproduce.
