### ISSUE TITLE
I am getting an error saying e.fill is not a function at the following line of my code: const buffer = await Packer.toBuffer(doc)

### ISSUE THREAD

**Issue by immocenter** [dolanmiu/docx#1357]
My code
```ts
const exportToWord = async () => {
    console.log("Test");
    const doc = new Document({
      sections: [
        {
          properties: {},
          children: [
            new Paragraph({
              children: [new TextRun("Hello World")],
            }),
          ],
        },
      ],
    });`
    `// Used to export the file into a .docx file`
    `const buffer = await Packer.toBuffer(doc);`
    `const blob = new Blob([buffer], {
      type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    });`
    `const link = document.getElementById("test");`
    `link.href = window.URL.createObjectURL(blob);`
    `link.download = "my.docx";`
    `link.click();`
 ` };
```

Full error is as following:
bundle.js:8110 Uncaught (in promise) TypeError: e.fill is not a function
    at Object.allocBuffer (bundle.js:8110)
    at Object.nodebuffer (bundle.js:8968)
    at Object.r.transformTo (bundle.js:9024)
    at i.processChunk (bundle.js:8440)
    at l.<anonymous> (bundle.js:8588)
    at l.emit (bundle.js:8578)
    at l.push (bundle.js:8554)
    at l.push (bundle.js:7815)
    at l.closedSource (bundle.js:7846)
    at i.<anonymous> (bundle.js:7882)

I consoled log the doc object to check if it is getting created and it looked all good. The error is getting thrown when it is converted into a buffer. Any help will be highly appreciated.

Thanks a lot in advance.

**Comment by dolanmiu** [comment]
It looks like you are using it on the browser

Buffer is not supported in the browser setting
try `toBlob` instead:

https://github.com/dolanmiu/docx/blob/master/demo/browser-demo.html
