### ISSUE TITLE
Border For TextRun 

### ISSUE THREAD

**Issue by nguyenvietthinh** [dolanmiu/docx#1360]
Is it possible to put a border for TextRun in Ver 7 ? Thanks !

**Comment by dolanmiu** [comment]
You can maybe use it, try to adapt this code:

https://github.com/dolanmiu/docx/blob/master/demo/26-paragraph-borders.ts

It is for a paragraph, but maybe it works for TextRun too?

**Comment by nguyenvietthinh** [comment]
> You can maybe use it, try to adapt this code:
> 
> https://github.com/dolanmiu/docx/blob/master/demo/26-paragraph-borders.ts
> 
> It is for a paragraph, but maybe it works for TextRun too?

Tks you help but it doesn't work because TextRun doesn't have border attribute like paragraph

**Comment by dolanmiu** [comment]
Will be added with this PR:

https://github.com/dolanmiu/docx/pull/1363
