### ISSUE TITLE
Feature suggestion: allow to use a template (.dotx) for new Document

### ISSUE THREAD

**Issue by amitm02** [dolanmiu/docx#137]
I wander how difficult it will be to enable the creation of new documents based on an existing template file.
It will sure be helpful for my project.

UPDAETE:
More specifically, i'm looking to initiate a new document with a given headers/footers. I've seen there Is "ImportedXmlComponent" class. 
Is this feature already implemented?
Is there a demo for it?

**Comment by dolanmiu** [comment]
Not implemented yet!

Great suggestion, will add to the todos

ImportedXmlComponent is made by @h4buli and co. I think it's for custom Xml elements, correct me if I am wrong

**Comment by amitm02** [comment]
I’m planning to implement it for my project. Any suggestion on where to plug it in, so it will make sense for a pull request? I was thinking to add a File blob as a constructor parameter for the compiler class. Do you feel it is the right approach?

**Comment by dolanmiu** [comment]
The compiler should have no knowledge of the word document for perfect de-coupling.

It's better if its something like:

```
import { TemplateDocument } from 'docx';

const document = new TemplateDocument([TEMPLATE_STUFF_HERE]);
```

where `TemplateDocument` is a subclass of Document (which is `File` in the code):

https://github.com/dolanmiu/docx/blob/master/src/file/file.ts

I think it will be more sexier API

How does this sound to you?

**Comment by h4buli** [comment]
Hi all, 
`ImportedXmlComponent` is used to represent whole xml tag. We use it only to load external styles. There are use cases when you have word file with predefined styles. So we read the 'style.xml' from that file and import in the project. 

For the request to use .dotx, we need new (different) solution than `ImportedXmlComponent`. We need to read whole .docx(dotx) file - meaning all xml files (not just document.xml), create relations, add images and so on. Of course, we can use `ImportedXmlComponent` and `ExternalStylesFactory' to help reading and importing the xml files. 

Note: @dolanmiu there was issue with first implementation of ExternalStylesFactory, maybe we need this PR to be merged here:
https://github.com/h4buli/docx/pull/11

**Comment by amitm02** [comment]
I'll look into it. I plan to do the following:
- build a class that can unzip and read a .dotx file, parse the xml files, and will return an "Header", "Footer" and "Image" objects
- in file.ts: add a function "addHeader(header? : Header)"
- in file.ts: add a function -> "createFooter(footer? : Footer)"

what do you think?

**Comment by amitm02** [comment]
Update: 
I can generate ImportedXmlComponent(s) from the ".dotx" file.

I don't think it is possible to generate the extended classes (e.g Header, Footer), at that point in time because the referenceNumber and Media are not known yet

When generating a new document (File), I plan to allow the use of those ImportedXmlComponent(s), to initialise the content of the extended classes (e.g Header, Footer)

To do that, I'll need to add an optional parameter "initData : XmlComponent" to the constructors XmlComponent and it's extensions (e.g Header, HeaderWrapper, Footer etc'), so it will be possible to init them with data.

**Comment by dolanmiu** [comment]
> What is the best approach the handle the integration? 

Make a seperate branch and make a PR into this repo :) I can also join in and write code into that PR until it is ready

**Comment by dolanmiu** [comment]
Closing as merged

**Comment by techquestions** [comment]
@dolanmiu can you please let me know how this can be done (i.e. creating a new document as a template)?
I could not find a suitable example.

**Comment by dolanmiu** [comment]
@techquestions better to use docxtemplater:

https://github.com/open-xml-templating/docxtemplater

**Comment by techquestions** [comment]
@dolanmiu I am interested in just generating a DOTX document and using it later as a main template in all new Word documents (with overriden Normal nad Heading styles, etc.).

Is that possible with `docx` at the moment?

**Comment by dolanmiu** [comment]
Not possible no, sorry, only .docx is producable

**Comment by tdnelson2** [comment]
Where can I find examples of this implementation (Importing .dotx templates)

**Comment by tdnelson2** [comment]
I found the demo but am looking for an example of it used to extract header and footer. How might I do this? I tried it this way but it didn't work:
```
// Example on how to use a template document
// Import from 'docx' rather than '../build' if you install from npm
const fs = require('fs');
const { Document, ImportDotx, Packer, Paragraph, Header } = require("docx");

const importDotx = new ImportDotx();
const filePath = "./template.dotx";

fs.readFile(filePath, (err, data) => {
    if (err) {
        throw new Error(`Failed to read file ${filePath}.`);
    }

    importDotx.extract(data).then((templateDocument) => {
        const doc = new Document(
            {
                sections: [
                    {
                        headers: templateDocument.headers,
                        properties: {
                            titlePage: templateDocument.titlePageIsDefined,
                        },
                        children: [new Paragraph("Hello World")],
                    },
                ],
            },
            {
                template: templateDocument,
            },
        );

        Packer.toBuffer(doc).then((buffer) => {
            fs.writeFileSync("My Document from Template.docx", buffer);
        });
    });
});
```
