### ISSUE TITLE
Footer of Multiple pages detection

### ISSUE THREAD

**Issue by savitha958** [dolanmiu/docx#1371]
I am trying detect page number present in footer of all pages in the whole document

first page is only recognised rest not

how to read text present in all footer of the word docx document using docx package

section = document.sections[0]
footer=section.footer
footer.paragraphs[0].text
document.sections

**Comment by dolanmiu** [comment]
This is not possible, it is not possible to read the document after it has been created

**Comment by savitha958** [comment]
But text is present in all pages footer
