### ISSUE TITLE
Adding images to a Paragraph

### ISSUE THREAD

**Issue by soutieslak** [dolanmiu/docx#138]
Hi I am having trouble when I try to add images to a paragraph, the .docx file creates the image "place-holder" but it just says "image not available" or "read-error". My code is as follows:

`var doc = new docx.Document();`
`const ImageParagraph = new docx.Paragraph();`
`const myImg = docx.Media.addImage(doc, "images/1.png");//returns 'Image'`
`ImageParagraph.addImage(myImg);//returns 'PictureRun'`
`doc.addParagraph(ImageParagraph);`

Could someone maybe help me, what am I doing wrong?

**Comment by soutieslak** [comment]
So I managed a workaround:

      `var` base64str = base64_encode("images/2.jpeg");`
     `const myImg = docx.Media.addImage(doc, Buffer.from(base64str, "base64"),150, 100);`
      `const ImageParagraph = new docx.Paragraph();`
      `ImageParagraph.addImage(myImg);//returns 'PictureRun'`

In summary `docx.Media.addImage(doc, Buffer.from(base64str, "base64"),150, 100);` works and `docx.Media.addImage(doc, "images/1.png");` does not... Weird

**Comment by dolanmiu** [comment]
Images no longer takes filepaths. It now only takes in `Buffers`:

https://github.com/dolanmiu/docx/blob/master/demo/demo5.ts
https://github.com/dolanmiu/docx/blob/master/demo/demo23.ts

I need to update the documentation

**Comment by soutieslak** [comment]
Ah okay no worries, thought I was doing something wrong heehee! Awesome! Thanks again for the quick support man!

I am starting to familiarise myself with this, it is so epic!

**Comment by dolanmiu** [comment]
no problem!
