### ISSUE TITLE
Getting error with using Packer with Blob

### ISSUE THREAD

**Issue by kharmonycentral** [dolanmiu/docx#139]
Thank you for your work on getting version 4 up, however I have an issue with the packer. In my NodeJs server file I have put in the code from the version 4 documentation for the blob packer.

```
const packer = new docx.Packer();

packer.toBlob(doc).then((blob) => {
    // saveAs from FileSaver will download the file
    saveAs(blob, "example.docx");
});
```

However I am receiving the following message. Is this due to Node not supporting blobs or something of that effect? My version of Node is 9.4.0. Thank you for any assistance!

(node:20663) UnhandledPromiseRejectionWarning: Error: blob is not supported by this platform
    at Object.exports.checkSupport (/home/kharmony/Development/un_ems/node_modules/docx/build/index.js:449:15)
    at JSZip.generateInternalStream (/home/kharmony/Development/un_ems/node_modules/docx/build/index.js:33921:17)
    at JSZip.generateAsync (/home/kharmony/Development/un_ems/node_modules/docx/build/index.js:33949:21)
    at Packer.<anonymous> (/home/kharmony/Development/un_ems/node_modules/docx/build/index.js:33391:40)
    at Generator.next (<anonymous>)
    at fulfilled (/home/kharmony/Development/un_ems/node_modules/docx/build/index.js:33362:58)
    at propagateAslWrapper (/home/kharmony/Development/un_ems/node_modules/async-listener/index.js:478:23)
    at /home/kharmony/Development/un_ems/node_modules/async-listener/glue.js:188:31
    at /home/kharmony/Development/un_ems/node_modules/async-listener/index.js:515:70
    at /home/kharmony/Development/un_ems/node_modules/async-listener/glue.js:188:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)

**Comment by dolanmiu** [comment]
Filesaver only works on the browser side, not Node side AFAIK, you need to use fs.write

**Comment by dolanmiu** [comment]
Closing, re-open if need

**Comment by kharmonycentral** [comment]
Thanks for the response. I do not believe it is an issue with Filesaver. When I comment out the saveAs line, and just add a console log, it gives me the same error without printing the console.log message. The error seems to come from the packer.toBlob line. I have it working using the toBuffer approach, but just wanted to report back the issue as it could be something that you may want to look into in the future. Thanks!

```
packer.toBlob(doc).then((blob) => {
          console.log("blob: " + util.inspect(blob));
          // saveAs from FileSaver will download the file
          // FileSaver.saveAs(blob, "EMS Guidance.docx");
      });
```

**Comment by dolanmiu** [comment]
hmm, maybe `Blob` is not supposed on Node 9.4?

Turns out its true:

https://stackoverflow.com/questions/14653349/node-js-can%C2%B4t-create-blobs
https://stackoverflow.com/questions/47960996/how-to-create-a-blob-in-node-server-side-from-a-stream-a-file-or-a-base64-str

Quote:
> After some research I found that it seems that the Blob constructor is only supported client-side.

Try using base64 or buffer
