### ISSUE TITLE
some unicode symbols break the document

### ISSUE THREAD

**Issue by jeetiss** [dolanmiu/docx#1390]
some unicode characters break the final document

### steps to reproduce

- go to https://runkit.com/jeetiss/61efceae312e0b0008d3a7c3
- download the document with [“Start of text”](https://unicodeplus.com/U+0002) symbol
- try to open

### current behavior

the document is broken and doesn't work

<img width="314" alt="Снимок экрана 2022-01-25 в 13 40 29" src="https://user-images.githubusercontent.com/6726016/150961728-d93f3552-bb15-4eb3-966d-a4242786d6ef.png">

### expected behavior

it works

### versions

docx [5.x,6.x,7.x]

**Comment by dolanmiu** [comment]
It is best to sanitise your text before passing it into `docx`

Before, it was sanitised, but that meant it broke tabs `\t` etc. So it was reverted out.
