### ISSUE TITLE
v4 packer.toBuffer -> fs.writeFileSync dot working in demos

### ISSUE THREAD

**Issue by michaelmyers** [dolanmiu/docx#140]
Attempting to open the generated docx files from the demos (1 & 2 specifically) in Word 16.16 for Mac and am getting an error.

![screen shot 2018-08-31 at 10 42 52 am](https://user-images.githubusercontent.com/921356/44919522-b7851d80-ad0b-11e8-9153-71ca477bba18.png)

I poked around a bit but I'm afraid this one is outside of my expertise.

**Comment by michaelmyers** [comment]
I think I figured it out, it is working on node v10.1.0 but not my ancient default version of 6.10.3.  Is there a minimum version that you know of?  I can open a PR with a `.nvmrc` and `engines` in the package.json.

**Comment by michaelmyers** [comment]
Closing, made #141

**Comment by dolanmiu** [comment]
Thanks, merged!
