### ISSUE TITLE
How to clear the last data

### ISSUE THREAD

**Issue by rxw-people** [dolanmiu/docx#1417]
When exporting many times at the same time, the exported contents will accumulate together. How can I clear them

**Comment by anti-the-social** [comment]
Hi!

There is a big chance that the reason is some sort of mistake in your code.
It would be great if you can paste some sort of code that can reproduce and issue. That helps in debugging, you know. A little hard to guess whats going on at your end :)

**Comment by rxw-people** [comment]
![8S SYC5)4FPVU`4}013E_ZM](https://user-images.githubusercontent.com/74702357/153529624-41d716db-5173-46f1-ac4b-bb9c6aebbd65.png)
I wonder if these can help you. My main code is these

**Comment by anti-the-social** [comment]
Do you do `new Document` for each document created? 
In your case I think it is variable `doc`

**Comment by rxw-people** [comment]
![1](https://user-images.githubusercontent.com/74702357/153790931-61f32591-d598-4d15-a469-a72e3c246158.jpg)
Is that what you're talking about? I have only one `new Document`,
and my code framework is this：
```
const doc = new docx.Document();
doc.addSection({
     children:[
    
     ]
})
docx.Packer.toBlob(doc).then((blob) => {
    saveAs(blob, "test.docx");
    console.log("success");
});
// Clear historical data
doc.addSection = () => {
    return {}
}
```

**Comment by rxw-people** [comment]
My problem seems to have been solved. I should put the `new Document` outside my function, but I have a question. Why do I put the `new Document` inside the function, the previously exported data cannot be cleared, and my function is only used once

**Comment by anti-the-social** [comment]
It really depends on your code structure. I can't answer your question.
Nevetheless, normally in logic sequence each request to create a document should have its own `new Document` so content doesn't overlap in any way.

**Comment by anti-the-social** [comment]
I also would like to ask to you to close issue once you feel satisfied / issue resolved. :)

**Comment by rxw-people** [comment]
Well, thank you very much.
