### ISSUE TITLE
I can't seem to get the latest data

### ISSUE THREAD

**Issue by xiaowen-Ren** [dolanmiu/docx#1419]
Hello, 
If my data is asynchronous, and I export the document before the data is displayed on the page, the exported document data displays the original data of the page, not the newly acquired data. What is the reason?

**Comment by anti-the-social** [comment]
Hi!

This doesn't sound like a problem in the lib, so it is a little wrong place to ask such a question.

Nevertheless, I think you might want to consider activate button "create document" only after you get your data from the server. In this way document would be possible to create only with newly acquired data.

**Comment by xiaowen-Ren** [comment]
Thank you. That's a good idea
