### ISSUE TITLE
How to activate 'Different First Page'

### ISSUE THREAD

**Issue by Hamza-Khyara** [dolanmiu/docx#1426]
It says in the documentation that the header on the first page will be applied when the 'Different First Page' option is activated, but it is not mentioned how to activate it. The same for activating 'Different Odd & Even Pages'.

**Comment by anti-the-social** [comment]
Hi!

You are looking for "titlePage" boolean property of the sections to activate 'Different First Page'
https://docx.js.org/api/interfaces/ISectionPropertiesOptions.html#titlePage

And I think odd/even is automatically activated once you specify even footer/header, but worth to test.

**Comment by Hamza-Khyara** [comment]
It works, thanks a lot.
