### ISSUE TITLE
Base64 cannot be used to export pictures in the browser

### ISSUE THREAD

**Issue by zhangheng1109** [dolanmiu/docx#1430]
Using 'fs.readFileSync("./demo/images/dog.png").toString("base64")' in nodejs, get Base64 result without 'data:image/png;base64,'.
When used in my Vue 2.0 project, no 'data:image/png;base64,' will report an error,the docx file generated by manually prefixing 'data:image/png;base64,' cannot be opened(see the picture below)
How can we solve this problem? Thank you
![20220223111326](https://user-images.githubusercontent.com/30252418/155256182-e85defb3-8fd3-44fc-ab96-d9573e985bdf.png)
![20220223110637](https://user-images.githubusercontent.com/30252418/155256188-314ae247-c220-4d8d-b2b1-23e9a38b18df.png)

**Comment by duanwenjian** [comment]
How to solve it?

**Comment by duanbaosheng** [comment]
i  meet the  same  problem!   how to deal with it ?
