### ISSUE TITLE
docx.NumberFormat is undefined

### ISSUE THREAD

**Issue by Hamza-Khyara** [dolanmiu/docx#1431]
I'm trying to determine a page starting number in a section, I defined the section properties as follows:
`properties: {
    page: {
        pageNumbers: {
            start: 1,
            formatType: docx.NumberFormat.DECIMAL,
        },
    },
}`,
but I get an error that docx.NumberFormat is undefined, I'm using docx@7.3.0.
if I comment formatType I get this message from the generated document
![image](https://user-images.githubusercontent.com/76873551/155313544-07070c6e-adab-4d06-950f-fc80afe25e9d.png)

**Comment by anti-the-social** [comment]
Hi!

Are you sure that you are running code within a browser?
If I put in this fiddle https://jsfiddle.net/dolanmiu/onadx1gu/
`console.log( docx.NumberFormat.DECIMAL)`
It is defined and equal `decimal`

**Comment by Hamza-Khyara** [comment]
You are right, my error was in another line, thank you
