### ISSUE TITLE
Image not showing using 4.0.0 packer

### ISSUE THREAD

**Issue by kharmonycentral** [dolanmiu/docx#144]
When I use version 3.6.0 LocalPacker, the image shows up in the exported document. Now when I use the toBuffer method in 4.0.0 the image no longer appears in the document. I use fs.writeFileSync("My Document.docx, buffer) to save the file to the server (for 4.0.0) I am using the same code to add the image to the document:

`var image = doc.createImage('app/img/interested-parties.png');`

When I log the media for the document (before packing) I get the following:

**3.6.0 version:**
```
doc: Media {
  map: 
   Map {
     'interested-parties.png' => { referenceId: 6,
     stream: [ReadStream],
     path: 'app/img/interested-parties.png',
     fileName: 'interested-parties.png',
     dimensions: [Object] } } }
```

**4.0.0 version**
```
doc: Media {
 map: 
  Map {
    'yd2g7tze36hyavgl3kx0ch.png' => { referenceId: 7,
    stream: <Buffer 6a 9a 7f 8a 68 3f 8a 7b 5e ad eb 2d 79 df a9 6a bb 62 7a ca 67 80>,
    path: undefined,
    fileName: 'yd2g7tze36hyavgl3kx0ch.png',
    dimensions: [Object] } } }
```

**Comment by kharmonycentral** [comment]
I was able to resolve the issue by using fs.readFileSync('app/img/interested-parties.png'). This was in the examples but the Usage documentation just says [BUFFER_OF_YOUR_IMAGE] so it wasn't totally clear. You can close this issue. Thanks

**Comment by dolanmiu** [comment]
I am working on making the documentation more clear

Glad you got it working
