### ISSUE TITLE
Getting Error while Updating from v5.5.0 to v7.3.0

### ISSUE THREAD

**Issue by noobyogi0010** [dolanmiu/docx#1443]
# Thank you for raising an issue to `docx`

Please do not raise an issue unless it is an **issue**.

-   Is your issue a feature request? Are you giving ideas to the community? Are you asking for help? Please raise a ticket in the `Discussions` section:

    https://github.com/dolanmiu/docx/discussions

    No, it's not a feature request.

-   Is your issue previously asked? Please respond to that thread instead

    No.

**Issue Description**

My app is working fine using docx `v5.5.0` but as soon as I am updating the version to `v7.3.0` I am getting the following error when I try to download the output docx file:

```
Unhandled rejection TypeError: Cannot read properties of undefined (reading 'creator')
    at new Yo (C:\Projects\demo\node_modules\docx\build\index.js:2:291617)
    at DocumentCreator.create (C:\Projects\demo\queries.js:4695:22)
    at C:\Projects\demo\queries.js:4806:33
    at tryCatcher (C:\Projects\demo\node_modules\bluebird\js\release\util.js:16:23)
```

I searched a lot for some solution but I was not able to find anything.

Can you please help me with this?

**Comment by dolanmiu** [comment]
Look at this example of how it is done now

The API has changed a little since v5:

https://github.com/dolanmiu/docx/blob/master/demo/66-fields.ts

**Comment by noobyogi0010** [comment]
Thank you @dolanmiu 
This significantly solves my problem. I will be changing my implementation.
I will go ahead and close this issue.
