### ISSUE TITLE
TableCellProperties - setVerticalAlign

### ISSUE THREAD

**Issue by soutieslak** [dolanmiu/docx#146]
I am trying to set the vertical alignement of a cell in my tabel to be "centre" but I am not succeeding.

`const Analysis = new docx.Paragraph("This text should  be in the middle of the cell");`
`table.getCell(6, 0).addContent(Analysis).CellProperties.setVerticalAlign("CENTER");`

When I try open the word document in windows 10, with Microsoft Word 365, then it gives an error:

_We're sorry. We can't open DocumentName.docx because we found a problem with its contents.
Details
Unspecified error
Location: Part: /word/document.xml, Line: 0, Column: 0_

Any idea or help? Am I assigning the setVerticalAlign(type: VerticalAlign) correctly?

I saw that the type is defined as follows:
export enum VerticalAlign {
    BOTTOM = "bottom",
    CENTER = "center",
    TOP = "top",
}

**Comment by dolanmiu** [comment]
Here you go:

```
const doc = new Document();

const table = doc.createTable(4, 4);
table.getCell(2, 2).addContent(new Paragraph("This text should be in the middle of the cell")).CellProperties.setVerticalAlign(VerticalAlign.CENTER);

const packer = new Packer();

packer.toBuffer(doc).then((buffer) => {
    fs.writeFileSync("My Document.docx", buffer);
});
```

**Comment by soutieslak** [comment]
You champ! Thank you so much fot the epic support!!!!

I am busy with NodeJS and declare this module as:
`var docx = require('docx');`

In your example I was getting "_VerticalAlign not defined_" so I changed it to:

`table.getCell(2, 2).addContent(new Paragraph("This text should be in the middle of the cell")).CellProperties.setVerticalAlign(**docx.**VerticalAlign.CENTER);`

And all works!!! Thanks dude! I really love this API!!!!

**Comment by leonardo1294** [comment]
I am creating an application using electron and react, and I will need to create a Word text document dynamically, I found a great package, DOCX, but I need to create some tables, and I can't set the size of the columns, I need help setting the size of the columns, follows an excerpt from the code, and documentation link https://docx.js.org/#/
`// eslint-disable-next-line
import { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, VerticalAlign, HeadingLevel } from 'docx';
const {dialog} = window.require('electron').remote;
const app = window.require('electron').remote
const fs = app.require('fs');

const doc = new Document();

export default function createDocx(){

    const table = new Table({
        rows: [
            new TableRow({
                children: [
                    new TableCell({
                        children: [new Paragraph({}), new Paragraph({})],
                        verticalAlign: VerticalAlign.CENTER,
                    }),
                    new TableCell({
                        children: [new Paragraph({}), new Paragraph({})],
                        verticalAlign: VerticalAlign.CENTER,
                    }),
                ],
            }),
            new TableRow({
                children: [
                    new TableCell({
                        children: [
                            new Paragraph({
                                text:
                                    "Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah",
                                heading: HeadingLevel.HEADING_1,
                            }),
                        ],
                    }),
                    new TableCell({
                        children: [
                            new Paragraph({
                                text: "This text should be in ",
                            }),
                        ],
                        verticalAlign: VerticalAlign.CENTER,
                    }),
                ],
            }),
        ],
    });
doc.addSection({
    properties: {},
    children: [
        table
    ],  
});

    var options = {
        title: "Save file",
        defaultPath : "my_filename",
        buttonLabel : "Save",

        filters :[
        {name: 'docx', extensions: ['docx',]},
        {name: 'txt', extensions: ['txt',]},
        {name: 'All Files', extensions: ['*']}
        ]
    }


    // Used to export the file into a .docx fil    
    dialog.showSaveDialog(options, (fileName) => {
        if (fileName === undefined){
            console.warn("You didn't save the file");
            return;
        }       
    }).then(result => {
        const filename = result.filePath;
        Packer.toBuffer(doc).then((buffer) => {     
            fs.writeFile(filename, buffer, (err) => {
                if(err){
                    alert("Erro ao salvar o arquivo, causa: "+ err.message)
                }else{
                    alert("Arquivo Salvo com Sucesso !!");
                }                       
            });
        });  
    }).catch(err => {
        alert(err)
    })

}`
