### ISSUE TITLE
How to insert page number in header in one row and different align?

### ISSUE THREAD

**Issue by zackzergzeng** [dolanmiu/docx#1464]
like this
![image](https://user-images.githubusercontent.com/42129897/160114092-2b104733-e1d1-4ae1-bcf5-fe18871c86b2.png)
header text in left and page number in right

**Comment by anti-the-social** [comment]
Hi!

In brief, you have an option to use frames or tables for this purpose https://github.com/dolanmiu/docx/issues/1082

**Comment by zackzergzeng** [comment]
It's useful, but my code use docx 5.2.2, this version not have this function.
I see docx 6.0.0 need node version > 10, but i use node version is 8.
so why the docx need node version > 10 after 6.0.0, and can docx 6.0.0 be used in node 8?

**Comment by anti-the-social** [comment]
Just got 5.2.2 on my pc and yes, it seems it doesn't have implementation for "w:framePr" which stands for iframes. To my understanding these text frames first appeared on version 6
Semi fix for the old version to your problem would be table with one row and two cells.

So I guess you either migrate to newer version of docx and potentially node (didn't check requirements) or stick to tables 
There isn't much dependant on node version in docx js library, potentially you can try to run on v8 like you say, but be ready for surprises.

**Comment by zackzergzeng** [comment]
Okay, i got it.
Thank you very much!

**Comment by anti-the-social** [comment]
Don't forget to close your issue once it's resolved :)
