### ISSUE TITLE
Zero Width Spacers are converted incorrectly

### ISSUE THREAD

**Issue by deathg0d** [dolanmiu/docx#1475]
I have a weird issue where the docx files I create contain incorrect zero width spacers. For example let's look at this word: `कर्‍याप्प`. If I create a docx file containing this word, the word converts to `कर्‌याप्प`. I checked the unicode values for these words and they are different:

```
'कर्‍याप्प'.split('').map((x)=>{return `${x}, ${x.charCodeAt(0)}`}).join("; ")
output: "क, 2325; र, 2352; ्, 2381; ‍, 8205; य, 2351; ा, 2366; प, 2346; ्, 2381; प, 2346"
```

```
'कर्‌याप्प'.split('').map((x)=>{return `${x}, ${x.charCodeAt(0)}`}).join("; ")
output: "क, 2325; र, 2352; ्, 2381; ‌, 8204; य, 2351; ा, 2366; प, 2346; ्, 2381; प, 2346"
```

As you can see the unicode value for the zerowidth character has changed from 8205 to 8204? Any idea what's going on?

**Comment by dolanmiu** [comment]
I am unsure, but most likely not to do with docx, but with the serialisation library `xml-js`. `docx` does not change any characters or text etc. It doesn't even escape it. All handled by other libraries
