### ISSUE TITLE
possible to inherit numbering.xml from template file

### ISSUE THREAD

**Issue by ui3o** [dolanmiu/docx#1477]
## numbering.xml from template

When I use a template file I set some numbering for header in template.docx . Docx do not copy numbering.xml from template. 

Is that possible to copy my numbering.xml into the new generated.docx?

Thank you for your help, and for your work!

**Comment by anti-the-social** [comment]
Hi!

Not to this moment. But you can potentially build some sort of parsing yourself ofc :) 
@dolanmiu I have seen few of such requests, I assume we can count this issue as feature request.

**Comment by dolanmiu** [comment]
Yes not at this moment, out of scope Im afraid
