### ISSUE TITLE
Option to set a "First page" Header or Footer is missing.

### ISSUE THREAD

**Issue by Rexter-DS** [dolanmiu/docx#1486]
The documentation for the Headers & Footers mentions there being an option that we can set to be able to use "even and odd" headers or "first page" headers. https://docx.js.org/#/usage/headers-and-footers

However, I cannot find any option to toggle the "first page" header. I can only find the property "evenAndOddHeaderAndFooters" that would set the "even and odd" headers.

```
export interface IPropertiesOptions {
    readonly sections: ISectionOptions[];
    readonly title?: string;
    readonly subject?: string;
    readonly creator?: string;
    readonly keywords?: string;
    readonly description?: string;
    readonly lastModifiedBy?: string;
    readonly revision?: number;
    readonly externalStyles?: string;
    readonly styles?: IStylesOptions;
    readonly numbering?: INumberingOptions;
    readonly footnotes?: {
        readonly [key: string]: {
            readonly children: Paragraph[];
        };
    };
    readonly background?: IDocumentBackgroundOptions;
    readonly features?: {
        readonly trackRevisions?: boolean;
        readonly updateFields?: boolean;
    };
    readonly compatabilityModeVersion?: number;
    readonly customProperties?: ICustomPropertyOptions[];
    readonly evenAndOddHeaderAndFooters?: boolean;
}
```

**Comment by anti-the-social** [comment]
Hi!

The properties you found are enabling those headers/footers, but headers and footers themselves are specified into section options take a look here:
https://docx.js.org/api/interfaces/ISectionOptions.html

**Comment by Rexter-DS** [comment]
Right, I understand that. However, there is no property that enables a "First page" header/footer.

```
const doc = new Document({
    // This property allows for there to be a different header/footer on even and odd pages
    evenAndOddHeaderAndFooters: true,
    sections: [{
        headers: {
            default: new Header({ 
                children: [],
            }),
            even: new Header({
                children: [],
            }),
        },
        footers: {
            default: new Footer({ 
                children: [],
            })
            even: new Footer({ 
                children: [],
            }),
        },
        children: [],
    }];
});
```
The property above ``evenAndOddHeaderAndFooters: true`` allows for the ``even: new Header({ ... })`` to show up as the header on even pages.  Without ``evenAndOddHeaderAndFooters: true``, the code above will not work.

However, the case is not true for ``first: new Header({ ... })``. I do not see a property that allows for the ``first`` header/footer section property to be utilized and show up on the document.

```
const doc = new Document({
    // --- Missing property that would allow for first to be utilized ---
    sections: [{
        headers: {
            default: new Header({ 
                children: [],
            }),
            first: new Header({
                children: [],
            }),
        },
        footers: {
            default: new Footer({ 
                children: [],
            })
            first: new Footer({ 
                children: [],
            }),
        },
        children: [],
    }];
});
```
Simply having the code above does not work as per the documentation in https://docx.js.org/#/usage/headers-and-footers, there exist an option that allows for ``first`` to work but as far as I can see, there are none.
```
first: new Header({ // The header on first page when the 'Different First Page' option is activated
                children: [],
            }),
```

**Comment by anti-the-social** [comment]
Hello again :) 

Now I understand, @Rexter-DS 
You are looking for `titlePage` section property. That enables first page headers&footers.
https://github.com/dolanmiu/docx/blob/0b0a185/src/file/document/body/section-properties/section-properties.ts#L39

**Comment by Rexter-DS** [comment]
Awesome! Thank you so much for the help!
