### ISSUE TITLE
Text frame position has to be optional

### ISSUE THREAD

**Issue by anti-the-social** [dolanmiu/docx#1487]
Me greetings :) 

According to my investigation the frame position properties have to be optional.
If `w:x` and `w:y` specified then alignment properties are ignored (`w:xAlign`, `w:yAlign`) 
https://github.com/dolanmiu/docx/blob/853219d/src/file/paragraph/frame/frame-properties.ts#L32

Proof of the concept:
Initial outlook
<img width="756" alt="image" src="https://user-images.githubusercontent.com/69673750/163956875-7583254c-a77f-4105-9a6c-ee405e975a84.png">
Source code
<img width="436" alt="image" src="https://user-images.githubusercontent.com/69673750/163957109-72b6eeed-b59f-475e-9047-21d70830c544.png">
Deleted w:x & w:y
<img width="436" alt="image" src="https://user-images.githubusercontent.com/69673750/163957277-97e2f5fb-4097-4216-9ead-c83116d4173b.png">
Output in a proper place
<img width="783" alt="image" src="https://user-images.githubusercontent.com/69673750/163957471-9a73f825-3b10-487c-b193-bfca1632b5db.png">

**Comment by anti-the-social** [comment]
Just realised this is a more detailed description for the issue I've risen some time ago: https://github.com/dolanmiu/docx/issues/933

**Comment by dolanmiu** [comment]
Ah, seems like an easy one to fix, I'll see if I could get round to it, and also add string values `left` and `right`, as you mentioned in #933

What other values could this be?

**Comment by anti-the-social** [comment]
That issue https://github.com/dolanmiu/docx/issues/933 wasn't too correct as I can see now.
Those values are coming from different places. It does take `w:x` if specified, but if it is not then it takes `w:xAlign` as left/right/center. So no additional values need to be added for position (`w:x`) :) 
<img width="646" alt="image" src="https://user-images.githubusercontent.com/69673750/163981292-0b43012d-fa32-4555-ade5-631d4ecb4b62.png">

**Comment by anti-the-social** [comment]
Its literally adding one question mark to solve this issue 😅
`readonly position: {` 
To
`readonly position?: {`
Here:
https://github.com/dolanmiu/docx/blob/853219d/src/file/paragraph/frame/frame-properties.ts#L32

**Comment by dolanmiu** [comment]
> If w:x and w:y specified then alignment properties are ignored (w:xAlign, w:yAlign)

What about a union type?

```ts
options: IXYPositionedFrameOptions | IAlignedFrameOptions
```

**Comment by anti-the-social** [comment]
Marvellous!  :)
