### ISSUE TITLE
ES5 support create-react-app wouldn't minify this module

### ISSUE THREAD

**Issue by caguilar187** [dolanmiu/docx#150]
I have this commit which solves this issue by targeting ES5. Is this something you would want in in the main repo? I was using this module in a react app and it wouldn't build when trying to get the distribution build. Took me a way to figure it out, so putting this here anyway for documentation sake for anyone else. Feel free to close if you decide not, otherwise i can clean up my package.json for a merge request.

https://github.com/fuzz-productions/docx/commit/a82ca78690d15e50f777d9e520c7afc2058cd88d

**Comment by dolanmiu** [comment]
By the way,

I am thinking of adding a section of companies which use this library

Is it ok if I put Fuzz Productions on the list?

**Comment by caguilar187** [comment]
Sure sounds good to me.

**Comment by dolanmiu** [comment]
`docx` is now supported in React:

https://stackblitz.com/edit/react-ts-qq25sp
