### ISSUE TITLE
Unable to Output Total Page Count

### ISSUE THREAD

**Issue by barberousse** [dolanmiu/docx#151]
The current API appears to only permit rendering the current page number, but no total page count number along with an optional separator.

**Comment by dolanmiu** [comment]
Yes, this is not supported yet

Will add as a feature request

**Comment by dolanmiu** [comment]
Done!

https://github.com/dolanmiu/docx/pull/247

Will be released in 4.7.0 tomrrow!

Thanks all

**Comment by dolanmiu** [comment]
Released!

This is a guide on how to use:

https://docx.js.org/#/usage/page-numbers
