### ISSUE TITLE
Cell vertical align prop is more explicit, than it should be

### ISSUE THREAD

**Issue by anti-the-social** [dolanmiu/docx#1514]
Bonjiorno :) 

While going through cells and it's alignment I noticed that `ITableCellOptions.verticalAlign` has more options, than OOXML specs provide (there is no "both"):

**OOXML:**
<img width="803" alt="image" src="https://user-images.githubusercontent.com/69673750/168008667-6e1ba2ac-5e6a-48bf-ab62-1e6b3ff93e7c.png">
http://officeopenxml.com/WPtableCellProperties-verticalAlignment.php

**The DOCX JS library**
<img width="803" alt="image" src="https://user-images.githubusercontent.com/69673750/168008800-e2e9d406-c752-4d90-9d21-ca89ca6a943d.png">
https://docx.js.org/api/enums/VerticalAlign.html

That is minor thing, altho worth to fix

**Comment by anti-the-social** [comment]
Checked source code, and `verticalAlign` seems to be created only for table cell alignment and it doesn't affect other elements.

And yeah, I guess that "both" came from horizontal alignment values, where both means justify

**Comment by dolanmiu** [comment]
Nice find, will make a PR later
