### ISSUE TITLE
Synchronous Compiler.compile?

### ISSUE THREAD

**Issue by felipeochoa** [dolanmiu/docx#154]
Is there a reason to keep [`Compiler.compile`](https://github.com/dolanmiu/docx/blob/5b28eb0d00b14d26fa2647b82ffb400bd897a00e/src/export/packer/next-compiler.ts#L35) synchronous? There are no awaits in there, so the current method could be sync, but not sure if you were planning on adding async calls

**Comment by dolanmiu** [comment]
Good point

I think it was remnants of the old compiler, which was async

Should be removed yes, but it may be slightly too late now because of backwards compatibility

**Comment by dolanmiu** [comment]
Will do for `v5.0.0` as this will break the API
