### ISSUE TITLE
Instantiating/referencing the same footnote ID across two FootnoteReferenceRuns produces structural errors.

### ISSUE THREAD

**Issue by wonder-bread** [dolanmiu/docx#1554]
Hi! Sorry to bother - been browsing through the documentation and demos, but haven't seen anything pertaining to this specific issue.

In some cases, our users would like to be able to reference the same footnote across distinct bodies/paragraphs/etc.

For example, footnote `1` should be pointed to at the end of two distinct `TextRun`s. In Word, this is apparently solved via the instantiation of a "cross-reference" (https://support.microsoft.com/en-us/office/create-a-cross-reference-300b208c-e45a-487a-880b-a02767d9774b), with the reference pointing to a footnote.

I was curious if the same behavior existed in Docx.js via the `FootnoteReferenceRun` structure, which otherwise works great - but if you instantiate a `FootnoteReferenceRun` with the same ID twice, e.g.,:

```
const bla = new FootnoteReferenceRun(1);
const bla2 = new FootnoteReferenceRun(1);

// ... 

return new Document({
    footnotes: {
        1: { children: [new Paragraph('a test footnote!')] }
    },
    sections: [
        {
            children: [
                new Paragraph({ children: [new TextRun('hi!'), bla] }),
                new Paragraph({ children: [new TextRun('hello again!'), bla2]})
            ]
        }
    ]
});
```

The resulting document will open, but Word will complain about structural errors, and you end up with a single footnote in the footer (as expected), but in the actual body of content, two distinct footnote numbers - a 1 and a (non-existent) 2.

I suppose I'm just trying to find clarification on (1) if this functionality even currently exists in the package, and (2) how to otherwise rectify the issue.

It's been a blast working with the package otherwise! Absolutely phenomenal work. Please let me know if this isn't clear enough - this is my first time posting an issue on GitHub. :)

**Comment by dolanmiu** [comment]
Interesting

I just had a play around, and yeah it does seem like you can't re-use references

I guess this isn't a supported feature in Word or OOXML :(
