### ISSUE TITLE
404s in documentation

### ISSUE THREAD

**Issue by khill-fbmc** [dolanmiu/docx#1568]
![image](https://user-images.githubusercontent.com/107003416/176716761-bd7e364b-acb9-4052-8186-891635fccdf1.png)
![image](https://user-images.githubusercontent.com/107003416/176717087-177f9d9c-42ed-41bc-9510-8ebb51ab4437.png)
![image](https://user-images.githubusercontent.com/107003416/176717141-72ec789e-2be0-474c-afac-1853fbe09df3.png)
I keep running into some 404s while navigating the documents... 🤔

**Comment by dolanmiu** [comment]
Could you give me reproduction steps? For me, its working fine
