### ISSUE TITLE
Using docx@v7.4.0 in Deno will prevent the process from finishing

### ISSUE THREAD

**Issue by wvbe** [dolanmiu/docx#1578]
I've been using `docx` in Deno by importing it from the esm.sh CDN. This is a service that performs some code transformation to serve NPM packages in an ES format. Conveniently it can be used to use just about any NodeJS module in Deno.

So far, `docx@7.3.0` has been working like a dream.

Unfortunately, bumping the dependency version to `docx@7.4.0` will prevent the process from finishing naturally.

**To reproduce:**

1. [Install Deno](https://deno.land/#installation) or run it in a Docker container
2. Create a file `test.ts` and paste the following contents into it;
	```ts
	import docx from 'https://esm.sh/docx@7.3.0';
	new docx.Document({
		sections: [],
	});
	console.log('End of program');
	```
3. Run it as `deno run test.ts`

nb; using Docker, an easy way to reproduce is to `docker run -it --init denoland/deno:ubuntu sh`, then `echo "import docx from 'https://esm.sh/docx@7.4.0'; new docx.Document({ sections: [] }); console.log('End of program');" > test.ts` and `deno run test.ts`.

**Expected**
- The process exits after logging "End of program" to terminal" -- which is what happens for the same script in NodeJS, or for the same script but depending on `7.3.0`

**Observed**
- "End of program" is logged to terminal, and
- The process never finishes

**Comment by dolanmiu** [comment]
Interesting

Does this work fine in a regular NodeJS environment?

Would you think this issue would be fixed if this module is built as a regular ESM module? This was something I was planning to do, so there shouldn't be any need for transformations

I don't know what could be breaking it, all the end-to-end tests seem to pass

**Comment by dolanmiu** [comment]
Just tested it on deno. First time I've used deno

The good news is, that at least the library works

But strange how it doesn't exit

**Comment by dolanmiu** [comment]
A workaround is calling `Deno.exit()`:

```ts
import docx from "https://esm.sh/docx@7.4.0";

const doc = new docx.Document({
  sections: [
    {
      properties: {},
      children: [
        new docx.Paragraph({
          children: [
            new docx.TextRun("Hello World"),
            new docx.TextRun({
              text: "Foo Bar",
              bold: true,
            }),
            new docx.TextRun({
              text: "\tGithub is the best",
              bold: true,
            }),
          ],
        }),
      ],
    },
  ],
});

docx.Packer.toBuffer(doc).then((buffer) => {
  Deno.writeFileSync("My Document.docx", buffer);
  Deno.exit();
});


```

**Comment by dolanmiu** [comment]
Excellent find!

Thank you so much
