### ISSUE TITLE
Numbering restart

### ISSUE THREAD

**Issue by trzopekm** [dolanmiu/docx#158]
Hello,
Is it possible to restart a numbering set on a header paragraph?

**Comment by dolanmiu** [comment]
can you show a picture of a word document to what you mean?

**Comment by flaglerkid** [comment]
Hello, I am having a similar issue.

Please see attached. I would like the list that starts at 5 to restart at 1.

I searched the code and I can't see any method that applies the <w:lvlRestart w:val="1"/> value to a numbering format as required:
http://officeopenxml.com/WPnumbering-restart.php

Attached is a file created using docx that has the issue:
[420bcb9a-92f8-4c11-9ca2-8549b02712e6.docx](https://github.com/dolanmiu/docx/files/2709142/420bcb9a-92f8-4c11-9ca2-8549b02712e6.docx)

And here is the file that has been fixed manually:
[420bcb9a-92f8-4c11-9ca2-8549b02712e6_Fixed.docx](https://github.com/dolanmiu/docx/files/2709144/420bcb9a-92f8-4c11-9ca2-8549b02712e6_Fixed.docx)

**Comment by lane-meisenheimer** [comment]
@trzopekm, @flaglerkid I found this issue happened for me because I instantiated multiple instances of the 
[Numbering Class](https://github.com/dolanmiu/docx/blob/master/src/file/numbering/numbering.ts) which reset the id counter ([nextId](https://github.com/dolanmiu/docx/blob/master/src/file/numbering/numbering.ts#L38)) to zero each time I instantiated it.

For example the code below produces the issue:

```javascript
const doc = new Document();
const makeList = (doc, items) => {
    const numbering = new Numbering();
    const abstractNum = numbering.createAbstractNumbering();

    abstractNum.createLevel(0, "upperRoman", "%1", "start");

    const concrete = numbering.createConcreteNumbering(abstractNum);

    items.forEach((item)) => {
        const itemPara = new Paragraph(item);
        itemPara.setNumbering(concrete, 0);
        doc.addParagraph(itemPara);
    });
};

makeList(doc, ['a', 'b', 'c']);
doc.addParagraph(new Paragraph('Some text in between'));
makeList(doc, ['d', 'e', 'f']);
```

When I output to word, it gives a document with the following structure:

1. a
2. b
3. c

Some text in between

4. d
5. e
6. f

Whereas the following resolves the issue for me:

```javascript
const doc = new Document();

const numbering = new Numbering();

const makeList = (doc, items) => {
    const abstractNum = numbering.createAbstractNumbering();

    abstractNum.createLevel(0, "upperRoman", "%1", "start");

    const concrete = numbering.createConcreteNumbering(abstractNum);

    items.forEach((item)) => {
        const itemPara = new Paragraph(item);
        itemPara.setNumbering(concrete, 0);
        doc.addParagraph(itemPara);
    });
};

makeList(doc, ['a', 'b', 'c']);
doc.addParagraph(new Paragraph('Some text in between'));
makeList(doc, ['d', 'e', 'f']);
```
When I output this to word I get this structure:

1. a
2. b
3. c

Some text in between

1. d
2. e
3. f

@dolanmiu maybe a note in the docs is all that's needed?

**Comment by dolanmiu** [comment]
Ah interesting, so you moved `const numbering = new Numbering();` to the top?

**Comment by lane-meisenheimer** [comment]
Yes, moving `const number = new Numbering();` out of the functional scope fixed the issue.  

In terms of a more intuitive way, it seems like each document should always only have one `Numbering` associated with it.

Perhaps having the doc class instantiate its own numbering property and exposing that property via an accessor would help in most standard cases.

**Comment by dolanmiu** [comment]
> Yes, moving `const number = new Numbering();` out of the functional scope fixed the issue.

Now you no longer need to create a new `Numbering` now, as the document has one.

> In terms of a more intuitive way, it seems like each document should always only have one `Numbering` associated with it.

There shouldn't be any issues now

If there is, re-open this!
