### ISSUE TITLE
Are these test descriptions accidental copy overs?

### ISSUE THREAD

**Issue by khill-fbmc** [dolanmiu/docx#1584]
https://github.com/dolanmiu/docx/blob/f183d38bb366e022cd66684130478d7aef51d13e/src/util/convenience-functions.spec.ts#L7

https://github.com/khill-fbmc/docx/blob/f183d38bb366e022cd66684130478d7aef51d13e/src/util/convenience-functions.spec.ts#L13

**Comment by dolanmiu** [comment]
Yup it is, thank for spotting!
