### ISSUE TITLE
Image from base64 inside a table inside header returns corrupted image

### ISSUE THREAD

**Issue by AkselHEGGERNES** [dolanmiu/docx#1591]
Hello again! 
Referring to #1588 

I agree with the link you sent on how to get a base64 image to a table cell. This works perfectly.
However, when placing the table inside of the **header** is when we experienced issues with a corrupted image. We place the table as in the illustration below:

![image](https://user-images.githubusercontent.com/92863543/178674982-834170b1-435e-4365-98c1-8283366ccc7d.png)

Thank you,
Aksel

**Comment by dolanmiu** [comment]
Understood, will look into this issue!

**Comment by Zayiadi** [comment]
Hi @dolanmiu, any updates on this issue?

**Comment by ns23** [comment]
Hello @Zayiadi @AkselHEGGERNES 

This is how I fixed this Issue.

```js
async createQR(text) {
    const url = await QRCode.toDataURL(text);
    return url.split(",")[1];
  },
  
const baseImg=createQR('123456'); 
// pass this image to to your code 
```

When `0:'data:image/png;base64'` is removed from base64 string, image is rendered properly.

**Comment by dolanmiu** [comment]
Great! nice one, closing.
