### ISSUE TITLE
Docx Zip files are corrupted when running an Express server on Ubuntu (16.04.2 LTS)

### ISSUE THREAD

**Issue by abirtley** [dolanmiu/docx#165]
Great library, very easy to use!

Everything works fine on OSX (standalone node application, and running a local express server). When running on Ubuntu, the standalone node application still worked fine, but when running the express server, all the docx files were corrupted.

This appeared to be a problem in [jszip](https://github.com/Stuk/jszip), as it was the actual zip file that was corrupted, not the XML contents.

My workaround was to use `packer.toBase64String` rather than `packer.toBuffer`, and to then use the `fs.writeFile` functions with `{encoding: 'base64'}`. 

My guess is that express changed the application state somehow, and jszip produced an invalid buffer as a result. I wanted to share the workaround here, however, in case anyone else has the same problem I did.

**Comment by dolanmiu** [comment]
Thanks for your kind words and for finding the solution for others

Glad it worked out for you!

have you got a stack trace for it? I want to (or you can) raise this issue to jszip

**Comment by abirtley** [comment]
There is no stack trace, as all the libraries think they've done a perfect job. The problem seems to be that the `Buffer` provided by jszip is different somehow in a (basic) express server setup than it is when running a standalone node.js script.

Examples attached:

[brokenbuffer.txt](https://github.com/dolanmiu/docx/files/2417262/brokenbuffer.txt)
[broken zip file.zip](https://github.com/dolanmiu/docx/files/2417263/broken.zip.file.zip)
[workingbuffer.txt](https://github.com/dolanmiu/docx/files/2417264/workingbuffer.txt)
[working zip file.zip](https://github.com/dolanmiu/docx/files/2417265/working.zip.file.zip)

You can see that their binary content differs (the uncompressed text is identical).
