### ISSUE TITLE
table cell properties (background-color)

### ISSUE THREAD

**Issue by danosaure** [dolanmiu/docx#167]
Hi,

I may be missing something, but I would like to create a table 100% width, then 4 cells 25% width each, and apply different background-color for each of the cell.

Is it possible?

**Comment by dolanmiu** [comment]
Good question! And no not yet currently

**Comment by danosaure** [comment]
It would be great if we could use `.getCell(x, y).style()`. That's probably part of your #23 card.

Thanks for the quick answer.

**Comment by ThoseDeafMutes** [comment]
Is there any way to implement row or cell colour for tables currently, even if it's a workaround? I'm trying to make the first row have a background colour for example.

**Comment by Meggie-Wang** [comment]
const table = doc.createTable(2, 4)
table.getCell(0, 0).addContent(new Paragraph('Hello'))
const packer = new Packer()
packer.toBlob(doc).then(blob => {
  saveAs(blob, '报告详情.docx')
})
I can't add content to the form like this, why？

**Comment by acgrama** [comment]
I am also highly interested in this. Is there perhaps a way of applying a predefined table style from a styles.xml file?

**Comment by dolanmiu** [comment]
Done in https://github.com/dolanmiu/docx/pull/292

**Comment by dolanmiu** [comment]
docx can produce:

![image](https://user-images.githubusercontent.com/2917613/54789200-95aca300-4c29-11e9-9469-768efb4f7ba3.png)
