### ISSUE TITLE
Applying the font for entire document

### ISSUE THREAD

**Issue by Ajeetmisra** [dolanmiu/docx#1673]
We are working on the download of a document where the entire document is of same font.
 

Is there a way we can apply font for entire document rather formatting each text run ?

**Comment by anti-the-social** [comment]
Hi!

You are looking for declarative styles.
https://docx.js.org/#/usage/styling-with-js?id=declaritive-styles-similar-to-external-css
If you set id and name to `Normal` then it would overwrite default "normal" style for text in Word
