### ISSUE TITLE
new PageBreak() corrupts the file

### ISSUE THREAD

**Issue by Slooti** [dolanmiu/docx#1693]
**Issue**
As soon as a `new PageBreak(),` is added to the document, it cannot be opened anymore. The file is corrupted somehow. 

**Code to reproduce**
```
        const doc = new Document({
            creator: "Eventy. by Anooky.",
            description: "Event Brief",
            title: "Event Brief",
            sections: [
                {
                    properties: {
                        type: SectionType.CONTINUOUS,
                    },
                    children: [
                        new Paragraph({
                            text: "Event Brief",
                            heading: HeadingLevel.TITLE,
                            alignment: AlignmentType.CENTER,
                        }),
                        new Paragraph({
                            text: event.title,
                            heading: HeadingLevel.TITLE,
                            alignment: AlignmentType.CENTER,
                        }),
                        new PageBreak(),
                        new Paragraph({
                            heading: HeadingLevel.HEADING_1,
                            text: "Key information"
                        })
                    ]
                },
                ]
        })
```
is not working. If the `new PageBreak(),` is removed, all works fine.

**Environment**
OS: Mac OS Monterey
Development Environment: Vue3

[event_brief(8).docx](https://github.com/dolanmiu/docx/files/9714530/event_brief.8.docx)

**Woraraound**
`pageBreakBefore: true, `  works correctly, so In some scenarios it's possible to work around with that.

**Comment by anti-the-social** [comment]
Hi!

`new PageBreak()` should not be on the same level as paragraph. It can be only a child to a paragraph:
`new Paragraph({
    children: [ new PageBreak() ]
})`

Please, close an issue if that has solved your problem.

**Comment by Slooti** [comment]
Thanks a lot,

apologies for filing this non-issue.

kind regards and thanks for this great piece of software!

kind regards

Martin
