### ISSUE TITLE
Pushing arrays to sections no longer possible in 7.5.0

### ISSUE THREAD

**Issue by Knexxxx** [dolanmiu/docx#1701]
Just something that surprised me:

Following was working fine until version 7.5.0: 
`IPropertiesOptions.sections.push(SectionOptions)`

now IDE throws an error:  _Property 'push' does not exist on type 'readonly ISectionOptions[]'_

the "readonly" is present since 7.5.0, see screenshot:

<img width="495" alt="Screenshot 2022-10-08 at 20 33 58" src="https://user-images.githubusercontent.com/84722988/194722620-cd212863-61fd-4f6e-99e8-ff3c141d2902.png">

**Comment by dolanmiu** [comment]
Yes, you should spread the section instead (create a new array) like:

```ts
const newSections = [mySection, ...existingSections];
```

Or even better, create the array once, and do not change it. Mutating the array is not encouraged
