### ISSUE TITLE
Feature Request: Convert *.docx to *.js

### ISSUE THREAD

**Issue by hunterwilhelm** [dolanmiu/docx#1708]
I am working on migrating some legacy software to a web based version. I would like to input a word document and have something output the equivalent docx javascript code that would generate something that looks close to the original.

Does a program that converts the word document into docx code already exist? 

It would improve my workflow if I could design new templates in word and have it generate the code for me in javascript to then automate.

I am interested in contributing to the project if it doesn't exist.

**Comment by dolanmiu** [comment]
Sorry, this is unfortunately way out of scope for this project
