### ISSUE TITLE
Image Is no working with ionic 6

### ISSUE THREAD

**Issue by ImAbhishekTomar** [dolanmiu/docx#1717]
Hello,
I am trying to add an image in my document using Ionic6 capacitor angular. here is my code and it's not working.

```ts
createTestImage(): Paragraph {
    //import { Photo } from '@capacitor/camera';
    //import { Filesystem, ReadFileResult } from '@capacitor/filesystem';

    const fileDataObj: Photo = {
      format: 'jpeg',
      exif: {
        ApertureValue: '297/100',
        DateTime: '2022:10:17 07:41:48',
        DateTimeDigitized: '2022:10:17 07:41:48',
        DateTimeOriginal: '2022:10:17 07:41:48',
        ExifVersion: '0220',
        ExposureTime: '0.01',
        Flash: '0',
        FocalLength: '5000/1000',
        FNumber: '2.8',
        ImageLength: '1280',
        ImageWidth: '960',
        LightSource: '0',
        Make: 'Google',
        Model: 'sdk_gphone64_arm64',
        Orientation: '1',
        PhotographicSensitivity: '100',
        PixelXDimension: '960',
        PixelYDimension: '1280',
        ShutterSpeedValue: '6643/1000',
        SubSecTime: '120',
        SubSecTimeDigitized: '120',
        SubSecTimeOriginal: '120',
        WhiteBalance: '0',
      },
      path: 'file:///storage/emulated/0/Android/data/com.rskbsl.ssralx/files/Pictures/JPEG_20221017_074142_5158577144977834283.jpg',
      webPath:
        'http://192.168.1.8:8100/_capacitor_file_/storage/emulated/0/Android/data/com.rskbsl.ssralx/files/Pictures/JPEG_20221017_074142_5158577144977834283.jpg',
      saved: false,
    };

    Filesystem.readFile({ path: fileDataObj.path }).then(
      (readFileResult: ReadFileResult) => {
        const imageObj = readFileResult?.data;
        const image = new ImageRun({
          data: imageObj,
          transformation: {
            width: 500,
            height: 500,
          },
        });
        return new Paragraph({
          children: [image],
        });
      }
    );
    return new Paragraph({
      children: [],
    });
  }
```

**ERROR**

> core.mjs:6485 ERROR Error: Uncaught (in promise): InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
> Error: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
>     at Wt.convertDataURIToBinary (index.js:2)
>     at new Wt (index.js:2)
>     at report-builder.service.ts:190
>     at _ZoneDelegate.push.23484._ZoneDelegate.invoke (zone.js:409)
>     at Object.onInvoke (core.mjs:25548)
>     at _ZoneDelegate.push.23484._ZoneDelegate.invoke (zone.js:408)
>     at Zone.push.23484.Zone.run (zone.js:169)
>     at zone.js:1326
>     at _ZoneDelegate.push.23484._ZoneDelegate.invokeTask (zone.js:443)
>     at Object.onInvokeTask (core.mjs:25535)
>     at resolvePromise (zone.js:1262)
>     at zone.js:1333
>     at _ZoneDelegate.push.23484._ZoneDelegate.invokeTask (zone.js:443)
>     at Object.onInvokeTask (core.mjs:25535)
>     at _ZoneDelegate.push.23484._ZoneDelegate.invokeTask (zone.js:442)
>     at Zone.push.23484.Zone.runTask (zone.js:214)
>     at drainMicroTaskQueue (zone.js:632)

**Comment by dolanmiu** [comment]
From my experience of ionic, it is like a web browser right?

So from looking at this:

```
'atob' on 'Window'
```

It is true, `atob` does not exist on `Window`

I have a suspicion that `Filesystem.readFile({ path: fileDataObj.path })` gives a NodeJS object, and `docx` doesn't like it because it seems like it is running it in a browser environment (hence complaining about `Window`, Node doesn't have `Window`.

**Comment by ImAbhishekTomar** [comment]
Any solution?

**Comment by dolanmiu** [comment]
Try and use Base64 as an image, it is simply a `string`, so it has maximum compatability
