### ISSUE TITLE
How do you add a hyperlink to a paragraph?

### ISSUE THREAD

**Issue by rosman21** [dolanmiu/docx#172]
Here is my code... not sure where I found the `.addHyperLink()` function but that wasn't working. Couldn't anything in the documentation either.

```
var topicText = new docx.TextRun("Topic: " + topic).bold();
var paragraph = new docx.Paragraph();
paragraph.addRun(topicText).addHyperLink(http);
doc.addParagraph(paragraph);
```

**Comment by dolanmiu** [comment]
Check this out:

https://github.com/dolanmiu/docx/blob/master/demo/demo21.ts

**Comment by rosman21** [comment]
Oh okay, yea it is a web link that is why I was having this error. Okay, that makes sense. Thank you!!
