### ISSUE TITLE
Strike and underline don't work in Word when used together

### ISSUE THREAD

**Issue by VLaSH** [dolanmiu/docx#1720]
Hi there,
I need an ability to use both strike and underline at the same time. It works great for Google docs but doesn't work for Word web version. Also text color and font size doesn't work. Here is code, I took it from example and changed a bit:
```
const fs = require("fs");
const docx = require("docx");
const {ExternalHyperlink} = require("docx");
const { Document, Packer, Paragraph, TextRun } = docx;
// Documents contain sections, you can have multiple sections per document, go here to learn more about sections
// This simple example will only contain one section
const doc = new Document({
    sections: [
        {
            properties: {},
            children: [
                new Paragraph({
                    alignment: 'center',
                    children: [
                        new TextRun({
                            text: "Foo Bar",
                            strike: true,
                            underline: true,
                            italics: true,
                            color: '#e30e0e',
                            size: 50,
                        })
                    ]
                })
            ],
        },
    ],
});

// Used to export the file into a .docx file
Packer.toBuffer(doc).then((buffer) => {
    fs.writeFileSync("My Document.docx", buffer);
});

// Done! A file called 'My Document.docx' will be in your file system.
```
And here is screenshot of result:
<img width="909" alt="Screen Shot 2022-10-19 at 8 22 45 PM" src="https://user-images.githubusercontent.com/16542258/196761767-331e46b1-5116-486f-a53c-6b6a272cb704.png">

Also if problem is confirmed, maybe you have any suggestions on how to overcome it before problem is solved?

**Comment by dolanmiu** [comment]
It works on my end:

I have updated demo 2 to demonstrate it:

https://github.com/dolanmiu/docx/blob/master/demo/2-declaritive-styles.ts

![image](https://user-images.githubusercontent.com/2917613/197848612-9ebaa11a-d5ee-4759-90f3-e388496686df.png)

**Comment by VLaSH** [comment]
Thank you for your reply!
Did you open it in Word Web? Because for the standalone version it works as expected I just tried to upload your example to OneDrive and opened it and here is what I've got:

<img width="1792" alt="Screen Shot 2022-10-25 at 9 44 18 PM" src="https://user-images.githubusercontent.com/16542258/197856082-caeff8b8-6067-4ab0-9f1d-beb27cfc602c.png">

**Comment by VLaSH** [comment]
What is interesting is that it works like that only for `.docx`. When I save file in `.doc` extension and upload it to OneDrive, all formatting works great.

**Comment by dolanmiu** [comment]
That is strange that there is an inconsistency there

I have found a fix though

I have updated demo 2 to reflect this

Essentially, you create a style, then apply the style to the run or paragraph

**Comment by VLaSH** [comment]
That works fine! Thank you very much for your help and time!
