### ISSUE TITLE
preserving order with fast xml parser 

### ISSUE THREAD

**Issue by amitm02** [dolanmiu/docx#174]
Hi, I've notice that the library uses fast xml parser (e.g my pull request but also elsewhere).
I had some bugs that are seem to be related to order of xml being lost in JSON.
e.g 
`<a><xx>1</xx><yy>2</yy></a> `
are translated to 
`{a:{xx:1, yy:2}}`

So the order of xx being before yy is lost. 
Is that correct? do you know a way around it?

**Comment by dolanmiu** [comment]
ok sweet nice

**Comment by amitm02** [comment]
fixed in pull request #143
