### ISSUE TITLE
lvlOverride logic adjustments

### ISSUE THREAD

**Issue by anti-the-social** [dolanmiu/docx#1740]
Moi :)

Currently concrete numbering related to overwriting starting value is applied to one level only.
<img width="383" alt="image" src="https://user-images.githubusercontent.com/69673750/198001148-2d5501b0-8164-4ffb-9650-da3c8a58a453.png">

Sometimes users want to start next concrete numbering with other level, than first one, but if we keep "overrideLevel" logic as it, numbering would be continued. Here is how it looks like: (`pref 1.2` meant to be `pref 1.1` since its restarted)

<img width="550" alt="image" src="https://user-images.githubusercontent.com/69673750/198002228-74aadd8e-273d-4cb9-a242-fae248703f23.png">

In order to fix this behaviour we have to be able to generate similar xml to this:
<img width="383" alt="image" src="https://user-images.githubusercontent.com/69673750/198001604-72920dc0-f6e4-4f66-94aa-c802630f459b.png">

And this is the reference to the place where its hardcoded:
https://github.com/dolanmiu/docx/blob/563e10fa92d206fdad897f243994386a5437e8a0/src/file/numbering/numbering.ts#L214

Potentially we can just propogate override for all levels with number 1, if instance has changed...But that would not be flexible e.g. you would be able to start with 10.1.1 after reset, but wouldn't be possible with 10.1.10

The best way, I guess, is to give extensive control over which level has to be actually reseted e.g. `[{lvl: 0, start: 1}, {lvl:1, start : 10}]`

**Comment by dolanmiu** [comment]
Hello :)

Hmm yeah I see what you mean, may require significant change in API you reckon?

**Comment by anti-the-social** [comment]
Yep, it does sound to me as a quite a break changes. 
`instance` at `IConcreteNumberingOptions` seem to be not enough to be "as flexible as possible"

Nevertheless, we have an option where instance would just set all levels to 1 and optional overrideLevel.start would modify first level only. That might stay compatible with old versions...

**Comment by anti-the-social** [comment]
Which way we want to go?
I might do PR, but wouldn't promise it to be fast 😅
Lets see if that would be very critical to the project I am working on.

**Comment by dolanmiu** [comment]
Sure thing

Maybe something like this could be cool:

```ts
const concreteNumbering = new ConcreteNumbering({
    numId: 0,
    abstractNumId: 1,
    reference: "1",
    instance: 0,
    overrideLevels: [{
        num: 1,
        start: 1,
    }, {
        num: 2,
        start: 1,
    }, {
        num: 3,
        start: 1,
    }],
});
```

So turn `overrideLevel` into `overrideLevels` breaking change? Then release `8.0.0` 

Also, what is your project/company? Mind if I add it to the `README`?

**Comment by dolanmiu** [comment]
Closing as fixed by https://github.com/dolanmiu/docx/pull/1823
