### ISSUE TITLE
support the use of the specVanish and vanish for combining list items with content

### ISSUE THREAD

**Issue by gjblajian** [dolanmiu/docx#1744]
# Thank you for raising an issue to `docx`
library does not currently support specVanish or vanish
useful when attempting to build a document with list items combined with list content on the same line

![image](https://user-images.githubusercontent.com/5183939/198399631-3c846391-4c6a-4196-a555-356f0d03ce40.png)

https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.wordprocessing.vanish?view=openxml-2.8.1
https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.wordprocessing.specvanish?view=openxml-2.8.1

**Comment by dolanmiu** [comment]
Feature is now done. Will release in the next version
