### ISSUE TITLE
Feature Request - Insert Text From DOCX

### ISSUE THREAD

**Issue by polizoto** [dolanmiu/docx#1765]
I have a DOCX file whose contents (styling and all) I would like to insert into the DOCX that I am creating with this library. Is there a way to do this currently? Is this in-scope?

_Note:_ this would be similar to functionality that does exist in MS Word: Insert > Object > Text from File... (browse to DOCX).

**Comment by dolanmiu** [comment]
Sorry not in scope, it would involve reading the docx file which is currently not supported atm
