### ISSUE TITLE
Make a "cover" image (stretch image to full page size)

### ISSUE THREAD

**Issue by qusysert** [dolanmiu/docx#1796]
I need to add a "cover" image or, in other words, title-page to my docx. 
Is there a proper way to stretch the cover image to full page size (with no any indents on sides, top or bottom)? Or maybe it is possible to concatenate docx files (to concatenate manually-created cover docx file with main automatically generated docx)?

**Comment by dolanmiu** [comment]
You can set the margins of the document to zero:

https://github.com/dolanmiu/docx/blob/master/demo/6-page-borders.ts

**Comment by qusysert** [comment]
Awesome, thanks!
