### ISSUE TITLE
Add screenshot to wiki

### ISSUE THREAD

**Issue by felipeochoa** [dolanmiu/docx#18]
I may be doing this wrong, but I'm trying to save this screenshot to the wiki and failing. It is the result of running the example program there:

![image](https://cloud.githubusercontent.com/assets/2739312/23797964/a3ca673a-05a2-11e7-9dc5-151c26ef25b7.png)

**Comment by felipeochoa** [comment]
Ha! I can use the link that github generated for this issue to embed in the wiki :smiling_imp:

**Comment by dolanmiu** [comment]
Wow didn't know you could do that 😵
I've been using Imgur all this time 😂😂😂
