### ISSUE TITLE
Error Showing in Downloaded fire

### ISSUE THREAD

**Issue by MRameez820** [dolanmiu/docx#1805]
Hi I am using docx for the Angular project when I am trying to open doc file it gives me error ( The office open XML file can not be opened because there are problems with the content ) . I am using below code

   const doc = new Document({
      sections: [
          {
              properties: {},
              children: [
                  new Paragraph({
                      children: [
                          new TextRun("Hello World"),
                          new TextRun({
                              text: "Foo Bar",
                              bold: true,
                          }),
                          new TextRun({
                              text: "\tGithub is the best",
                              bold: true,
                          }),
                      ],
                  }),
              ],
          },
      ],
  });

  Packer.toBlob(doc).then(blob => {
    console.log(blob);
    saveAs(blob, "example.docx");
    console.log("Document created successfully");
  });

**Comment by dolanmiu** [comment]
I re-created your project in Angular:

https://stackblitz.com/edit/angular-wmd6k3

It works fine for me
