### ISSUE TITLE
 I can't use the Document template

### ISSUE THREAD

**Issue by TruongTri711** [dolanmiu/docx#1808]
When I write the code to use the template document, the return result is that the template is not displayed, can anyone help me how to fix it?

**Comment by dolanmiu** [comment]
This feature is deprecated. There are other libraries out there which do templating

https://www.npmjs.com/package/docxtemplater

**Comment by TruongTri711** [comment]
thanks so much.

**Comment by TruongTri711** [comment]
> This feature is deprecated. There are other libraries out there which do templating
> 
> https://www.npmjs.com/package/docxtemplater

thanks so much.

**Comment by dolanmiu** [comment]
`docx` now has this feature out of the box! As of `v8.0.0`:

https://github.com/dolanmiu/docx/blob/master/demo/85-template-document.ts

This library can now read and write docx files.
