### ISSUE TITLE
Cannot create image

### ISSUE THREAD

**Issue by sleepinzombie** [dolanmiu/docx#186]
Based on what I read, Angular 6 doesn't support fs. 

I'm trying to create an image by using _docx.createImage('logo.png')_ but ending with the following error:

**ERROR DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.**

Any help would be much appreciated.

**Comment by dolanmiu** [comment]
yes, you need to use a `base64` string, it cannot be a filename

**Comment by dolanmiu** [comment]
Do something like this:

https://github.com/dolanmiu/docx/blob/master/demo/demo18.ts

**Comment by sleepinzombie** [comment]
Hello, I'm not having another error which says, **ERROR ReferenceError: Buffer is not defined**

**Comment by dolanmiu** [comment]
Ok that was a bad example, Buffer does not exist on the browser.

You need to pass in a base64 string or blob image somehow without using the Buffer class

**Comment by kunizial** [comment]
The example would be almost the same, just the following differences:
`const imageBase64Data = 'iVBORw0KGgoAAAANSUhEUgAA...`
to
`const imageBase64DataURL = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...`
and
`doc.createImage(Buffer.from(imageBase64Data, "base64"), 100, 100);`
to
`doc.createImage(imageBase64DataURL, 100, 100);`

**Comment by dolanmiu** [comment]
Closing as this is the solution

**Comment by skjgithub950423** [comment]
> The example would be almost the same, just the following differences:
> `const imageBase64Data = 'iVBORw0KGgoAAAANSUhEUgAA...`
> to
> `const imageBase64DataURL = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...`
> and
> `doc.createImage(Buffer.from(imageBase64Data, "base64"), 100, 100);`
> to
> `doc.createImage(imageBase64DataURL, 100, 100);`
I tried your method. There is no error. But i didn't see picture in my docx file.

**Comment by skjgithub950423** [comment]
> > The example would be almost the same, just the following differences:
> > `const imageBase64Data = 'iVBORw0KGgoAAAANSUhEUgAA...`
> > to
> > `const imageBase64DataURL = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...`
> > and
> > `doc.createImage(Buffer.from(imageBase64Data, "base64"), 100, 100);`
> > to
> > `doc.createImage(imageBase64DataURL, 100, 100);`
> > I tried your method. There is no error. But i didn't see picture in my docx file.
This is my code.
![image](https://user-images.githubusercontent.com/13342063/61705545-86289c80-ad78-11e9-9711-2874ea1cd655.png)
