### ISSUE TITLE
How to set columns for documents, such as two columns and three columns

### ISSUE THREAD

**Issue by ISyangk** [dolanmiu/docx#1873]
How to set columns for documents, such as two columns and three columns.

**Comment by anti-the-social** [comment]
This is not an issue. 
Check demos, use a search before rising issue here.
There are many real closed issues on this theme too.

**Comment by dolanmiu** [comment]
Try this:

https://github.com/dolanmiu/docx/blob/master/demo/77-side-by-side-tables.ts

**Comment by ISyangk** [comment]
> 

thanks for your help,so my problem has been solved

**Comment by ISyangk** [comment]
> 

ok
