### ISSUE TITLE
aligment: AlignmentType.END not working

### ISSUE THREAD

**Issue by oballi** [dolanmiu/docx#1876]
Hello,
Alignment on **Headers** and **Footers** side: **Alignment Type.END** is not working.

How can I solve it?

My Code; 
```
const {
  Bookmark,
  Document,
  Packer,
  Paragraph,
  SimpleField,
  TextRun,
  Header,
  Footer,
  AlignmentType,
  HeadingLevel,
  alignment,
} = require("docx");
const fs = require("fs");

// Create a new Word document
const doc = new Document({
  sections: [
    {
      headers: {
        default: new Header({
          children: [new Paragraph("Header text")],
        }),
      },
      footers: {
        default: new Footer({
          children: [
            new Paragraph({
              text: "Footer Text",
              aligment: AlignmentType.END,
            }),
          ],
        }),
      },
      children: [
        new Paragraph({
          text: "HEADING",
          heading: HeadingLevel.HEADING_1,
          aligment: AlignmentType.END,
        }),
      ],
    },
  ],
});

Packer.toBuffer(doc).then((buffer) => {
  fs.writeFileSync("My Document.docx", buffer);
});
```

Output;

![image](https://user-images.githubusercontent.com/43172199/212054003-c5979512-9256-478c-b9c8-0a18bfa84cad.png)

**Comment by anti-the-social** [comment]
Hello!

Great example for the issue, thank you!
I can confirm the issue, output xml lacking those:
<img width="403" alt="image" src="https://user-images.githubusercontent.com/69673750/212263437-32b67dac-37ba-4d84-82fc-a6f8e71ed682.png">
If I add few lines and re-pack then alignment works
<img width="403" alt="image" src="https://user-images.githubusercontent.com/69673750/212263541-631de4c3-f385-4431-a34c-4f19485b2d2b.png">
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/69673750/212263600-1f9ae944-ba20-4beb-9d6b-59cdabe079e0.png">

**Comment by anti-the-social** [comment]
Hello!

Thank you for the great reporting style <3
Deleted my last message, you can ignore it. 
Running your script doesn't do alignment - it is true. 
Nevertheless problem not in the library. You just mistyped the paragraph property
It should be `alignment` not `aligment`
Have a good day!

**Comment by oballi** [comment]
Ah. I'm sorry. How did I miss this :)

Thank you.

**Comment by Mihai-github** [comment]
Hey, I'm having a similar issue... what I'm trying is to put on the footer right the current page of total pages but my content doesn't align as I need it to the end ... what am I doing wrong?

```
footers: {
            default: new Footer({
              children: [
                new Paragraph({
                  alignment: AlignmentType.END,
                  children: [
                    new TextRun({
                      children: ['Page ', PageNumber.CURRENT, ' of ', PageNumber.TOTAL_PAGES],
                      bold: true,
                      size: 10 * 2,
                      color: '#000000',
                      font: {
                        name: 'Calibri',
                      },
                    }),
                  ],
                }),
              ],
            }),
          },
```
