### ISSUE TITLE
How to convert the Word Document to PDF?

### ISSUE THREAD

**Issue by sleepinzombie** [dolanmiu/docx#188]
Based on what I saw on the official documentation of docx, version 4 and up does not support the 'export the pdf' functionality.

Actually I have to save both word documents and PDF. I successfully converted the .docx file but not being able to export to pdf.

Do you have any other alternative I can use to successfully convert and save the docx to pdf?

**Comment by dolanmiu** [comment]
Yes, you can check the source of the old pdf packer here:

https://github.com/dolanmiu/docx/blob/5f594a822fc2b4a89e2c82c5ca255f9ac05eefa7/src/export/packer/pdf-convert-wrapper.ts

As you can see, its a cheat, and only calls an endpoint, which you can do yourself

**Comment by dolanmiu** [comment]
Closing because PDF creation is no longer in scope
