### ISSUE TITLE
Not able to set "right to left" alignment style for Arabic text

### ISSUE THREAD

**Issue by KhalilBHA** [dolanmiu/docx#1880]
Hi,
I've tried to export an Arabic text with react using Docx. My problem is when setting text alignment to be from right to left, the text is still the same and doesn't change. The only case that I have found and it works is when using `heading` parameter.

**React version:** "^17.0.2"
**Docx version:** "^7.8.2"
**File-saver version**: "^2.0.5"

**CODE:**
```
const document = new Document({
          sections: [
            {
              children: [
                new Paragraph({
                  text: results,
                  alignment: AlignmentType.CENTER,
                })
              ]
            }
          ],
        });
Packer.toBlob(document).then(blob => {
  saveAs(blob, "example.docx");
});
```

**Comment by anti-the-social** [comment]
Hi!

Have you tried this?
https://github.com/dolanmiu/docx/blob/master/demo/22-right-to-left-text.ts

**Comment by KhalilBHA** [comment]
Thanks for your response.
I've tried this solution but it's the same thing... It didn't align the text on the right side.

**Comment by KhalilBHA** [comment]
Thanks a lot 🙏
I'm using Apple Pages to read the file so that's why I got a non-aligned text... I try the same file using Microsoft word and it works...

Sorry for taking your time, sir.

**Comment by anti-the-social** [comment]
No problem :) 
Don't forget to close an issue once its solved
