### ISSUE TITLE
Header Background Color

### ISSUE THREAD

**Issue by sgtjukker** [dolanmiu/docx#1895]
### Discussed in https://github.com/dolanmiu/docx/discussions/1608

<div type='discussions-op-text'>

<sup>Originally posted by **aviau** July 26, 2022</sup>
Hello!

Is it possible to set the background color of a header?</div>

**Comment by dolanmiu** [comment]
Yes this is possible with `shading`:

https://github.com/dolanmiu/docx/blob/master/demo/46-shading-text.ts
