### ISSUE TITLE
Documentation issue: what is the unit used in SectionProperties

### ISSUE THREAD

**Issue by semiosys** [dolanmiu/docx#191]
Hi,

I am struggling to pass correct width and height size at document creation time for international paper size (a4, a3, etc).
The when opening the word document is unreadable because the width and heigh I passed are wrong.

When looking at the SectionPropertiesOptions, I see that the values are expressed in an unknown unit :  for example the default width is 11906, what is this unit ??? Inches, mm, ? It does not seems so.
I 'd love to known to be able to do conversion.

Thank you !

EDIT:
I found the information here https://startbigthinksmall.wordpress.com/2010/01/04/points-inches-and-emus-measuring-units-in-office-open-xml/

"The main unit in OOXML is a twentieth of a point. This is used for specifying page dimensions, margins, tabs, etc."

Please close this issue.

const {
            width = 11906,
            height = 16838,
            top = 1440,
            right = 1440,
            bottom = 1440,
            left = 1440,
            header = 708,
            footer = 708,
            gutter = 0,
            mirror = false,
            space = 708,
            linePitch = 360,

**Comment by dolanmiu** [comment]
Yes, that is right 😄
