### ISSUE TITLE
Request footnote multiple paragraphs

### ISSUE THREAD

**Issue by johnhungerford** [dolanmiu/docx#192]
Your module is fantastic. Any chance you will update the API to support multiple paragraphs in a footnote with style support? Something like: 
`fn = new docx.Footnote();`
`para = new docx.Paragraph('First footnote paragraph text').style('FootnoteText');`
`fn.addParagraph(para);`
`doc.addFootnote(fn);`

**Comment by dolanmiu** [comment]
Thanks!

I thought you can only have one Footnote, do you mean add paragraph to the Footer?

**Comment by johnhungerford** [comment]
In Microsoft Word, you can make footnotes with multiple paragraphs, and each paragraph can be styled differently. From what I can tell, your API builds each footnote from a single paragraph, and there does not seem to be any way to add more paragraphs. 

From your example:
`doc.createFootnote(new Paragraph("Test"));`

For the application I have in mind, I would need to be able to have multiple paragraphs in a given footnote, with the option to style each paragraph differently, e.g.:
`var fnpara1 = new docx.Paragraph('This is the first paragraph of a footnote.').style('footnotetext');`
`var fnpara2 = new docx.Paragraph('This is the second paragraph of a footnote, which is a blockquote and needs to be styled accordingly.').style('footnoteblockquote');`
I'd like to be able to add them to a footnote in one of two ways:
`var fnparas = [fnpara1,fnpara2];`
`doc.createFootnote(fnparas);`
OR something like:
`var fn = new docx.Footnote();`
`fn.addParagraph(fnpara1);`
`fn.addParagraph(fnpara2);`

In case you're interested, the application I have in mind is to generate docx documents of court cases from xml data obtained from Harvard's new Caselaw Access Project API. This would allow my organization to make all American caselaw available for free to teachers in a format that can be edited for classroom use.  Court case reports often have very long footnotes with multiple paragraphs and blockquotes; managing the footnotes is the one piece that's missing from the application.

**Comment by dolanmiu** [comment]
This is now a feature:

an example here:

https://github.com/dolanmiu/docx/blob/master/demo/17-footnotes.ts
