### ISSUE TITLE
Styling hyperlink

### ISSUE THREAD

**Issue by kunizial** [dolanmiu/docx#194]
Is it possible yet to style a Hyperlink with TextRun-styles, like calling .bold() ?
```javascript
var doc = new Document();
var paragraph = new Paragraph();
var link = doc.createHyperlink('http://www.example.com', 'Hyperlink');
link.bold();
paragraph.addHyperLink(link);
doc.addParagraph(paragraph);
```
I'm writing in browser and try to convert user-generated input from an RTE.

**Comment by dolanmiu** [comment]
I will look into this when I get home

**Comment by dolanmiu** [comment]
https://github.com/dolanmiu/docx/blob/master/demo/demo21.ts

here you go

Essentially you add the hyperlink in a paragraph, then you can style it as per usual

**Comment by kunizial** [comment]
So there's no easy way to just call `.bold` or similar, right? Usecase is translation of a frontend-website with RTE-Editor and including that in a docx, and as styling works on inline-element basis, either `<span style="font-weight=bold"></span>` or `<strong></strong>`, styling individual text-runs is more appropriate than paragraphs.
The docx-output is meant as a more flexible output so the user can be creative and adapt the output-file how he wants, so if it's not possible yet, that's fine.

**Comment by dolanmiu** [comment]
Ok I did some digging, and it is not yet possible

There's no way to apply styles to `Paragraph`s or `Hyperlink`s, only `TextRun`s at the moment

Will do this in future
