### ISSUE TITLE
Hello,  how to set  autoSpaceDN  ？

### ISSUE THREAD

**Issue by onekilogram** [dolanmiu/docx#1949]
# Thank you for raising an issue to `docx`

Please do not raise an issue unless it is an **issue**.

-   Is your issue a feature request? Are you giving ideas to the community? Are you asking for help? Please raise a ticket in the `Discussions` section:

    https://github.com/dolanmiu/docx/discussions

-   Is your issue a previously asked? Please respond to that thread instead

**Comment by anti-the-social** [comment]
Hello!

autoSpaceDN is not a part of the OOXML specification that docx js based on
http://officeopenxml.com/WPparagraphProperties.php

Altho it exists in Microsoft's standard
https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.wordprocessing.autospacedn?view=openxml-2.8.1

What do you think @dolanmiu ? Should such things be implemented?

P.S. would be nice if you format issue properly next time

**Comment by dolanmiu** [comment]
Can be added in, but with a warning upon use? to let people know that it is dangerous to use as it is off-spec
