### ISSUE TITLE
Formulas from docx.js to .docx

### ISSUE THREAD

**Issue by Behemoth0** [dolanmiu/docx#1959]
Hi all. How in this code to make, in addition to the text, the output of the formula as in microsoft word (as in the screenshot)? And so that this formula can be edited later in word using native tools for creating and editing formulas? I will be grateful for help. Version docx.js 5.5.0 - I want to use it in the browser (this is possible in this version). Thanks in advance for your help

![Formula1](https://user-images.githubusercontent.com/122596029/221173182-1ead8bb5-a61a-4b45-8fc0-605e7eecac08.jpg)

https://codepen.io/Behemoth0/pen/yLxaLVJ?editors=1010

**Comment by dolanmiu** [comment]
You can use Math in `docx`, example below:

https://github.com/dolanmiu/docx/blob/master/demo/55-math.ts

**Comment by Behemoth0** [comment]
i used this code, but is not works: https://codepen.io/Behemoth0/pen/poOEJoQ

**Comment by dolanmiu** [comment]
Yes because thats not how it is used

**Comment by Behemoth0** [comment]
can you tell me how to rewrite this code?

**Comment by Behemoth0** [comment]
what libraries do I need (except docx.js 5.5.0) to display formula code in Word?

**Comment by dolanmiu** [comment]
Something like this:

```ts
new Paragraph({
    children: [
        new Math({
            children: [
                new MathRun("Std = Sj + Va x"),
                new MathFraction({
                    numerator: [new MathRun("T3")],
                    denominator: [new MathRun("7.2")],
                }),
                 new MathRun("- L - C"),
            ],
        }),
    ],
}),
```

**Comment by Behemoth0** [comment]
console write error: Uncaught ReferenceError: MathRun is not defined

**Comment by dolanmiu** [comment]
Try using the latest version of `docx`, and in your case, add `docx.` in front of everything.

E.g. `docx.MathRun`

**Comment by Behemoth0** [comment]
Only version docx.js 5.5.0 is suitable for me, for the rest I need a server and Node.js, I need to run only code through the browser, in versions above this is impossible, as I understand it

**Comment by Behemoth0** [comment]
I fixed problem, thanks too much for your help 😊

**Comment by dolanmiu** [comment]
> Only version docx.js 5.5.0 is suitable for me, for the rest I need a server and Node.js, I need to run only code through the browser, in versions above this is impossible, as I understand it

Versions above, it is possible to run on browser and node, shouldn't be an issue. Upgrade if possible!

**Comment by Behemoth0** [comment]
Do you want to say that the same code will work on version 7.8.2 in the browser? (without server and Node.js)

**Comment by dolanmiu** [comment]
Yes, correct

**Comment by Behemoth0** [comment]
I checked - when I use version 5.5.0 in WebStorm - the code works, when I change it to 7.8.2 (in the script where this library is included), the console gives errors: "index.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'creator')
    at new Ho (index.js:2:308022)
    at generate (testDOC.html:16:17)
    at HTMLButtonElement.onclick (testDOC.html:12:44)" , https://codepen.io/Behemoth0/pen/poOEJoQ (if you change to version 5.5.0 it works correctly)

**Comment by Behemoth0** [comment]
and another question: when I create and open a document, the formula is displayed with a font size of 10px, although the size is 36, how can I fix the size to 14px? (I haven't found the answer yet)

**Comment by dolanmiu** [comment]
This is because this is no longer supported:

```ts
doc.addSection({
    
    });
```

You'd need to do it the new v7 way!

**Comment by Behemoth0** [comment]
Ok, thanks for your help☺

**Comment by Behemoth0** [comment]
Hello, tell me please, if I installed only webpack for myself (without using React and other things), then version 7.8.2 will work for me correctly? Now I'm running the project through http://localhost:3000/testDOC.html

**Comment by dolanmiu** [comment]
You don't need webpack to run docx

If you are using it in a html page, you can use a cdn? That's the easiest approach

**Comment by Behemoth0** [comment]
I keep getting this error "Uncaught TypeError: Cannot read properties of undefined (reading 'creator')
    at new Ho (index.js:2:308022)
    at generate (gaml_ly_TEST.js:271:17)
    at HTMLButtonElement.onclick (galm_ly_TEST.html:95:48)" when I run this code https://codepen.io/Behemoth0/pen/poOEJoQ Can you help me fix the error in the above code? under version 7.8.2. I will be very grateful. I haven't been able to fix it for three days now

**Comment by Behemoth0** [comment]
By the way - in version 5.5.0 the code worked correctly, but I decided to update the version and I can't rewrite the code for it correctly

**Comment by dolanmiu** [comment]
It is because you are doing:

```ts
 doc.addSection({
      children: children
    });
```

I have mentioned above that this is not possible in v7

**Comment by Behemoth0** [comment]
what to use instead of this part of the code that is no longer relevant?

**Comment by dolanmiu** [comment]
put it in the `sections` array

**Comment by Behemoth0** [comment]
remade, this structure is correct?: https://codepen.io/Behemoth0/pen/poOEJoQ?editors=1010

**Comment by dolanmiu** [comment]
`t3` is undefined, and ` doc.addSection(section);` is not allowed

**Comment by Behemoth0** [comment]
About "t3" - it is in the code before this code. How to fix this problem - "doc.addSection(section);"? I use webpack and node.js . Maby use " fs" and require & import?
