### ISSUE TITLE
Correct mime-type for packer.toBlob

### ISSUE THREAD

**Issue by kunizial** [dolanmiu/docx#196]
It'd be nice to generate the export-Blob with docx-mimetype `application/vnd.openxmlformats-officedocument.wordprocessingml.document`, not the default zip-mimetype `application/zip`

Short look into the api, I believe it's just in `packer.ts` line 27:
`const zipData = (await zip.generateAsync({ type: "blob", mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document" })) as Blob;`

JSZip-mimeType: https://stuk.github.io/jszip/documentation/api_jszip/generate_async.html
List of mimeTypes: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types

**Comment by dolanmiu** [comment]
Yes, thats a good idea!

**Comment by dolanmiu** [comment]
Made a fix here:

https://github.com/dolanmiu/docx/pull/201
