### ISSUE TITLE
e.sections is not iterable error when reading docx file

### ISSUE THREAD

**Issue by robertavich** [dolanmiu/docx#1965]
# Thank you for raising an issue to `docx`

Please do not raise an issue unless it is an **issue**.

-   Is your issue a feature request? Are you giving ideas to the community? Are you asking for help? Please raise a ticket in the `Discussions` section:

    https://github.com/dolanmiu/docx/discussions

-   Is your issue a previously asked? Please respond to that thread instead

**Comment by dolanmiu** [comment]
Can you explain more?

**Comment by robertavich** [comment]
I am attempting to read a .docx file  like this:
const fs = require('fs');
const docx = require('docx');

const docxFile = fs.readFileSync('path/to/your/file.docx');
const doc = new docx.Document(docxFile);

when _new docx.Document(docxFile)_ is executed, I get **e.sections is not iterable error**

**Comment by anti-the-social** [comment]
Hi!

Docx js doesn't read files. 
Docx js creates them using json/methods of the library.
Take a look on the documentation.

**Comment by dolanmiu** [comment]
Soon, docx will be able to read and patch docx files:

https://github.com/dolanmiu/docx/pull/1960
