### ISSUE TITLE
Image followed by HyperLink results in corrupted file

### ISSUE THREAD

**Issue by kunizial** [dolanmiu/docx#198]
There seems to be a weird bug in combination of an Image followed up by an HyperLink. The file is reported as being corrupted by word when trying to open it, followed with the question to restore it, which works.
This happens even when there's a normal Paragraph in between, and even with a pageBreak in between. If the Hyperlink goes first, this is not a problem.

Played around with the following codepen:
https://codepen.io/anon/pen/xQOqKq

**Comment by dolanmiu** [comment]
Thanks for reporting this

Will fix

**Comment by dolanmiu** [comment]
Fixed as of v5.0.2

Updated the demo to show that it works:


https://github.com/dolanmiu/docx/blob/master/demo/35-hyperlinks.ts
