### ISSUE TITLE
Regex fail in NumberingReplacer due to reference begin composed only of numbers

### ISSUE THREAD

**Issue by ladislasdellinger** [dolanmiu/docx#1987]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

I was facing a problem when exporting a docx file, due to the reference of a list being composed only of numbers. It failed with the following error:

```
SyntaxError: Invalid regular expression: /{32}/: Nothing to repeat\n    at new RegExp (<anonymous>)
at NumberingReplacer.replace (/app/node_modules/docx/build/index.js:19066:53)
```

Not sure this is the right fix, but escaping the brackets in the Regex solved my problem. Here is the diff:

```diff
diff --git a/node_modules/docx/build/index.js b/node_modules/docx/build/index.js
index 458ce9f..d6ead76 100644
--- a/node_modules/docx/build/index.js
+++ b/node_modules/docx/build/index.js
@@ -19063,7 +19063,7 @@ class NumberingReplacer {
             if (!concreteNumbering.reference) {
                 continue;
             }
-            currentXmlData = currentXmlData.replace(new RegExp(`{${concreteNumbering.reference}}`, "g"), concreteNumbering.id.toString());
+            currentXmlData = currentXmlData.replace(new RegExp(`\\{${concreteNumbering.reference}\\}`, "g"), concreteNumbering.id.toString());
         }
         return currentXmlData;
     }
```

I am not sure if I am doing something wrong or if this is maybe a bug, so any help on that would be highly appreciated 🙂

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by dolanmiu** [comment]
Could you provide reproduction steps?

**Comment by ladislasdellinger** [comment]
Yes sure, here it is: https://github.com/ladislasdellinger/docx-reproduction

Note that we are still using the version 5.5.0.

**Comment by anti-the-social** [comment]
Hello!

I don't think that old v5.x version would be fixed any time soon.. even if we figure out problem stated in this issue.
If you do stick to old versions it sort of becomes your legacy. (unfortunately)
Docx js library would just need lot more people for development to keep up with the approach that f.e. Node has (LTS versions and the latest one)
There were tonns of fixes in v7 that were not added into v5

I would suggest migrate to v7 even if it would take development time

**Comment by dolanmiu** [comment]
This is indirectly fixed because currently, it has a dash in between the numbers, so it will always be valid. There will never be a scenario which is always numbers:

https://github.com/dolanmiu/docx/blob/master/src/export/packer/numbering-replacer.ts#L9
