### ISSUE TITLE
feat(comments): add the possibility to insert break lines

### ISSUE THREAD

**Issue by BensimonSamy** [dolanmiu/docx#1988]
At the moment we cannot insert a break line in comment.

**Comment by anti-the-social** [comment]
Hello!

Have you tried standard way to insert line break?
`const lineBreak = new TextRun({ text: '', break: 1 })`

**Comment by dolanmiu** [comment]
Will be a breaking change - Essentially, the `text` property` needs to take in `children` like other places, so you can add multiple `TextRun`s, such as the `lineBreak` TextRun mentioned by @anti-the-social:

https://github.com/dolanmiu/docx/blob/9827ed30bba5529360019c8c43da0d13fc5d1fce/demo/73-comments.ts#L8
