### ISSUE TITLE
createEvenPageFooter and createEvenPageHeader

### ISSUE THREAD

**Issue by ditiem** [dolanmiu/docx#200]
According to the types HeaderReferenceType and FooterReferenceType, it seems possible to create a different header / footer for even pages.

Is this possible?

**Comment by dolanmiu** [comment]
Yes, it is possible,

It will be something like this:

https://github.com/dolanmiu/docx/blob/master/demo/demo16.ts

**Comment by ditiem** [comment]
Are you saying that in version 5.0.0 the "footers" specified in the section would be { default: ..., even: ..., first: ...} ?

**Comment by dolanmiu** [comment]
Yup, before it was like:

https://github.com/dolanmiu/docx/blob/f9a0d1b3881459347b97f34a4110bc750d35a5df/demo/demo16.js

Then multiple footer/headers were added:

https://github.com/dolanmiu/docx/blob/1a3603dbfb811c1f59e59ae6da4082a75f52e7c7/demo/demo16.ts

And then it became:

https://github.com/dolanmiu/docx/blob/master/demo/demo16.ts

**Comment by ditiem** [comment]
It looks great!

Any ETA for v5?

**Comment by dolanmiu** [comment]
No ETA as of yet

I want to get as much breaking changes in as possible before this release!

If you got an idea of how to improve the API, let me know

I also want to document a lot of the code in docx.js.org first, I am aware the documentation is fairly lacking

**Comment by dolanmiu** [comment]
createEvenPageHeader() method is done in 4.5.0, I will do createEvenPageFooter in a later release

**Comment by dolanmiu** [comment]
Done in `4.6.0`:

https://github.com/dolanmiu/docx/releases/tag/4.6.0

**Comment by Mitiryl** [comment]
Hello,
Thank you for the great library!
I was wondering about createEvenPageFooter/createEvenHeader. I didn't be able to create a even page footer (also header).
The code I tred is:
`
const footer: FooterWrapper = this.doc.createEvenPageHeader();
footer.addParagraph('footer');
    this.doc.addSection({
           footers: {
                even: footer
            }
});
` 
But no footer is shown.
What am I doing wrong?

**Comment by dolanmiu** [comment]
I will investigate
