### ISSUE TITLE
Please add src to .npmignore

### ISSUE THREAD

**Issue by jcwatson11** [dolanmiu/docx#2002]
First, thank you for your work, and your contribution to open source. This product is very well done.

If you don't mind, please add the `src` directory to your .npmignore file so that it does not get published to other people's node_modules directories. This will help with errors like I get when I try to run my unit tests using ts-node:

```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /home/jwatson/Source/import.fh.org/node_modules/docx/src/export/formatter.spec.ts
```

Interestingly, this error occurs regardless of any tsconfig.json exclude settings. I very well may be missing something simple. But standard practice is to add .ts src files to the .npmignore file.

Thank you again for your work!

**Comment by dolanmiu** [comment]
Thanks!

I will add that to `.npmignore` for the next release
