### ISSUE TITLE
new PageReference("anchorForChapter1")  void

### ISSUE THREAD

**Issue by 704738749** [dolanmiu/docx#2026]
# Thank you for raising an issue to `docx`

Please do not raise an issue unless it is an **issue**.

-   Is your issue a feature request? Are you giving ideas to the community? Are you asking for help? Please raise a ticket in the `Discussions` section:

    https://github.com/dolanmiu/docx/discussions

-   Is your issue a previously asked? Please respond to that thread instead

**Comment by 704738749** [comment]
Failed to obtain the page number of the corresponding label when using a internal hyperlink

**Comment by dolanmiu** [comment]
Can you show me some code to demonstrate your issue?

**Comment by 704738749** [comment]
![image](https://user-images.githubusercontent.com/46706821/228123255-be12a629-4c64-4d4a-af8f-04bf63ad7a0e.png)
![image](https://user-images.githubusercontent.com/46706821/228123303-3de43aeb-cc93-428c-bd78-b7acd0a67d03.png)
![image](https://user-images.githubusercontent.com/46706821/228123423-bd2fac7b-c839-491b-8c38-1b7d0dbc12d4.png)
生成后的没有显示页码

**Comment by 704738749** [comment]
new PageReference() How does this method work? Is there an example?

**Comment by dolanmiu** [comment]
Yes there is:

https://github.com/dolanmiu/docx/blob/master/demo/21-bookmarks.ts
