### ISSUE TITLE
ICommentOptions has no children

### ISSUE THREAD

**Issue by minyoung90** [dolanmiu/docx#2050]
https://docx.js.org/api/interfaces/ICommentOptions.html

Above link, there is no property about "children" 

https://docx.js.org/#/usage/comments

But, above example, ICommentOptions has children!

And also, typescript gives me an error when copy and paste it into vscode
```
Type '{ id: number; author: string; date: Date; children: Paragraph[]; }' is not assignable to type 'ICommentOptions'.
  Object literal may only specify known properties, and 'children' does not exist in type 'ICommentOptions'.
```

and also I have one more question. Can I make a comment thread? I think that example from document gives me some hints but I want to know about it! Thanks.

**Comment by dolanmiu** [comment]
It should have children yes:

https://github.com/dolanmiu/docx/blob/master/demo/73-comments.ts

Look at this example

Perhaps you're using an older version of docx

> Can I make a comment thread?

Yup, that is possible. You can do anything you want with `children`

**Comment by minyoung90** [comment]
I sovled error message by install latest version "docx"
```
npm install docx@latest
```

but, I got another error execute example (https://docx.js.org/#/usage/comments)
```
index.js:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'break')
    at new me (index.js:2:224676)
    at new we (index.js:2:225355)
    at new cr (index.js:2:238131)
    at new ur (index.js:2:240509)
    at new Ho (index.js:2:308247)
...
```

**Comment by dolanmiu** [comment]
Replying is not possible.

I did some research, and it is a Microsoft Word only feature. This will not work in other Word Processors

**Comment by minyoung90** [comment]
Thank you for your answer!

**Comment by VictorBaron** [comment]
Sorry, adding a bit on a closed issue.

If me & my team were willing to implement this; would it be accepted ?
May be through a compatibility flag, for it not to impact other Word processors ?

This is a must have for us.

**Comment by kalda341** [comment]
@VictorBaron I would also be very interested in this.
