### ISSUE TITLE
How can we use the border on the text frame？

### ISSUE THREAD

**Issue by gjlong** [dolanmiu/docx#2055]
Dear author,
I used the text frame in the paragraph.
But its border is not working.
Example site: https://docx.js.org/#/usage/text-frames
I can't find the wrong in the code.

**Here is my code:**

section.children.push(new Paragraph({
        text:'test',
        frame: {
            position: {
                x: 9000,
                y: 700,
            },
            width: 600,
            height: 100,
            anchor: {
                horizontal: FrameAnchorType.MARGIN,
                vertical: FrameAnchorType.MARGIN,
            },
            alignment: {
                x: HorizontalPositionAlign.CENTER,
                y: VerticalPositionAlign.TOP,
            },
        },
        border: {
            top: {
                color: "00FFFF",
                space: 1,
                value: "single",
                size: 6,
            },
            bottom: {
                color: "00FFFF",
                space: 1,
                value: "single",
                size: 6,
            },
            left: {
                color: "00FFFF",
                space: 1,
                value: "single",
                size: 6,
            },
            right: {
                color: "00FFFF",
                space: 1,
                value: "single",
                size: 6,
            },
        },
    }))

Can you tell me where is the wrong in my program and how to fix it？
Thank you.

**Comment by dolanmiu** [comment]
Example here shows how to do it:

https://github.com/dolanmiu/docx/blob/master/demo/61-text-frame.ts

It works when I tested it just now

**Comment by gjlong** [comment]
@dolanmiu  
Thanks a lot!
I find a different place in this code.

top: {
color: "00FFFF",
space: 1,
value: "single",
size: 6,
},

The code works when I replaced the "value" element with the "style" element.
But the "value" element example is from this document.
document url:https://docx.js.org/#/usage/text-frames
Is the document example deprecated？

**Comment by dolanmiu** [comment]
It's not deprecated, but it may be inaccurate.

Soon I will focus on improving documentation in general, which should help a lot

**Comment by gjlong** [comment]
> It's not deprecated, but it may be inaccurate.
> 
> Soon I will focus on improving documentation in general, which should help a lot

Thank you!
