### ISSUE TITLE
Vite production build, runtime errors — ... is not a constructor

### ISSUE THREAD

**Issue by pooledge** [dolanmiu/docx#2056]
I am using SvelteKit with
- Vite v4.2.1
- Node v16.15.0
- DocX v8.0.1

Importing like:
```
import { AlignmentType, Paragraph, TextRun, TabStopType, HeadingLevel } from 'docx';
```
production build fails with:
```
import { AlignmentType, Paragraph, TextRun, TabStopType, HeadingLevel } from "docx";
         ^^^^^^^^^^^^^
SyntaxError: Named export 'AlignmentType' not found. The requested module 'docx' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'docx';
const { AlignmentType, Paragraph, TextRun, TabStopType, HeadingLevel } = pkg;
```
which, when applied as states in the last line is not working in dev mode. Same applies to `HeadingLevel` — looks like exporting enumeration like this causes the problem?

I was somewhat able to build successfully by importing:
```
import * as docx from 'docx/build';
const { Paragraph, TextRun, TabStopType, HeadingLevel } = docx;
```
and setting alignment with a string `'center'` instead if the import. `HeadingLevel` was used as `HeadingLevel.HEADING_1` and did not complain, strangely.

However, when calling my lib in production, I am getting `TypeError: TextRun is not a constructor`. Maybe related to https://github.com/dolanmiu/docx/issues/1858?

**Comment by pooledge** [comment]
Funny thing, I am all fine using bun v0.5.8 instead of Node v16.15, dunno if it helps

**Comment by dolanmiu** [comment]
Very odd, I think I have a feeling as to why

I had issues with vite too in my day job with CommonJS modules (which docx is)

I guess the fix would be to somehow make docx a umd/esm/commonjs module, but I need to research into how

**Comment by pooledge** [comment]
Rollup takes over here: https://github.com/rollup/plugins/tree/master/packages/commonjs#options
I've tried those with no avail: 
```
commonjsOptions: {
	include: [],
	strictRequires: true,
	transformMixedEsModules: true,
	esmExternals: true,
	dynamicRequireTargets: ['node_modules/docx/**/*.js']
}
```

**Comment by pooledge** [comment]
Unfortunately for someone reading this having the same problem, I was able to overcome this issue by separating docx in a simple microservice, bundled by bun into a simple http server.

@dolanmiu let's keep this issue open until further resolution. Also I'll be glad to assist on testing stuff out.

**Comment by dolanmiu** [comment]
Does it work for you if you use webpack or `ts-node`?

I am leaning towards replacing webpack with vite for `docx`'s bundler, maybe that would solve a lot of the issues

**Comment by pooledge** [comment]
Using Vite as bundler would be an amazing upgrade for this very niché and powerful library! 

> Interesting. I am curious to how the microservice was set up for it to work

Actually surprisingly smooth thanks to bun. it has http server, bundler and test env by default, transpiles ts natively, so moving a lib utilizing docx and attaching a simple route handler can be done within an hour.

**Comment by dolanmiu** [comment]
`8.1.0` now uses `vite` and `vitest`, fully replaces `webpack` and `mocha`

Closing for now, can re-open if this problem persists
