### ISSUE TITLE
`docx` not compatible with electron nodejs

### ISSUE THREAD

**Issue by rdp1414** [dolanmiu/docx#2076]
I built a simple desktop app in `Windows 11` using [electron](https://www.electronjs.org/) with [Svelte ](https://svelte.dev/)as front-end and [nodejs ](https://nodejs.org/en)as back-end. The front-end  just contains one button to be clicked, see below image.
![image](https://user-images.githubusercontent.com/48443806/232316358-be5be187-7561-4bbc-a198-9fb8460ba5a8.png)

Clicking on the above button triggers creating and saving of a `docx` file in the back-end in `nodejs`, see below code.
```js
const fs = require('fs');
const {Document, Paragraph, TextRun, Packer} = require('docx');

function createDocxFile() {
   console.log('Triggered in backend'); // This is getting logged correctly on console.
    const rndNumber = Math.random();

    const doc = new Document({
        sections: [{
          properties: {},
          children: [
            new Paragraph({
              children: [
                new TextRun(`Hello World - ${rndNumber}`),
              ],
            }),
          ],
        }]
    });

    Packer.toBuffer(doc).then((buffer) => {
        fs.writeFileSync(`example-${rndNumber}.docx`, buffer);
    });
}

module.exports = {
    'createDocxFile': createDocxFile,
};
```
In development environment `npm run dev`, the entire app works correctly - When the button is clicked, a `docx` file is saved on the computer. But in packaged environment `npm run package`, inside `dist` directory, when `svelte-app` setup Application file is opened, the below error is raised.
![image](https://user-images.githubusercontent.com/48443806/232316070-2a7471c0-e613-419c-b62b-45263445b370.png)

I searched a lot on the internet, but couldn't find relevant details. Can you please offer help? This is a critical project that is complete, except for the above error which is blocking us from shipping it to clients.

**Comment by dolanmiu** [comment]
Do other packages work? It is just `docx`?

**Comment by rdp1414** [comment]
Hello,

Thank you for such a prompt response. And, apologies for my late reply. I was busy in delivering the above project and delivered it yesterday. The problem was that my project contained two `package.json` files - one in the root directory and other inside another directory. I was installing `npm` in the second file; moving `npm` to the root file fixed the issue.

---
Given the opportunity, I wish to ask one question. Suppose I have a string:
```
const text = "- The human brain has nearly tripled in mass in two million years. One of the main reasons that our brain got so big is because it got a new part, called the frontal lobe.\n- The frontal lobes are the largest lobes in the human brain and they are also the most common region of injury in traumatic brain injury.\n - The frontal lobes are important for voluntary movement, expressive language and for managing higher level executive functions.\n
```
I want to write the above in a docx file in bullet points, as shown below:
- The human brain has nearly tripled in mass in two million years. One of the main reasons that our brain got so big is because it got a new part, called the frontal lobe.
- The frontal lobes are the largest lobes in the human brain and they are also the most common region of injury in traumatic brain injury.
- The frontal lobes are important for voluntary movement, expressive language and for managing higher level executive functions.

---

Is it possible to achieve the above using `npm docx` module?

Thank You,
rdp1414

**Comment by dolanmiu** [comment]
Glad it's all resolved

Yes, it is possible:

https://github.com/dolanmiu/docx/blob/master/demo/3-numbering-and-bullet-points.ts
