### ISSUE TITLE
document image positioning better

### ISSUE THREAD

**Issue by efx** [dolanmiu/docx#208]
I am having a hard time positioning images simply. I realize there are advanced options for floating ones, but I would like to see a few examples for simple image positions. E.g. right top aligned on the page, centered, etc.

**Comment by dolanmiu** [comment]
On my to-do list

**Comment by efx** [comment]
@dolanmiu let me know if you would like any help, glad to contribute some documentation.

**Comment by efx** [comment]
I think we could also note in the documentation what the default unit is for positioning per your comment: https://github.com/dolanmiu/docx/issues/50#issuecomment-445268838

**Comment by dolanmiu** [comment]
Yes would be nice if you can do some documentation!

**Comment by dolanmiu** [comment]
https://github.com/dolanmiu/docx/blob/4.5.0/docs/usage/images.md

Done, it is well documented now :)

**Comment by efx** [comment]
excellent, thank you for doing this @dolanmiu !
