### ISSUE TITLE
new docx.Numbering() throws Error

### ISSUE THREAD

**Issue by nicmila** [dolanmiu/docx#2081]
version 8.0.2 ,  a webpack project, docx used via require('docx'),  reproduced with https://unpkg.com/docx@8.0.2/build/index.js

the script runs in a webworker, the error message:

 **Uncaught TypeError: Cannot read properties of undefined (reading 'config')**

**Comment by dolanmiu** [comment]
This is not how you are supposed to use numbering. You should not manually instantiate that instance. Refer to this example:

https://github.com/dolanmiu/docx/blob/master/demo/3-numbering-and-bullet-points.ts

**Comment by OliverLeighC** [comment]
Is this out of date then? https://docx.js.org/#/usage/numbering?id=using-bulletsnumbering-in-docx

**Comment by dolanmiu** [comment]
> Is this out of date then? https://docx.js.org/#/usage/numbering?id=using-bulletsnumbering-in-docx

Ah yes it is, will update shortly

**Comment by dolanmiu** [comment]
Updated docs!
