### ISSUE TITLE
Numbering instance restart number not work since v8.0.0 and work well in v7.8.2

### ISSUE THREAD

**Issue by hom** [dolanmiu/docx#2082]
In `v7.8.2`, the numbering of instance to restart number is work well, but since `v8.0.0`, the instance not work.

see:
```bash
# demo of 29
npm run demo
```

in `v7.8.2`:
<img width="577" alt="Screen Shot 2023-04-18 at 15 47 26" src="https://user-images.githubusercontent.com/23349958/232708328-f82cb38e-04f1-4d15-afe2-11ba6c070ec2.png">

in `v8.0.0`
<img width="468" alt="Screen Shot 2023-04-18 at 15 45 39" src="https://user-images.githubusercontent.com/23349958/232708039-7df39cda-764b-4f70-b673-1bd0ef8bc5b6.png">

**Comment by Sliffcak** [comment]
@dolanmiu   have you found any work around? The issue is still present in latest v8.2.1

**Comment by curlycabbage** [comment]
I am seeing the same issue

**Comment by tripodsan** [comment]
me, too
