### ISSUE TITLE
V8.0.2 => TypeError: Cannot read properties of undefined (reading 'creator') in Nodejs v16.14.0

### ISSUE THREAD

**Issue by gowy222** [dolanmiu/docx#2090]
"docx": "^8.0.2",  (pnpm)

const docx = require("docx");
const doc = new docx.Document();

then =>
`TypeError: Cannot read properties of undefined (reading 'creator')
    at new ta (D:\mycode\app\node_modules\.pnpm\docx@8.0.2\node_modules\docx\build\index.js:2:309631)`

**Comment by tylerdoreilly** [comment]
Hi everyone,
Having the same issue as above. Trying to upgrade from an older version (5.5.0) to anything above. Is this a node version issue? 

Node V - 16.17.1


import via:
import { ... } from "docx";
let doc = new Document`

or
import * as docx from "docx";
let doc = new docx.Document`

 doc.addSection({...})
 
Can't figure out what the deal is. Any help would be appreciated.

**Comment by dolanmiu** [comment]
`doc.addSection({...})` is now deprecated, there is a new way to add sections

Refer to the `demos` in this repository

**Comment by tylerdoreilly** [comment]
Ah well that's embarrassing. Works as expected. 
Thanks for the reply.
