### ISSUE TITLE
table cell width

### ISSUE THREAD

**Issue by Meggie-Wang** [dolanmiu/docx#211]
Hello @dolanmiu!
I created the table successfully, but no width.
I used various methods of finding,like this:
```
table.getCell(0, 0).addContent(new Paragraph('Hellow')).CellProperties.setWidth(WidthType.PERCENTAGE, '50%')
table.getCell(0, 1).addContent(new Paragraph('word')).CellProperties.setWidth('50%', WidthType.PERCENTAGE)
table.getCell(0, 2).addContent(new Paragraph('haha')).CellProperties.setWidth(200)
```
Can you help me?
Thanks.

**Comment by Meggie-Wang** [comment]
And the table I created will be created twice.
`doc.createTable(2,  2)`
This will result in a table with 4 rows and 2 columns.
By the way, how to center the picture?
Thanks!

**Comment by Meggie-Wang** [comment]
`
let img = Media.addImage(doc, Buffer.from(imageBase64Data, 'base64'), 500, 300)
doc.addImage(img)
`

**Comment by dolanmiu** [comment]
> And the table I created will be created twice.
doc.createTable(2, 2)
This will result in a table with 4 rows and 2 columns.

Can you show me your code for this?

**Comment by Meggie-Wang** [comment]
`
const topTable = doc.createTable(2, 4)
topTable.setWidth(WidthType.PERCENTAGE, '100%')
topTable.getCell(0, 0).addContent(new Paragraph('hello')).properties.setVerticalAlign(VerticalAlign.CENTER)
`

**Comment by Meggie-Wang** [comment]
Can you point out my mistake?I found that other people didn't encounter this problem.

**Comment by affonso** [comment]
Same here, Meggie-Wang.

**Comment by mettin** [comment]
This worked for me for setting it to full width. No idea why setting percentage (pct) to 5000 works though
```js
  const table = doc
    .createTable(numberOfColumns, numberOfRows)
    .setWidth('pct', 5000);
```

**Comment by mettin** [comment]
```js
table.setWidth('pct', '100%');
```
 also works

**Comment by Meggie-Wang** [comment]
Is there a duplicate problem with the table you created?
`const table = doc.createTable(2, 2)`
This should be a table that creates 2 rows and 2 columns, but it repeated once.
Like this：
|--------------|--------------|
|hello             |aa                |
|--------------|--------------|
|word            |bb                |
|--------------|--------------|
|hello             |aa                |
|--------------|--------------|
|word            |bb                |
|--------------|--------------|

**Comment by ricustr** [comment]
hello, I tried to use CellProperties.setWidth to a table but it's don't work.

**Comment by mettin** [comment]
Im using this and it works perfectly:
```js

    const table = doc
      .createTable(numberOfColumns, numberOfRows)
      .setWidth('pct', '100%');

    table.getCell(0, 0).CellProperties.setWidth('93%', 'pct');
    table.getCell(0, 1).CellProperties.setWidth('7%', 'pct');
```

**Comment by ricustr** [comment]
I use the same code for create and setWidth.     
```
      const document = new Document();
      const table = document.createTable(1, 2)
          .setWidth(WidthType.PERCENTAGE, '100%');

      table.getCell(0, 0)
          .CellProperties.setWidth('20%', WidthType.PERCENTAGE);
      table.getCell(0, 1)
          .CellProperties.setWidth('80%', WidthType.PERCENTAGE);
```
 
![image](https://user-images.githubusercontent.com/30500221/53010274-5fff7900-3435-11e9-9364-6008fe09cb83.png)    

[test (16).docx](https://github.com/dolanmiu/docx/files/2879637/test.16.docx)

LibreOffice Writer Version: 6.0.7.3
Build ID: 1:6.0.7-0ubuntu0.18.04.2

**Comment by mettin** [comment]
As far as i know (im not a maintainer) only 'real' word is supported. I opened your file in word and looks fine!
![image](https://user-images.githubusercontent.com/1436111/53010377-0780a980-343e-11e9-983a-82c078224a5e.png)

**Comment by ricustr** [comment]
Okay, thank you for fast responses. Have a nice day.

**Comment by mettin** [comment]
Try converting to pdf to test: https://cloudconvert.com/

**Comment by ricustr** [comment]
Converting helped, thank for advice.

**Comment by dolanmiu** [comment]
Yes, only Microsoft Office is supported

Other office suites will be supported at some point. But no ETA. It's just so difficult to make it working for every Word processor. It's like Safari vs IE vs Firefox vs Chrome all over again... but less easier to test

**Comment by dolanmiu** [comment]
Will be fixed with:

https://github.com/dolanmiu/docx/pull/288

**Comment by Meggie-Wang** [comment]
`const table = doc.createTable(2, 2).setWidth('pct', '100%')`
This code should create a table with two rows and two columns，however, a table with four rows and four columns was created.

**Comment by dolanmiu** [comment]
> This code should create a table with two rows and two columns，however, a table with four rows and four columns was created.

This is not a problem in v5

**Comment by Willworkgogogo** [comment]
why not  apply a way to directly generate doc file
