### ISSUE TITLE
How can I customize the Numbering Text?

### ISSUE THREAD

**Issue by carlleton** [dolanmiu/docx#212]
Hello, @dolanmiu !
I want customize the Numbering text,
like the chinese number, or others languages, or another geometric'\u27A3',but it's not in the normal enums.
eg:
```
一、aaa
  1.  xxx
  2. two
    ➣ cc
```

**Comment by dolanmiu** [comment]
Not a feature yet!

Thank you, will be on the todos

**Comment by dolanmiu** [comment]
This is now possible!

https://github.com/dolanmiu/docx/blob/master/demo/29-numbered-lists.ts

**Comment by LaysDragon** [comment]
For anyone want to known how to setup for chinese numbering, you can use `taiwaneseCountingThousand` as numbering format
```
一、aaa
```
```js
{
  level: 0,
  format: 'taiwaneseCountingThousand' as LevelFormat,
  text: "%1、",
  alignment: AlignmentType.LEFT,
  style: {
    paragraph: {
      indent: { left: 720, hanging: 259 },
    },
  },
},
```
