### ISSUE TITLE
Breaks include undesired spaces

### ISSUE THREAD

**Issue by jacwright** [dolanmiu/docx#213]
`paragraph.createTextRun().break();` is adding a bunch of spaces on the line of the break.

_I think_ it might be because a linebreak is added to the `document.xml` like this:

```xml
                <w:br>
                </w:br>
```

and should be like this:

```xml
                <w:br></w:br>
```

or

```xml
                <w:br />
```

**Comment by jacwright** [comment]
Never mind. I was using `paragraph.createTextRun().break()` which is what was causing this issue. `paragraph.addRun(new Run().break())` is the correct way to add breaks in a paragraph.

**Comment by dolanmiu** [comment]
👍

**Comment by bba278** [comment]
Both ```paragraph.createTextRun().break()``` and ```paragraph.addRun(new Run().break()) ``` create two empty lines, one for the **Paragraph** and another for the **Run**

I simply have the following function, which I call after I've created the **Document** object

``` 
// Helper function creates the general Document layout
  function createPret4Document (doc, jbName, fmName, pdValue, pdText) {
    doc.createParagraph(null).addRun(new Run().break())// eslint-disable-line
    createTable(doc, jbName, fmName, pdValue, pdText)
  }
```
Any suggestions?

**Comment by dolanmiu** [comment]
I'll need to look into this

**Comment by bba278** [comment]
Thank you, @dolanmiu. 

For now, I have solved the problem with the following line: 

```doc.createParagraph(null).addRun(new Run(null).tab()) ```
