### ISSUE TITLE
Help !!! how do I space between lines in a paragraph?

### ISSUE THREAD

**Issue by abreudiego94** [dolanmiu/docx#215]
how do I space between lines in a paragraph ?

**Comment by dolanmiu** [comment]
Have you tried break?

https://docx.js.org/#/usage/text?id=break

**Comment by dolanmiu** [comment]
Closing because I think this is the answer, feel free to open if you need more help

**Comment by LalindaSampath** [comment]
@dolanmiu I want to have a space between two paragraphs. Not a text break. Can you tell me how to achieve that ?

**Comment by dolanmiu** [comment]
do you mean like hitting the enter key? or pressing `tab` or `space bar`?

**Comment by LalindaSampath** [comment]
Pressing the enter key twice. Please find the attached image as well.

![Capture](https://user-images.githubusercontent.com/8786867/59346494-0b5b7300-8d30-11e9-9350-40678f54f312.PNG)

**Comment by LalindaSampath** [comment]
> @dolanmiu Pressing the enter key twice. Please find the attached image as well.
> 
> ![Capture](https://user-images.githubusercontent.com/8786867/59346494-0b5b7300-8d30-11e9-9350-40678f54f312.PNG)

Below piece of code does it.
`paragraph.addRun(new Run().break());`
