### ISSUE TITLE
Cannot open generated docx on Android

### ISSUE THREAD

**Issue by mikewesthad** [dolanmiu/docx#218]
I've been exploring a couple docx generation techniques and stumbled upon your work (thanks for making it btw!). I hit an issue in testing out the examples. Docx files generated by the lib will not open in mobile browsers. Running the examples in the readme for generating docs client-side (e.g. [this one](https://jsfiddle.net/3xhezb5w/2)) results in android throwing an "unable to open file" when you generate, download and then click the "open" toast message.

They will open if you navigate to downloads and open them outside of the browser, or if you run your server-side examples like [this one](https://runkit.com/dolanmiu/docx-demo1). I don't hit this issue with the docxtemplater examples which also use FileSaver, so I suspect this might be something like a missing mimetype in the blob?

Device info: Android 7.0, Galaxy S6

**Edit**
~~Did a little digging while I had a minute. Mime type matches docxtemplater, so I don't think that's the problem. I did notice that docxtemplater uses jszip@2 and docx uses jszip@3, so that might be the source of the problem.~~

**Comment by mikewesthad** [comment]
It is a problem with mime types that was fixed in this [commit](https://github.com/dolanmiu/docx/commit/ff443aa7c4b11278e6b56c069d495505a6cdabfb), which hasn't been published to npm. I verified that it works by pulling the repo and building a local copy. Any chance there will be a new version published to npm so devs can take advantage of the fix?

**Comment by dolanmiu** [comment]
Published 4.4.1 with the fix, thanks!

https://github.com/dolanmiu/docx/releases/tag/4.4.1

**Comment by mikewesthad** [comment]
Thanks for doing that so quickly!
