### ISSUE TITLE
Inserting HTML formatted Text

### ISSUE THREAD

**Issue by Deftness** [dolanmiu/docx#219]
Hey,

In a project I am working on, I have extracted from an Excel file the marked up text for a given cell (HTML rendering of the text). I am hoping I can insert that marked up text instead of me parsing the html directly. For Example:

**From Excel Document:**
```
var cell =  "This is sample text, and this is <b>bolded</b>";
```

Unfortunately, when I try to insert this text using:

```
paragraph.AddRun(new TextRun(cell));
```
It prints out the `<b></b>` tags, as opposed to rendering them. I think this is especially useful because then someone could do:

    doc.createParagraph("This is some long text. <b>This is bolded.</b> Now, we are going to use <i>italics</i>");

**Comment by dolanmiu** [comment]
I don't think this could go into this library, if `<b>Hello</b>` is valid, then surely `<div>Hello</div>` is also allowed? 

What about `<html><body>...</body></html>`?

**Comment by Deftness** [comment]
Ah yep, fair enough! Was just wondering if something already existed to support that. I guess I'll have to manually parse the text and try to rebuild it using the api.

**Comment by Deftness** [comment]
I was more thinking of just the styling of text.

**Comment by dolanmiu** [comment]
Yeah would be a difficult task though, not even sure on how to begin with:

`<b style="color: red; align: center">Hello</b>`

**Comment by bhattrahul712** [comment]
Hello @dolanmiu ,
Is there a support for this yet?

Hey @YawWashout ,
were you able to do something for this scenario, I am stuck with something similar where I want to output a rich text content taken from the user into the doc.

I am sorry if this is not the right place to ask this question but I am in a desperate need of an answer, I am stuck with this for quite sometime now.

Any help will be deeply appreciated.
Thanks in advance.

**Comment by dolanmiu** [comment]
@bhattrahul712 no there wont be support for this as it is out of scope of the library

maybe render the html as an image, then import the image?

**Comment by bhattrahul712** [comment]
Thanks for the reply and the suggestion @dolanmiu .
I actually need the ability to edit the formatted content after the docx generation.
