### ISSUE TITLE
Cannot override default hyperlink style

### ISSUE THREAD

**Issue by zetlen** [dolanmiu/docx#2202]
Default run styles for `hyperlink` are ignored.

## Steps to reproduce
1. Create a Document with default hyperlink styles:
   ```js
   new Document({
     styles: {
       default: {
         hyperlink: {
           run: {
             color: "FF0000",
             underline: {
               color: "0000FF"
             }
           }
         }
       }
     }
   })
   ```

2. Populate that Document with some content including hyperlinks
3. Render and view

**Expected results**: Red links with blue underlines  
**Actual results**: Normal default link style

## Background
I think the culprit is here, where the passed `options` are overridden by the default definition of `run`.
https://github.com/dolanmiu/docx/blob/e3ee45518646054b5f4715c7b41c31bec8e71bb8/src/file/styles/style/default-styles.ts#L170-L179

**Comment by dolanmiu** [comment]
Thank you, good spot!

Making a fix right away
