### ISSUE TITLE
tablecell width setting is not work in some cases

### ISSUE THREAD

**Issue by KzqKzq** [dolanmiu/docx#2207]
### Discussed in https://github.com/dolanmiu/docx/discussions/2204

<div type='discussions-op-text'>

<sup>Originally posted by **KzqKzq** June 29, 2023</sup>

I'm trying to generate some Tabel in docx by looping, and I've set the same width to each TableCell. In most cases, the settings are in effect, but there is a part of the table and the TableCell is not as wide as expected, as in the screenshot below. Do I still need to set any properties or is this a bug?
![image](https://github.com/dolanmiu/docx/assets/61263079/2c6f0907-2d61-44aa-92a0-de36c479d9eb)
```
  return new TableRow({
    children: [
      new TableCell({
        children: [alignmentCenterParagraph(headerField ? String(headerField) : '', AlignmentType.LEFT, true)],
        borders: borderStyle,
        width: {
          size: 1500,
          type: WidthType.DXA,
        },
      }),
      new TableCell({
        children: child,
        borders: borderStyle,
        verticalAlign: VerticalAlign.CENTER,
        width: {
          size: 6900,
          type: WidthType.DXA,
        },
      }),
    ],
    cantSplit: true,
  })
```</div>

**Comment by toramameseven** [comment]
Hi @KzqKzq. How about #1139 .

**Comment by KzqKzq** [comment]
> Hi @KzqKzq. How about #1139 .

@toramameseven  Thanks a lot, its worked for me.
