### ISSUE TITLE
Two Paragraphs in a text-frame

### ISSUE THREAD

**Issue by nitayke** [dolanmiu/docx#2219]
Hi, I'm trying to create a text-box with 2 lines inside - heading and body of text.
I want the heading to be bold, and the body to be aligned to both sides.
If I use "break" in "TextRun", it makes line break but the heading is aligned to both sides:
![image](https://github.com/dolanmiu/docx/assets/63166525/c657d4d9-fc09-4c52-a30e-6a2a6da206a6)
Is there a way to make the heading not be aligned to both sides?
Thanks

**Comment by dolanmiu** [comment]
Yes
Try making the heading as a separate Paragraph

**Comment by nitayke** [comment]
But the text-frame itself is a paragraph...
Can I put two paragraphs in the children of a text-frame paragraph?

**Comment by dolanmiu** [comment]
Yeah, i am not sure if this is possible. Is this even possible with Word itself?

I can do it in word by adding a table into the text box, but that seems hacky, the generated `ooxml` is weird

**Comment by dolanmiu** [comment]
Perhaps we need two features, a `TextFrame` and Word's `TextBox`

Seems to be different concepts.

`TextBox` would be a new feature, seems complicated, uses the graphics API

**Comment by kalda341** [comment]
I would love a text box feature too. I agree it would likely be a big job.
