### ISSUE TITLE
Is there a way control the space between the index number and the text in a list?

### ISSUE THREAD

**Issue by amitm02** [dolanmiu/docx#222]
Is there a way control the space between the index number and the text in a list?
I could find how to control the indent of an item, but not the space between the text and the index number..

**Comment by dolanmiu** [comment]
Perhaps styles?

**Comment by dolanmiu** [comment]
Can do like so:

https://github.com/dolanmiu/docx/blob/master/demo/29-numbered-lists.ts#L50
