### ISSUE TITLE
Packer.toBuffer() returns a UInt8Array

### ISSUE THREAD

**Issue by tripodsan** [dolanmiu/docx#2222]
with version 8.2, the `Packer.toBuffer()` now returns a UInt8Array:

![image](https://github.com/dolanmiu/docx/assets/917628/b5785c21-e7ad-4dc6-807a-c779ec7eecd5)

maybe something changed during the TS compilation and bundling?

```
$ node --version
v18.16.0
```

**Comment by dolanmiu** [comment]
Weird. It does seem to return Buffer from the source code:

https://github.com/dolanmiu/docx/blob/master/src/export/packer/packer.ts#L31

And yes, in 8.2, I have moved the project from `webpack` to a more modern `vite` based build system, so maybe that's why?

**Comment by tripodsan** [comment]
btw, my workaround:

```
  let buf = await Packer.toBuffer(doc);
  if (buf instanceof Uint8Array) {
    buf = Buffer.from(buf);
  }
  ```

**Comment by dolanmiu** [comment]
I've made a PR here to hopefully fix it:

https://github.com/dolanmiu/docx/pull/2244

**Comment by pooledge** [comment]
Just a heads up, presumably related. I had an edge case, where `bun` (v0.7.3 at moment of writing) stopped responding after repeatedly calling:
```ts
await Packer.toBuffer(document);
```
at least 3 times in a row. It came out during performance testing. I was able to overcome it by converting to `Buffer` on my own:
```ts
const blob = await Packer.toBlob(document);
const arrayBuffer = await blob.arrayBuffer();
const file = Buffer.from(arrayBuffer);
```
