### ISSUE TITLE
Enable "Track Revisions"

### ISSUE THREAD

**Issue by bre7** [dolanmiu/docx#223]
I'll submit a PR soon.

Add `w:trackRevisions` flag under settings (https://github.com/dolanmiu/docx/blob/master/src/file/settings/settings.ts ???)

`<w:trackRevisions w:val="true"/>`
or
`<w:trackRevisions w:val="false"/>`

**Comment by dolanmiu** [comment]
sweet, ok, sounds good to me

**Comment by dolanmiu** [comment]
Track revisions is now supported
