### ISSUE TITLE
Can't set table cell margins

### ISSUE THREAD

**Issue by mettin** [dolanmiu/docx#225]
according to the documentation found at https://docx.js.org/api/classes/tablecellmargin.html i should be able to add margin to table cells but that documentation doesnt make sense to me at all since it assumes you're styling with XML i think. How can you implement this in js?

**Comment by dolanmiu** [comment]
I noticed you posted a reply on another issue

have you resolved your problem?

**Comment by dolanmiu** [comment]
I am working on better image support at the moment

I'll get round to making the table API better once I finish that

**Comment by mettin** [comment]
Haven't resolved my issue, just went through the issues to see if I could help anyone else.
Thanks for the update, keep up the good work!

**Comment by bba278** [comment]
Are there any updates on setting table cell margins? Thanks

**Comment by dolanmiu** [comment]
Will be fixed with:

https://github.com/dolanmiu/docx/pull/288
