### ISSUE TITLE
docx 8.2.1 can't be imported client-side in Next.js 13 at all

### ISSUE THREAD

**Issue by Alazoral** [dolanmiu/docx#2255]
8.2.1, the latest release, results in an empty module being imported in Next.js on the client, (but not on the server). I have created a [repo that reproduces this issue minimally](https://github.com/Alazoral/docx-import-error-repro). It doesn't seem to occur with 8.2.0, so that is my workaround at this point.

Thanks so much for all the hard work you all do on this. I really appreciate the library.

**Comment by LubosD** [comment]
Also reproduced with Angular when using ES2022 as the module type in TypeScript.

**Comment by dolanmiu** [comment]
Does anyone have experience of how bundlers work?

All these issues are happening because of `webpack` to `vite`, brings some benefits like ES Modules, and ESBuild, but a lot of other strange issues like this

**Comment by dolanmiu** [comment]
@LubosD I think for your issue, it could be that Angular for some reason picked the CommonJS bundle

I found some resources, maybe it's about how it's exported:

https://nodejs.org/api/packages.html#conditional-exports

**Comment by dolanmiu** [comment]
I have made a fix https://github.com/dolanmiu/docx/pull/2256

And have released `8.2.2`

Hopefully it fixed it?

**Comment by ginagr** [comment]
8.2.2 fixed it for me in my Angular project, thank you for such a quick fix!

**Comment by Alazoral** [comment]
Awesome that seems to have fixed it, thanks so much
