### ISSUE TITLE
How to add image to a paragraph with position vertical center?

### ISSUE THREAD

**Issue by candysp** [dolanmiu/docx#226]
Hi. I am trying to add pictures to a paragraph, I hope that image will be in the middle of the paragraph. Can someone help me?
This is my code:
```
const doc = new docx.Document();
const paragraph = new docx.Paragraph();
paragraph.addRun(new docx.TextRun('Hello'));
const image = docx.Media.addImage(doc, fs.readFileSync(imgUri), width, height, {
  floating: {
    verticalPosition: {
      align: "center",
      relative: "paragraph"
    }
  }
});
paragraph.addImage(image);
doc.addParagraph(paragraph);
```

**Comment by dolanmiu** [comment]
Have you tried this?

https://docx.js.org/#/usage/paragraph?id=text-alignment

**Comment by dolanmiu** [comment]
That is not possible AFAIK.

In technical words, you are trying to use `horizontal alignment` in a `text run`, but this is only a feature in Paragraphs:

http://officeopenxml.com/WPalignment.php
