### ISSUE TITLE
Unable to read vector images

### ISSUE THREAD

**Issue by cactuer** [dolanmiu/docx#2263]
# Thank you for raising an issue to `docx`

Please do not raise an issue unless it is an **issue**.

-   Is your issue a feature request? Are you giving ideas to the community? Are you asking for help? Please raise a ticket in the `Discussions` section:

    https://github.com/dolanmiu/docx/discussions

-   Is your issue a previously asked? Please respond to that thread instead

**Comment by dolanmiu** [comment]
Duplicate ticket:

https://github.com/dolanmiu/docx/issues/1162

**Comment by cactuer** [comment]
Thank you very much for your answer！
