### ISSUE TITLE
Impossible to multiple patches of a key in a same paragraph

### ISSUE THREAD

**Issue by Suniron** [dolanmiu/docx#2267]
Hey there!

I can't do multiple patches of the same key in one sentence.

For example, in the following text, only the first key will be patched:

```
The company {{company_name}}, is {{company_name}}
```

I'm using the code above to patch my docx files: 

```ts
import {
  PatchType,
  TextRun,
  patchDocument,
} from 'docx'

const patchedDocxTemplate = await patchDocument(baseDocxTemplate, {
   patches: {
    company_name: {
      children: [new TextRun('MY_COMPANY')],
      type: PatchType.PARAGRAPH,
    },
  }
})
```

**Comment by Suniron** [comment]
I'm using this fix but I'm not really proud about it 🥲

```ts
      const patchTheDocument = async (data: Buffer) => await patchDocument(data, {
        patches: {
          company_name: {
            children: [new TextRun('MY_COMPANY')],
            type: PatchType.PARAGRAPH,
          },
        },
      })

      // Patch the document a first time:
      let patchedDocxTemplate = await patchTheDocument(baseDocxTemplate)
      // Patch the document 10 times to avoid the case where multiple same keys are in the template (not patched), see https://github.com/dolanmiu/docx/issues/2267
      for (let i = 0; i < 10; i++) {
        patchedDocxTemplate = await patchTheDocument(Buffer.from(patchedDocxTemplate))
      }
```

**Comment by mateobv07** [comment]
> I'm using this fix but I'm not really proud of it 🥲
> 
> ```ts
>       const patchTheDocument = async (data: Buffer) => await patchDocument(data, {
>         patches: {
>           company_name: {
>             children: [new TextRun('MY_COMPANY')],
>             type: PatchType.PARAGRAPH,
>           },
>         },
>       })
> 
>       // Patch the document a first time:
>       let patchedDocxTemplate = await patchTheDocument(baseDocxTemplate)
>       // Patch the document 10 times to avoid the case where multiple same keys are in the template (not patched), see https://github.com/dolanmiu/docx/issues/2267
>       for (let i = 0; i < 10; i++) {
>         patchedDocxTemplate = await patchTheDocument(Buffer.from(patchedDocxTemplate))
>       }
> ```

Im still having the same issue when the same word to be patched is multiple times in the same paragraph, using your fix worked but is there a better solution now?

**Comment by carlgleisner** [comment]
I'm also running into this 🤔

**Comment by Suniron** [comment]
I don't really understand why my issue was closed.. 😞

**Comment by carlgleisner** [comment]
Ok @Suniron I'm going to attempt to debug this issue and provide a solution – if possible. Don't know when I'll be able to find the time to familiarise myself with the codebase but, yeah. It's the "open source thing" to do in this situation. Very happy to contribute! If I'm able to solve it.

To state the obvious: I guess it's a logical issue where subsequent occurrences of a `{{patch}}` within the same paragraph aren't processed.

If we put our minds together at some point, we really should be able to get to the bottom of this.

**Comment by mateobv07** [comment]
Thanks @carlgleisner If you need any help im down, I also really want this fixed :)

**Comment by mateobv07** [comment]
I started looking into this, I am pretty sure it has already been fixed lol. I think this is the problem https://github.com/dolanmiu/docx/issues/2605

It isnt released in the latest version. When I cloned the project and started running some tests it was actually working and replacing all patches in the same paragraph.

**Comment by carlgleisner** [comment]
> I think this is the problem #2605

This makes a lot of sense 🙂
