### ISSUE TITLE
Looking for implementation around how to get the current page number in the section.

### ISSUE THREAD

**Issue by asitparida** [dolanmiu/docx#2274]
The documentation at https://docx.js.org/#/usage/headers-and-footers?id=example says "New headers and footers can be set per Section" but am unsure how to do it. The three props inside headers or footers are "default", "first", "even". Where do I put a header/footer where I have some custom logic per section or per page ? I dont think it goes inside "children" for a section.

Ideally I am looking for something like

```
const section = {
...
{
headers :{
 children : [CUSTOM HEADER FOR PAGE/SECTION GOES HERE]
}
}
...
}
```

**Comment by asitparida** [comment]
I was able to figure out where I made the mistake. But any pointers on how to print what page number it is for the current section ? PageNumber.CURRENT is the number against the entire docx. Looking to implement something like 
`PageNumber.CURRENT_IN_SECTION`

**Comment by dolanmiu** [comment]
Not possible, would require rendering of the document to figure out where each element is placed, and this find the page
