### ISSUE TITLE
typings not found when ESModules with typescript

### ISSUE THREAD

**Issue by simonmumenthaler** [dolanmiu/docx#2289]
When working with esm and typescript, the types cannot be found.

probably same issue as this documented here:

[github.com/microsoft/TypeScript/issues/50067#issuecomment-1201663658](https://github.com/microsoft/TypeScript/issues/50067#issuecomment-1201663658)

**Comment by dolanmiu** [comment]
Can you show me your project set up? It works with me with ESM/Typescript

**Comment by simonmumenthaler** [comment]
## Setup
#### package.json
```json
{
  "name": "docx-lib-with-ts-and-esm",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "tsc"
  },
  "dependencies": {
    "docx": "^8.2.0"
  },
  "devDependencies": {
    "typescript":"5.1.6"
  }
}

```
#### tsconfig.json
```json
{
    "compilerOptions": {
      "baseUrl": ".",
      "outDir": "./dist",
      "target": "ES2022",
      "module": "ES2022",
      "moduleResolution": "Node16"
    }
  }
```
#### index.ts
```ts
import { TextRun } from 'docx'

const r = new TextRun('Test')
```

## Resulting Error
When executing `tsc`, the error is this one:

```
node_modules/docx/build/index.d.ts:1:34 - error TS2834: Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

1 export { File as Document } from "./file";
```


## proposed solution in `docx`
In `package.json` the `exports` value should probably look something like this:
```json
{
    "exports": {
        ".": {
            "require": { "default": "./build/index.cjs", "types": "./build/index.d.ts"}
            "import": { "default": "./build/index.js", "types": "./build/index.d.mts"}
        }
    }
}
```

Then the `index.d.mts` should use the `.js` extension for the relative file imports while the `index.d.ts` doesn't need any change.
#### index.d.mts
```ts
export { File as Document } from "./file.js";
```

**Comment by dolanmiu** [comment]
There is no `index.d.mts` in the build:

![image](https://github.com/dolanmiu/docx/assets/2917613/d81b305b-3c8b-482d-a5de-f9ea755dc7e8)

**Comment by dolanmiu** [comment]
Closing, stale

Open if this is an issue again
