### ISSUE TITLE
Standardized formatting methods

### ISSUE THREAD

**Issue by felipeochoa** [dolanmiu/docx#23]
Right now there are multiple places where formatting methods (like `.bold()` or `.font()`) can be called, and we're not consistent in the ones we support. There are a few things we have to do:

- [ ] Document the complete list of formatting methods available
    - [X] Run-level (e.g., bold)
    - [X] Paragraph-level (e.g., indent)
    - [ ] Table-level (e.g., layout algorithm)
- [ ] Ensure they can be consistently applied in relevant contexts
    - [X] In-line runs (run-level)
    - [X] In-line paragraphs (~~run-level~~ + paragraph)
    - [ ] In-line tables (~~run-level + paragraph~~ + table)
    - [ ] Run named styles (run-level)
    - [X] Paragraph named styles (run + paragraph)
    - [ ] Table named styles (all three)
    - [ ] Numbering styles (all three)
        - [X] Run methods
        - [X] Paragraph methods
        - [ ] Table methods

**Comment by dolanmiu** [comment]
> Right now there are multiple places

but `.bold()` and `.font(fontName: string)` can only be called from `Run` though. I don't fully understand

**Comment by felipeochoa** [comment]
Yeah that's precisely the issue. `Paragraph.bold()` should work, since DOCX allows setting the property paragraph-wide; ditto tables. We should also have `RunStyle` object with a `.bold()` method, and should add it to `ParagraphStyle`

**Comment by dolanmiu** [comment]
Does the office xml documentation even allow applying **bold** to paragraphs? 

I assumed all that stuff was only available to the run. I could be (and hope that I am) wrong!

**Comment by felipeochoa** [comment]
I could have sworn there was an element for "paragraph run-style properties", but looking through the spec now it looks like I was wrong! I think I just got confused with the paragraph styles, which do indeed have a separate section for run-styles. So you can, e.g., define `ListParagraph` to be indentend and bold.

**Comment by dolanmiu** [comment]
If **bold** is only available in the run, we would in future make `.bold()` in the `Paragraph` object which manually adds bold to all the `Runs`, which will make it less tedious for the user

Otherwise the user would have to `.bold()` every time, which might not be fun

But this is non-priority though, I don't see much reason for a user to bold an entire paragraph, it will look weird maybe 😂

**Comment by dolanmiu** [comment]
Closing, stale
