### ISSUE TITLE
How to position and scale image in footer/header

### ISSUE THREAD

**Issue by paulgrove** [dolanmiu/docx#230]
I can see how to use the PictureRun interface as documented, but I can't work out how to apply that interface to images added to the document.Footer or document.Header.

My goal is to have an image simply right aligned in the document.

Could an example of how to do this be provided.

Snippet of my current code so far, which places the image in the wrong location and wrong scale:
```
		const footerImageResp = await axios.get("/vue/footer-image.png", {responseType: "arraybuffer"});
		const footerImage = docx.Footer.createImage(footerImageResp.data);
```

**Comment by paulgrove** [comment]
I've been trying this for a while, digging into the source a bit.

Here is my closest attempt:
```
		const footerImageResp = await axios.get("/vue/footer-image.png", {responseType: "arraybuffer"});
		const image = Media.addImage(docx, footerImageResp.data, undefined, undefined, {
			position: PlacementPosition.FLOATING,
			floating: {
				horizontalPosition: {
					relative: HorizontalPositionRelativeFrom.MARGIN,
					align: HorizontalPositionAlign.RIGHT,
				},
				verticalPosition: {
					relative: VerticalPositionRelativeFrom.MARGIN,
					align: VerticalPositionAlign.BOTTOM,
				},
			}
		});
		docx.Footer.createParagraph().addImage(image); // displays "The picture can't be displayed."
		docx.addImage(image); // correctly displays the image - but only in the main document, not on every page in the footer
```

**Comment by dolanmiu** [comment]
Sorry for late response, been busy, I was going to write an example for you

This issue has been fixed on master with https://github.com/dolanmiu/docx/pull/217

Pending release

**Comment by paulgrove** [comment]
Thanks for this.

I managed to work around the issue using `document.Footer.addImageRelationship` but will look forward to the next release!

Great library by the way, love it!

**Comment by dolanmiu** [comment]
Yes that is the work around :)

The bug is essentially that it wasn't adding the relationship as you mentioned

Thanks again

**Comment by kongsgard** [comment]
Has this issue been fixed?

I can change the position of an image with the floating option for `doc.createImage([...])` in docx/demo/demo38.ts
However, this does not work if I add the image to the header with `doc.Header.createImage([...])`.

**Comment by dolanmiu** [comment]
> However, this does not work if I add the image to the header

Yes, that feature isn't on headers and footers yet

**Comment by jafox7** [comment]
Is there any chance that the case will be fixed?
