### ISSUE TITLE
TableRow tableHeader sometimes not working correctly?

### ISSUE THREAD

**Issue by longgtruong** [dolanmiu/docx#2310]
I set `tableHeader` to `true` on `TableRow`. It used to work sometimes but now it does not repeat the header rows on the other pages for my table? I have to pin the row manually in Word.

**Comment by longgtruong** [comment]
No updates on this, i tried a sample code and it's not repeating row?

**Comment by anti-the-social** [comment]
Header for the table doesn't mean it should repeat itself on every page.
Even in Word you have to do additional button click.
Therefore, there is specific tag or property in OOXML standard that is responsible for it.

1. You can create simple word document with table where headers are not repeatable
2. Duplicate it
3. Add the repetitivness
4. Compare xml of the documents
5. Find proper tag
6. Check the source code of the docxjs library
7. If such tag/property is not possible to add -> propose new feature
8. If such property exist -> propose new article into documentation
9. You are beautiful 😉

P.S. yes, .docx file you can change extension from .docx to .zip and just open it and see the xml files.

**Comment by longgtruong** [comment]
Thanks for your reply, but i was referring to this function: https://docx.js.org/#/usage/tables?id=repeat-row

`If a table is paginated on multiple pages, it is possible to repeat a row at the top of each new page by setting tableHeader to true`

**Comment by anti-the-social** [comment]
Well,

The tblHeader is used 
https://github.com/dolanmiu/docx/blob/d5d80550e7785d59a5d09415c324ab813fa7fcf3/src/file/table/table-row/table-row-properties.ts#L53C2-L53C2

Like standard suggests 
http://officeopenxml.com/WPtableRowProperties.php

May be its related to this exception (not the first row)?
<img width="856" alt="image" src="https://github.com/dolanmiu/docx/assets/69673750/520b2cf7-fe44-4a2a-b738-4881c78f9b80">

**Comment by longgtruong** [comment]
i have found my issue, thanks for your help! it was because of the code i wrote. closing this!
