### ISSUE TITLE
Unsupported type for pageMargin coordinates

### ISSUE THREAD

**Issue by Dheeraj3reddy** [dolanmiu/docx#2327]
Hi,
The generated docx documents contains the following pgMar tag in document.xml 
`<w:pgMar w:top="1in" w:right="1in" w:bottom="1in" w:left="1in" w:header="708" w:footer="708" w:gutter="0"/>` 
As specified in documentation of Ecma Office Open XML. Section 17.6.11, ( you can also refer it [here](http://webapp.docx4java.org/OnlineDemo/ecma376/WordML/pgMar.html))

According to it the possible values for the coordinates are in twips.
`The possible values for this attribute are defined by the [ST_SignedTwipsMeasure](http://webapp.docx4java.org/OnlineDemo/ecma376/WordML/ST_SignedTwipsMeasure.html) simple [type](http://webapp.docx4java.org/OnlineDemo/ecma376/WordML/type.html) (§2.18.88).`

But the generated documents contain the dimensions in inches. Please look into this issue.

**Comment by Dheeraj3reddy** [comment]
Hi, any update on this issue?

**Comment by rahon6000** [comment]
I had similar issue today. Maybe this would help.

Add this `properties` in the `section`.

```javascript
const doc = new Document({
    sections: [
        {
            properties: {
                page: {
                    margin: {
                        top: convertInchesToTwip(1),
                        bottom: convertInchesToTwip(1),
                        left: convertInchesToTwip(1),
                        right: convertInchesToTwip(1)
                    }
                }
            },
...
```

In my case, (maybe has same origin you wrote) my old word editor doesn't support "inches" unit.

Since some minor editors fail to open samples provide here. I think there should be an option to use twip for inches. (or at least default value should be twip?)

😅

**Comment by dolanmiu** [comment]
Defaults are now Twip:

https://github.com/dolanmiu/docx/pull/2379
