### ISSUE TITLE
[BUG] Mobile: Text Z-index of Hero Overlaps Navbar

### ISSUE THREAD

**Issue by jrTilak** [dolanmiu/docx#2329]
[BUG] on mobile devices in [https://docx.js.org/#/](https://docx.js.org/#/). The hero section overlaps the navbar.
## Watch this video for steps to reproduce and solution:

https://github.com/dolanmiu/docx/assets/106688422/ff44b84a-dd16-4eec-ab27-70e5eb3165c8

**Comment by dolanmiu** [comment]
This is a bug with docsify unfortunately. nothing docx can do about this!
