### ISSUE TITLE
Any change you'll be adding highlighting or comments to code

### ISSUE THREAD

**Issue by sshadmand** [dolanmiu/docx#233]
Pretty please ;-D

**Comment by dolanmiu** [comment]
on the to-do list now 😄

**Comment by bre7** [comment]
@sshadmand http://officeopenxml.com/WPtextShading.php 😉 

> <w:highlight w:val="red"/>

> Possible values are: black, blue, cyan, darkBlue, darkCyan, darkGray, darkGreen, darkMagenta, darkRed, darkYellow, green, lightGray, magenta, none, red, white, yellow

**Comment by dolanmiu** [comment]
thanks! im looking into it

Just hard to think of a suitable easy to use API

**Comment by mbrevda** [comment]
I believe this was added in v5?

**Comment by dolanmiu** [comment]
Yup 

https://github.com/dolanmiu/docx/blob/master/demo/45-highlighting-text.ts
