### ISSUE TITLE
error starting an empty table

### ISSUE THREAD

**Issue by jimyhdolores** [dolanmiu/docx#2344]
I need to create the rows and columns dynamically, so I start the "rows" arrary empty

![image](https://github.com/dolanmiu/docx/assets/10909792/6b8f5d11-35c9-4878-b1a3-29b6cac086ed)

But when executing the code it throws the following error:
![image](https://github.com/dolanmiu/docx/assets/10909792/9e28e7b2-2773-4d55-bb8f-aa89ccefbed7)

This problem is solved if I add a row with an empty cell, but the table remains with that and it does not look aesthetic; It should be possible to start a table with empty rows, I understand that a table cannot be left without rows but that depends on the developer, it should not be a problem when developing

**Comment by dolanmiu** [comment]
This is not the way to do it. It is immutable so you can't use the private addChildElement methods. You'd need to code it in a declarative way for it to work
