### ISSUE TITLE
Table inside paragraph not possible

### ISSUE THREAD

**Issue by lukasbash** [dolanmiu/docx#2368]
At the moment, outputting tables inside paragraphs does not work. Is this an intended behaviour?

We use the library to convert our document structure into Word documents and track the current paragraph to output our structure in a semantical way.

Related: https://github.com/dolanmiu/docx/issues/2120

**Comment by anti-the-social** [comment]
Hi!

By my experience, Word doesn't not allow wrap table with paragraph. (or insert table into paragraph)
It would take time to find proof tho. Probably you can dig ooxml standard yourself for it?
