### ISSUE TITLE
Generate buffer from image in browser

### ISSUE THREAD

**Issue by hmouhtar** [dolanmiu/docx#238]
So I'm using the library on browser-side without nodeJS.
In the docs the method `document.createImage()` requires a buffer. I'm using a [library](https://github.com/feross/buffer) to implement the nodeJS buffer functionality in the browser but I honestly have no clue about how to proceed without having to implement fileSystem functionality.

I'd like to use an URL to load the image.
Thanks for any help!

**Comment by dolanmiu** [comment]
`Buffer` is only supported in NodeJS, there is no such concept as buffer in the browser world!

Fortunately, `createImage()` can also take in a `base64 string` or a `Uint8Array` or `ArrayBuffer`, which are in the browser world:

https://github.com/dolanmiu/docx/blob/master/src/file/file.ts#L139

**Comment by hmouhtar** [comment]
Thanks! Also, may I ask why can't images be inserted directly? I'm not very familiar with nodeJS environment.

**Comment by dolanmiu** [comment]
I wanted that de-coupling from the implementation

I wanted `docx` to not care about how/where/when the image was gotten from. It can be from NodeJS buffers, or through Angular's `this.http.get`. All `docx` needed to know was the data.

**Comment by hmouhtar** [comment]
Makes sense. Thanks!
