### ISSUE TITLE
Possibility to indent text without starting new paragraph

### ISSUE THREAD

**Issue by lukasbash** [dolanmiu/docx#2381]
So I have the following situation:
I am currently mapping a custom document structure to docx via your library. So far most of the things are working out. Right now I came to the topic of setting an indent to a specific part of the text. Imagine a text similar to a list level (e.g. `A. MyText`). The requirement is now, do be able to indent the text at any given part of the paragraph (e.g. semantically indent to `A.         MyText`).

Should this be possible with the following key points?:
- I cannot use tabstops
- I cannot use list settings
- I cannot define the paragraph indents beforehand (I thought about defining all paragraphs with relative variants; e.g. `header_indent_10pt`, or similar, but this does not work as I do not know all the indentations before I visited them in my structure), and also I would have to switch style runs on-the-fly, which I did not get working either
- I tried using `new docx.Indent`, incrementing a value for the `left`/`hanging` property whenever I visit an indent, and then when I come to a text element, using `Paragraph#addChildElement`, but it does not change anything.

Any ideas how I can indent text without creating new paragraphs, new lines, etc.? It should also be possible to nest indents, either absolutely to the page, or relative to the indent before.

**Comment by anti-the-social** [comment]
Have you tried doing it in Word in general? If yes then how?

**Comment by lukasbash** [comment]
@anti-the-social Good question. The only way was using textboxes, position them absolutely on X an centered to line Y, using the same format. What is the purpose on allowing standalone `Indent` instances?

It sounds like you're gonna tell me it is not possible 😄

**Comment by anti-the-social** [comment]
textboxes/frames is something that exist in docxjs library, I've been using it for locating e.g. page numbers.

I wanted to tell that if such indentation came to your mind then it probably exist somewhere. If that was CSS then you might be in trouble, if it was Word then providing the steps/file with such things can let me to disassemble it to XML and check what kind of tags or attributes of OOXML format you've been using. Thereafter its possible to find the methods of docxjs lib that implements the same thing (or suggest an improvement if such do not exist)
