### ISSUE TITLE
Embedding font

### ISSUE THREAD

**Issue by filippomuscolino** [dolanmiu/docx#239]
Hi!
I was wondering if it could be possible to embed fonts into the document. Is it something that maybe you planned to do?
Thanks!

Filippo

**Comment by dolanmiu** [comment]
need to look into what work that would entail

seems possible, now need to replicate this in code

https://www.howtogeek.com/106681/how-to-embed-fonts-in-a-microsoft-word-document/

**Comment by filippomuscolino** [comment]
I did some research and in [ECMA-376-1](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-376,%20Fifth%20Edition,%20Part%201%20-%20Fundamentals%20And%20Markup%20Language%20Reference.zip) there's a description on how to embed a font.
It seems that you have to include a fontsTable.xml and the embedded version of the font (I tried with LibreOffice and the format is ODTTF)

**Comment by dolanmiu** [comment]
This document is 5039 pages long, can you direct me to the specific page?

**Comment by filippomuscolino** [comment]
You're right, sorry! :) It's page 669 (chapter 17.8)

**Comment by dolanmiu** [comment]
Seems doable actually!

Thanks! I'll most likely prepare it for the v5 release

**Comment by filippomuscolino** [comment]
Great! I'll wait for it, then!
Thanks

**Comment by dolanmiu** [comment]
From what i've been reading, the font needs to be coverted to a special type of format, im not sure of anywhere which does this

do you know?

**Comment by jwerre** [comment]
I wonder if you could include a font engine such as [fontkit](https://github.com/foliojs/fontkit) to embed the font in the document.

**Comment by dolanmiu** [comment]
Never heard of it, but I'll take a look

**Comment by dolanmiu** [comment]
So I don't think fontkit creates ODTTF, which is the format Word documents need:

https://github.com/foliojs/fontkit/issues?utf8=%E2%9C%93&q=ODTTF

**Comment by dolanmiu** [comment]
On a side note, I found this though:

https://gist.github.com/dungsaga/ab8d2379bb566c9925b27df3bc82ca8b

But it's in reverse, it converts ODTTF to TTF

Would welcome a PR which creates the reverse of that gist above

**Comment by vijayarun** [comment]
any update?

**Comment by dolanmiu** [comment]
I am stuck on the conversion of TTF to ODTTF, need to figure out how to do this.

Word only accepts the ODTTF file format for fonts

**Comment by Hunderhan** [comment]
I found a paper that might be helpful to you @dolanmiu 
4.2.2 Remote Font Attack Vector – Docx: 
The remote font attack can be launched by embedding a crafted font into a 
Microsoft Office document. To do this, a TTF file format has to be converted 
into an obfuscated TTF font file format (ODTTF) before performing the 
embedding process and this must satisfy the following requirements. 
1. A 128-bit Global Unique Identifier (GUID) is generated. 
2. An XOR operation on the first 32 byte of the TTF is performed. 
3. The ODTTF font file is embedded into Microsoft Office Word. 
![image](https://user-images.githubusercontent.com/71619766/227828131-df9a25c9-aaec-45a8-9974-d58dbcf24288.png)
Figure 6: Performing the XOR operation on the first 32 byte of the TTF 
The Python code below simplifies the obfuscation process by converting the 
TTF file to an ODTTF file. 
1. fontKey = keys.decode("hex")     
2. obfFontString = open(ttfFontFile, 'rb').read()
3. fontString = [ord(x) for x in obfFontString]
4. fori in range(16):
5.      fontString[i] = ord(obfFontString[i]) ^ ord(fontKey[15‐i])
6.      fontString[i+16] = ord(obfFontString[i+16]) ^ ord(fontKey[15‐i])
![image](https://user-images.githubusercontent.com/71619766/227828245-10cc40f9-9f24-4989-9091-dc80def924d7.png)
Figure 7: Successfully embedded a crafted TTF font file in Microsoft

**Comment by dolanmiu** [comment]
Thank you so much for this!

**Comment by jacwright** [comment]
Not sure if it works, but I asked Chat GPT 4 to reverse the Gist posted above and got https://gist.github.com/jacwright/40c50faa29257c8b76666c1e077352f1.

**Comment by Gin-Quin** [comment]
@Hunderhan Can you explain a bit more your algorithm? I tried to use it but not successfully.

DOCX files use a key in the form `DCE3A64CF7794054BEB7A126DC76748C` to obfuscate/unbofuscate .ttf files. This is the 128-bits GUID you are talking about.

But where do you use it?

In your algorithm, it seems you are using a key of 16 characters, that you use twice, for the first 16 bytes, then again for the last 16 bytes:

```
     fontString[i] = ord(obfFontString[i]) ^ ord(fontKey[15‐i])
     fontString[i+16] = ord(obfFontString[i+16]) ^ ord(fontKey[15‐i])
 ```
