### ISSUE TITLE
Text size Reduce font size by twice

### ISSUE THREAD

**Issue by benstCodsf** [dolanmiu/docx#2391]
After setting the size of docxjs TextRun, I don't know why the font size of the downloaded file has doubled

**Comment by anti-the-social** [comment]
Hi,

That's intended way of working. Font size is measured in half-points.

docxjs documentation reference: https://docx.js.org/#/usage/styling-with-js?id=run-formatting
OOXML standard reference: http://officeopenxml.com/WPtextFormatting.php
