### ISSUE TITLE
docx + Angular2

### ISSUE THREAD

**Issue by dolanmiu** [dolanmiu/docx#24]
Trying to get it working with Angular2 for a `docx` demo, but I get the following issue:

![screen shot 2017-03-11 at 21 41 47](https://cloud.githubusercontent.com/assets/2917613/23827096/a3566482-06a3-11e7-9175-695f8ee3b619.png)

I believe its a fault within the `archiver` npm module which uses `grateful-fs`

https://github.com/isaacs/node-graceful-fs/issues/109

Maybe it is simply not possible to do this on the client side and it must be on a node instance

**Comment by danad02** [comment]
Same problem with React

**Comment by dolanmiu** [comment]
Doesn't work as this library depends on the `fs` module which is exclusive to node, not front end

**Comment by cschoeni** [comment]
Why you write the text "Easily generate .docx files with JS/TS. Works for Node and on the Browser. 100" on the docs?

Please change this to "Easily generate .docx files with JS/TS. Works only with Node. 100!

**Comment by dolanmiu** [comment]
Why? It works on the browser

**Comment by dolanmiu** [comment]
Forgot to mention that there was a PR which made it work on the browser
