### ISSUE TITLE
docx is not being transpiled correctly in IE11

### ISSUE THREAD

**Issue by alperunal** [dolanmiu/docx#240]
Hello,

I use docx in my Angular 7 application. It works well on Chrome, Firefox, Safari and Edge. However, i get syntax error on ie11. 

![docx-bug](https://user-images.githubusercontent.com/3315113/50962169-ebe2c480-14c9-11e9-98b7-caff5537bc79.PNG)

Target is ES5 in my tsconfig file. Other 3rd party libraries are correctly being transpiled.

**Comment by dolanmiu** [comment]
I have never tested this library on internet explorer before

Good to know

**Comment by dolanmiu** [comment]
Can you tell me what front-end framework you are using? Angular?

**Comment by alperunal** [comment]
Yes, I use Angular 7.

I set target to es5 also needed to add 
`"lib": [ "es2015", "dom" ]`
to build docx for es5.

**Comment by efx** [comment]
Seeing a similar thing in an ember application. `ember-cli` uses babel for transpiling.

**Comment by msv-phulatt** [comment]
I'm also experiencing this issue, is there a workaround for getting it working in IE11?

**Comment by dolanmiu** [comment]
There is a PR which solves this issue, but it is failing some tests

https://github.com/dolanmiu/docx/pull/241

**Comment by XGhozt** [comment]
Same issue here.

**Comment by DakotaWray2** [comment]
Any follow up on why the test fails?
Would love to be able to use this with IE

**Comment by chetanraskar** [comment]
Any progress on this ,I am facing this for Vue. Although I could transpile library. I am getting below error 
"export 'Paragraph' was not found in 'docx'

**Comment by XGhozt** [comment]
I thought maybe I should share this... I have it working but, the tests fail. From what I can tell it works fine though (in ie11 and not ie11). https://github.com/XGhozt/docx

**Comment by dolanmiu** [comment]
I won't be doing this feature as the solution is to change the target from `es6` to `es5`, which significantly increases the size of the bundle (300kb to 1.3mb, that's a 400% increase).

I am not sure if it is worth it. Microsoft will drop support of IE completely in 2021, so I don't think developers should support it either.

If people want IE11 support, then im afraid they need to build their own one.
