### ISSUE TITLE
Attempted import error: 'Packer' is not exported from 'docx' (imported as 'Packer').

### ISSUE THREAD

**Issue by emon5122** [dolanmiu/docx#2420]
Getting Error after upgrading to 8.2.4
Given code below:
```ts
import { format } from "date-fns";
import { Document, ISectionOptions, Packer } from "docx";
import { saveAs } from "file-saver";

export const saveToWord = async ({
  sections,
  name,
  type,
}: {
  sections: readonly ISectionOptions[];
  name: string;
  type: string;
}) => {
  const doc = new Document({
    sections: sections,
  });
  const blob = await Packer.toBlob(doc);
  saveAs(
    blob,
    `${name}-${type}-${format(new Date(), "HH:mm:ss dd-MM-yyyy")}.docx`,
  );
};

```

**Comment by dolanmiu** [comment]
Is this in a regular browser environment? Or React? etc

**Comment by emon5122** [comment]
React

**Comment by emon5122** [comment]
I was getting errors on all imports after that. 

Following #2365, Cjs import works. ESM has issues.

**Comment by dolanmiu** [comment]
I just tried this using NextJS, and it works fine for me on `8.3.0`

Re-open if there are any more issues

**Comment by emon5122** [comment]
Yes, After Nextjs 14.0.1+ it's working. I think the issue was with Nextjs webpack instead of the library.

**Comment by aoshita** [comment]
I still encounter this issue. Have tried both CJS and ESM. Using latest docx (8.5.0), next 14.1, react 18.2, and javascript. 

When creating a new document (const doc = new Document()), I receive the following error:

`TypeError: Cannot read properties of undefined (reading 'creator')
    at new File (index.cjs:15435:31)
`

**Comment by dolanmiu** [comment]
This is a separate issue, this is because you need to add at least an empty `{ sections: [] }` object in `Document` for it to be valid
