### ISSUE TITLE
ExternalHyperlink renders empty line

### ISSUE THREAD

**Issue by jonmcgill** [dolanmiu/docx#2424]
docx version `8.2.4`

I have a function that generates a link:
```js
function link(text, link) {
  return new docx.ExternalHyperlink({
    link,
    children: [
      new docx.TextRun({
        text,
        style: 'Hyperlink'
      })
    ],
  })
}
```
No matter where I use this (Paragraph, Table, Header, Footer), I just get an empty line. I'm opening the docx file in Pages, Google Docs, and LibreOffice, and in every case there is an empty line.

**Comment by anti-the-social** [comment]
Hi,

Syntax looks correct.
Did you check what's in `text` and `link`?
Did you just update version, or you used only 8.2.4 from the beginning?

**Comment by jonmcgill** [comment]
Hello. Both `text` and `link` are just strings. I have not updated. I just installed `8.2.4` and was trying to get something basic working.

**Comment by dolanmiu** [comment]
It works fine for me?

Check out: https://github.com/dolanmiu/docx/blob/master/demo/35-hyperlinks.ts
