### ISSUE TITLE
Adding different numbering within the same line of paragraph 

### ISSUE THREAD

**Issue by mwashambw** [dolanmiu/docx#2430]
I have been  reading documentation about numbering, passed through all closed, opened issues and discussions but I have not figured out the way of attaining my disired output.

I want to create a document that look like following

1.  (a)  Some random text
     (b)  another text here

2.  (a)  Some random text
     (b)  another text here

3.  (a)  (i)  Some random text \n Bellow should be (ii) with indatation and hanging as (i)
            

     (b)  (i)  Some random text \n Bellow should be (ii) with indatation and hanging as (i)
            

It seem it require a feature of one paragraph having another paragraph but each with different numbering.
Is there any feature to implement this numbering ? OR is there any work round?

**Comment by anti-the-social** [comment]
Hi!

Could you explain how do you do that using Word?

**Comment by mwashambw** [comment]
I have never done this in Word my self, but I have seen many documents that look like that.

**Comment by anti-the-social** [comment]
Well, its all about `text: "%1"` and what you put there for different levels. All the formatting is up to you.
https://docx.js.org/#/usage/numbering?id=using-ordered-lists-in-docx
If you provide some example document we can extract that format from there

**Comment by anti-the-social** [comment]
Unfortunately, I cannot help with pdf or images.
.docx is .zip with .xml files and there we can get exact format
So .docx file required

**Comment by mwashambw** [comment]
Ok, this is the docx file with the same arrangement,
[example_124722.docx](https://github.com/dolanmiu/docx/files/13472519/example_124722.docx)

**Comment by mwashambw** [comment]
So to attain that arrangement I need to play With spaces and tab stop? Or is there any other work round?

**Comment by anti-the-social** [comment]
Not something to complain about docxjs library, but rather Word that is not flexible enough for your case.

**Comment by mwashambw** [comment]
I get the point.Thank you very much for your time

**Comment by anti-the-social** [comment]
Don't forget to close an issue once your problem is resolved :)
