### ISSUE TITLE
Export as blob in version 4 with styles

### ISSUE THREAD

**Issue by hmouhtar** [dolanmiu/docx#244]
So in the docs it says that the correct way to include styles is the following: 
`const packer = new Packer(doc,myStyles);`

But with V4, it doesn't specify how to export as a blob with styles included.

**Comment by dolanmiu** [comment]
Refer to demo 13:

https://github.com/dolanmiu/docx/blob/master/demo/demo13.ts

**Comment by dolanmiu** [comment]
Closing as this is the answer. Feel free to comment here if you need more help

**Comment by hmouhtar** [comment]
But that applies for XML styles, what about JS styles?

**Comment by dolanmiu** [comment]
Refer to demo 2:

https://github.com/dolanmiu/docx/blob/master/demo/demo2.ts

**Comment by hmouhtar** [comment]
Thanks! is there a way to set a global style for all elements, like font family?

**Comment by dolanmiu** [comment]
Yes you can

Override the `Normal` style. All styles in word inherit off this.

```ts
doc.Styles.createParagraphStyle("Normal", "Normal")
    .font("Impact");
```
