### ISSUE TITLE
`PageNumber.TOTAL_PAGES_IN_SECTION` not documented and not functional, but within TS enum

### ISSUE THREAD

**Issue by Jimmy89** [dolanmiu/docx#2449]
I create a docx file with multiple section, where I have in the footer of one section the code:

```
     footers: {
                    default: new Footer({
                        children: [
                            new Paragraph({
                                alignment: AlignmentType.CENTER,
                                children: [
                                    new TextRun({
                                        children: ["Page", PageNumber.CURRENT],
                                    }),
                                    new TextRun({
                                        children: [" of ", PageNumber.TOTAL_PAGES_IN_SECTION],
                                    }),
                                ],
                            }),
                        ],
                    }),
                },
```

I have another section (before this section) with a frontpage and TOC, so this section starts at page 3.
Furthermore, I want to display: page 1 of 15 (with a total of 17 pages). `PageNumber.TOTAL_PAGES_IN_SECTION` should do this, according to its name. The property is valid according to the TS file. However, this property renders nothing.

Update: part of my bug report was invalid. Adjusted that.

**Comment by dolanmiu** [comment]
Hmm yes this is incorrectly named, will address

**Comment by dolanmiu** [comment]
Did some research, I think you are trying to use `CURRENT_PAGE_IN_SECTION`? Which is not possible with OOXML from my research

> However, this property renders nothing.

What does this mean? Try out https://github.com/dolanmiu/docx/blob/master/demo/14-page-numbers.ts

it works for me
