### ISSUE TITLE
When I open a document using WPS office, the width of the table cannot fill the entire page

### ISSUE THREAD

**Issue by xiaowen-Ren** [dolanmiu/docx#2456]
When I open a document using WPS office,The width of the table cannot fill the entire page,May I ask what the reason is?

**Comment by xiaowen-Ren** [comment]
The problem has been resolved

**Comment by anhuet** [comment]
can tell me how to solve it?

**Comment by xiaowen-Ren** [comment]
> can tell me how to solve it?

I just increased the width of the exported table
Type is "WidthType.DXA"
