### ISSUE TITLE
Question prepForXml and MathML 

### ISSUE THREAD

**Issue by LimarenkoDenis** [dolanmiu/docx#249]
Thanks for this awesome lib

I am trying to fill a table with equation values
```
const equation = `
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
    <mi>E</mi>
    <mo>=</mo>
    <mi>m</mi>
    <msup>
    <mi>c</mi>
    <mn>2</mn>
    </msup>
</math>
`
i used https://github.com/mathjax/MathJax-node lib 
doc.addParagraph(new Paragraph(equation).prepForXml())
```

it does not work for me, in the result i get string as is, not formula in word doc

**Comment by dolanmiu** [comment]
Because it adds it in literal text

Equations (or MathML) are not supported. Consider turning it into an image, then adding that in.

MathML is not part of the OOXML (Microsoft Word) spec
