### ISSUE TITLE
Is page break implemented correctly?

### ISSUE THREAD

**Issue by felipeochoa** [dolanmiu/docx#25]
The implementation of `paragraph.pageBreak()` has it add a `<w:br w:type="page"/>` element to the `w:pPr` element of the paragraph. Looking at the spec, I could only find `w:br` under "17.3.3 Run Content", which is implemented as `Run#break`.

If my reading is correct, I think we should remove this method and add it to `Run`

**Comment by dolanmiu** [comment]
https://web.archive.org/web/20160820235211/http://officeopenxml.com/WPtextSpecialContent-break.php

I followed this documentation when implementing it

you can see that it has `<w:br>` with various options for `type`, including `page`

I'm using waybackmachine cos the original website is down (hence im porting it) 😂

**Comment by dolanmiu** [comment]
I have ported the page over:

https://github.com/dolanmiu/Office-Open-XML-Reference/wiki/Paragraph-Line-Break

**Comment by dolanmiu** [comment]
I think you was thinking of the below. Paragraph and Run both have breaks! but they do different things.

https://github.com/dolanmiu/docx/wiki/Text#break

**Comment by jacwright** [comment]
@dolanmiu you are correct that `<w:br w:type="page"/>` is the right way to create a paragraph break. However, docx currently puts that inside `<w:pPr>` which breaks it.

What it looks like now:
```
<w:p>
  <w:pPr>
    <w:r>
      <w:rPr />
      <w:br w:type="page" />
   </w:r>
  </w:pPr>
</w:p>
```

What it should look like:
```
<w:p>
    <w:r>
      <w:br w:type="page" />
   </w:r>
</w:p>
```

**Comment by jacwright** [comment]
This has been fixed in https://github.com/dolanmiu/docx/pull/41. We should be able to close this issue.
