### ISSUE TITLE
Couple issues with embedded fonts

### ISSUE THREAD

**Issue by mattidupre** [dolanmiu/docx#2521]
I might be jumping the gun but I wanted to play with embedded fonts. I've noticed two issues.

Using Word 365 / MacOS:

1: Font names with spaces corrupt the docx file.
2. Every font I tried aside from Pacifico (which I had already installed) is failing to render. The document loads fine but the font disappears from the Word UI selection once it gets changed. I do see those fonts showing up in fontTable.xml file. Confirmed the fonts have no embedding restrictions. Repo using demo 91 and swapping for [Rubik](https://fonts.google.com/specimen/Rubik+Doodle+Shadow) or [Salsa](https://fonts.google.com/specimen/Salsa).

(I did notice that Word will retain a previously-installed font after it has been removed from the system.)

**Comment by jcyovera** [comment]
I have the same trouble using ` "docx": "^8.5.0",` 
Scenario: I embed fonts on the code, `fonts: [{ name: "Pacifico," data: font, characterSet: CharacterSet.ANSI }],` but when I try to open the Word file, the Word app shows an alert that the file is corrupted.

The workaround is to embed the fonts and put a name without spaces, that works for me.

**Comment by jcyovera** [comment]
You are right. The fonts are not loading on the document. It is an issue with the docx library because I follow the example in the repository.

**Comment by vm11elim2** [comment]
i have same issue.... embedded fonts  only works for Pacifico....

**Comment by vatsenko** [comment]
On my side - Corrupted file when space persist in font name (Microsoft Word error - Word found unreadable content ... )

**Comment by YousefED** [comment]
I'm running into this as well. Could it be because there's no link from document.xml.rels to the fonttable? When I export a document with embedded font from Word, I see the following entry in `document.xml.rels`:

```xml
<Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/fontTable" Target="fontTable.xml"/>```

However, when I export a document with an embedded font using docx.js, this seems to be missing
