### ISSUE TITLE
Error "Can't read the data of 'the loaded zip file'" from docx patcher

### ISSUE THREAD

**Issue by mickey58github** [dolanmiu/docx#2539]
I'm trying to run the samples for the patcher, unchanged, with the corresponding demo documents from GitHub, like 85-template-document.ts with simple-template.docx as the test document, or 87-template-documents.ts with simple-template-2.docx as the test document.

But for all of those test runs, both from browser and from Node, I get the same error message: **"Error: Can't read the data of 'the loaded zip file'. Is it in a supported JavaScript type (String, Blob, ArrayBuffer, etc) ?"**

This error seems to be created by an internal call of **jszip** in docx.

It is unlikely that this is caused by my docx test environment, since I'm able to run other docx samples that generate new documents (without patcher) without errors, both in browser and on Node. And I can open the mentioned template test docs in Word without a problem, so the cause is unlikely to be a corruption of these files. 

Any hint for the cause of this problem?

**Comment by ZergHeureux** [comment]
Same issue here !
Have some short example :
```JavaScript
    const file = fs.readFileSync(__dirname+"/../../templates/document.docx")
    const doc = await patchDocument({
        outputType: "nodebuffer",
        data: file,
        patches: {
            version: {
                type: PatchType.PARAGRAPH,
                children: [new TextRun("V5555")],
            }
        }
    })
    fs.writeFileSync("C:\\PATH\\demo.docx",doc)
```

The error returned by Node : 
```

*\node_modules\docx\build\index.cjs:16888
}(e3))), e3) : u.Promise.reject(new Error("Can't read the data of '" + r2 + "'. Is it in a supported JavaScript type (String, Blob, ArrayBuffer, etc) ?"));

Error: Can't read the data of 'the loaded zip file'. Is it in a supported JavaScript type (String, Blob, ArrayBuffer, etc) ?

```

**Comment by ZergHeureux** [comment]
Maybe there is another way of editing the docx ? 
Like rewrite the Buffer before paking, reading the ByteArray and comparing it with a template to catch identical Bytes and replacing it with the content we are looking for. 

But it would be very time consuming and a bit complicated tho :)

**Comment by mateobv07** [comment]
I got the same error, this worked for me: 

`patchDocument(fs.readFileSync("input.docx"), {
  outputType: "nodebuffer",
  data: fs.readFileSync("input.docx"),
  patches: {
    test: {
      type: PatchType.PARAGRAPH,
      children: [new TextRun("test")],
    },
  },
}).then((doc) => {
  fs.writeFileSync("output.docx", doc);
});`

**Comment by ZergHeureux** [comment]
> I got the same error, this worked for me:
> 
> ```ts
> patchDocument(fs.readFileSync("input.docx"), {
>   outputType: "nodebuffer",
>   patches: {
>     test: {
>       type: PatchType.PARAGRAPH,
>       children: [new TextRun("test")],
>     },
>   },
> }).then((doc) => {
>   fs.writeFileSync("output.docx", doc);
> });
> ```
> 
> The only problem is that patcher doesn't patch all the keys if the same key is multiple times in the same paragraph doing it this way. Then the fix to that is running it over the same file multiple time: [#2267 (comment)](https://github.com/dolanmiu/docx/issues/2267#issuecomment-1651408316)

This worked for me too, replacing ALL occurences by using it in a non-promise way :
```JavaScript
    const doc = await patchDocument(fs.readFileSync("example.docx"), {
        outputType: "nodebuffer",
        patches: {
            version: {
                type: PatchType.PARAGRAPH,
                children: [new TextRun("V5555")],
            },
        },
      });
    fs.writeFileSync("demo.docx",doc)
```
However it doesnt apply the correspondant style to the new text. (Not sure its part of the patchers usage)

**Comment by akiross** [comment]
Having the same issue, but I couldn't make it work as the others did.
I tried with packages from npm from 8.5.0 up to 8.1.0, but the issue remained.

**Comment by samconran** [comment]
@ZergHeureux  
> However it doesnt apply the correspondant style to the new text. (Not sure its part of the patchers usage)

This is a separate boolean (`keepOriginalStyles`) you can pass to the patch object like so:
```javascript
const doc = await patchDocument(fs.readFileSync("example.docx"), {
    outputType: "nodebuffer",
    patches: {
        version: {
            type: PatchType.PARAGRAPH,
            children: [new TextRun("V5555")],
        },
    },
    keepOriginalStyles: true
  });
fs.writeFileSync("demo.docx",doc)
```

**Comment by akiross** [comment]
I managed to make it work by using the `data` argument instead of the `data` attribute in the options object:

```
patchDocument(templateData, { outputType, patches})
```

instead of

```
patchDocument({ data, outputType, patches})
``

**Comment by zararashigal** [comment]
It's not completed. Please fix this issue. The above workarounds did not work.
