### ISSUE TITLE
How to space for cell on table

### ISSUE THREAD

**Issue by uldcra** [dolanmiu/docx#255]
M y english is very poor,

but How padding o marging o space a new Paragraph inside cell on/in the table, for default, the space is minium, are there the posibility to increase the sapce and align vertical.

**Comment by dolanmiu** [comment]
i dont think this is a feature yet!

Will add to to do

**Comment by uldcra** [comment]
a lot of thanks.

**Comment by Mitiryl** [comment]
+1

**Comment by MikeThacker1** [comment]
+1

**Comment by dolanmiu** [comment]
Will be in V5

**Comment by dolanmiu** [comment]
Will be fixed with:

https://github.com/dolanmiu/docx/pull/288

This will be the "margains" feature

**Comment by uldcra** [comment]
I am so sorry for the long delay for the response.
but it´s 
table.addMargins? or it´s in Document
Thanks

**Comment by dolanmiu** [comment]
No released yet, will be available on release v5
