### ISSUE TITLE
I cannot seem to get rid of TS Errors.

### ISSUE THREAD

**Issue by demitchell14** [dolanmiu/docx#258]
I just recently installed docx for a work project, and although its not really a critical problem, but more of a nuisance, I wanted to post this here and see if anyone else has this problem, or if its a setting that I'm missing.

I seem to be getting Typescript errors every time TS Compiles, however they're part of docx, not my app.

    c9:41:56 PM - File change detected. Starting incremental compilation...
    
    node_modules/docx/src/file/core-properties/components.ts(1,30): error TS2307: Cannot find module 'file/xml-components'.
    node_modules/docx/src/file/core-properties/components.ts(7,14): error TS2339: Property 'root' does not exist on type 'Title'.
    node_modules/docx/src/file/core-properties/components.ts(14,14): error TS2339: Property 'root' does not exist on type 'Subject'.
    node_modules/docx/src/file/core-properties/components.ts(21,14): error TS2339: Property 'root' does not exist on type 'Creator'.
    node_modules/docx/src/file/core-properties/components.ts(28,14): error TS2339: Property 'root' does not exist on type 'Keywords'.
    node_modules/docx/src/file/core-properties/components.ts(35,14): error TS2339: Property 'root' does not exist on type 'Description'.
    node_modules/docx/src/file/core-properties/components.ts(42,14): error TS2339: Property 'root' does not exist on type 'LastModifiedBy'.
    node_modules/docx/src/file/core-properties/components.ts(49,14): error TS2339: Property 'root' does not exist on type 'Revision'.
    node_modules/docx/src/file/core-properties/components.ts(69,9): error TS2554: Expected 0 arguments, but got 1.
    node_modules/docx/src/file/core-properties/components.ts(70,14): error TS2339: Property 'root' does not exist on type 'Created'.
    node_modules/docx/src/file/core-properties/components.ts(71,13): error TS2554: Expected 0 arguments, but got 1.
    node_modules/docx/src/file/core-properties/components.ts(75,14): error TS2339: Property 'root' does not exist on type 'Created'.
    node_modules/docx/src/file/core-properties/components.ts(81,9): error TS2554: Expected 0 arguments, but got 1.
    node_modules/docx/src/file/core-properties/components.ts(82,14): error TS2339: Property 'root' does not exist on type 'Modified'.
    node_modules/docx/src/file/core-properties/components.ts(83,13): error TS2554: Expected 0 arguments, but got 1.
    node_modules/docx/src/file/core-properties/components.ts(87,14): error TS2339: Property 'root' does not exist on type 'Modified'.
    node_modules/docx/src/file/core-properties/properties.ts(1,30): error TS2307: Cannot find module 'file/xml-components'.
    node_modules/docx/src/file/core-properties/properties.ts(19,14): error TS2339: Property 'root' does not exist on type 'CoreProperties'.
    node_modules/docx/src/file/core-properties/properties.ts(20,13): error TS2554: Expected 0 arguments, but got 1.
    node_modules/docx/src/file/core-properties/properties.ts(29,18): error TS2339: Property 'root' does not exist on type 'CoreProperties'.
    node_modules/docx/src/file/core-properties/properties.ts(32,18): error TS2339: Property 'root' does not exist on type 'CoreProperties'.
    node_modules/docx/src/file/core-properties/properties.ts(35,18): error TS2339: Property 'root' does not exist on type 'CoreProperties'.
    node_modules/docx/src/file/core-properties/properties.ts(38,18): error TS2339: Property 'root' does not exist on type 'CoreProperties'.
    node_modules/docx/src/file/core-properties/properties.ts(41,18): error TS2339: Property 'root' does not exist on type 'CoreProperties'.
    node_modules/docx/src/file/core-properties/properties.ts(44,18): error TS2339: Property 'root' does not exist on type 'CoreProperties'.
    node_modules/docx/src/file/core-properties/properties.ts(47,18): error TS2339: Property 'root' does not exist on type 'CoreProperties'.
    node_modules/docx/src/file/core-properties/properties.ts(49,14): error TS2339: Property 'root' does not exist on type 'CoreProperties'.
    node_modules/docx/src/file/core-properties/properties.ts(50,14): error TS2339: Property 'root' does not exist on type 'CoreProperties'.
    node_modules/docx/src/file/document/body/section-properties/columns/columns-attributes.ts(1,39): error TS2307: Cannot find module 'file/xml-components'.
    node_modules/docx/src/file/document/body/section-properties/columns/columns.ts(1,30): error TS2307: Cannot find module 'file/xml-components'.
    node_modules/docx/src/file/document/body/section-properties/columns/columns.ts(7,14): error TS2339: Property 'root' does not exist on type 'Columns'.
    node_modules/docx/src/file/document/body/section-properties/columns/columns.ts(8,13): error TS2554: Expected 0 arguments, but got 1.
    node_modules/docx/src/file/document/body/section-properties/doc-grid/doc-grid-attributes.ts(1,39): error TS2307: Cannot find module 'file/xml-components'.
    node_modules/docx/src/file/document/body/section-properties/doc-grid/doc-grid.ts(1,30): error TS2307: Cannot find module 'file/xml-components'.
    node_modules/docx/src/file/document/body/section-properties/doc-grid/doc-grid.ts(7,14): error TS2339: Property 'root' does not exist on type 'DocumentGrid'.
    node_modules/docx/src/file/document/body/section-properties/doc-grid/doc-grid.ts(8,13): error TS2554: Expected 0 arguments, but got 1.
    node_modules/docx/src/file/document/body/section-properties/footer-reference/footer-reference-attributes.ts(1,39): error TS2307: Cannot find module 'file/xml-components'.
    node_modules/docx/src/file/document/body/section-properties/footer-reference/footer-reference.ts(1,30): error TS2307: Cannot find module 'file/xml-components'.
    node_modules/docx/src/file/document/body/section-properties/footer-reference/footer-reference.ts(13,14): error TS2339: Property 'root' does not exist on type 'FooterReference'.
    node_modules/docx/src/file/document/body/section-properties/footer-reference/footer-reference.ts(14,13): error TS2554: Expected 0 arguments, but got 1.
    node_modules/docx/src/file/document/body/section-properties/header-reference/header-reference-attributes.ts(1,39): error TS2307: Cannot find module 'file/xml-components'.
    node_modules/docx/src/file/document/body/section-properties/header-reference/header-reference.ts(1,30): error TS2307: Cannot find module 'file/xml-components'.
    node_modules/docx/src/file/document/body/section-properties/header-reference/header-reference.ts(12,14): error TS2339: Property 'root' does not exist on type 'HeaderReference'.
    node_modules/docx/src/file/document/body/section-properties/header-reference/header-reference.ts(13,13): error TS2554: Expected 0 arguments, but got 1.
    node_modules/docx/src/file/document/body/section-properties/page-border/page-borders.ts(2,29): error TS2307: Cannot find module 'file/styles'.
    node_modules/docx/src/file/document/body/section-properties/page-border/page-borders.ts(3,69): error TS2307: Cannot find module 'file/xml-components'.
    node_modules/docx/src/file/document/body/section-properties/page-border/page-borders.ts(55,14): error TS2339: Property 'root' does not exist on type 'PageBorder'.
    node_modules/docx/src/file/document/body/section-properties/page-border/page-borders.ts(55,24): error TS2554: Expected 0 arguments, but got 1.
    node_modules/docx/src/file/document/body/section-properties/page-border/page-borders.ts(85,14): error TS2339: Property 'root' does not exist on type 'PageBorders'.
    node_modules/docx/src/file/document/body/section-properties/page-border/page-borders.ts(85,24): error TS2554: Expected 0 arguments, but got 1.
    node_modules/docx/src/file/document/body/section-properties/page-border/page-borders.ts(88,18): error TS2339: Property 'root' does not exist on type 'PageBorders'.
    node_modules/docx/src/file/document/body/section-properties/page-border/page-borders.ts(91,18): error TS2339: Property 'root' does not exist on type 'PageBorders'.
    node_modules/docx/src/file/document/body/section-properties/page-border/page-borders.ts(94,18): error TS2339: Property 'root' does not exist on type 'PageBorders'.
    node_modules/docx/src/file/document/body/section-properties/page-border/page-borders.ts(97,18): error TS2339: Property 'root' does not exist on type 'PageBorders'.
    node_modules/docx/src/file/document/body/section-properties/page-border/page-borders.ts(102,18): error TS2339: Property 'root' does not exist on type 'PageBorders'.
    node_modules/docx/src/file/document/body/section-properties/page-margin/page-margin-attributes.ts(1,39): error TS2307: Cannot find module 'file/xml-components'.
    node_modules/docx/src/file/document/body/section-properties/page-margin/page-margin.ts(1,30): error TS2307: Cannot find module 'file/xml-components'.
    node_modules/docx/src/file/document/body/section-properties/page-margin/page-margin.ts(7,14): error TS2339: Property 'root' does not exist on type 'PageMargin'.
    node_modules/docx/src/file/document/body/section-properties/page-margin/page-margin.ts(8,13): error TS2554: Expected 0 arguments, but got 1.
    node_modules/docx/src/file/document/body/section-properties/page-number/page-number.ts(2,53): error TS2307: Cannot find module 'file/xml-components'.
    node_modules/docx/src/file/document/body/section-properties/page-number/page-number.ts(34,14): error TS2339: Property 'root' does not exist on type 'PageNumberType'.
    node_modules/docx/src/file/document/body/section-properties/page-number/page-number.ts(35,13): error TS2554: Expected 0 arguments, but got 1.
    node_modules/docx/src/file/document/body/section-properties/page-size/page-size-attributes.ts(1,39): error TS2307: Cannot find module 'file/xml-components'.
    node_modules/docx/src/file/document/body/section-properties/page-size/page-size.ts(1,30): error TS2307: Cannot find module 'file/xml-components'.
    node_modules/docx/src/file/document/body/section-properties/page-size/page-size.ts(10,14): error TS2339: Property 'root' does not exist on type 'PageSize'.
    node_modules/docx/src/file/document/body/section-properties/page-size/page-size.ts(11,13): error TS2554: Expected 0 arguments, but got 1.
    node_modules/docx/src/file/document/body/section-properties/section-properties.ts(2,31): error TS2307: Cannot find module 'file/footer-wrapper'.
    node_modules/docx/src/file/document/body/section-properties/section-properties.ts(3,31): error TS2307: Cannot find module 'file/header-wrapper'.
    node_modules/docx/src/file/document/body/section-properties/section-properties.ts(4,30): error TS2307: Cannot find module 'file/xml-components'.
    node_modules/docx/src/file/document/body/section-properties/section-properties.ts(83,14): error TS2339: Property 'root' does not exist on type 'SectionProperties'.
    node_modules/docx/src/file/document/body/section-properties/section-properties.ts(84,14): error TS2339: Property 'root' does not exist on type 'SectionProperties'.
    node_modules/docx/src/file/document/body/section-properties/section-properties.ts(85,14): error TS2339: Property 'root' does not exist on type 'SectionProperties'.
    node_modules/docx/src/file/document/body/section-properties/section-properties.ts(86,14): error TS2339: Property 'root' does not exist on type 'SectionProperties'.
    node_modules/docx/src/file/document/body/section-properties/section-properties.ts(91,14): error TS2339: Property 'root' does not exist on type 'SectionProperties'.
    node_modules/docx/src/file/document/body/section-properties/section-properties.ts(94,18): error TS2339: Property 'root' does not exist on type 'SectionProperties'.
    node_modules/docx/src/file/document/body/section-properties/section-properties.ts(106,18): error TS2339: Property 'root' does not exist on type 'SectionProperties'.
    node_modules/docx/src/file/document/body/section-properties/section-properties.ts(113,22): error TS2339: Property 'root' does not exist on type 'SectionProperties'.
    node_modules/docx/src/file/document/body/section-properties/section-properties.ts(122,22): error TS2339: Property 'root' does not exist on type 'SectionProperties'.
    node_modules/docx/src/file/document/body/section-properties/section-properties.ts(131,22): error TS2339: Property 'root' does not exist on type 'SectionProperties'.
    node_modules/docx/src/file/document/body/section-properties/section-properties.ts(144,22): error TS2339: Property 'root' does not exist on type 'SectionProperties'.
    node_modules/docx/src/file/document/body/section-properties/section-properties.ts(153,22): error TS2339: Property 'root' does not exist on type 'SectionProperties'.
    node_modules/docx/src/file/document/body/section-properties/section-properties.ts(162,22): error TS2339: Property 'root' does not exist on type 'SectionProperties'.
    node_modules/docx/src/file/document/body/section-properties/title-page/title-page-attributes.ts(1,39): error TS2307: Cannot find module 'file/xml-components'.
    node_modules/docx/src/file/document/body/section-properties/title-page/title-page.ts(1,30): error TS2307: Cannot find module 'file/xml-components'.
    node_modules/docx/src/file/document/body/section-properties/title-page/title-page.ts(7,14): error TS2339: Property 'root' does not exist on type 'TitlePage'.
    node_modules/docx/src/file/document/body/section-properties/title-page/title-page.ts(8,13): error TS2554: Expected 0 arguments, but got 1.
    node_modules/docx/src/file/document/document-attributes.ts(1,39): error TS2307: Cannot find module 'file/xml-components'.
    
    9:41:57 PM - Found 87 errors. Watching for file changes.

I know there is a --skipLibCheck setting for TS which I don't normally use because I don't normally have to. However, for some reason, even with that setting checked, I continue to get the errors. I have also tried excluding node_moduels from TS, and I already only compile specific files/directories.

This is my tsconfig file.

    {
      "compilerOptions": {
        "target": "esnext",
        "module": "commonjs",
        "allowJs": true,
        "sourceMap": true,
        "outDir": "dist",
        "moduleResolution": "node",
        "declaration": false,
        "skipLibCheck": true,
        "skipDefaultLibCheck": true
      },
      "exclude": ["node_modules", "node_modules/docx"],
      "include": [
        "bin", "routes", "app.ts", "config.ts", "tests"
      ]
    }

I went to the extreme, just to test, which is why I basically double excluded docx && node_modules.

I can't figure out why I am still getting the redundant errors, and they've started getting in the way of actual errors that I dont' see because theres 87 errors already there.

**Comment by demitchell14** [comment]
Yes and yes @dolanmiu

**Comment by demitchell14** [comment]
@dolanmiu 
I tried setting the target to es6, however, the same errors occur (I actually get 3 more errors, but they are related to my code, not docx).

If it helps, docx is running server-side, not in React itself.

**Comment by dolanmiu** [comment]
It's pretty interesting because it's trying to look for `.ts` files, but docx is transpiled into `.js`, so it shouldn't come up with those errors

**Comment by demitchell14** [comment]
That was exactly my thoughts as well when I looked into docx itself.
I thought about trying to just remove the source files from the package so there's no way for it look for the files and seeing how it responds, but to me, that is just a temporary fix, IF it worked at all. The problem I see though, is that would ruin the entire purpose of using typescript, since the source IS the declaration files??? I'm rather new to TS, so I don't really know how it all works behind the scenes.

**Comment by dolanmiu** [comment]
No, the `.d.ts` are the declaration files, the `.ts` arent used for source mapping

**Comment by demitchell14** [comment]
That definitely doesn't make sense then. 
Also, if it helps, its not a single use case. I work on my project on 2 separate computers, regularly, and ever since I added docx, both do get the same errors (Both are Windows 10).

**Comment by demitchell14** [comment]
Just checking to see if you ever got around to looking into, or could replicate the warnings/errors I receive while using docx.

**Comment by dolanmiu** [comment]
sorry for the delayed response

tried it just now, works fine for me

I used the exact same tsconfig as yours, but changed one line:

```
"outDir": "./dist",
```

you used `"outDir": "dist",`

**Comment by demitchell14** [comment]
I was so hoping it would be some dumb user error like that, however even with that change from `dist` to `./dist`, I still get the 87 errors.. 😕

One thing that I did notice is I dont get the errors if I use the following commands..

    tsc -b

I DO however get it when I watch my project, or use

    tsc -p .

Which confuses me even more

**Comment by dolanmiu** [comment]
Yes if you let me have a look at the repo I could try help

**Comment by demitchell14** [comment]
Here is the full repo

https://github.com/demitchell14/ids-ezagenda

However, the only file that actually uses docx is 

https://github.com/demitchell14/ids-ezagenda/blob/master/bin/DocumentBuilder.ts

This repo isn't exactly organized yet, so I apologize in advance for that. It is still early stages.

**Comment by dolanmiu** [comment]
Found out the reason, it is because you should not import from `docx/src`:

https://github.com/demitchell14/ids-ezagenda/blob/master/bin/DocumentBuilder.ts#L2-L4

you shouldn't really import from `docx/build` either, only import from `docx`

`src` contains all the `.ts` files

**Comment by demitchell14** [comment]
Okay, I use phpstorm and I usually just import whatever it tells me to import, and If I'm not mistaken, those are just used as references for TS, so I assumed it would be alright.

Definitely appreciate the clarification though!
