### ISSUE TITLE
Generate Table Of Contents (TOC) programmatically

### ISSUE THREAD

**Issue by aviau** [dolanmiu/docx#2582]
Hello,

The documentation says:
> Tables of Contents are fields and, by design, it's content is only generated or updated by Word. We can't do it programmatically.

What would be needed to fix this? Is this even long-term-fixable?

Are there workarounds for this use case?

We have an app where:
- We generate docx reports
- We have also a download-as-pdf button where we use libreoffice to convert it from docx to PDF

For us, this is a dealbreaker and we would need to move away from docxjs if there is no long-term fix. We need our PDFs to have a TOC.

Thanks,

**Comment by anti-the-social** [comment]
Even if constructor will be given, how would you think to calculate page numbers?

**Comment by josephmetabase** [comment]
> Hello,
> 
> The documentation says:
> 
> > Tables of Contents are fields and, by design, it's content is only generated or updated by Word. We can't do it programmatically.
> 
> What would be needed to fix this? Is this even long-term-fixable?
> 
> Are there workarounds for this use case?
> 
> We have an app where:
> 
> * We generate docx reports
> * We have also a download-as-pdf button where we use libreoffice to convert it from docx to PDF
> 
> For us, this is a dealbreaker and we would need to move away from docxjs if there is no long-term fix. We need our PDFs to have a TOC.
> 
> Thanks,

hey, what did you end up using?

**Comment by aviau** [comment]
We put this project on hold right now. We are thinking of dropping docx support for our use case and move to a PDF with links.

**Comment by dolanmiu** [comment]
Duplicate https://github.com/dolanmiu/docx/issues/380
