### ISSUE TITLE
Header/Footer duplicated

### ISSUE THREAD

**Issue by filippomuscolino** [dolanmiu/docx#259]
Hi,

I'm using last version of docx and I noticed that the Header/Footer is duplicated (at least in LibreOffice, did not try in Office).
It seems that the XML has <w:sectPr> duplicated, with the same content.
(To reproduce this, try for instance demo14)

Could you please check it? Thanks!

Filippo

**Comment by dolanmiu** [comment]
interesting, I will have a look

**Comment by wheelsandcogs** [comment]
I'm seeing the same issue in Pages on a Mac.

```
doc.Footer.createParagraph()
    .addRun(new TextRun('Page ').pageNumber())
    .addRun(new TextRun(' of ').numberOfTotalPages())
    .right();
```
Creates 2 identical lines in the footer.
