### ISSUE TITLE
can i add background color on entire header section? please suggest me

### ISSUE THREAD

**Issue by shibuchapagain** [dolanmiu/docx#2593]
# Thank you for raising an issue to `docx`

Please do not raise an issue unless it is an **issue**.

-   Is your issue a feature request? Are you giving ideas to the community? Are you asking for help? Please raise a ticket in the `Discussions` section:

    https://github.com/dolanmiu/docx/discussions

-   Is your issue a previously asked? Please respond to that thread instead

**Comment by anti-the-social** [comment]
This is not an issue.

**Comment by shibuchapagain** [comment]
Okay .. could you give me answer?

**Comment by shibuchapagain** [comment]
Thank you!
