### ISSUE TITLE
Set table width of columns individually

### ISSUE THREAD

**Issue by kongsgard** [dolanmiu/docx#260]
I'm familiar with these two options in the API:
`table.setFixedWidthLayout();`
 `table.setWidth(WidthType.PERCENTAGE, '100%');`

However, what should I do if I want to set the width of specific columns?

Example: I want a table with two columns; the first one to have a width of 25% and the second one to have a width of 75%.

**Comment by emilps** [comment]
This feature would be really useful to me too! Is there any quick-fix we could use in the meantime?

**Comment by dolanmiu** [comment]
Seems like theres a lot of tables related feature requests lately, I will do a good development session on the whole Tables feature when I get time

**Comment by emilps** [comment]
Have you gotten any further on this issue?

**Comment by dolanmiu** [comment]
Unfortunately not

I am still active don't worry. 

Just been spending my time on another open source project at the moment

Trying to learn graph theory and implementing it.

I will be on `docx` next week after this graph piece is done!

![image](https://user-images.githubusercontent.com/2917613/53211906-cdc8c200-363a-11e9-81cd-31e857770174.png)

**Comment by dolanmiu** [comment]
Will be fixed with:

https://github.com/dolanmiu/docx/issues/260
