### ISSUE TITLE
NPM 8.5.0 Package / wrong types for patchDocument

### ISSUE THREAD

**Issue by chkch1** [dolanmiu/docx#2605]
Wrong version of from-docx.ts packaged for NPM 8.5.0 package?

I installed the docx 8.5.0 Package via NPM 
"dependencies": {
    "docx": "^8.5.0"
  }
and wanted to run the Demos
* 85-template-document.ts
* 87-template-document.ts
* 88-template-document.ts
* 89-template-document.ts

but they are not working, because of the wrong type definition for the function "patchDocument". 
![image](https://github.com/dolanmiu/docx/assets/56638400/f5e65a98-ecdd-4f78-8162-b47cafb92857)

When looking into build/patcher/from-docx.d.ts of the downloaded NPM package, it shows that the exported type for patchDocument has another parameter definition as used in the demos:
![image](https://github.com/dolanmiu/docx/assets/56638400/8b76859b-fd45-4e42-9b50-c3a5ce21e096)

It's also explained on the pull requests page, that there had been breaking changes: https://github.com/dolanmiu/docx/pull/2497 but it seems that it did not get it into the NPM package.

On gitHub when looking into the source the type is defined that way that it is working with the demos.

**Comment by laurent512** [comment]
same problem

**Comment by mateobv07** [comment]
Same problem

**Comment by dolanmiu** [comment]
Yes, this is not released as of yet

Will be part of the next major version as this is a breaking API change

**Comment by mateobv07** [comment]
> Yes, this is not released as of yet
> 
> Will be part of the next major version as this is a breaking API change

do you have an estimated date of when the next major version will be released? 😀

**Comment by kunoSchlonz** [comment]
i faced the same issue. what i did as workaround:

1. clone the project
2. npm install && npm run build
3. go to your own project in ./myproject/node_modules/docx and delete the build folder
4. copy the build folder of the docx project into ./myproject/node_modules/docx
5. the code should work now

but please be careful on this - its a workaround!

**Comment by dolanmiu** [comment]
Published `8.6.0` which has the correct types

Aware that this is a API change on a minor, so use with caution
