### ISSUE TITLE
patchDocument - input.prepForXml Error

### ISSUE THREAD

**Issue by Blair-24** [dolanmiu/docx#2606]
Just wondering if its a limitation or I'm doing something wrong. Trying to patch an existing document with an array of objects that I want to format into ultimately repeating sections for each object. This is my code at present (plan is to add more, e.g. tables etc):

![image](https://github.com/dolanmiu/docx/assets/160080020/e56c47c3-fa67-43d2-b884-8d624ea83c05)

But I get this error: 

`TypeError: Cannot read properties of undefined (reading 'prepForXml')`

**Comment by dolanmiu** [comment]
`patchDocument` has been fixed in `9.0.0`. Please try again. if it persists, please open a new issue

**Comment by asim-rauf** [comment]
I am getting same issue again I have below patches 
{
  prepared_by: { type: 'paragraph', children: [ [Object] ] },
  conclusion: { type: 'paragraph', children: [ [Object] ] },
  summary: { type: 'paragraph', children: [ [Object] ] },
}
