### ISSUE TITLE
Can i set border style for 'dashLargeGap'?

### ISSUE THREAD

**Issue by fionazs** [dolanmiu/docx#2640]
Hello, 
1：I noticed that docx currently does not support the "dashLargeGap" style. How should I set the split line for this style?
![image](https://github.com/dolanmiu/docx/assets/117974868/7c9bb41c-bb26-4662-b533-f761ef7cdd1a)

2：why i set border spaces '0', but there is still a large gap between the text and the lines

**Comment by dolanmiu** [comment]
I don't think `dashLargeGap` is a valid option in the OOXML spec:

http://officeopenxml.com/WPtableBorders.php#:~:text=single%20%2D%20a%20single,a%20wavy%20line

Can't see it here
