### ISSUE TITLE
PageMargin set value & Table positions

### ISSUE THREAD

**Issue by ferrthrash** [dolanmiu/docx#266]
Hello
first of all, im really happy to find this add! i love it.

My questions are the next:
1. can't set pageMargin, now i export to docx file and move the margin in word applications. the default value is 2,54 cm and need 1.5cm. :(

2. can´t set the position of the table un paragraph. i need to set in center positions, but always put in left side

```
document.addTable(this.createTableSection(structureItem,5));

method:
	createTableSection(itemTitles, section){
		const table = new Table(13,3);
		table.setWidth(WidthType.PERCENTAGE,'60%');
		let i = 1;
		table.getCell(0,1).addContent(new Paragraph('Unidades').center());
		table.getCell(0,2).addContent(new Paragraph('Valor').center());
		for(let item of itemTitles){
			if(item.section === section){
				for(let nameField of item.items){
					table.getCell(i,0).addContent(new Paragraph(nameField.field));
					table.getCell(i,1).addContent(new Paragraph(nameField.measurment).center());
					if(nameField.value === null){
						table.getCell(i,2).addContent(new Paragraph('---').center());
					}else{
						table.getCell(i,2).addContent(new Paragraph(nameField.value).center());
					}
					++i;
				}
			}
		}
		return table;
	}
```

Best regards

**Comment by dolanmiu** [comment]
Setting stylistic properties for tables such as borders and margins, padding will be made for the next release!

**Comment by ferrthrash** [comment]
thx for response!
ok, i wait for new update.

PD: the margin is for all document, i can't set it

**Comment by ferrthrash** [comment]
Here for page margin (Documentation):
```
 const doc = new Document(undefined, {
   top: 0,
   right: 0,
   bottom: 0,
   left: 0,
 });
```

**Comment by dolanmiu** [comment]
Floating tables will be fixed with:

https://github.com/dolanmiu/docx/pull/288
