### ISSUE TITLE
How to skip numbering first page (Leave first page without number) start numbering from second page

### ISSUE THREAD

**Issue by kavin404** [dolanmiu/docx#267]

**Comment by dolanmiu** [comment]
Page numbers? you do that with sections

https://github.com/dolanmiu/docx/blob/master/demo/demo16.ts

**Comment by kavin404** [comment]
Yes, Page numbers.Thanks for quick response.

**Comment by kavin404** [comment]
Yes, Page numbers.Thanks for quick response.
