### ISSUE TITLE
Text Frame not working correctly after save to docx file, and not support for almost doc viewer

### ISSUE THREAD

**Issue by Sariln** [dolanmiu/docx#2670]
I try to make a Text Frame that like below : 
<img width="1055" alt="Screenshot 2024-04-09 at 10 29 50 in the morning" src="https://github.com/dolanmiu/docx/assets/45432573/911090e2-b543-4f3c-a383-0d49708106de">

but always it give me that : 
<img width="741" alt="Screenshot 2024-04-09 at 10 11 22 in the morning" src="https://github.com/dolanmiu/docx/assets/45432573/ec66defc-6653-4e94-ab74-758096000771">

and when I try to open on other viewer it not support Text Frame : 
<img width="659" alt="Screenshot 2024-04-09 at 10 20 08 in the morning" src="https://github.com/dolanmiu/docx/assets/45432573/21b40885-7f7d-4b12-b3d3-0eafcdc579db">

my code : 
<img width="623" alt="Screenshot 2024-04-09 at 10 51 12 in the morning" src="https://github.com/dolanmiu/docx/assets/45432573/694b8bf0-a217-4f34-87db-035fc8b44352">

version : 8.5.0

Text Frame it hard to make and edit compare to Draw Text Box, so how can I fixed it or can we have Draw Text Box feature instead of Text Frame. Thank you

**Comment by dolanmiu** [comment]
This is expected behaviour.

This is because if you make your `Text Frame` paragraph position absolute, then it doesn't "take up any space". Think of:

```html
<div style="position:absolute;">Hello</div>
```

Same sort of behaviour.
