### ISSUE TITLE
Table of contents is not working

### ISSUE THREAD

**Issue by Ankit-Naag** [dolanmiu/docx#2673]
I'm using docx@8.5.0 and the table of content is not working for me:

Here's a sample of my output:
![image](https://github.com/dolanmiu/docx/assets/83116830/3636ab0f-7497-4274-89dc-831fae745773)

**Comment by vonWolfehaus** [comment]
I have the same problem, except it just appears blank in the rendered docx until i click on the general area it should be in and have google docs refresh it with the correct data. updateFields does not do anything and there's nothing else in the docs to suggest other steps to take for it to render properly.

**Comment by vect-sderory2** [comment]
Same issue here as vonWolfehaus

**Comment by dolanmiu** [comment]
Closing because of duplicate

https://github.com/dolanmiu/docx/issues/380
