### ISSUE TITLE
build failed when adding docx. import issue 

### ISSUE THREAD

**Issue by dhallX** [dolanmiu/docx#2674]
I saw this issue was a old issue but none of the change helped...

I have a problem with my next.is @14.0. 3 app when i install and use the package  in localhost the package works! however the moment i try to build the app i get this:

  
![image](https://github.com/dolanmiu/docx/assets/106660145/9d555e8e-9eee-48d8-936f-3947d921782d)

![image](https://github.com/dolanmiu/docx/assets/106660145/3e2d0067-d1d7-4166-9373-68112b8f75b5)

I am sure this has to do with a webpack setup but i don't know what it should be so that the proper module are imported.

below is my config file 

`const nextConfig = {
  reactStrictMode: false, // Enable React strict mode for improved error handling
  swcMinify: true, // Enable SWC minification for improved performance
  experimental: {
    optimizePackageImports: [
      'react-big-calendar',
      '@mui/lab',
      '@mui/x-date-pickers',
      'material-react-table',
      'react-calendar-timeline',
      'react-hook-form',
      '@emotion/react',
      '@emotion/styled',
      'aws-amplify',
      'uuidv4',
      'html2pdf.js',
      'dayjs',
    ],
  },

  images: {
    remotePatterns: [
    ],
  },
};

module.exports = nextConfig;`

**Comment by dolanmiu** [comment]
Fixed now as https://github.com/dolanmiu/docx/issues/2635 is merged
