### ISSUE TITLE
how to add a graphical horizontal line

### ISSUE THREAD

**Issue by dhallX** [dolanmiu/docx#2677]
just a question is their a solution to create a graphical line the runs horizontal across the page?

**Comment by dolanmiu** [comment]
To do this, make a table or paragraph with a top/bottom border

This is the way I found using Microsoft Word itself

https://answers.microsoft.com/en-us/msoffice/forum/all/add-horizontal-line-in-word-to-separate-document/f6973260-06e3-4a59-979c-8b7f47a51b7f
