### ISSUE TITLE
PageReference returns with 1 at all.

### ISSUE THREAD

**Issue by idavidka** [dolanmiu/docx#2686]
Adding bookmarks and using internal hyperlinks works as intended. 
If I try to add a PageReference to any Paragraph, it always returns with 1, even if the bookmark is on other page.

Tested with latest docx, 8.5.0. Issue also happening with your sample code.
OS: macOS Ventura 13.5

https://github.com/dolanmiu/docx/blob/022b25cfcd33cd2ab9456f4b16cbc01ec3a1ed63/demo/21-bookmarks.ts#L69

<img width="251" alt="Screenshot 2024-05-14 at 9 47 28" src="https://github.com/dolanmiu/docx/assets/3583862/185a1203-858e-48d4-bd48-800a5c2960a5">

**Comment by hughedwards2** [comment]
Why was this closed?  
I'm experiencing this

**Comment by idavidka** [comment]
> Why was this closed? I'm experiencing this

Because it’s working. 

Page references themselves are in the document, just the it was needed to be updated. It is because the number depend on the document format, font-size, page break etc. At first time Word is not able to recognize, you need to do it manually.

It needed to run “Update fields” command on document open. 
On macOS: Select all (CMD + A) and right click and Update fields (CMD + Shift + Option + U)
