### ISSUE TITLE
How can I insert Text Box?

### ISSUE THREAD

**Issue by popo1221** [dolanmiu/docx#269]
Hi,

    Can I insert a text box with float positioning?

**Comment by dolanmiu** [comment]
Text boxes are not supported currently, but are planned

**Comment by popo1221** [comment]
Great. 
I really look forward to the feature.

**Comment by lucashmorais** [comment]
That would be great indeed!

**Comment by dolanmiu** [comment]
Will be a feature here:

https://github.com/dolanmiu/docx/pull/821

Thanks!
