### ISSUE TITLE
Images in header and footer are transparent by default in Microsoft Word

### ISSUE THREAD

**Issue by arthaud-proust** [dolanmiu/docx#2692]
Hello, thanks a lot for this package ! I think there is an issue with images in header/footer

## Problem
Inserted image in footer or header appear transparent when you open the .docx file with Microsoft Word 16.76 (non-activated)

## Reproduction 
TL;DR : You can reproduce by opening the file generated by the demo`9-images-in-header-and-footer`

Steps: 
1. Clone the repo
2. Run `npm i`
3. Run `npm run demo`
4. Select `9-images-in-header-and-footer`
5. Open the generated file `My Document.docx`
6. Observe that the gif image is transparent (more lighter than the original asset in /demo/images/pizza.gif)

#### In the word file
<img width="188" alt="Capture d’écran 2024-06-19 à 17 03 24" src="https://github.com/dolanmiu/docx/assets/28672596/83a12bcf-a2ee-403b-98de-b7e49e7d4d4d">

#### The original gif 
<img width="379" alt="Capture d’écran 2024-06-19 à 17 04 23" src="https://github.com/dolanmiu/docx/assets/28672596/b66f085c-77ef-4f47-b79c-5e31b650a4e0">

## Other observations
- https://github.com/dolanmiu/docx/issues/369#issuecomment-947402582

**Comment by dolanmiu** [comment]
This is expected. This is actually a "feature" in word by letting you know that it is inside the header/footer.

If you print your document, it won't be transparent, don't worry.

**Comment by arthaud-proust** [comment]
Hi, ok thanks for the explanation, so the problem is not related to the package
