### ISSUE TITLE
Can't add images due to 'type' not existing on 'IImageOptions'

### ISSUE THREAD

**Issue by vitorMarraHernandes** [dolanmiu/docx#2693]
I'm following the documentation but I can't add images because of the following error: 
  
 `Object literal may only specify known properties, and 'type' does not exist in type 'IImageOptions'`

This happens because the property 'type' doesn't exist in 'IImageOptions'

Here's what my code looks like: 
```
import { AlignmentType, Document, ImageRun, Packer, Paragraph, TextRun, Table } from "docx";
import * as fs from 'fs';

const image = new ImageRun({
        type: 'png',
        data: fs.readFileSync('../../../assets/images/logo_task.png'),
        transformation: {
            width: 150,
            height: 150,
        },
    });
      const doc = new Document({
        sections: [
          {
            children: [
              new Paragraph({
                children: [image]
              }),
              ...
```

This is pretty much everything the documentation says, what am I missing? Any help would be greatly appreciated

**Comment by dolanmiu** [comment]
> This happens because the property 'type' doesn't exist in 'IImageOptions'

`type` is in `IImageOptions`:

https://github.com/dolanmiu/docx/blob/master/src/file/paragraph/run/image-run.ts#L20

You must have a code error somewhere

Feel free to re-open if it is still an issue
