### ISSUE TITLE
How to right align images in header?

### ISSUE THREAD

**Issue by emilps** [dolanmiu/docx#270]
I have tried to right align an image in the header, but it seams like it's not supported. 
Do you have any methods for doing this?

**Comment by dolanmiu** [comment]
Like this:

But it does not work on `4.7.1` at the moment, only on master.

This will be planned on a `5.x.x` release!

```ts
const doc = new Document();

doc.createParagraph("Hello World");

const image = Media.addImage(doc, fs.readFileSync("./demo/images/image1.jpeg"));

doc.Header.addParagraph(image.Paragraph.right());
```

**Comment by dolanmiu** [comment]
Another way I just thought of is to use floating images, which is probably more of what you want because then it allows you to write text on the header too:

https://github.com/dolanmiu/docx/blob/4.7.1/demo/demo38.ts
