### ISSUE TITLE
TextRun fonts do not work in Word Online

### ISSUE THREAD

**Issue by dan-cooke** [dolanmiu/docx#2704]
## Description
When using the `TextRun` property `font` to set a font family. The docx just uses the default `Aptos` font.

## Reproduction code
```.ts
      new TextRun({ text: 'hello world', font: 'Comic Sans MS' })
```

apologies this is taken from a larger library that I am working on for prosemirror. I can supply a fully working example if required, but its a pretty simple bug to reproduce. 

If I generate a docx using this font property. 

- I can successfully open it in Google Docs and everything is in Comic Sans MS
- I can open it in MS Word Desktop just fine
- MS Word web does not apply the Comic Sans MS font

## Edit
- I can succesfully set Comic Sans MS font via the `Paragraph` node and th is works on Web - so this hints that its not an issue with MS Word itself, but seemingly something I am doing / docx is doing

**Comment by anti-the-social** [comment]
That's probably need to be reported to Microsoft, not here. To make license more flexible, you know.
I would guess its about licensing of the Comic Sans MS and absence of it in Chrome.
If you open it in IE or Edge it might work for you since Microsoft invented that font.

**Comment by dan-cooke** [comment]
@anti-the-social I don't think thats quite right, correct me if I'm wrong - but if you have Comic Sans MS installed as a System Font on a Windows machine. You own a license to that font. 

The browser should render that font.

The issue here is not to do with licensing its seemingly a bug in docx, the reason I am so sure about this?

The font property works when used in a [`Paragraph`](https://docx.js.org/api/classes/Paragraph.html)

**Comment by anti-the-social** [comment]
@dan-cooke I tend to disagree here :) 
Neither my mac nor windows are not having Comic Sans font available in Chrome as a font-family.
But my windows machine has Comic Sans at C:/Windows/Fonts
In other words, font is not attached to browser Chrome as you said.

And yes, Word document is zip file and it can include custom fonts in it.
And probably Word in Web does that - attaches Comic Sans if you chose it for some Paragraph.

**Comment by anti-the-social** [comment]
BTW, here is an example how to attach custom font to the document
https://github.com/dolanmiu/docx/blob/962795743c4f21d84c52e47e4f82dcf4ca536dc3/demo/91-custom-fonts.ts

**Comment by dan-cooke** [comment]
@anti-the-social I think we are getting our wires crossed here.

I am not distributing the Comic Sans Font. I am simply setting a CSS variable `font-family: 'Comic Sans'`

>But my windows machine has Comic Sans at C:/Windows/Fonts
>In other words, font is not attached to browser Chrome as you said.

That is not what I said :) ... the font will be available as a system font. I highly advise for you to read up on how fonts work on the web, here is a quick primer on [safe web fonts](https://web.mit.edu/jmorzins/www/fonts.html) as you can see Comic Sans MS is listed here (because every windows and mac user in the world have this font in their system fonts)

Here is a simple example for you:

1. Right click some text in this github thread
2. Attach a css property `font-family: 'Comic Sans MS'` 
3. Boom

![image](https://github.com/user-attachments/assets/5b0c845f-4a07-448b-bbbc-6d4c64e20c65)


You see that right? Github did not "distribute" the Comic Sans MS font to you, the browser read it from your system fonts

Anyway. This issue is being derailed - this is not about licensing of Comic Sans. You are talking about a completely unrelated circumstance.

**Comment by dan-cooke** [comment]
I am closing this as this now seems to be resolved - I actually now suspect this was an issue with Word Online itself.
