### ISSUE TITLE
Published not export MathLimitLower, MathLimitUpper, FileChild in index

### ISSUE THREAD

**Issue by glj1102** [dolanmiu/docx#2715]

**Comment by dolanmiu** [comment]
It is exported:

https://github.com/dolanmiu/docx/blob/master/src/file/index.ts#L1

This one then recursively exports `MathLimitLower` and `MathLimitUpper` and others

`FileChild` is here: https://github.com/dolanmiu/docx/blob/master/src/file/index.ts#L4
