### ISSUE TITLE
文件用Microsoft word打开显示正常，用WPS打开表格和目录均无法显示

### ISSUE THREAD

**Issue by fangzhengok** [dolanmiu/docx#272]
内容都是docx生成的，其中段落和文字都是能正常显示的，就是在WPS中表格和目录无法显示，请问是因为docx没考虑兼容WPS吗？

**Comment by dolanmiu** [comment]
Translate:

> The content is generated by docx, in which the paragraphs and texts can be displayed normally, that is, the tables and directories cannot be displayed in WPS. Is it because docx does not consider compatible with WPS?

**Comment by dolanmiu** [comment]
Correct, only Microsoft word is supported currently

This may be considered in the future. The next platform to target will be Google Docs or Libre Office

**Comment by fangzhengok** [comment]
> 正确，目前仅支持Microsoft字
> 
> 这可能在将来考虑。下一个目标平台将是Google Docs或Libre Office



> Correct, only Microsoft word is supported currently
> 
> This may be considered in the future. The next platform to target will be Google Docs or Libre Office

Thank you for your reply

**Comment by fangzhengok** [comment]
> Correct, only Microsoft word is supported currently
> 
> This may be considered in the future. The next platform to target will be Google Docs or Libre Office

Thank you for your reply

**Comment by whereamazinghappen** [comment]
WPS解析表格可能优先解析了<w:gridCol w:w="100"> </w:gridCol>定义的列宽，而Ms word可能优先解析了<w:tblW w:w="9070" w:type="dxa"> </w:tblW>定义的表格宽度，所以在如果只设置了表格宽度table.setWidth(docx.WidthType.DXA, 9070)，WPS下是无法正常显示。

**Comment by zackzergzeng** [comment]
> WPS解析表格可能优先解析了<w:gridCol w:w="100"> </w:gridCol>定义的列宽，而Ms word可能优先解析了<w:tblW w:w="9070" w:type="dxa"> </w:tblW>定义的表格宽度，所以在如果只设置了表格宽度table.setWidth(docx.WidthType.DXA, 9070)，WPS下是无法正常显示。
> 
> Translation:
> 
> > The WPS parsing table may preferentially parse the column width defined by <w:gridCol w:w="100"> </w:gridCol>, and Ms word may preferentially parse <w:tblW w:w="9070" w: Type="dxa"> </w:tblW> defines the width of the table, so if you only set the table width table.setWidth(docx.WidthType.DXA, 9070), it will not display properly under WPS.

so what should I do to make the table display correctly?
