### ISSUE TITLE
PatchDocument cannot replace multiple identical items within the same paragraph

### ISSUE THREAD

**Issue by 1998feng** [dolanmiu/docx#2726]
This is a template
![image](https://github.com/user-attachments/assets/a9c7eca5-b2c6-44ca-9e70-cc4dbe6e6005)
This is the result after patching
![image](https://github.com/user-attachments/assets/be187f31-d140-4518-9a57-dc64c4da9ff7)

**Comment by lyh458** [comment]
I believe this is issue #2267 , and it has been resolved in #2497 , but it has not yet been released in the most recent npm version.

**Comment by dolanmiu** [comment]
Now it is released in v `9.0.0`
