### ISSUE TITLE
How to scale images?

### ISSUE THREAD

**Issue by acgrama** [dolanmiu/docx#281]
As the title says, I cannot figure out how to use **Image.scale()**.

I can add to the document images created with **Media.addImage(..)**, but they have the wrong aspect ratio.
If I apply the **scale()** function on an image object created like this, I get a runtime error:
```
ERROR TypeError: Cannot read property 'scale' of undefined
    at Drawing.scale (index.js:11883)
    at PictureRun.scale (index.js:11876)
    at Image.scale (index.js:7957)
...

```
I am using v4.7.1 of docx.

**Comment by dolanmiu** [comment]
Check this out:

https://github.com/dolanmiu/docx/blob/master/demo/demo12.ts
