### ISSUE TITLE
Type error when importing docx in CJS file with TypeScript moduleResolution set to node16

### ISSUE THREAD

**Issue by danewilson** [dolanmiu/docx#2846]
Attempting to import anything from `docx` when using CommonJS using TypeScript when `moduleResolution` is `node16` results in a type error like:

> TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'.

This is because you haven't specified a CJS type declaration file. [This tool](https://arethetypeswrong.github.io/?p=docx%409.0.3) explains the issue well, and also the solution.

**Comment by dolanmiu** [comment]
Isn't it specified here?

https://github.com/dolanmiu/docx/blob/master/package.json#L8
