### ISSUE TITLE
INFO How use Media object to embed file

### ISSUE THREAD

**Issue by ferlolo** [dolanmiu/docx#285]
INFO
i would like embed a file into a document, but i didn't find the documentation, can someone help me plz???
I only found https://docx.js.org/api/classes/media.html#addmedia, but i don't understand so good the information.

Regards

**Comment by dolanmiu** [comment]
Try this:

https://github.com/dolanmiu/docx/blob/master/demo/demo5.ts

**Comment by greekdude90** [comment]
Hello,

Looks like that link is no longer active?  Has that functionality been removed, or is there another script I can reference?

**Comment by dolanmiu** [comment]
I have updated the link

**Comment by greekdude90** [comment]
Hi dolanmiu,

Thanks for the quick response.  I was wondering though about arbitrary objects.  Like, embedding an excel sheet, word doc, txt file, etc.

Is that possible to do at this time?

Thanks!

**Comment by dolanmiu** [comment]
Not possible unfortunately
