### ISSUE TITLE
first page header not working

### ISSUE THREAD

**Issue by ankibunkers** [dolanmiu/docx#289]
this demo is buggy and not working

https://github.com/dolanmiu/docx/blob/master/demo/demo14.ts

**Comment by maziyank** [comment]
experience the same....

**Comment by dolanmiu** [comment]
Correct, `titlePage: true` fixes the issue, I have amended demo 14 to show case this:

https://github.com/dolanmiu/docx/blob/master/demo/14-page-numbers.ts
