### ISSUE TITLE
Broken DOCX with image export since 8.6.0

### ISSUE THREAD

**Issue by GreatApo** [dolanmiu/docx#2897]
I have been getting corrupted docx files since version 8.6.0. MS Word comes up with an error:
"Word found unreadable content in 'XXX.docx'. DO you want to recover the contents of this document? If you trust the source of this document, click Yes."
Recover seems to fix the file. Upon comparison of the brocken/working docxs, i see that the saved media are stored as "undefined" in the new version (the docs contain and images):
![image](https://github.com/user-attachments/assets/0f169e8d-b30c-41d4-b785-7ba8f36a0c10)

Here are the documents:
[with_9.1.0.docx](https://github.com/user-attachments/files/18087094/with_9.1.0.docx)
[with_8.5.0.docx](https://github.com/user-attachments/files/18087095/with_8.5.0.docx)

The code used for generation is quite simple:
```javascript
// Image
let max_width = 600;
let stmImage = new docx.ImageRun({
	data: Graph.stage.toDataURL(), // Canvas to Data URL
	transformation: (() => {
		let size = {
			width: Graph.stage.width(),
			height: Graph.stage.height(),
		};
		let scale = max_width / size.width;
		return {
			width: size.width * scale,
			height: size.height * scale,
		}
	})(),
});

// Doc object
let doc = new docx.Document({
	sections: [{
		properties: {},
		children: [
			new docx.Paragraph({text: "Preview Image", heading: docx.HeadingLevel.HEADING_1}),
			new docx.Paragraph({children: [stmImage]})
		]
	}]
});
docx.Packer.toBlob(doc).then((blob) => {
	window.saveAs(blob, "report.docx");
});
```

**Comment by DreaminDani** [comment]
I'm having this same problem. I've tried importing images a number of different ways (including embedding the Base64 directly) and they still end up with this error message

**Comment by GreatApo** [comment]
> I'm having this same problem. I've tried importing images a number of different ways (including embedding the Base64 directly) and they still end up with this error message

I just found the issue, since version 8.6.0, you need to add a type property in the ImageRun. For example:
```javascript
let stmImage = new docx.ImageRun({
        type: "png",
	data: Graph.stage.toDataURL(), // Canvas to Data URL
	transformation: (() => {
		let size = {
			width: Graph.stage.width(),
			height: Graph.stage.height(),
		};
		let scale = max_width / size.width;
		return {
			width: size.width * scale,
			height: size.height * scale,
		}
	})(),
});
```

**Comment by DreaminDani** [comment]
That's not working for me unfortunately. I specify a type and I still get an issue:
```
new docx.Paragraph({
                          children: [
                            new docx.ImageRun({
                              type: 'png',
                              data: await fetch(LOGO_IMAGE).then((res) => res.arrayBuffer()),
                              transformation: {
                                width: Math.round(8.01 * 0.14 * 72), // 14% of original 8.01 inches
                                height: Math.round(1.78 * 0.14 * 72) // 14% of original 1.78 inches
                              }
                            })
                          ],
                          alignment: docx.AlignmentType.LEFT
                        })
```

I'm using vite so I can't use Buffer.from. not sure if that's the problem or something else.

Using the base64 directly also loads the image after I click "yes" on the dialog... but still shows the dialog:
```
new docx.Paragraph({
                          children: [
                            new docx.ImageRun({
                              type: 'png',
                              data: LOGO_IMAGE,
                              transformation: {
                                width: Math.round(8.01 * 0.14 * 72), // 14% of original 8.01 inches
                                height: Math.round(1.78 * 0.14 * 72) // 14% of original 1.78 inches
                              }
                            })
                          ],
                          alignment: docx.AlignmentType.LEFT
                        })
```

**Comment by GreatApo** [comment]
> That's not working for me unfortunately. 

The base64 should have worked (the relevant commit has similar examples 24c159de37090e711eae50af72ef51260f487f95). Are you sure you added the type on all images?

**Comment by DreaminDani** [comment]
> Are you sure you added the type on all images?

Oh shoot! You're right. There were multiple images in my file and i neglected to add the type to both of them. I'm no longer getting the error. Thanks so much!
