### ISSUE TITLE
Replace contents of loaded word file

### ISSUE THREAD

**Issue by martin-braun** [dolanmiu/docx#293]
I've seen at #143 that we can import existing word files now. My question is, is it possible to replace any strings (located anywhere) in the loaded word file and write it back as new file?

If so, how?

**Comment by dolanmiu** [comment]
This will be released in v5, not released yet

AFAIK (i did not develop this), it only works for .dotx files (document templates)

**Comment by MartyMaro** [comment]
> This will be released in v5, not released yet
> 
> AFAIK (i did not develop this), it only works for .dotx files (document templates)

I'd be fine if it works only with .dotx files, as long as I can iterate all elements and replace text in it. If this is not possible, I guess I have to look for something else. :/

**Comment by mbrevda** [comment]
Was this added to v5?

**Comment by dolanmiu** [comment]
Not in v5


After some thought, it is way out of scope of this library at the moment.
