### ISSUE TITLE
Merge multiple docx file

### ISSUE THREAD

**Issue by tsulatsitamim** [dolanmiu/docx#295]
Hi!
Is it possible to add/combine/merge docx files?

Thank you!

**Comment by dolanmiu** [comment]
This is not possible and is out of scope of this library

This library aims to convert JS/TS to `.docx`

What you are suggesting requires the tool to read two `.docx` files then create a single one

**Comment by mbrevda** [comment]
Are you familiar with tools that can do this? We have about 30 pages of "static" text that we would like to combine with some dynamic stuff

**Comment by dolanmiu** [comment]
Maybe use this:

https://convertio.co/docx-html/ which converts documents to html, then you can extract the text out, then use `docx`

**Comment by mbrevda** [comment]
Thanks for the quick response! I don't suppose there is some way to merge
in the html file?

**Comment by mbrevda** [comment]
Tried this as well as https://github.com/apurvaojas/docx-merger, but some things were corrupted (such as styles) as well as other issues (headers/footers, page numbering, etc). It would be great if this lib allowed creating new doc as it does now as well as allow for merging in preexisting docs.
