### ISSUE TITLE
Table example no longer works

### ISSUE THREAD

**Issue by jneljneljnel** [dolanmiu/docx#297]
copied from the main tables page. throws error (Error): Index out of bounds when trying to get row on table

import * as fs from "fs";
import { BorderStyle, Document, Packer, Paragraph } from "../build";

const doc = new Document();

const table = doc.createTable({
    rows: 4,
    columns: 4,
});
table
    .getCell(2, 2)
    .addParagraph(new Paragraph("Hello"))
    .Borders.addTopBorder(BorderStyle.DASH_DOT_STROKED, 3, "red")
    .addBottomBorder(BorderStyle.DOUBLE, 3, "blue")
    .addStartBorder(BorderStyle.DOT_DOT_DASH, 3, "green")
    .addEndBorder(BorderStyle.DOT_DOT_DASH, 3, "#ff8000");

const packer = new Packer();

packer.toBuffer(doc).then((buffer) => {
    fs.writeFileSync("My Document.docx", buffer);
});

**Comment by dolanmiu** [comment]
Try version `5.0.0-rc1`

**Comment by stefanwub** [comment]
Same problem here.. Any idea how to build and fill tables with recent version? Or from which version the tables still work?

Thanks!

**Comment by dolanmiu** [comment]
hmm ill check this one out, last time i checked it did

Are you using Microsoft Word? Is it failing at compiling? Or creating a corrupted doc?

**Comment by stefanwub** [comment]
Thanks for your quick response @dolanmiu!

I figured out that the problem occured when using `new Table(1, 2)`, you have to use `new Table({rows : 1, columns: 2})`

An other issue I had with adding tables is that documentation is not right for version `4.7.1`. The function `addParagraph` doesn't exists for `table.getCell()`. 

In version `5.0.0-rc1` this is working as expected.

**Comment by dolanmiu** [comment]
> you have to use new Table({rows : 1, columns: 2})

Yes this is the new API

> The function addParagraph doesn't exists for table.getCell().

Oh right, yeah the documentation is for `origin/master` actually, im not sure how to create documentation for different versions just yet with `docsify` https://docsify.now.sh/ (what I use to make documentation)
