### ISSUE TITLE
Lodash type definitions incompatible with latest typescript

### ISSUE THREAD

**Issue by felipeochoa** [dolanmiu/docx#3]
I hit [this issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14324) with the `lodash` type definitions, so had to manually edit `ts/typings/lodash/lodash.d.ts` to comment out the bottom line. I don't really use typescript/know what I'm doing, but this made the build work

```diff
diff --git a/ts/typings/lodash/lodash.d.ts b/ts/typings/lodash/lodash.d.ts
index 7901073..6d0e85d 100644
--- a/ts/typings/lodash/lodash.d.ts
+++ b/ts/typings/lodash/lodash.d.ts
@@ -19169,4 +19169,4 @@ declare module "lodash" {
 interface Set<T> {}
 interface Map<K, V> {}
 interface WeakSet<T> {}
-interface WeakMap<K, V> {}
+// interface WeakMap<K, V> {}
```

**Comment by dolanmiu** [comment]
ill look into this, weird. maybe I need to update the type definitions
