### ISSUE TITLE
Setting row heights in table

### ISSUE THREAD

**Issue by pdashford** [dolanmiu/docx#302]
Hi all.

Could someone let me know how you can set the row height for a table? Thanks

**Comment by nickgeorgiou** [comment]
Not currently possible... would definitely be good to add.

**Comment by semiosys** [comment]
Yes for sure, it would be very useful !

**Comment by andidev** [comment]
Is there any other hacky way to set the height of a table row? This is really needed for us since we need to print lables with exact distances between them.

**Comment by MLD5000** [comment]
I have been using paragraph spacing to increase row height:

`    paragraph.center().spacing({before: 90, after: 90});
`
