### ISSUE TITLE
Is there a highlight function?

### ISSUE THREAD

**Issue by batatop** [dolanmiu/docx#305]
In the documentation, I found functions for all (bold,  italic...) the styling options except "Highlighting". Does it have a different name or is it implemented?

Thank you.

**Comment by dolanmiu** [comment]
It is planned

I'm working on it now

**Comment by mbrevda** [comment]
dup of #309?

**Comment by dolanmiu** [comment]
There is now on `5.0.0-rc5`!

https://github.com/dolanmiu/docx/blob/master/demo/45-highlighting-text.ts
