### ISSUE TITLE
Optimize XML output

### ISSUE THREAD

**Issue by brucehappy** [dolanmiu/docx#306]
Currently the XML output always includes open and close tags for every element, even if that element has no children.  Additionally, there are some elements, such as `w:rPr` and `w:pPr` which do not need to be included in the output at all if they have no children.  The underlying `xml` library does support producing elements that are a single tag, but only if the value is an object containing a single `_attr` key, or if the value is null.  Therefore, the xml serialization should be changed to support sending objects in this format to the `xml` library for output.

Related to #213

**Comment by dolanmiu** [comment]
This was a design decision

Although it increases the document size, it keeps the code much cleaner without having to deal with null conditions

**Comment by dolanmiu** [comment]
null is toxic

https://medium.com/@hbarcelos/why-i-banned-null-from-my-js-code-and-why-you-should-too-13df90323cfa

> JavaScript originally intended undefined to refer to a value that doesn’t yet exist, while null was meant to refer to a value that does exist but points to nothing. That’s confusing. undefined is the default value when object members don’t exist, and is the return value for newer native collection APIs such as Map.get

https://palantir.github.io/tslint/rules/no-null-keyword/

> I can certainly change it to only be disabled on the lines in which it is needed instead

Yes please!

I will need to study your PR to see if it warrants the added complexity, because at the end of the day, no one will care if a `.docx` file increases by 10kb

**Comment by brucehappy** [comment]
I have updated the PR.  I've changed the single line in `XmlComponent`'s `prepForXml` that used `null` to indicate to the `xml` library that it should produce an empty element.  As documented here:
https://github.com/dylang/node-xml/issues/24
You can also use an empty object, which is what I've changed the PR to do.  This allowed me to change the tslint configuration back to what it was, re-enabling the `no-null-keyword` rule.  I've updated the JSON objects hardcoded into the test case checks as well.  `null` is, once again, no longer present in the source code.

You mention added complexity.  I would point out that vast majority of the changes have been to the hardcoded JSON objects in the test cases.  The changes to the other classes have been quite few.  The quick summary of those changes are:
* `XmlComponent`'s `prepForXml` now handles outputting objects for three different cases for use by the `xml` library:
1. Element with attributes and children:
`{ elementName: [ { _attr: { attributeName: attributeValue, ... } }, { childElementName: { ... } }, ... ] }`
2. Element with only attributes and no children:
`{ elementName: { _attr: { attributeName: attributeValue, ... } } }`
3. Element with no attributes and no children:
`{ elementName: { } }`

* In several places in the code you have checks in overridden `prepForXml` functions that checked for the `root` array having any members, and if it did not, it returned undefined, which caused the element to be ignored during XML output.  I have moved this concept up into a new subclass of `XmlComponent` and made those classes which had the `prepForXml` overrides be a subclass of this new `XmlComponent` subclass instead.  I have also used this concept for several classes that did not have the `prepForXml` code, but could also use it (such as `w:rPr` elements, etc).

As I mentioned in the original comment, this PR reduces file size, but it also brings the output much closer to what is produced by Word itself, allowing for easier debugging/file comparison and future development.  This seemed like a helpful improvement for any developer working on the project, including myself.  As such, I didn't see it as a premature optimization.  Perhaps I should have used a different issue title?  How about "Make XML output closer to Word to aid development"?
