### ISSUE TITLE
Is there a way to add a text background color to a Paragraph or TextRun

### ISSUE THREAD

**Issue by brunogaleski** [dolanmiu/docx#309]
Is there a way to add a text background color to a Paragraph or TextRun.

Like we can do with tables:

`    
table.getCell(0, 0).setShading({
        fill: "42c5f4",
        color: "auto",
  })`

**Comment by dolanmiu** [comment]
coming soon!

I am working on that piece now

**Comment by apptiseNI** [comment]
This would be a great addon, started looking at this module and this would get me round the problems I am having.

**Comment by mbrevda** [comment]
Is there a way to do this in the mean time?

**Comment by dolanmiu** [comment]
Nope, no way at the moment, essentially its implementing this:

http://officeopenxml.com/WPtextShading.php

which is no where in the codebase so far

**Comment by mforman1** [comment]
@dolanmiu Any update on this?

**Comment by dolanmiu** [comment]
There is now on `5.0.0-rc5`!

https://github.com/dolanmiu/docx/blob/master/demo/45-highlighting-text.ts
https://github.com/dolanmiu/docx/blob/master/demo/46-shading-text.ts
