### ISSUE TITLE
cell.addParagraph is not working

### ISSUE THREAD

**Issue by dashmaker** [dolanmiu/docx#312]
When I do the following:

```
const table = doc.createTable(2,2)
      table.setWidth(100,WidthType.PCT) 
      const row = table.getRow(0)
      row.mergeCells(0,1)
      var cell = table.getCell(0,0)
      var paragraph = new Paragraph(titleText).heading2();
      cell.addParagraph(paragraph);
```

I get an error stating that cell.addParagraph() is not a function

if I try to use
`doc.createtable({rows: numFields+1, columns: 2}), `

I get the error 

> Index out of bounds when trying to get row on table

Any idea what's going on and how I can get it to work?

**Comment by dolanmiu** [comment]
Try using

```
doc.createTable(numFields+1, 2)
```

What you wrote is the new API, which is on `5.0.0-rc1`

**Comment by FishNon** [comment]
> 
> 
> When I do the following:
> 
> ```
> const table = doc.createTable(2,2)
>       table.setWidth(100,WidthType.PCT) 
>       const row = table.getRow(0)
>       row.mergeCells(0,1)
>       var cell = table.getCell(0,0)
>       var paragraph = new Paragraph(titleText).heading2();
>       cell.addParagraph(paragraph);
> ```
> 
> I get an error stating that cell.addParagraph() is not a function
> 
> if I try to use
> `doc.createtable({rows: numFields+1, columns: 2}), `
> 
> I get the error
> 
> > Index out of bounds when trying to get row on table
> 
> Any idea what's going on and how I can get it to work?

Hello,
I get the same error, would you tell me how did you do to get it to work?

**Comment by ssamateh** [comment]
Try this 
`
const table = new Table(2, 2)
const row = table.getRow(0)
row.mergeCell(0, 1)
let cell = row.getCell(0)
cell.addContent(paragraph)
`

**Comment by suityou01** [comment]
`const table = document.createTable({
            rows: 4,
            columns: 4,
        });
        const row = table.getRow(0);`

Error: Index out of bounds when trying to get row on table

**Comment by suityou01** [comment]
`console.log(table.rows)`
[]

**Comment by dolanmiu** [comment]
try:

document.createTable(4,4);

`document.createTable({ rows: 4, columns: 4, });` is in the new API

**Comment by jiangyongyuan** [comment]
cell.addContent(paragraph) 

it can be work 

> Try this
> `const table = new Table(2, 2)`
> `const row = table.getRow(0)`
> `row.mergeCell(0, 1)`
> `let cell = row.getCell(0)`
> `cell.addContent(paragraph)`

**Comment by dolanmiu** [comment]
Closing because this is a non-issue
