### ISSUE TITLE
Is there a way to read and replace paragraphs from existing docx file

### ISSUE THREAD

**Issue by joshualimpj** [dolanmiu/docx#313]

**Comment by dolanmiu** [comment]
Nope that isn't the purpose of this library

No reading is available

**Comment by thgh** [comment]
It could save people's time if this were mentioned in the README. The `docx` package name sounds generic enough that one could expect this is supported.

For those still searching, check out [docxtemplater](https://www.npmjs.com/package/docxtemplater)

Which works like this:

```ts
writeFileSync('example.docx', generate({ name: 'Elon', price: '123' }))

function generate(replacements) {
  const zip = new PizZip(readFileSync('template.docx'))
  return new Docxtemplater(zip, { paragraphLoop: true, linebreaks: true })
    .render(replacements)
    .getZip()
    .generate({ type: 'nodebuffer', compression: 'DEFLATE' })
}

```

**Comment by dolanmiu** [comment]
`docx` now has this feature out of the box! As of `v8.0.0`:

https://github.com/dolanmiu/docx/blob/master/demo/85-template-document.ts

This library can now read and write docx files.
