### ISSUE TITLE
[question] ERROR in app/chunks/8.beb76.chunk.js from UglifyJs Unexpected token: name (match) [./~/docx/build/index.js:873,0]

### ISSUE THREAD

**Issue by FishNon** [dolanmiu/docx#315]
When I use `npm start` , my project is ok.
But when I use `npm run build`, this is the error info, what can I do to resolve this error?

> ERROR in app/chunks/8.beb76.chunk.js from UglifyJs
Unexpected token: name (match) [./~/docx/build/index.js:873,0][app/chunks/8.beb76.chunk.js:7397,8]

> ERROR in app/chunks/8.beb76.chunk.js from UglifyJs
Unexpected token: name (match) [app/chunks/8.beb76.chunk.js:7397,8]
Child html-webpack-plugin for "index.html":
       [0] ./~/lodash/lodash.js 540 kB {0} [built]
       [1] ./~/html-webpack-plugin/lib/loader.js!./src/index.template.html 32.1 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! boot@1.0.0 build: `npm run clean && webpack --config ./webpack/webpack.production.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the boot@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

> npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Liu\AppData\Roaming\npm-cache\_logs\2019-04-29T08_42_33_595Z-debug.log

**Comment by dolanmiu** [comment]
Are you using react?

**Comment by FishNon** [comment]
> 
> 
> Are you using react?

Yes, I'm using react.
And I've fix the error by adding the part of code in `webpack.production.js`.
`
{
      test: /\.(js|jsx)$/,
      loader: "babel-loader",
      include:[path.resolve(__dirname,"../node_modules/docx/")]
 }
`
Someone said that is because the UglifyJs doesn't support to display ES6.
Thanks for your response.

**Comment by dolanmiu** [comment]
thanks

do you mean `webpack.config.js`? There is no `webpack.production.js` in this repo

**Comment by FishNon** [comment]
> 
> 
> thanks
> 
> do you mean `webpack.config.js`? There is no `webpack.production.js` in this repo
> 
> or did you make your own webpack config?

Yes, I use webpack config in my project.
