### ISSUE TITLE
Is there a function or attribute that I can set table or paragraph that text wrap isn't around the table?

### ISSUE THREAD

**Issue by FishNon** [dolanmiu/docx#317]
Hello,

I want to set the table's position is center , and the next paragraph isn't around the table.

How can I do for the table or paragraph ( docx@4.7.1 ).

Thanks.

**Comment by ferrthrash** [comment]
the bad way is use Paragraph.break. Only if your table is not dynamic

**Comment by dolanmiu** [comment]
Closing as stale
