### ISSUE TITLE
Not able to create empty first page header

### ISSUE THREAD

**Issue by pieterprovoost** [dolanmiu/docx#320]
I'm trying to have an empty first page header and page numbers starting from the second page only, but I get page numbers on all pages. Am I missing something?

```
const firstPageHeader = doc.createFirstPageHeader();
firstPageHeader.addParagraph(new docx.Paragraph(""));

const pageNumber = new docx.TextRun("page ").pageNumber();
const header = (new docx.Paragraph()).addRun(pageNumber).right();
doc.Header.addParagraph(header);
```

**Comment by dolanmiu** [comment]
Check out https://github.com/dolanmiu/docx/blob/master/demo/demo16.ts

**Comment by dolanmiu** [comment]
You need the `titlePage` attribute:

https://github.com/dolanmiu/docx/blob/master/demo/14-page-numbers.ts
