### ISSUE TITLE
Column MergeCells does not work over 3+ rows

### ISSUE THREAD

**Issue by Scarface2013** [dolanmiu/docx#321]
The column cell merge needs to set the property of ALL of the cells in between startIndex and endIndex with 'continue', not just the last. 

I can't find the exact OpenXML reference for this, but it doesn't work right now (in 5.0.0.rc-1) and it does if I manually touch the XML to have the missing tags.

**Comment by dolanmiu** [comment]
thanks for this

noted, will make a fix and release on rc-2 soon
