### ISSUE TITLE
Date delimiter '.' instead of '/'

### ISSUE THREAD

**Issue by powderham** [dolanmiu/docx#323]
I am working with german clients and need to display dates as `25.12.2020` instead of `25/12/2020`.

I can't see in the docs if this is possible to force somehow, or whether it is dependent only on the docx viewer the user has installed.

**Comment by dolanmiu** [comment]
can you show me your code? Can you not use javascript to format the dates?

**Comment by dolanmiu** [comment]
Closing as stale and no reproduction steps
