### ISSUE TITLE
How can I use base64 image?

### ISSUE THREAD

**Issue by burakkp** [dolanmiu/docx#326]
Hi Everybody,

I want use base64 image in my project. How can i do that? I am generating dynamic image in my project, I want to implement docx with that image in word document. Is that possible or not?

**Comment by dolanmiu** [comment]
That is possible yes

Check this out: 

https://github.com/dolanmiu/docx/blob/master/demo/demo23.ts

**Comment by burakkp** [comment]
Thank you.
