### ISSUE TITLE
First page footer is not working! 

### ISSUE THREAD

**Issue by vamshi9** [dolanmiu/docx#327]
I have found this code through one of the pull requests/threads. It is supposed to work but somehow it is creating an empty page for `first` attribute. `default` is working as it is supposed to.

```
const footer1 = doc.createFooter();
  footer1.createParagraph('Footer on another page');
  const footer2 = doc.createFooter();
  footer2.createParagraph('Footer on first page');

  doc.addSection({
    footers: {
      default: footer1,
      first: footer2
    },
    pageNumberStart: 1
  });
```
version: 4.7.1

What could be the possible reason for this?

**Comment by dolanmiu** [comment]
I'll have a look tonight, potentially a bug, need to investigate

**Comment by dolanmiu** [comment]
Check out these demos:

https://github.com/dolanmiu/docx/blob/master/demo/demo14.ts
https://github.com/dolanmiu/docx/blob/master/demo/demo16.ts

**Comment by vamshi9** [comment]
Yeah, I have tried both of them, but unfortunately, it didn't work!

**Comment by zahrafali** [comment]
demo14 doesnt work

**Comment by Sraleik** [comment]
Doesn't work for me either ( on v 5.0.0-rc7)

**Comment by dolanmiu** [comment]
Got it working, you need the `titlePage` attribute for first page headers and footers to work

I have amended demo 14 to showcase this:

https://github.com/dolanmiu/docx/blob/master/demo/14-page-numbers.ts
