### ISSUE TITLE
Can't find an option to split page/paragraph into more than 1 column

### ISSUE THREAD

**Issue by zahrafali** [dolanmiu/docx#328]
<img width="536" alt="Screenshot 2019-05-27 at 1 03 41 PM" src="https://user-images.githubusercontent.com/25129766/58403286-e86a6700-807f-11e9-9293-4642509628bb.png">

Trying to create something like this

**Comment by dolanmiu** [comment]
Good question

Nope, not supported at the moment, will add as a feature request!

**Comment by zahrafali** [comment]
http://officeopenxml.com/WPsectionCols.php 
This could be the solution for multiple columns. Can it be made dynamic so that we can choose to have any number of columns.

**Comment by dolanmiu** [comment]
ill take a look

**Comment by zahrafali** [comment]
This issue can be closed as i've made a fix for this

**Comment by dolanmiu** [comment]
Will be released in `5.0.0-rc4`
