### ISSUE TITLE
Default line spacing

### ISSUE THREAD

**Issue by vamshi9** [dolanmiu/docx#329]
Hey there, we've been using docx package a lot and it is amazing and thanks. In our course of development of the application, we found that when a document is created, by default there are certain things that are coming into play. One thing we've noticed is the default spacing between paragraphs. It is great that the package already has before and after attributes in spacing. But, is there a way we can remove default spacing between similar paragraphs when the document is created? 
![image](https://user-images.githubusercontent.com/11611776/58579828-735a8580-8269-11e9-973f-366733e53df6.png)

**Comment by dolanmiu** [comment]
Do you by any chance have the OOXML documentation for this?

**Comment by vamshi9** [comment]
Sorry, I do not have it! But if it helps out, we can start contributing to the repository starting with this feature. Can you please share the resources to get started with the contribution. Thanks, @dolanmiu

**Comment by dolanmiu** [comment]
Thanks! yeah stars do help and motivate me

if you can find the documentation here, that would be great:

http://officeopenxml.com/

**Comment by vamshi9** [comment]
Could this be any helpful! @dolanmiu 
http://officeopenxml.com/WPspacing.php

**Comment by dolanmiu** [comment]
I think its related for sure, but theres no mention of "paragraphs of the same style" as you mentioned.

Perhaps that check box is a Microsoft Word only feature, but sure, I can add spacing in general no problem

**Comment by vamshi9** [comment]
Great to hear that, dolanmiu! 😃

**Comment by dolanmiu** [comment]
This feature is now available!

Check out:

https://github.com/dolanmiu/docx/blob/master/demo/27-declaritive-styles-3.ts
