### ISSUE TITLE
I would like to know how to add or make a Table of Contents

### ISSUE THREAD

**Issue by Lottid** [dolanmiu/docx#33]

**Comment by dolanmiu** [comment]
Can you please elaborate on what you mean by a directory in the word?

I do not understand.

A word document does not have directories.

**Comment by Lottid** [comment]
I want to add a directory to the word document.What should I do?
I am sorry,My English is very bad.Thinks for you.

**Comment by dolanmiu** [comment]
That is a contents page

That is not yet supported in this library yet!

Perhaps in a future update

**Comment by Lottid** [comment]
I'm looking forward to the next release.
thinks for you
