### ISSUE TITLE
Cannot set cell text color through setShading

### ISSUE THREAD

**Issue by Tonghua-Li** [dolanmiu/docx#330]
when setting cell's shading properties, it cannot set text color.
Can someone help me on it?

Demo code is here, in cv-generator.ts file
https://stackblitz.com/edit/angular-wft9un
```ts
    const table = new Table(3, 3, [1000, 8000, 1000]);
    table.setWidth(WidthType.PERCENTAGE, 100);
    table.setFixedWidthLayout();

    // this way cannot set text color
    const row = table.getRow(0);
    row.getCell(0).createParagraph("Has no color");
    row.getCell(0).CellProperties.setShading({color: "#ff5733", fill: "#42c5f4"});

    // this way can set text color
    const r: TextRun = new TextRun("Has color");
    r.color("#ff5733");
    row.getCell(1).createParagraph().addRun(r);
    row.getCell(1).CellProperties.setShading({fill: "#42c5f4"});
```

**Comment by dolanmiu** [comment]
This is a non issue and is working as expected

You are correct that this does not set the text color. You are setting the foreground pattern color
```
// this way cannot set text color
    const row = table.getRow(0);
    row.getCell(0).createParagraph("Has no color");
    row.getCell(0).CellProperties.setShading({color: "#ff5733", fill: "#42c5f4"});
```

Official docs:

http://officeopenxml.com/WPtableShading.php

# Color:

> Specifies the color to be used for any foreground pattern specified with the val attribute. Values are given as hex values (in RRGGBB format). No #, unlike hex values in HTML/CSS. E.g., fill="FFFF00".
