### ISSUE TITLE
.docx files are created in "Compatibility Mode"

### ISSUE THREAD

**Issue by PaulMest** [dolanmiu/docx#332]
My team is investigating which library to use for creating some reports in `.docx` format. We have noticed that this library creates documents in `Compatibility Mode`.
1) Is that expected behavior?
1) If so, what's the reason to create them in `Compatibility Mode`?
1) Is there any benefit to creating a `.docx` that is not in `Compatibility Mode`?

![image](https://user-images.githubusercontent.com/1721104/58996320-7c3ce100-87ac-11e9-848a-1b92d4950a5d.png)

**Comment by dolanmiu** [comment]
yes, i have noticed this too, but i am unsure why it does this

if you can provide some insight, that would be helpful

**Comment by mbrevda** [comment]
Perhaps this tool from Microsoft can help find the invalid parts of the doc? https://docs.microsoft.com/en-us/office/open-xml/how-to-validate-a-word-processing-document

**Comment by dolanmiu** [comment]
I have attempted this, but it hasnt got too far:

https://github.com/dolanmiu/Docx-Validator

**Comment by mbrevda** [comment]
Sorry but I don't know enough about .net to be able to help!

**Comment by goeh** [comment]
I don't know if this helps but in a Java project where I used the docx4j library I managed to avoid the compatibility mode warning with the following Java code:
```
    private static final String OFFICE_VERSION = "15";

    private void setDocumentVersion(MainDocumentPart mdp) throws Docx4JException {
        DocumentSettingsPart dsp = mdp.getDocumentSettingsPart(true);
        CTCompat compat = objectFactory.createCTCompat();
        dsp.getContents().setCompat(compat);
        compat.setCompatSetting("compatibilityMode", "http://schemas.microsoft.com/office/word", OFFICE_VERSION);
    }
```
I don't know if setting office version to "15" has any other effect on the created document.
I spent some time trying to add this settings attribute to the JS version but I failed due to lack of TS knowledge.

**Comment by tadmi** [comment]
To disable compatibility mode, add to settings.xml in the w:settings tag:

<w:compat>
        <w:compatSetting w:name="compatibilityMode" w:uri="http://schemas.microsoft.com/office/word" w:val="15"/>
</w:compat>

**Comment by dolanmiu** [comment]
Thank you @tadmi I have implemented this, and is fixed in:
https://github.com/dolanmiu/docx/pull/783
