### ISSUE TITLE
.toBuffer() not working with s3.putObject

### ISSUE THREAD

**Issue by tms1337** [dolanmiu/docx#333]
When I try to write my generated .docx file to s3, everything goes well. But when I download the file from s3 using the public link, my text editor can't open it as it is base64 encoded string. If I use `packer.toBuffer(doc)` instead the `s3.putObject` is not happy and says he requires buffer or base64 string. Why is `toBuffer` not valid argument for s3.putObject.

```
...
// set up doc and packer, doc is generated normally I checked
const documentBuffer = await packer.toBase64String(doc);

s3.putObject(
    {
      Bucket: "my-bucket",
      Key: "my-file.docx",
      Body: documentBuffer,
      ACL: "public-read",
      ContentEncoding: "base64",
      ContentType:
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    },
    resp => {
      console.log({ resp });
    }
  );
```

**Comment by tms1337** [comment]
Solved it with

```
  const documentBuffer = await packer.toBase64String(doc);
  let buff = new Buffer(documentBuffer, "base64"); 
```

This way buff is compatible with `s3.putObject()`. But shouldn't `packer.toBuffer(doc)` produce valid buffer without need for hacks like this?

**Comment by dolanmiu** [comment]
Good question

don't have an answer for that one im afraid

I think it's out of this library's control though

**Comment by tms1337** [comment]
> Good question
> 
> don't have an answer for that one im afraid
> 
> I think it's out of this library's control though

Not sure I agree since people expect `packer.toBuffer(doc)` to behave same as `Buffer` in node.

**Comment by dolanmiu** [comment]
It should do, here is the source:

https://github.com/dolanmiu/docx/blob/master/src/export/packer/packer.ts#L13-L18

Corresponding documentation:

https://stuk.github.io/jszip/documentation/api_jszip/generate_async.html

Search for "nodebuffer"

**Comment by jwerre** [comment]
I had the same issue (https://github.com/dolanmiu/docx/issues/379). 

You can wrap the "buffer" and it will work:

```js
buffer = await Packer.toBuffer(doc);

s3.putObject({
    Bucket: "my-bucket",
    Key: "my-file.docx",
    Body: Buffer(buffer), // wrap here
}, (res) => {
    console.log(res);
});


```

**Comment by kelvanince21** [comment]
@dolanmiu 
Why was this issue closed? It isn't resolved.
