### ISSUE TITLE
Is there a way to apply watermarks to our document?

### ISSUE THREAD

**Issue by ankushgarg1998** [dolanmiu/docx#338]

**Comment by dolanmiu** [comment]
not as of yet

**Comment by neelz040** [comment]
@dolanmiu any chance this is added soon? Would be a great feature !

**Comment by dolanmiu** [comment]
Is this a specific feature for Word? Or is it just an image on top of the document?

I can't find any documentation on it this feature on OOXML

**Comment by neelz040** [comment]
@dolanmiu Its a feature in Word. In the design tab (on my Mac) I can add a watermark. 

<img width="278" alt="image" src="https://user-images.githubusercontent.com/8742300/67843020-84027680-fafb-11e9-838e-5e196a8f34f2.png">

**Comment by jamesmontalvo3** [comment]
I'm not sure if this will help, but adding a watermark to a simple docx file using the method @neelz040 shows above creates, among other things, a `word/header2.xml` file inside the docx that looks like this: 

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:hdr 
  xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" 
  xmlns:cx="http://schemas.microsoft.com/office/drawing/2014/chartex" 
  xmlns:cx1="http://schemas.microsoft.com/office/drawing/2015/9/8/chartex" 
  xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
  xmlns:o="urn:schemas-microsoft-com:office:office" 
  xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" 
  xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" 
  xmlns:v="urn:schemas-microsoft-com:vml" 
  xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" 
  xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" 
  xmlns:w10="urn:schemas-microsoft-com:office:word" 
  xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" 
  xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" 
  xmlns:w15="http://schemas.microsoft.com/office/word/2012/wordml" 
  xmlns:w16se="http://schemas.microsoft.com/office/word/2015/wordml/symex" 
  xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" 
  xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk" 
  xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml" 
  xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape" mc:Ignorable="w14 w15 w16se wp14">
  <w:p w:rsidR="00FE5CF7" w:rsidRDefault="00F02E7B">
    <w:pPr>
      <w:pStyle w:val="Header"/>
    </w:pPr>
    <w:r>
      <w:rPr>
        <w:noProof/>
      </w:rPr>
      <w:pict>
        <v:shapetype id="_x0000_t136" coordsize="21600,21600" o:spt="136" adj="10800" path="m@7,l@8,m@5,21600l@6,21600e">
          <v:formulas>
            <v:f eqn="sum #0 0 10800"/>
            <v:f eqn="prod #0 2 1"/>
            <v:f eqn="sum 21600 0 @1"/>
            <v:f eqn="sum 0 0 @2"/>
            <v:f eqn="sum 21600 0 @3"/>
            <v:f eqn="if @0 @3 0"/>
            <v:f eqn="if @0 21600 @1"/>
            <v:f eqn="if @0 0 @2"/>
            <v:f eqn="if @0 @4 21600"/>
            <v:f eqn="mid @5 @6"/>
            <v:f eqn="mid @8 @5"/>
            <v:f eqn="mid @7 @8"/>
            <v:f eqn="mid @6 @7"/>
            <v:f eqn="sum @6 0 @5"/>
          </v:formulas>
          <v:path textpathok="t" o:connecttype="custom" o:connectlocs="@9,0;@10,10800;@11,21600;@12,10800" o:connectangles="270,180,90,0"/>
          <v:textpath on="t" fitshape="t"/>
          <v:handles>
            <v:h position="#0,bottomRight" xrange="6629,14971"/>
          </v:handles>
          <o:lock v:ext="edit" text="t" shapetype="t"/>
        </v:shapetype>
        <v:shape id="PowerPlusWaterMarkObject82850627" o:spid="_x0000_s2051" type="#_x0000_t136" style="position:absolute;margin-left:0;margin-top:0;width:569.85pt;height:89.95pt;rotation:315;z-index:-251653120;mso-position-horizontal:center;mso-position-horizontal-relative:margin;mso-position-vertical:center;mso-position-vertical-relative:margin" o:allowincell="f" fillcolor="silver" stroked="f">
          <v:fill opacity=".5"/>
          <v:textpath style="font-family:&quot;Calibri&quot;;font-size:1pt" string="CUSTOM WATERMARK 2"/>
          <w10:wrap anchorx="margin" anchory="margin"/>
        </v:shape>
      </w:pict>
    </w:r>
  </w:p>
</w:hdr>
```

The above is with the custom watermark text being `CUSTOM WATERMARK 2`. Originally I had written `CUSTOM WATERMARK`, and this is the diff between the two versions:

```diff
diff --git a/test.docx.contents/word/header2.xml b/test.docx.contents/word/header2.xml
index 03445b4..5a6deeb 100644
--- a/test.docx.contents/word/header2.xml
+++ b/test.docx.contents/word/header2.xml
@@ -19,7 +19,7 @@
   xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk"
   xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml"
   xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape" mc:Ignorable="w14 w15 w16se wp14">
-  <w:p w:rsidR="00FE5CF7" w:rsidRDefault="00FE5CF7">
+  <w:p w:rsidR="00FE5CF7" w:rsidRDefault="00F02E7B">
     <w:pPr>
       <w:pStyle w:val="Header"/>
     </w:pPr>
@@ -52,9 +52,10 @@
           </v:handles>
           <o:lock v:ext="edit" text="t" shapetype="t"/>
         </v:shapetype>
-        <v:shape id="PowerPlusWaterMarkObject82708986" o:spid="_x0000_s2051" type="#_x0000_t136" style="position:absolute;margin-left:0;margin-top:0;width:565.5pt;height:94.25pt;rotation:315;z-index:-251653120;mso-position-horizontal:center;mso-position-horizontal-relative:margin;mso-position-vertical:center;mso-position-vertical-relative:margin" o:allowincell="f" fillcolor="silver" stroked="f">
+        <v:shape id="PowerPlusWaterMarkObject82850627" o:spid="_x0000_s2051" type="#_x0000_t136" style="position:absolute;margin-left:0;margin-top:0;width:569.85pt;height:89.95pt;rotation:315;z-index:-251653120;mso-position-horizontal:center;mso-position-horizontal-relative:margin;mso-position-vertical:center;mso-position-vertical-relative:margin" o:allowincell="f" fillcolor="silver" stroked="f">
           <v:fill opacity=".5"/>
-          <v:textpath style="font-family:&quot;Calibri&quot;;font-size:1pt" string="CUSTOM WATERMARK"/>
+          <v:textpath style="font-family:&quot;Calibri&quot;;font-size:1pt" string="CUSTOM WATERMARK 2"/>
+          <w10:wrap anchorx="margin" anchory="margin"/>
         </v:shape>
       </w:pict>
     </w:r>
diff --git a/test.docx.contents/word/header3.xml b/test.docx.contents/word/header3.xml
index 38bd1f6..440c850 100644
--- a/test.docx.contents/word/header3.xml
+++ b/test.docx.contents/word/header3.xml
@@ -19,7 +19,7 @@
   xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk"
   xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml"
   xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape" mc:Ignorable="w14 w15 w16se wp14">
-  <w:p w:rsidR="00FE5CF7" w:rsidRDefault="00FE5CF7">
+  <w:p w:rsidR="00FE5CF7" w:rsidRDefault="00F02E7B">
     <w:pPr>
       <w:pStyle w:val="Header"/>
     </w:pPr>
@@ -52,9 +52,10 @@
           </v:handles>
           <o:lock v:ext="edit" text="t" shapetype="t"/>
         </v:shapetype>
-        <v:shape id="PowerPlusWaterMarkObject82708984" o:spid="_x0000_s2049" type="#_x0000_t136" style="position:absolute;margin-left:0;margin-top:0;width:565.5pt;height:94.25pt;rotation:315;z-index:-251657216;mso-position-horizontal:center;mso-position-horizontal-relative:margin;mso-position-vertical:center;mso-position-vertical-relative:margin" o:allowincell="f" fillcolor="silver" stroked="f">
+        <v:shape id="PowerPlusWaterMarkObject82850625" o:spid="_x0000_s2049" type="#_x0000_t136" style="position:absolute;margin-left:0;margin-top:0;width:569.85pt;height:89.95pt;rotation:315;z-index:-251657216;mso-position-horizontal:center;mso-position-horizontal-relative:margin;mso-position-vertical:center;mso-position-vertical-relative:margin" o:allowincell="f" fillcolor="silver" stroked="f">
           <v:fill opacity=".5"/>
-          <v:textpath style="font-family:&quot;Calibri&quot;;font-size:1pt" string="CUSTOM WATERMARK"/>
+          <v:textpath style="font-family:&quot;Calibri&quot;;font-size:1pt" string="CUSTOM WATERMARK 2"/>
+          <w10:wrap anchorx="margin" anchory="margin"/>
         </v:shape>
       </w:pict>
     </w:r>
```

**Comment by ryanbucci5** [comment]
Any potential update on this feature request? Am also looking to see if we could add this at some point! Thanks for all your hard work as well on the package!

**Comment by billreynolds007** [comment]
Here is how I achieved a watermark affect.
First I defined my watermark PNG. It is just "Testing Only" in bold, a faint red color, and slanted.
For the next steps, I then went to https://www6.lunapic.com/editor/
1. Upload the watermark PNG file
2. Choose Effects; Needlepoint (at the very bottom)
3. Choose File;Save Image
4. Click “Save as PNG”

Next I make the white pixels in the PNG transparent. I used an old Paintshop app. 
The needle point affect above is key to getting the desired end result.
In my document creation code I load that new PNG's raw bytes.

```
var oReq = new XMLHttpRequest();
oReq.open("GET", 'image/watermark2.png', true);
oReq.responseType = "arraybuffer";
var contentType = '';
var self = this;
var myPromise = new Promise( function(resolve, reject) {
	oReq.onabort = function()
		{
		reject('retrieveBinaryResourceContent, Abort');
		};
	oReq.onerror = function()
		{
		reject('retrieveBinaryResourceContent, Error of some sort');
		};
	oReq.onload = function(oEvent) {
		var arrayBuffer = oReq.response;
		var bytes = new Uint8Array(arrayBuffer);
		resolve(bytes);
	};
	oReq.send();
} );
return myPromise;
```

Next I create an image.

```
const watermark = docx.Media.addImage(doc, myRawBytes, width, height, {
    floating: {
    	// https://startbigthinksmall.wordpress.com/2010/01/04/points-inches-and-emus-measuring-units-in-office-open-xml/
    	// One inch equates to 914400 EMUs 
    	// Placement is relative: HorizontalPositionRelativeFrom.PAGE by default
        horizontalPosition: {
            offset: 914400 * 1,
        },
        verticalPosition: {
            offset: 914400 * 1,
        }
    },
});
```
In the document generation code I then add this image to the section children. For example,
```
paragraphs.push(new docx.Paragraph(watermark) );
doc.addSection({
    children: paragraphs,
});

```
Below is the result.

![sampleWatermark](https://user-images.githubusercontent.com/50873440/80504752-76f70080-8941-11ea-8b9e-b5f3150f1d05.png)

**Comment by YovelBecker** [comment]
hi! any update on that feature? the image solution seems to not work so much because as it looks like a watermark, its still an image and it still moves when handling the document.

**Comment by dolanmiu** [comment]
Water mark is actually a microsoft word feature and isn't part of the official OOXML spec

So a lot of manual work is required. It isn't simply a "turn it on" feature

**Comment by YovelBecker** [comment]
ohh i see.
so if i'm going with the image solution, is there a way for me to lock the image in place so it wont move when trying to click around in the page?

**Comment by dolanmiu** [comment]
@YovelBecker Adding it in the header or footer will do the trick

It seems thats what Word does, as explained here:

https://answers.microsoft.com/en-us/msoffice/forum/msoffice_word-mso_winother-mso_o365b/how-can-i-lock-a-watermark-in-a-word-document-or/4828dbdb-2057-4a82-9b34-0c8f3cf3693d

After some thought, I have decided that this feature is is out of scope as it is something implemented by Microsoft or LibreOffice etc in their own word processors.

@billreynolds007 has an excellent solution though

**Comment by tiejunhu** [comment]
> Here is how I achieved a watermark affect. First I defined my watermark PNG. It is just "Testing Only" in bold, a faint red color, and slanted. For the next steps, I then went to https://www6.lunapic.com/editor/
> 
> 1. Upload the watermark PNG file
> 2. Choose Effects; Needlepoint (at the very bottom)
> 3. Choose File;Save Image
> 4. Click “Save as PNG”
> 
> Next I make the white pixels in the PNG transparent. I used an old Paintshop app. The needle point affect above is key to getting the desired end result. In my document creation code I load that new PNG's raw bytes.
> 
> ```
> var oReq = new XMLHttpRequest();
> oReq.open("GET", 'image/watermark2.png', true);
> oReq.responseType = "arraybuffer";
> var contentType = '';
> var self = this;
> var myPromise = new Promise( function(resolve, reject) {
> 	oReq.onabort = function()
> 		{
> 		reject('retrieveBinaryResourceContent, Abort');
> 		};
> 	oReq.onerror = function()
> 		{
> 		reject('retrieveBinaryResourceContent, Error of some sort');
> 		};
> 	oReq.onload = function(oEvent) {
> 		var arrayBuffer = oReq.response;
> 		var bytes = new Uint8Array(arrayBuffer);
> 		resolve(bytes);
> 	};
> 	oReq.send();
> } );
> return myPromise;
> ```
> 
> Next I create an image.
> 
> ```
> const watermark = docx.Media.addImage(doc, myRawBytes, width, height, {
>     floating: {
>     	// https://startbigthinksmall.wordpress.com/2010/01/04/points-inches-and-emus-measuring-units-in-office-open-xml/
>     	// One inch equates to 914400 EMUs 
>     	// Placement is relative: HorizontalPositionRelativeFrom.PAGE by default
>         horizontalPosition: {
>             offset: 914400 * 1,
>         },
>         verticalPosition: {
>             offset: 914400 * 1,
>         },
> 	behindDocument: true
>     },
> });
> ```
> 
> In the document generation code I then add this image to the section children. For example,
> 
> ```
> paragraphs.push(new docx.Paragraph(watermark) );
> doc.addSection({
>     children: paragraphs,
> });
> ```
> 
> Below is the result.
> 
> ![sampleWatermark](https://user-images.githubusercontent.com/50873440/80504752-76f70080-8941-11ea-8b9e-b5f3150f1d05.png)

I did an experiment, if I add this floating image to header, it'll appear as watermark in every page. It's now an almost perfect solution.

**Comment by jyothinGIT1** [comment]
> docx.Media.addImage

is there any deprecation happend in the function for latest version of docx, i am getting a "docx.Media.addImage is not a function", this error

**Comment by jamesmontalvo3** [comment]
Yes a long time ago. v7 or earlier. Code on this issue predates that.

**Comment by lgodard** [comment]
Hi all,

I needed this watermark feature and i'm happy to find the PNG based workaround.

In case of `PatchDocument` , here is a proposal that works for me without the need of an image
(btw, i would also need a watermark API when i'm not in a `PatchDocument` context ;-) )

First, set a watermark in your docx template, say `{{watermark}}`
Then, the idea is to open the `docx_buffer` as a zip file and replace the watermark in the xml files

```javascript
import jszip from 'jszip';

async function setDocxWatermark(docx_buffer, watermark_value) {

    const zip = await jszip.loadAsync(docx_buffer);

    const watermark_markup = new RegExp('{{watermark}}', 'g');

    const promises = [];

    ['word/header1.xml'].forEach((filepath) => {

        const p = zip.file(filepath).async('text')
            .then((xml_content) => {
                xml_content = xml_content.replace(watermark_markup, escapeXml(watermark_value));
                return zip.file(filepath, xml_content);
            });

        promises.push(p);
    });

    await Promise.all(promises);

    return zip.generateAsync({type: 'nodebuffer'});
}

function escapeXml(string_value) {
    return string_value != null ? string_value.toString().replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;') : '';
}
``` 
 note the loop over `['word/header1.xml']` in case tour watermark falls in other xml files of your template

HTH

**Comment by ethpsantos** [comment]
I was looking for that :(
The lib is awesome but what I needed was the watermark text feature.
Sadly it won't come.
