### ISSUE TITLE
Document.xml output file is pretty printed

### ISSUE THREAD

**Issue by markcharyk** [dolanmiu/docx#342]
When the .docx file is generated, all of its constituent zipped .xml files are output without whitespace, *except* for `word/document.xml`. This file has its XML pretty printed with newlines and indentation.

This isn't an issue for Word to open the file, but if you do a "Save As" Word will overwrite the pretty printed XML with a non-whitespace XML.

My team uses some XML parsing code to read Word documents that gets tripped up by pretty printed files so this became an issue for us when we used `docx` to generate the documents we later wanted to input to our parsers.

Is there a reason for the pretty printing? I'll be opening a pull request soon that allows for a "pretty print all the files" option to be passed in to the `Packer()` constructor but defaults to `false` so the behavior is closer to what happens when you do a save from Word. Does this seem like an OK solution?

Thanks!

**Comment by dolanmiu** [comment]
Pretty printing is for debugging really

I often dig into the word document to investigate issues, its just easier to pretty print

didnt realise it would cause issues

I assume https://github.com/dolanmiu/docx/pull/343 fixes this?

What is your company? Do you mind if I put it on the README.md?

**Comment by markcharyk** [comment]
Yeah, #343 is an adequate fix for our use case, thank you for the quick turnaround on it!

Arguably, the issue always was on our end by writing XML parsing logic that doesn't parse what is, technically, valid XML with whitespace, but our goal in creating .docx files is to make them as close as possible to what someone would create from scratch in Word.

I work with a company that writes legal software called TurboPatent. You can find a link to our website [here](https://turbopatent.com/) and no issues about adding us to your README.

Thanks again!

**Comment by markcharyk** [comment]
Closing because of the merged #343
