### ISSUE TITLE
Escape bad characters

### ISSUE THREAD

**Issue by jacwright** [dolanmiu/docx#345]
I have customers who copy-paste bad characters into their documents by accident sometimes. This causes the final word doc to not be openable until they find and delete those characters. It would be nice if docx could escape characters (or add `<![CDATA[...]]>` surrounding text with it) so it can always generate valid Word documents.

BTW, https://www.dabblewriter.com/ is the app and uses your project for exporting novels. We love it! Nice work on everything here.

**Comment by jacwright** [comment]
For example, a customer reporting this issue today had this at the end of several of the scenes in her novel.

```
"...change that.\n\f\n"
```

but there are plenty of other characters which can cause a Word doc to not open.

**Comment by dolanmiu** [comment]
Thanks for the great feedback! Is it ok if I put the logo on the readme?

do you know the correct way to escape `\f\n`?

**Comment by jacwright** [comment]
I do not mind you using the logo there.

I did some research about this issue and found https://stackoverflow.com/questions/12229572/php-generated-xml-shows-invalid-char-value-27-message. Quang Tran submitted a JavaScript version of the regex to strip out characters that are not valid in XML documents which will prevent this problem. I should also strip these characters out from my data since they are not useful or valuable data to have.

```javascript
function utf8_for_xml(inputStr) {
  return inputStr.replace(/[^\x09\x0A\x0D\x20-\xFF\x85\xA0-\uD7FF\uE000-\uFDCF\uFDE0-\uFFFD]/gm, '');
}
```

I recommend this be used on all text added to a document, keeping it clean and creating valid XML documents.

**Comment by dolanmiu** [comment]
Regarding bad characters, sometimes it's good to have `\t` as an actual tab character in documents:

https://github.com/dolanmiu/docx/blob/master/demo/6-page-borders.ts

So I am wondering how to deal with this conflicting scenario

**Comment by dolanmiu** [comment]
Closing this as there is a conflict of interest with:

https://github.com/dolanmiu/docx/issues/529
