### ISSUE TITLE
[Question] Fill with symbol until line break

### ISSUE THREAD

**Issue by bre7** [dolanmiu/docx#346]
Is there a way to pad the line until line break with a symbol (e.g: `-`) ? No luck in finding any info about it.

Page margins:

```
______________________
|  abcdefg.----------|
|                    |
|                    |
|                    |
|                    |
______________________
```

**Comment by dolanmiu** [comment]
I don't think this is a microsoft word feature? so probably it wont be added into this library

**Comment by bre7** [comment]
Thought was much. Couldn't find any way to do it programatically.
