### ISSUE TITLE
Number of Total Pages Per Section

### ISSUE THREAD

**Issue by rivkiroten** [dolanmiu/docx#348]
in a doc with multiple sections, is it possible to implement NumberOfTotalPages for each section separately?

**Comment by dolanmiu** [comment]
Yes, https://github.com/dolanmiu/docx/blob/master/demo/demo16.ts

**Comment by rivkiroten** [comment]
this demo does not work correctly. the pageNumber resets for each section (even without entering the line pageNumberStart: 1)
