### ISSUE TITLE
There is an option to add page cover? or add the html to exist docx?

### ISSUE THREAD

**Issue by veredwpsemantix** [dolanmiu/docx#351]

**Comment by dolanmiu** [comment]
No option to add html to this library, thats out of scope for this library

cover page not supported yet

**Comment by veredwpsemantix** [comment]
I can't put an image in the header and put it behind the text?

**Comment by dolanmiu** [comment]
I think what you are thinking of is floating images,

check these out:

https://github.com/dolanmiu/docx/blob/master/demo/demo5.ts
https://github.com/dolanmiu/docx/blob/master/demo/demo38.ts

**Comment by veredwpsemantix** [comment]
Thank's!
For something like page cover I did this:

 const image = docx.Media.addImage(doc, Buffer.from(imageBase64Data, "base64"),793.3228346456693, 1122.141732283465 , {
    floating: {
        horizontalPosition: {
            offset: 0,
        },
        verticalPosition: {
            offset: 0,
        },
         behindDocument:true,
    },});

doc.Header.addImage(image);
