### ISSUE TITLE
Column width property doesnt work when there's text in the cells

### ISSUE THREAD

**Issue by zahrafali** [dolanmiu/docx#352]
I am trying to add column width of 12.5% for all and i have 8 columns
If there's no text in any cell then they follow the spacing specified by columnWidths, But when there's text, they are not following the given width size
 Here is my code - 
```
const doc = new Document();
const abc = new Table({
    rows: 8,
    columns: 8,
    width: 100,
    columnWidths: new Array(8).fill(12.5),
    widthUnitType: WidthType.PERCENTAGE,
});

abc.getCell(0, 0).addParagraph(new Paragraph("Hellohello hellohellohello"));

doc.addTable(abc);
```

and this is the result 
<img width="1440" alt="Screenshot 2019-07-10 at 4 32 13 PM" src="https://user-images.githubusercontent.com/25129766/60965064-85cce200-a332-11e9-9081-020543497938.png">

**Comment by zahrafali** [comment]
If there's no text in any cell then they follow the spacing specified by columnWidths

**Comment by ducviet1696** [comment]
add the function abc.setFixedWidthLayout()

**Comment by zahrafali** [comment]
> add the function abc.setFixedWidthLayout()

Thanks! this worked!!

**Comment by henry132109** [comment]
In case it helps, you can also use the layout property
```
new Table({
  width: {...},
  layout: "fixed",
  rows: [...],
  ...
})
```
Btw could @zahrafali please close this issue?
