### ISSUE TITLE
[Question] on ParagraphStyle Class

### ISSUE THREAD

**Issue by hrestrepop** [dolanmiu/docx#353]
Hi @dolanmiu.

By working with the `Styles` class, I realized that its children are instances of the `ParagraphStyle` class, but this last one is not being exported (not part of the API). So the only one way I found to add more Styles children is by using the method `createParagraphStyle`, which is honestly bad since it's too coupled and out of control (for custom validations for instance)  –what if you wanna work with a more functional approach? it would be nice to be able import all parent and children class as well such as `ParagraphStyle`.

Let me know what you think, thanks!

**Comment by hrestrepop** [comment]
Checked on the newest version. Thanks!

**Comment by dolanmiu** [comment]
I am actually redesigning the whole API to be more functional and declarative, which will be in the major `5.0.0` release, kind of inspired by Flutter and React:

https://github.com/dolanmiu/docx/tree/feat/declaritive

Example:

```ts
const doc = new Document();

doc.addSection({
    properties: {},
    children: [
        new Paragraph({
            children: [
                new TextRun("Hello World"),
                new TextRun({
                    text: "Foo Bar",
                    bold: true,
                }),
                new TextRun({
                    text: "Github is the best",
                    bold: true,
                }).tab(),
            ],
        }),
    ],
});
```

watch this space!

**Comment by hrestrepop** [comment]
Looks awesome mate, looking forward to it then :)
