### ISSUE TITLE
Can I insert different margin to footer?

### ISSUE THREAD

**Issue by veredwpsemantix** [dolanmiu/docx#354]
I want to move the page number without changing the margin of the page, or if there is an option to let position to footer?

**Comment by dolanmiu** [comment]
This would be done using "Text Boxes" in word, which is not a feature yet

on the todo list

**Comment by veredwpsemantix** [comment]
Ok! thanks!

**Comment by Sraleik** [comment]
I would like to set an image banner as my header with a width of 100% and from the top of the page.
Right now, when i'm trying, the page margin prevent me from doing so :(

**Comment by dolanmiu** [comment]
This is now possible!

Check out:

https://github.com/dolanmiu/docx/blob/master/demo/59-header-footer-margins.ts
