### ISSUE TITLE
How do I create an external hyperlink with alternate displayed text

### ISSUE THREAD

**Issue by jim-moore-sp** [dolanmiu/docx#355]
I'd like to create a hyperlink similar to the html `<a href="https://www.example.com">example</a>` but it doesn't seem to work with the current version (5.0.0-rc4)

The code in example [demo35.ts ](https://github.com/dolanmiu/docx/blob/master/demo/demo35.ts) no longer works as the method createHyperlink has been removed from Document:
```
const doc = new Document();
const paragraph = new Paragraph();
const link = doc.createHyperlink("http://www.example.com", "Hyperlink");

link.bold();
paragraph.addHyperLink(link);
doc.addParagraph(paragraph);
```
and the new version with an anchor string only works for internal links.

**Comment by dolanmiu** [comment]
Thanks

I will fix the demos soon

**Comment by yoheioka** [comment]
+1

**Comment by dolanmiu** [comment]
https://github.com/dolanmiu/docx/blob/master/demo/35-hyperlinks.ts

here is the fixed demo
