### ISSUE TITLE
Text indent in numbering

### ISSUE THREAD

**Issue by veredwpsemantix** [dolanmiu/docx#357]
How can I change the default ident?
I tried to do this, but it doesn't do anything.
abstractNum.createLevel(0, "upperRoman", "%1", "start").addParagraphProperty(new Indent({ left: 338, hanging: 0 }));

![image](https://user-images.githubusercontent.com/42737154/61215718-4a585c00-a714-11e9-85db-7a2f182a6622.png)

**Comment by veredwpsemantix** [comment]
?

**Comment by saus-75** [comment]
Same here, was wondering how I can match the indentation to .bullet()

**Comment by saus-75** [comment]
@veredwpsemantix had a glance through the source code for how default bullet point is created
it seems that it passes this im indentation constructor through, maybe try this? 
`new Indent({ left: 720, hanging: 360 })`
source: https://github.com/dolanmiu/docx/blob/master/src/file/numbering/numbering.ts

**Comment by dolanmiu** [comment]
Check out: https://github.com/dolanmiu/docx/blob/master/demo/3-numbering-and-bullet-points.ts

I am able to change the indenting.

![Screen Shot 2019-11-24 at 03 33 48](https://user-images.githubusercontent.com/2917613/69489080-40392d80-0e6b-11ea-9f0a-d48ec7b7a12e.png)

I hope this helps

Re-open if this is still an issue

**Comment by laurent512** [comment]
same problem here, any update?
