### ISSUE TITLE
How to use character style?

### ISSUE THREAD

**Issue by AlessiaCorsini** [dolanmiu/docx#358]
I have a paragraph and my goal is to have an highlighted word inside of it.

I am currently using xml styling, and what I did is the following:
- in the word document, set a character style 'foo' with relative background color.
- extracted docx  and imported the styles.xml  as externalStyles
- assigned 'foo' as style to a TextRun

After the export, when I open the docx, I have the style visually assigned to the 'TextRun' but in the Format panel the character style is missing and is interpreted as an updated default paragraph style.

Most likely my approach is wrong, but I could not find any reference.
Any suggestion would be really appreciated

**Comment by dolanmiu** [comment]
An example of how to do it is here:

https://github.com/dolanmiu/docx/blob/master/demo/51-character-styles.ts

**Comment by hshoja** [comment]
@dolanmiuThe question pertains to utilizing the style from `externalStyles` for TextRun, whereas the example provided explains the usage of `characterStyles`. The example that involves xml style does not seem to be functional.
