### ISSUE TITLE
Table exemple + border styling.

### ISSUE THREAD

**Issue by KennyBarraud** [dolanmiu/docx#36]
Hello.
Could I have a table exemple with your package ?
Plus is it possible to define the border of this table ?
Thx.

**Comment by dolanmiu** [comment]
I need to have a look into this myself actually, tables was made by another guy, and I swear there was documentation, but I guess not

**Comment by dolanmiu** [comment]
I have just written a demo for Tables, in `demo4.js`:

https://github.com/dolanmiu/docx/blob/master/demo/demo4.js

I will write documentation for it soon

And from what I can see, no border support yet, seems like that other guy didn't add it. I got to research how to do it, then implement it which may take a long time

**Comment by KennyBarraud** [comment]
Ok thank you !

**Comment by dolanmiu** [comment]
Border is now done, on tables, there is a border by default:

Check out `demo 4`:

https://runkit.com/dolanmiu/docx-demo4

Thanks!
