### ISSUE TITLE
Bug: Documents generated from .dotx templates contain errors

### ISSUE THREAD

**Issue by moritz-tr** [dolanmiu/docx#361]
I tried generating a .docx file from a .dotx template.
You can reproduce this error with `demo/demo30.ts` and the according .dotx file from this repo.
The resulting file contains errors and cannot be opened in Office365 Word. When I try to open it in Libre Office i get a little more information about the error:

```
An error occurred during opening the file. This may be caused by incorrect file contents.
The error details are:
SAXException: [word/header1.xml line 1]: Attribute xmlns:w16se redefined

Proceeding with import may cause data loss or corruption, and application may become unstable or crash.

Do you want to ignore the error and attempt to continue loading the file?
```
When I ignore the error, Libre Office opens the document, but it contains only the added Paragraph. Content from the template is missing.

Thanks for your help and the good work 👏

**Comment by dolanmiu** [comment]
I wasn't the one who created the document template feature actually, so I would need to spend some time learning about it before doing any work on it

Thanks for raising!

**Comment by moritz-tr** [comment]
Maybe @amitm02 has some insights he can share with us?

**Comment by amitm02** [comment]
On first sight, Unfortunately no. It has been a long time.
The only insight I can share is that the way I used to address those bugs is to unzip the output document, look into the xml files, see what is wrong, and try to go back to the code and figure out which component is responsible to that part of the XML.
In your case it should be relatively easy as you know what to look for in the xml files: "xmlns:w16se".

**Comment by moritz-tr** [comment]
Thanks @amitm02 for your hint. I will make a PR for the fix when GitHub let me. The Problem was that we add `HeaderAttributes` from the template as well as the default ones which causes the redefinement error.

**Comment by efx** [comment]
I am unable to generate a word document from a template using https://github.com/dolanmiu/docx/blob/master/demo/30-template-document.ts.

**Comment by moritz-tr** [comment]
It is hard to help without more information about the error you are facing.
