### ISSUE TITLE
maxRightTabStop() does not work with custom margin

### ISSUE THREAD

**Issue by ghost** [dolanmiu/docx#364]
I customized the document left and right margins like this:

```
const doc = new Document(
     { creator: 'test' },
     { top: 10, bottom: 10, left: 1000, right: 1000 }
)
```

With any custom left and right margin, however, maxRightTabStop() **no longer aligns to the right of the page**. Instead, there is some spacing between the right edge of this paragraph and the right edge of a paragraph without maxRightTabStop()

See below: the dates are a rendered within a paragraph with maxRightTabStop()

<img width="283" alt="Screen Shot 2019-07-23 at 1 22 46 PM" src="https://user-images.githubusercontent.com/10790628/61733103-10f3a200-ad4d-11e9-8159-d4b17a380cc8.png">

**Comment by alexcasella** [comment]
@dolanmiu please advise

**Comment by dolanmiu** [comment]
It's because max tab stop sets a hard absolute value rather than a relative one depending on the margin
