### ISSUE TITLE
Publishing release candidates with "latest" tag

### ISSUE THREAD

**Issue by lennym** [dolanmiu/docx#374]
Just a note to let you know that by publishing "rc" releases as "latest" you've been shipping breaking changes to users.

Between `rc4` and `rc5` there were some pretty big breaking changes, which were silently installed by npm because both releases were tagged as "latest".

For future reference I'd make sure you tag "rc" releases with a tag other than `latest`, so that users can opt in to pre-release versions (and then you can ship all the breaking changes you like 😉).

If this was a mistake (which I'm guessing it probably was - npm auto-publishing as latest even when it's an rc version is pretty nasty) then you can re-publish 4.7.1 as 4.7.2 and then that will be fetched as the latest tag.

Thanks for the work on the module generally. 💯 👍

**Comment by dolanmiu** [comment]
Good point

It is automatically `latest` because `npm publish` regardless of anything automatically sets it to `latest`

This module is almost close to a `5.0.0` release now though
