### ISSUE TITLE
Spacing on bulleted paragraph - v.5.0.0-rc5

### ISSUE THREAD

**Issue by pherrera91** [dolanmiu/docx#378]
Hi @dolanmiu ,

I want to apply some spacing to the lines of a bulleted paragraph.

This is my style

```
doc.Styles.createParagraphStyle('space-1.5', 'Space - 1.5')
    .basedOn('Normal')
    .spacing({ line: 360, lineRule: "auto", before: 0, after: 0});
```

This works for me

```
new Paragraph({
    text: 'Some large text',
    alignment: AlignmentType.LEFT,
    text: situation,
    style: 'space-1.5',
}));
```

When I add the bullet configuration, It seems the style is no longer respected.

```
new Paragraph({
    text: 'Some large text',
    alignment: AlignmentType.LEFT,
    text: situation,
    style: 'space-1.5',
    bullet: {
        level: 0,
    },
}));
```

So, the bullet is added, but I think the style is lost.

Is this not supported?

**Comment by rickgrana** [comment]
I think that is because when you add the bullets, the ListParagraph is applied.

SO, one workaround is to style the ListParagraph and make your style basedOn the ListParagraph.

**Comment by dolanmiu** [comment]
You can do it by declaring a new bullet numbering system, shown here:

https://github.com/dolanmiu/docx/blob/master/demo/3-numbering-and-bullet-points.ts
