### ISSUE TITLE
toBuffer does not return a Buffer

### ISSUE THREAD

**Issue by jwerre** [dolanmiu/docx#379]
Not sure why but `Packer.toBuffer()` does not produce a Buffer.

```js
buffer = await Packer.toBuffer(doc);
console.log(buffer instanceof Buffer); // false
console.log(Buffer.from(buffer) instanceof Buffer); // true
```

**Comment by dolanmiu** [comment]
What environment is this in? Node or in the browser?

Under the hood, it uses JSZip ;https://github.com/dolanmiu/docx/blob/master/src/export/packer/packer.ts#L7-L11

And it indeed does return `Buffer`, but I think it needs node?

https://stuk.github.io/jszip/documentation/api_jszip/generate_async.html

**Comment by jwerre** [comment]
Yes, sorry. I'm using Node v10.16.0

**Comment by dolanmiu** [comment]
Can you try this:

https://www.w3schools.com/nodejs/met_buffer_isbuffer.asp

**Comment by jwerre** [comment]
Yes, that's pretty much the same thing as using in `instanceof`: https://github.com/nodejs/node/blob/v10.16.2/lib/buffer.js#L429

**Comment by dolanmiu** [comment]
Oh yeah, I am getting the same thing too, I don't know why that is

**Comment by dolanmiu** [comment]
Really weird

![image](https://user-images.githubusercontent.com/2917613/63066672-30708b80-bf03-11e9-9525-19bf3fb5cca6.png)

**Comment by jwerre** [comment]
Yes, I say that. Wrapping it in a Buffer seems to work. Couldn't you just add something like:

```js
if( typeof Buffer !== 'undefined'){
    zipData = Buffer(zipData)
}
```

**Comment by dolanmiu** [comment]
No because it would break the Browser compatability of it

Browsers dont have the concept of Buffer

I'd say wrap that in your app
