### ISSUE TITLE
Landscape

### ISSUE THREAD

**Issue by KennyBarraud** [dolanmiu/docx#38]
Hi again !
Is it possible to put a page in landscape orientation ?
Thanks !

**Comment by dolanmiu** [comment]
Landscape is currently not possible, didn't really cross my mind for landscape!

It is an easy addition though

**Comment by dolanmiu** [comment]
Landscape mode will be released in `4.0.0`!

How to use is here:

https://github.com/dolanmiu/docx/blob/master/demo/demo7.js
