### ISSUE TITLE
doesn't create filled TOC in downloaded docx

### ISSUE THREAD

**Issue by lacera** [dolanmiu/docx#380]
Hi! Help, please. This simple example (copied from codepen.io HTML block) doesn't create filled TOC in downloaded docx and i have no ideas, why :(
`<!DOCTYPE html>
<html>

<head>
    <script src="https://unpkg.com/docx@5.0.0-rc5/build/index.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.8/FileSaver.js"></script>
</head>

<body>
    <button type="button" onclick="generate()">Click to generate document</button>

    <script>
        function generate() {
            const doc = new Document();
          
            doc.addSection({
                children: [
                      new TableOfContents("Summary", {
                           hyperlink: true,
                           headingStyleRange: "1-5",
                     }),
                     new Paragraph({
                          text: "Header #1",
                          heading: HeadingLevel.HEADING_1,
                          pageBreakBefore: true,
                     }),
                ]
            });
            Packer.toBlob(doc).then(blob => {
                console.log(blob);
                saveAs(blob, "example.docx");
                console.log("Document created successfully");
            });
        }
    </script>
</body>
</html>`

**Comment by dolanmiu** [comment]
Ah it does work for me, but you need to press that button:

![image](https://user-images.githubusercontent.com/2917613/63063727-ac63d700-bef5-11e9-9945-fe3623207c6f.png)

This is a known issue, but I'm not sure how to fix it.

Then it displays like normal:

![image](https://user-images.githubusercontent.com/2917613/63063745-bbe32000-bef5-11e9-87ae-60b47d4674a1.png)

Check out demo 28: https://github.com/dolanmiu/docx/blob/master/demo/28-table-of-contents.ts

**Comment by lacera** [comment]
heh, i have two ways: open it in *nix LibreOffice (no result with broken TOC but other docx with filled TOC open with filled TOC) and open it in docs.google.com (no result too... but there i may update TOC and see it but this it dances with tambourine :) )

**Comment by dolanmiu** [comment]
If you can find a way to fix it, please make a PR!

**Comment by vijayarun** [comment]
Any update on this enhancement

**Comment by Veeresh870** [comment]
Any new updates for this issue...???

**Comment by kalda341** [comment]
I would love to have this fixed also, but I suspect it is very hard.

**Comment by dolanmiu** [comment]
I do not think it is possible actually, and thats by design. OOXML does not know about the concept of pages.
I have wrote an explanation on the related issue.

### Related issue:

https://github.com/dolanmiu/docx/issues/1212
