### ISSUE TITLE
How to insert images in document when running in browser and not using nodejs

### ISSUE THREAD

**Issue by tommykjensen** [dolanmiu/docx#384]
I have looked at all the previous questions about this and did not find a solution.

Can somebody give me an example of using an image from a url and insert it in a document. Without using nodejs.

**Comment by dolanmiu** [comment]
Turn the image into base 64, then add it in:

https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding
