### ISSUE TITLE
Extra line before paragraph

### ISSUE THREAD

**Issue by jamesmontalvo3** [dolanmiu/docx#388]
Thank you for a great module. I'm really looking forward to using it.

Using docx version `5.0.0-rc5` I'm getting an extra line prior to (or within) each paragraph. For example:

![image](https://user-images.githubusercontent.com/716482/63719450-8baf5180-c812-11e9-96da-b65def9a4a4f.png)

The above file was generated using the code below, which is a JS version of [demo/1-basic.ts](https://github.com/dolanmiu/docx/blob/d8b60d82f33b64b2c3223ee670713fe4f7d7517f/demo/1-basic.ts).

```js
var fs = require('fs')
var docx = require('docx');

const doc = new docx.Document();

doc.addSection({
	children: [
		new docx.Paragraph({
			children: [
				new docx.TextRun("Hello World"),
				new docx.TextRun({
					text: "Foo Bar",
					bold: true
				}),
				new docx.TextRun({
					text: "Github is the best",
					bold: true
				})
			]
		})
	],
});

docx.Packer.toBuffer(doc).then((buffer) => {
	fs.writeFileSync("docx-simple.docx", buffer);
});
```

**Comment by bokuweb** [comment]
I run into same problem.

**Comment by jamesmontalvo3** [comment]
Fixed by #391.

**Comment by jamesmontalvo3** [comment]
Reopening due to #391 causing bigger issues and needing to be reverted. See #418.

**Comment by dieterc** [comment]
Is there a work around?
I have the same issue and this is a bit annoying.

**Comment by dolanmiu** [comment]
I think this is no longer an issue, I just tested this now and it doesn't seem to happen anymore

Closing.

Can re-open if its still persistant.
