### ISSUE TITLE
Custom bullet points - 5.0.0-rc5

### ISSUE THREAD

**Issue by dieterc** [dolanmiu/docx#393]
Thanks for creating this package!
But I'm trying to use different bullet points. They look too big for me so I created a new numbering with a different icon but I cannot select this new numbering because it's always using the id  = 1 :https://github.com/dolanmiu/docx/blob/5.0.0-rc5/src/file/paragraph/paragraph.ts#L158. 

If you choose numbering you can in fact select the id:
https://github.com/dolanmiu/docx/blob/5.0.0-rc5/src/file/paragraph/paragraph.ts#L165

Is my reasoning correct or do you have another way of solving this?

**Comment by dolanmiu** [comment]
Good point actually, I'll look to changing this to see what happens

**Comment by ElDubsNZ** [comment]
@dieterc 

Could you share the new numbering you created? I've been trying to set up the default Word bullet points, which are smaller.

**Comment by dolanmiu** [comment]
It is possible, I have created a demo showcasing it:

https://github.com/dolanmiu/docx/blob/master/demo/3-numbering-and-bullet-points.ts
