### ISSUE TITLE
(intermediate value).font is not a function 

### ISSUE THREAD

**Issue by Maestro5563** [dolanmiu/docx#395]
Hello, I've been trying to set a different font to a TextRun. 
Here is the code:
`
import { Document, Paragraph, Packer, TextRun} from "docx";
`
`
let title = new TextRun("xxxxxx").font("Calibri");
`
And the browswer console says:
TypeError: (intermediate value).font is not a function

So how do I set font correctly? Apparently the method listed in [https://docx.js.org/#/usage/styling-with-js](url) didn't work for me. 

Thanks!

p.s. I am using docx5.0.0 rc-5 in Vue.

**Comment by zhenggaowei** [comment]
I have the same problem, and the same is true when I create tables. Have you solved it?

**Comment by dolanmiu** [comment]
The examples have now changed:

https://github.com/dolanmiu/docx/blob/master/demo/2-declaritive-styles.ts#L85-L92
