### ISSUE TITLE
tabStops seem to have moved from Paragraph in 5.0.0 versions

### ISSUE THREAD

**Issue by htkibar** [dolanmiu/docx#397]
While the .tab() and stuff like that work in 4.7.1, it does not seem to work in 5.0.0-rc5. Is the documentation just stale and there is a way I am missing or did the functionality move away?

I am talking about the following type of code;

`
    const paragraph = new Paragraph();
    paragraph.maxRightTabStop();
    paragraph.leftTabStop(1000);
    const text = new TextRun('Second tab stop here I come!').tab().tab();
    paragraph.addRun(text);
`

Even creating a Paragraph without any arguments is no longer possible in 5.0.0-rc5. (Which is what gets installed by default when you do `yarn add docx`

**Comment by jamesmontalvo3** [comment]
He seems to be aiming for a declarative style in 5.x. See release notes for [5.0.0-rc5](https://github.com/dolanmiu/docx/releases/tag/5.0.0-rc5).
