### ISSUE TITLE
Adding check boxes to the document, is it possible?

### ISSUE THREAD

**Issue by tukantje** [dolanmiu/docx#398]
In the documentation I could not find anything about the checkboxes. Is it a part of the library, is it planned? Or is it something that can be added by someone else?

Thanks!

**Comment by jamesmontalvo3** [comment]
Checkbox characters, or an interactive check-able checkbox?

**Comment by htkibar** [comment]
@jamesmontalvo3 Interactive check-able checkboxes. Specifically `w:checkBox`.

**Comment by htkibar** [comment]
I have done the required research into how to add this to the library. However I have a question;

The definition of the checkbox is not just one element. This requires me to create a Run with a Bookmark that has 2 runs inside as 3 same level elements. As such, I can't contain it as just one Run. What would be the preferable way to approach this for the library?

**Comment by chf12345678** [comment]
@htkibar 具体怎么使用？

**Comment by htkibar** [comment]
@dolanmiu If you have time, could you please help me about the questions? I might be able to send this feature as a PR.

@chf12345678 你什么意思？

**Comment by dolanmiu** [comment]
> The definition of the checkbox is not just one element. This requires me to create a Run with a Bookmark that has 2 runs inside as 3 same level elements. As such, I can't contain it as just one Run. What would be the preferable way to approach this for the library?

Create a run of a certain type. This library has `TextRun` and `PictureRun` already, I see why not a `CheckboxRun` could be implemented

> This also requires me to update the BookmarkStart and give it the ability to have something inside there. Is this alright?

Ok sure, add it in, then I will review, and alter it if need be.

**Comment by skylerp208** [comment]
Was this ever added?

**Comment by veeresh745-sys** [comment]
Is this added??

**Comment by dolanmiu** [comment]
Not yet no

**Comment by rzempo** [comment]
Hi @dolanmiu, are checkboxes something to be added in the near future or is it still not in the foreseeable future?

**Comment by jiazez** [comment]
text   ☑

**Comment by dolanmiu** [comment]
It is possible yes, a PR has been raised and merged in with the feature:

https://github.com/dolanmiu/docx/pull/2189

Thanks!
