### ISSUE TITLE
Insert image does not work online

### ISSUE THREAD

**Issue by Voileexperiments** [dolanmiu/docx#399]
In the latest version,

```
doc.createImage(imgBase64String, img.naturalWidth, img.naturalHeight);
```

works but

```
var image = Media.addImage(doc, imgBase64String, img.naturalWidth, img.naturalHeight);
doc.addSection({
    children: [
        new Paragraph({
            children: [image],
        }),
    ],
```

as in the examples given in the docs never works. The generated word document cannot be opened.

**Comment by dolanmiu** [comment]
Yes, the documentation is outdated

It's best to look at the ~50 examples in here: https://github.com/dolanmiu/docx/tree/master/demo
