### ISSUE TITLE
Online version pollutes global namespace and breaks other scripts

### ISSUE THREAD

**Issue by Voileexperiments** [dolanmiu/docx#400]
The docx JS file to be embedded in HTML documents dumps everything in the global scope and breaks other scripts as a result. There are at least several other JS libraries that break when docx is also included, mostly related to displaying images.

Why are the exports in the JS file in global scope when they're under `docx` object in the Node version?

**Comment by dolanmiu** [comment]
Found this:

https://webpack.js.org/configuration/output/#outputlibrary

I'll make a PR soon
