### ISSUE TITLE
new Pragraph() => TypeError: options is undefined

### ISSUE THREAD

**Issue by michaelzangl** [dolanmiu/docx#403]
Error when using the `new Paragraph()` constructor without arguments. As in https://docx.js.org/#/usage/tab-stops?id=example

The error occurs in 5.0.0-rc5 but not in 5.0.0-rc4

It seems to be caused by this line in the constructor of the paragraph:
```
        this.properties = new properties_1.ParagraphProperties({
            border: options.border,
        });
```

Workaround: use `new Paragraph({})`

**Comment by dolanmiu** [comment]
Please check the demos and examples: https://github.com/dolanmiu/docx/tree/master/demo

The API is undergoing a change, the documentation is being updated shortly!
