### ISSUE TITLE
Unable to build my app after imported docx

### ISSUE THREAD

**Issue by weiye5188** [dolanmiu/docx#404]
I cannot build my app after imported docx, it appears the issue is due to docx/index.js that contains modern Javascript syntax instead of ES5's. For example, line 3037 has class/extends which is not understood by npm build script

 class Bold extends xml_components_1.XmlComponent 

Is there any way docx can provide an ES5 syntax index.js?

**Comment by weiye5188** [comment]
I was trying to build docx and got the following error
----------------------------------------------------
λ npm run build

> docx@5.0.0-rc5 build C:\testapp\node_modules\docx
> npm run webpack && npm run fix-types


> docx@5.0.0-rc5 webpack C:\testapp\node_modules\docx
> rimraf ./build && webpack

No configuration file found and no output filename configured via CLI option.
A configuration file could be named 'webpack.config.js' in the current directory.
Use --help to display the CLI options.
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! docx@5.0.0-rc5 webpack: `rimraf ./build && webpack`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the docx@5.0.0-rc5 webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by dolanmiu** [comment]
There are PRs for this, but it's not complete:

https://github.com/dolanmiu/docx/pull/164

**Comment by dolanmiu** [comment]
Closing this as there are other issues talking about this
