### ISSUE TITLE
why are lockfiles being ignored?

### ISSUE THREAD

**Issue by efx** [dolanmiu/docx#405]
Do you know why a lockfile is not being used? https://github.com/dolanmiu/docx/blob/master/.gitignore#L54-L56
Using npm's `package-lock.json` or yarn's `yarn.lock` are important to avoid certain sub dependency bugs. I propose we decide on which format and version them.

I would suggest using `yarn` as I have found the lockfile behavior more consistent and easier 
to support for developers.

## related PRs
#156

**Comment by efx** [comment]
A benefit to using yarn will be easier documentation for running commands..

> To run a demo, pass the name of the file to `ts-node`. You can do this easily by running:
```shell
yarn ts-node demo/30-template-document.ts
```

**Comment by dolanmiu** [comment]
I remember a few years back when package-lock was introduced I had so many problems with it, and constantly had to delete package-lock, it also affected CI builds, so I deleted it.

Things are probably different now

Also, I prefer NPM over Yarn: https://iamturns.com/yarn-vs-npm-2018/

**Comment by efx** [comment]
> I remember a few years back when package-lock was introduced I had so many problems with it, and constantly had to delete package-lock, it also affected CI builds, so I deleted it.


I have had the same experience in other projects.

> It’s impossible to keep up with JavaScript.

Amen. 

I'm aware of the differences between the tools but find  the author is making a more social argument than technical one. ([volta](https://volta.sh/) also helps mitigate installer incompatibilities. I think the same problem exists for npm too).

I'll defer to your decision here since this is your project @dolanmiu! 
I would advocate we restore the `package-lock.json` because the lock resolution algorithm implementation has  improved since npm v5 and above.
