### ISSUE TITLE
Does library work with JS or do you have to use TS +  index.d.ts file 

### ISSUE THREAD

**Issue by mathoi** [dolanmiu/docx#406]
Hi,
I was wondering if you can use this library wiht JavaScript or do you have to use TypeScript.

I'm using Kotlin and if there is a index.d.ts file somewhere (I have tried the DefinitelyTyped repo) then that would be quite useful for defining the Kolin external declarations.

One of the reasons that I'm wondering whether the library works with JavaScript or not is for example:
to get the TableCellBorders of af TableCell cell, the examples and documentation seems to suggest, that you simply write

cell.Borders

This gives me "undefined", whereas writing

cell.properties.Borders

works.

**Comment by dolanmiu** [comment]
yeah you can use Javascript, you don't nessesarily need the index.d.ts

Yes, the documentation isn't updated, I have been updating it slowly

**Comment by zhenggaowei** [comment]
@dolanmiu 
"docx": "^5.0.0-rc5”和文档地址(https://docx.js.org/#/usage/tables)不相符，其中const table = new Table(4, 4);doc.add(table); 实例doc并没有add方法，
并且在样式添加中，链式调用亦是如此，例：new docx.TextRun("Foo Bar").center() 或者 new Paragraph("Foo Bar").center()等，报错提示“(intermediate value).center() is not a function”
