### ISSUE TITLE
Use vue, javascript, call method according to document, but report error! For example, create a new table. add () and style. center ()

### ISSUE THREAD

**Issue by zhenggaowei** [dolanmiu/docx#408]
In today's documents, docx instances do not have. add () methods, nor do they chain-call style methods, such as. center (),. Font (), links (https://github.com/dolanmiu/docx/wiki/Styling-with-JS), which will all report errors. Does the document and package not correspond, or is there a problem with the way I use it?

**Comment by dbalgley** [comment]
Hello,

Apparently the examples have changed and certain styling settings are now done as part of a key-value pair within the paragraph/run.  See: https://github.com/dolanmiu/docx/blob/master/demo/2-declaritive-styles.ts#L85-L92

`new Paragraph({}).addRun(
            new TextRun({
                text: "Some monospaced content",
                font: {
                    name: "Monospace",
                },
            }),
        ),`

Hope this helps, I can't get anything working with this package but noticed this while I was doing a dive in the closed tickets. Good luck!

**Comment by dolanmiu** [comment]
Yes, this library is moving more to a declarative approach, as there are some problems with method chaining:

when you do

```ts
paragraph.addRun().center()
```

it's hard to tell if its centering the run or the paragraph, this is why I decided to move to a more clearer declaritive approach

https://softwareengineering.stackexchange.com/questions/80244/are-there-any-actual-drawbacks-to-self-referential-method-chaining

**Comment by dbalgley** [comment]
Good stuff. Btw-I was able to get some really excellent .docx out of your package, so sorry if I sounded exasperated before...I was having troubles that are now solved! Thanks for your hard work.

**Comment by dolanmiu** [comment]
Thanks for all your support, means a lot
