### ISSUE TITLE
Add rows to existing table

### ISSUE THREAD

**Issue by jamesmontalvo3** [dolanmiu/docx#410]
It seems like it should be pretty straightforward to add table rows to an existing table. The following two snippets seem to work for me. @dolanmiu would this be something you'd be interested in including if I submit a PR?

Insert a row into the middle of the table:
```js
const newRow = new docx.TableRow(
	Array(numColumns).fill(new docx.TableCell())
);
table.rows.splice(rowIndex, 0, newRow);
table.root.splice(rowIndex, 0, newRow);
```

Insert at the end:
```js
const newRow = new docx.TableRow(
	Array(numColumns).fill(new docx.TableCell())
);
table.rows.push(newRow);
table.root.push(newRow);
```

**Comment by dolanmiu** [comment]
Hey

If you are referring to your PR:

https://github.com/dolanmiu/docx/pull/409

I'll need to check it if it interfeers with this PR:

https://github.com/dolanmiu/docx/pull/407

**Comment by jamesmontalvo3** [comment]
I wasn't really referring to the PR. I started looking into adding rows to a table and noticed that a simplification could be made to the existing code, so I submitted the PR.

**Comment by dolanmiu** [comment]
Closed because tables are now immutable and declarative. Adding rows (mutation) to an existing table is no longer allowed
