### ISSUE TITLE
Unable to set cell's width

### ISSUE THREAD

**Issue by exsesx** [dolanmiu/docx#411]
There's no way to set the width of the `table-cell`. 

The `table-cell-properties` have method `setWidth(width: string | number, type?: WidthType): TableCellProperties` But maybe you forgot to add this to the `table-cell` constructor?

Docx version: **5.0.0-rc6**

**Comment by jamesmontalvo3** [comment]
@dolanmiu merged #407 yesterday. This part of the change may be of use to you:

https://github.com/dolanmiu/docx/blob/b43ed12c8476e34cc56e33f097d85515405332ae/demo/32-merge-and-shade-table-cells.ts#L61-L65

**Comment by exsesx** [comment]
@jamesmontalvo3 I can set column widths as percentage values in MS Word. How can I achieve the same after these changes? 
It's confusing because type definition of `columnWidths` property is `number[]`.

**Comment by dolanmiu** [comment]
I think column widths don't have percentage:

http://officeopenxml.com/WPtableGrid.php

But table cells can use percentage

**Comment by exsesx** [comment]
Exactly! But we’re not able to set cell width, please tell me that I’m wrong :)

**Comment by olegdunkan** [comment]
> @dolanmiu merged #407 yesterday. This part of the change may be of use to you:
> 
> https://github.com/dolanmiu/docx/blob/b43ed12c8476e34cc56e33f097d85515405332ae/demo/32-merge-and-shade-table-cells.ts#L61-L65

In my case it dosn't work, because of 

> It can be overridden when the table is displayed by the table layout algorithm or by the preferred widths of particular cells that are a part of the column.
http://officeopenxml.com/WPtableGrid.php

**Comment by dolanmiu** [comment]
Some of the documentation is still being updated, so it may be out of date

**Comment by Rogers-Development-Services** [comment]
I'm having an issue where I've set my table to be a preferred column width of 100% and within that, each of my table column cells have a set width in DXA. This setup works great until I add my text to one of my columns table cells dynamically because the string length (151 characters) overrides the width in DXA. Is there a way to ensure the table column cell width is fixed?

`new Table({
    width: {
      size: 100,
      type: WidthType.PERCENT
    },
    rows: [
      new TableRow({
        tableHeader: true,
        children: [
          new TableCell({
            width: {
              size: 1584,
              type: WidthType.DXA,
            },
            shading: {
              fill: TABLE_HEADER_FILL,
            },
            verticalAlign: 'center',
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({
                    text: 'Test',
                    bold: true,
                  }),
                ],
              }),
            ],
          }),
          new TableCell({
            width: {
              size: 2160,
              type: WidthType.DXA,
            },
            shading: {
              fill: TABLE_HEADER_FILL,
            },
            verticalAlign: 'center',
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({
                    text: 'Scenario',
                    bold: true,
                  }),
                ],
              }),
            ],
          }),
          new TableCell({
            width: {
              size: 5688,
              type: WidthType.DXA,
            },
            shading: {
              fill: TABLE_HEADER_FILL,
            },
            verticalAlign: 'center',
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({
                    text: 'Input',
                    bold: true,
                  }),
                ],
              }),
            ],
          }),
          new TableCell({
            width: {
              size: 5688,
              type: WidthType.DXA,
            },
            shading: {
              fill: TABLE_HEADER_FILL,
            },
            verticalAlign: 'center',
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({
                    text: 'Output',
                    bold: true,
                  }),
                ],
              }),
            ],
          }),
        ],
      }),
    ],
  })`

**Comment by rpratap2102** [comment]
Hey,
@Rogers-Development-Services I was facing a similar issue recently,
not sure this will help you with this late posting here for someone like me

It worked by using a Fixed layout type like this 
`    const table = new Table({
        width: {
            size: 100,
            type: WidthType.PERCENTAGE,
        },
        layout:TableLayoutType.FIXED,
        rows: rows
    });
`

**Comment by 1Tsw0rd** [comment]
@rpratap2102 
Thank U Bro~~
