### ISSUE TITLE
Multiple tabstops of same type in a paragraph

### ISSUE THREAD

**Issue by mathoi** [dolanmiu/docx#417]
In 4.71 it was possible to have several tabstops of the same kind in a single Paragraph e.g.

```ts
const paragraph = new docx.Paragraph();
paragraph.leftTabStop(1000);
paragraph.leftTabStop(2000);
```

Now in 5.0.0-rc6 the tabStop part of the IParagraphOptions is as follows:

```ts
 readonly tabStop?: {
        readonly left?: ITabStopOptions;
        readonly right?: ITabStopOptions;
        readonly maxRight?: {
            readonly leader?: LeaderType;
        };
        readonly center?: ITabStopOptions;
    };
```

hence it seems, that one can only specify
- at most 1 LeftTabStop
- at most 1 RightTabStop
- at most 1 MaxRightTabStop
- and at most 1 CenterTabStop

Is this correct or is there a way to specify several tabStops of the same kind for a paragraph?

**Comment by dolanmiu** [comment]
Will fix

Thanks for finding this
