### ISSUE TITLE
section columns do not work in 5.0.0-rc6

### ISSUE THREAD

**Issue by pecirep** [dolanmiu/docx#420]
I adapted [demo/44-multiple-columns.ts](https://github.com/dolanmiu/docx/blob/master/demo/44-multiple-columns.ts) for use in a browser environment, but the saved document does not have any columns.

This is the full HTML (appended .txt because github doesn't allow html files):
[docx-test-columns.html.txt](https://github.com/dolanmiu/docx/files/3691166/docx-test-columns.html.txt)

**Comment by jamesmontalvo3** [comment]
This is probably due to #418 and will hopefully be fixed when #419 is merged.

**Comment by dolanmiu** [comment]
#419 merged

fixed
