### ISSUE TITLE
image size

### ISSUE THREAD

**Issue by alexaalex70** [dolanmiu/docx#422]
Hi,

I have this line of code where height/width are the real values of the picture:

> mediaImage = Media.addImage(document, image.downloadResult, image.width, image.height);

Is there any way to make word work like when inserting a picture from it? Like auto-resize of the picture to look nice. 

Thank you

**Comment by dolanmiu** [comment]
Nope, no auto size

explained here: https://github.com/dolanmiu/docx/issues/283
