### ISSUE TITLE
Overlapping Tables for Floating Tables

### ISSUE THREAD

**Issue by seiya-git** [dolanmiu/docx#425]
http://officeopenxml.com/WPfloatingTables.php#overlappingTables

**Comment by dolanmiu** [comment]
Could you elaborate?

**Comment by seiya-git** [comment]
For now floating table imposible to set <w:tblOverlap> value, if table was created with float option.

**Comment by dolanmiu** [comment]
https://github.com/dolanmiu/docx/pull/460 will fix this
