### ISSUE TITLE
Empty paragraph at the start of document

### ISSUE THREAD

**Issue by olegdunkan** [dolanmiu/docx#433]
When we crate simple document with only one paragraph:

```
doc.addSection({
    children: [
        new Paragraph({
            children: [new TextRun("Hello World")],
        }),
    ],
}); 
```
we see in resulting document before text "Hello World" empty line with line break
I exctracted from .docx file the document.xml and found out that it contains 

```
<w:body>
    <w:p/>
   <w:p>
      <w:r>
          <w:t xml:space="preserve">Hello world</w:t>
       </w:r>
    </w:p>
...
```
you can see <w:p/> is empty paragraph.

I have checked it out in code and I see 
`const currentSection = this.sections.pop() as SectionProperties;`

First call of this metod will generate empty <p/> element in document.xml.
https://github.com/dolanmiu/docx/blob/75c3c2f98500a891691047ae683d2fb15153ee59/src/file/document/body/body.ts#L21

Is it intened behaviour or bug?

**Comment by jamesmontalvo3** [comment]
Related to #388 though it only appears to be happening at the beginning of the document now, not on every paragraph. It’s a bug.
