### ISSUE TITLE
how to add horizontal line?

### ISSUE THREAD

**Issue by cool-firer** [dolanmiu/docx#437]
is there a way to add horizontal line, cant find api related to it.

**Comment by rajavijayavendan** [comment]
@cool-firer Any workaround for drawing shapes?

**Comment by cool-firer** [comment]
@rajavijayavendan no solution.

**Comment by nasriime** [comment]
try this works in version 5.0.0-rc5    

new Paragraph({
                    text: " ",
                    thematicBreak: true,
                }),

**Comment by dolanmiu** [comment]
This is how you do it with `docx`. It add's a border to a paragraph

https://github.com/dolanmiu/docx/blob/master/demo/26-paragraph-borders.ts

This is how it is done officially with Microsoft Word too:

Word generated code:

```xml
<p w:rsidR="00F371A5" w:rsidRDefault="00F371A5">
	<pPr>
		<pBdr>
			<bottom w:val="single" w:sz="12" w:space="1" w:color="auto" />
		</pBdr>
	</pPr>
	<bookmarkStart w:id="0" w:name="_GoBack" />
	<bookmarkEnd w:id="0" />
</p>
```
