### ISSUE TITLE
Headers and footers, how to use first and even?

### ISSUE THREAD

**Issue by mathoi** [dolanmiu/docx#439]
Hi,
In the document I'm generating, I would like to have a different header on the first page of each section, hence for the ISectionOptions, i define a default and a first header 

```ts
file.addSection({
    headers: {
        default: new Header({ 
            children: [  new Paragraph({
                      children: [new TextRun("Default")],
                   }),],
        }),
        first: new Header({
            children: [  new Paragraph({
                        children: [new TextRun("First")],
                  }),],
        }),
    },
    children: [
        new Paragraph({
            children: [new TextRun("Hello World")],
        }),
    ],
});
```

but all the pages (including the first page) have the default header. 

In the generated document, if I check the box "Different First Page" under the "Header & Footer Tools", then the first correctly shows on the first page and all other pages correctly uses the default header.

The question is thus: How do i check the "Different First Page" box when generating the document?

By the way: Thanks a lot for all the work, you have put into this library and thanks for the fast responses to my prior questions in other threads.

**Comment by kwyz** [comment]
Any updates ?

**Comment by marlonwanger** [comment]
Any updates ?

**Comment by BrentFarese** [comment]
I am experiencing this same issue.  I can generate the different first-page footer, but it's not "checked" when the doc is generated and is therefore hidden.

**Comment by dolanmiu** [comment]
yeah if you can amend the documentation, that should suffice

thanks

**Comment by dolanmiu** [comment]
This will be fixed in: https://github.com/dolanmiu/docx/pull/828
