### ISSUE TITLE
By adding a hyperlink with doc.createHyperlink document won't open

### ISSUE THREAD

**Issue by ramonmata** [dolanmiu/docx#440]
Hello,

If I run the code below or even with **demo/35-hyperlinks.ts**, the result word document can not be opened by word, resulting in a message saying:

> Word found unreadable content in links. Do you want to recover the contents of this document? If you trust the source of this document, click Yes.

I have manage to fix it by updating the logic in [relationships.ts](https://github.com/ramonmata/docx/blob/104c4c4deb84e1a5deb47ac7fc4dc156632f4cc6/src/file/relationships/relationships.ts#L27) which at this time seems more like a hack.

**Sample program to reproduce error**
```
import * as fs from "fs";
import { Document, Paragraph, TextRun, Packer} from "./build";


const doc = new Document();

doc.addSection({
    properties: {},
    children: [
        new Paragraph({
            children: [
                new TextRun('Documentation URL for '),
                doc.createHyperlink('https://docx.js.org', 'DOCX.js')
            ]
        })
    ]
});

Packer.toBuffer(doc).then((buffer) => {
    fs.writeFileSync("links.docx", buffer);
});
```

**Comment by dolanmiu** [comment]
Fixed with 448
