### ISSUE TITLE
Unable to set the width of a TableCell

### ISSUE THREAD

**Issue by iklemm** [dolanmiu/docx#441]
documentation says:

`const cell = new TableCell({
    ...,
    width: {
        size: number,
        type: WidthType,
    },
});`

If i do so, it has no effect on cell width. I tried different types and values for size. cell width seems to me quite irregular. I generate a bunch of tables with the same width values but each table has others width and i even don't see any systematic behavour.

example of my code (i would expect a cell width of 50%) :
` new TableCell({
                    children: [new Paragraph(`${text.type} [${text.id}]`)],
                    width: {
                        size: 2500,
                        type: WidthType.PERCENTAGE,
                    }
                }),`

B.t.w. 

I just compared: latest npm package 5.0.0-rc7 does not contain a width property in TableCell what explains why this is not working....

**Comment by iklemm** [comment]
And after i installed dirctly from github Document class accept no argument any more and has no addSection method any more...

Quite confusing.

**Comment by alex-bogomolov** [comment]
The PR that fixes this is already merged, until the next release you can use this:

```
cell.properties.setWidth(50, WidthType.PERCENTAGE)
```

If you use TypeScript, you can use

```
cell["properties"].setWidth(50, WidthType.PERCENTAGE)
```

**Comment by Alex-Sessler** [comment]
> The PR that fixes this is already merged, until the next release you can use this:
> 
> ```
> cell.properties.setWidth(50, WidthType.PERCENTAGE)
> ```
> 
> If you use TypeScript, you can use
> 
> ```
> cell["properties"].setWidth(50, WidthType.PERCENTAGE)
> ```

I can't get this to work in in rc7. Cell width is unchanged.

**Comment by seiya-git** [comment]
@Alex-Sessler, which Office version you use?
