### ISSUE TITLE
How to create rows in cell rowspan of row?

### ISSUE THREAD

**Issue by thuctd** [dolanmiu/docx#453]
I have a table need same below:
1   |   2  |  3    |
________________
     |  4   |   x  |
a   |  5   |   y  |
     |  6   |   z  |
________________
How i can create row "a", I create new Table have 3 rows 4, 5, 6 in cell of rows a but not ok!
Thanks!

**Comment by dolanmiu** [comment]
These demos demonstrate `rowSpan`

https://github.com/dolanmiu/docx/blob/master/demo/32-merge-and-shade-table-cells.ts

https://github.com/dolanmiu/docx/blob/master/demo/41-merge-table-cells-2.ts
