### ISSUE TITLE
Create a blank first page when using the 'heading' option with the 'HeadingLevel.HEADING_1' value

### ISSUE THREAD

**Issue by nlapshin** [dolanmiu/docx#455]
Hello!

Thank you very much for the good library.

I use the library to generate reports. My reports is a simple document with format as can be seen below.

```
TITLE

HEADER
TEXT

HEADER
TEXT
...
```

I create one section

```ts
doc.addSection({
  children: [
      makeHeader(title),
      makeHoursCount(list),
      ...addTickets(doc, list),
  ]
});
```

For header I created paraghraph.

```ts
function makeHeader(title) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_1,
    alignment: AlignmentType.CENTER,
    children: [ makeHeaderTextElement(title) ],
  });
}
```

And, if I use for heading option a value equal to 'HeadingLevel.HEADING_1' as a result, I can get a blank first page, If the section itself is more than one page. I use for heading option a value equal to 'HeadingLevel.HEADING_2' or any valid value, then the result is correct for any section sizes.

I have no idea, what I do wrong and how can I properly debug this problem.

docx version 5.0.0-rc7.
node version 9.4.0.

Thanks in advance for your reply!

**Comment by dolanmiu** [comment]
Can you send me a code sample?

**Comment by dolanmiu** [comment]
Closing due to no follow-up
