### ISSUE TITLE
rowSpan:3 of 2 cells close to each other not working.

### ISSUE THREAD

**Issue by thuctd** [dolanmiu/docx#456]
```ts
table5 = new Table({
    rows: [
        new TableRow({
            children: [
                new TableCell({
                    children: [new Paragraph("0,0")],
                }),
                new TableCell({
                    children: [new Paragraph("0,1")],
                    rowSpan: 3,
                }),
                new TableCell({
                    children: [new Paragraph("0,2")],
                    rowSpan: 3,
                }),
                new TableCell({
                  children: [],
              }),
            ],
        }),
        new TableRow({
            children: [
                new TableCell({
                    children: [],
                }),
                new TableCell({
                  children: [],
                }),
            ],
        }),
        new TableRow({
            children: [
                new TableCell({
                    children: [],
                }),
                new TableCell({
                  children: [],
              }),
            ],
        }),
    ],
    width: {
        size: 100,
        type: WidthType.PERCENTAGE,
    },
});
```

**Comment by codal-sbelim** [comment]
Any update on this?

**Comment by vjancic** [comment]
I encountered the same issue, on v5.0.2, but there's a workaround, and that is to use verticalMerge property (RESTART for row that is the main row, others being merged have CONTINUE):

`table5 = new docx.Table({
                          	rows: [
                            	new docx.TableRow({
                              	children: [
                                	new docx.TableCell({
                                  	children: [new docx.Paragraph("0,0")], 
                                  }),
                                  new docx.TableCell({
                                  	children: [new docx.Paragraph("0,1")],
                                    verticalMerge: docx.VerticalMergeType.RESTART
                                  }),
                                  new docx.TableCell({
                                  	children: [new docx.Paragraph("0,2")],
                                    verticalMerge: docx.VerticalMergeType.RESTART,
                                  }),
                                  new docx.TableCell({
                                  	children: []
                                  }),
                                ]
                              }),
                              new docx.TableRow({
                              	children: [
                                	new docx.TableCell({
                                  	children: []
                              		}),
                                  new docx.TableCell({
                                  	children: [],
                                    verticalMerge: docx.VerticalMergeType.CONTINUE
                                  }),
                                  new docx.TableCell({
                                  	children: [],
                                    verticalMerge: docx.VerticalMergeType.CONTINUE
                              		}),
                                  new docx.TableCell({
                                  	children: []
                                  })
                                ]
                              }),
                              new docx.TableRow({
                              	children: [
                                	new docx.TableCell({
                                  	children: []
                                  }),
                                  new docx.TableCell({
                                  	children: [],
                                    verticalMerge: docx.VerticalMergeType.CONTINUE
                                  }),
                                  new docx.TableCell({
                                  	children: [],
                                    verticalMerge: docx.VerticalMergeType.CONTINUE
                              		}),
                                  new docx.TableCell({
                                  	children: []
                                  })
                                ]
                              })
                            ],
                          	width: { size: 100, type: docx.WidthType.PERCENTAGE, }
                          })`

**Comment by Volper212** [comment]
Thank you, `verticalMerge` helped me with custom cell widths (you need to set the width in cells of every row when merging).
