### ISSUE TITLE
None of the methods exist when imported in an angular application

### ISSUE THREAD

**Issue by oviquez87** [dolanmiu/docx#457]
I have installed and imported docx and created a new document like so:

`const document = new Document({
            title: 'My Doc',
 });`

if I do something like document.addParagraph() it say the property does not exist. All I can have acces to is document.addSection();

is there a difference on how it works on the latest version. I cant seem to be able to use stuff like .bold() and so on.

**Comment by dolanmiu** [comment]
Yes, `addParagraph` is removed as of version 5

Check out the `/demo` folder for the v5 way of doing things

docs will be updated soon
