### ISSUE TITLE
Missing tab interfaces

### ISSUE THREAD

**Issue by jacwright** [dolanmiu/docx#46]
In the wiki (specifically here https://github.com/dolanmiu/docx/wiki/Tab-Stops) it says there is a `centerTabStop` (spelled wrong in the wiki BTW) and a `rightTabStop` method. These do not exist. They should be added to the `Paragraph` and `ParagraphStyle` classes.

**Comment by dolanmiu** [comment]
Fixed spelling issue

yes you are right, they are missing, will add

**Comment by dolanmiu** [comment]
Done

https://github.com/dolanmiu/docx/commit/da8405b5b9eb18ff9cca45b3a0d3bd350f623d8c

**Comment by dolanmiu** [comment]
https://github.com/dolanmiu/docx/releases/tag/3.0.1

`3.0.1` released
