### ISSUE TITLE
Can i set border in header?

### ISSUE THREAD

**Issue by chareice** [dolanmiu/docx#462]
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/1624785/69730163-8d1a4e00-1162-11ea-9781-c60ee334165b.png">

**Comment by dolanmiu** [comment]
How did you add the border to the header?

I can't see any options to

![image](https://user-images.githubusercontent.com/2917613/69756146-af57a000-1151-11ea-9adf-24284a2bd3d9.png)

**Comment by chareice** [comment]
@dolanmiu you can set header's border in the home panel.
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/1624785/69775386-8972df80-11d3-11ea-803e-9eebc4e7faac.png">

**Comment by dolanmiu** [comment]
The home panel is the header of the Paragraph, not the header

![image](https://user-images.githubusercontent.com/2917613/70103276-960f9180-1632-11ea-8428-176f3869c9ae.png)

You can set the borders of a paragraph already

Closing
