### ISSUE TITLE
feature request about Paragraph indent

### ISSUE THREAD

**Issue by Ken-twenty** [dolanmiu/docx#463]
Thanks for ur awesome **docx** firstly! 

Right indent should be a necessary option of `Paragraph`, but there are only `left`, `hanging`, `firstLine`, `start` and `end` in `IIndentAttributesProperties`, did I miss something?

**docx@5.0.0-rc7**

**Comment by dolanmiu** [comment]
Thanks for your kind words!

I believe `start` is right, but I might be wrong, got to check the OOXML documentation

**Comment by dolanmiu** [comment]
i will make an update to add `right`, but you can use `end`
