### ISSUE TITLE
Wiki Styling page is outdated

### ISSUE THREAD

**Issue by mkloouo** [dolanmiu/docx#464]
# Concern
[Styling page](https://github.com/dolanmiu/docx/wiki/Styling) is outdated.

I was struggling to work with examples provided up until I checked [API](https://docx.js.org/api/)

# Suggestion
Keep the old wiki, but renaming it to `4< version` of the package.
Create new pages with `5>` version of the package usage.

**Comment by jwerre** [comment]
Examples are out of date as well.

**Comment by dolanmiu** [comment]
Documentation is moved from the Wiki to a dedicated website:

https://github.com/dolanmiu/docx/wiki

All examples are up to date now:

https://github.com/dolanmiu/docx/blob/master/demo/2-declaritive-styles.ts
