### ISSUE TITLE
[v5.0.0.-rc7] Page number demo -> "TypeError: Cannot read property 'CURRENT' of undefined"

### ISSUE THREAD

**Issue by acgrama** [dolanmiu/docx#469]
Is it possible that some configuration or such is missing from the page numbers demo?
[https://github.com/dolanmiu/docx/blob/master/demo/14-page-numbers.ts](https://github.com/dolanmiu/docx/blob/master/demo/14-page-numbers.ts)

I am using v5.0.0-rc7 and I am getting this error when running it:
`TypeError: Cannot read property 'CURRENT' of undefined`

EDIT: Same error for demo 39:
[https://github.com/dolanmiu/docx/blob/master/demo/39-page-numbers.ts](https://github.com/dolanmiu/docx/blob/master/demo/39-page-numbers.ts)

I did not only come to complain, however :) Thank you @dolanmiu for this library, and especially for the new rewrite: it makes code much more readable and intuitive.

**Comment by dolanmiu** [comment]
Thanks for your kind words :)

Probably because it isn't exported, i will fix in the next release

**Comment by acgrama** [comment]
Thank you! Just wanted to make sure that I did not miss anything :)

**Comment by wcqrnj** [comment]
> Is it possible that some configuration or such is missing from the page numbers demo?
> https://github.com/dolanmiu/docx/blob/master/demo/14-page-numbers.ts
> 
> I am using v5.0.0-rc7 and I am getting this error when running it:
> `TypeError: Cannot read property 'CURRENT' of undefined`
> 
> EDIT: Same error for demo 39:
> https://github.com/dolanmiu/docx/blob/master/demo/39-page-numbers.ts
> 
> I did not only come to complain, however :) Thank you @dolanmiu for this library, and especially for the new rewrite: it makes code much more readable and intuitive.

Hello @acgrama,

You can use pageNumber() and numberOfTotalPages() functions of TextRun according to the API:
https://docx.js.org/#/usage/page-numbers
![image](https://user-images.githubusercontent.com/48729704/70910758-a7807280-2010-11ea-8ccd-b92d0c43fce0.png)
I created an example in codepen according to demo 39:
https://codepen.io/wcqrnj/pen/abzBNqJ

Unfortunatelly the header of the first page is not different in case of demo 14:
https://codepen.io/wcqrnj/pen/yLyVOEN

BR, He-Wolf

**Comment by acgrama** [comment]
@wcqrnj Thank you so much for the tip, I appreciate it!

**Comment by dolanmiu** [comment]
Demo 14 and 39 are now fixed

Closing
