### ISSUE TITLE
Section breaks

### ISSUE THREAD

**Issue by YacYac** [dolanmiu/docx#47]
Would it be possible to add support for section breaks? 

Thematic breaks allow you to add a break within a page much like a section break, but proper section allows them to be further styled in word within Page Setup.

**Comment by dolanmiu** [comment]
Do you mean a page break? 

so that it forces the text to be on a new page?

**Comment by dolanmiu** [comment]
![image](https://user-images.githubusercontent.com/2917613/31040422-2e2d210c-a57f-11e7-838b-f66613440156.png)

**Comment by dolanmiu** [comment]
This feature is now done:

Check out how to do it here:

https://github.com/dolanmiu/docx/blob/master/demo/demo16.js

The thread is here:

https://github.com/h4buli/docx/pull/10

**Comment by AntonKrutikov** [comment]
Can't find section "type" property which can control duplex printing by sections in class SectionProperties.
[http://officeopenxml.com/WPsection.php](http://officeopenxml.com/WPsection.php)

> Specifies the section type. It determines how the contents of the section will be placed relative to the previous section. E.g., <w:type w:val="nextPage"/> There are five different types, corresponding to the five possible values of the val attribute.
> 
> **continuous** - Begins the section on the next paragraph. Certain page-level section properties cannot be specified, as they are inherited from the previous section. If a footnote occurs of the same page as a section of this kind, the new section begins on the following page.
> **evenPage** - The section begins on the next even-numbered page, leaving the next odd page blank if necessary.
> **nextColumn** - The section begins on the following column on the page.
> **nextPage** - The section begins on the following page.
> **oddPage** - The section begins on the next odd-numbered page, leaving the next even page blank if necessary.
> Reference: ECMA-376, 3rd Edition (June, 2011), Fundamentals and Markup Language Reference § 17.10.22.

**Comment by dolanmiu** [comment]
Section type is added in: https://github.com/dolanmiu/docx/pull/780
