### ISSUE TITLE
[Request?] Option to have Table header/footer persist on each page break

### ISSUE THREAD

**Issue by CamronCapps** [dolanmiu/docx#470]
Looking through the documentation, I haven't been able to locate a way to have the table header repeat on page-breaks. 

Am I dumb? Or is this not currently a feature?

**Comment by dolanmiu** [comment]
This might not be available just yet

I'll add to the to do

**Comment by c-bibek-shrestha** [comment]
@CamronCapps 
`const row = new TableRow({
    ...,
    tableHeader: true,
});`
works fine for me.

**Comment by dolanmiu** [comment]
Thanks for this, will close
