### ISSUE TITLE
How can edit exist word file

### ISSUE THREAD

**Issue by vuonghungvinh** [dolanmiu/docx#472]
How can I load exist word file and then edit that file, such as: change fontsize to 19px, margin: 1px...?

**Comment by dolanmiu** [comment]
Not in scope of this library

**Comment by jpros** [comment]
They should update the README.MD to reflect this:

"Easily generate and **modify** .docx files with JS/TS. Works for Node and on the Browser."
@dolanmiu  please remove the "modify" word as it is misleading.

**Comment by dolanmiu** [comment]
It is now with `patchDocument`
