### ISSUE TITLE
What's the current way of setting numbered list attributes?

### ISSUE THREAD

**Issue by jamesalester** [dolanmiu/docx#473]
[This recent example](https://github.com/dolanmiu/docx/blob/master/demo/29-numbered-lists.ts) in the demo folder indicates that numbered list styles should be set in the document config.

However IParagraphOptions is showing that numbering takes a num parameter instead of a reference parameter: 

<img width="283" alt="image" src="https://user-images.githubusercontent.com/19751644/70534724-883a9e80-1b53-11ea-97c6-3322477fa508.png">

I'm on version 5.0.0-rc7. Is the reference parameter the new way that hasn't been released yet or is it the old way and the demo hasn't been updated?

**Comment by dolanmiu** [comment]
Hasn't been released yet

Will be in v5.0.0, which will be released very soon

**Comment by BrentFarese** [comment]
This is fixed now?  Should be closed?

**Comment by dolanmiu** [comment]
Yes will close, good spot. This has been released for a while now:

https://github.com/dolanmiu/docx/blob/master/src/file/paragraph/properties.ts#L45
