### ISSUE TITLE
declarative numbering - error

### ISSUE THREAD

**Issue by wcqrnj** [dolanmiu/docx#475]
Hello All!

I have tried to run demo 3 (https://github.com/dolanmiu/docx/blob/master/demo/3-numbering-and-bullet-points.ts) in browser and I get error message.
![image](https://user-images.githubusercontent.com/48729704/70861304-441d1480-1f2c-11ea-95aa-1cd65815040b.png)
I put my code in codepen: https://codepen.io/wcqrnj/pen/QWwKVNQ
Did I do something in a wrong way?

Thanks for your response in advance.
Stay cool!

**Comment by dolanmiu** [comment]
Seems like demo 3 is fixed now!

Check out the latest version
