### ISSUE TITLE
addRun, not addText

### ISSUE THREAD

**Issue by thiagorova** [dolanmiu/docx#48]
Hi guys,
i was testing your system today (really cool by the way!), and I found an inconsistency between what worked for me and your docs (maybe my fault, who knows)

i had to use the following code here:
var docx_para = new docx.Paragraph();
text = new docx.TextRun("whatever");
docx_para.addRun(text);

instead of what's in the docs:

var docx_para = new docx.Paragraph();
text = new docx.TextRun("whatever");
docx_para.addText(text);

my docx package is version 3.0.1

thanks again!

**Comment by dolanmiu** [comment]
Could you show me where in the docs, then I will amend!

**Comment by thiagorova** [comment]
sure (I should've done that in the first place hahaha)

1: Paragraph page (Wiki => paragraph). On the second code:

var text = new docx.TextRun('Lorem Ipsum Foo Bar');
var paragraph = new docx.Paragraph();
**paragraph.addText(text);**

2: Text page (Wiki => Text), first code:

var text = new docx.TextRun("My awesome text here for my university dissertation");
**paragraph.addText(text);**

3: Tab stops: (Wiki => Tab Stops). The last 2 codes

var paragraph = new docx.Paragraph().maxRightTabStop();
var leftText = new docx.TextRun("Hey everyone").bold();
var rightText = new docx.TextRun("11th November 2015").tab();
paragraph.addText(leftText);
paragraph.addText(rightText);

var paragraph = new docx.Paragraph();
paragraph.maxRightTabStop();
paragraph.leftTabStop(1000);
var text = new docx.TextRun("Second tab stop here I come!").tab().tab();
**paragraph.addText(text);**

(wiki => Examples). The first 2 codes

var doc = new docx.Document();

var paragraph = new docx.Paragraph("Hello World");
var institutionText = new docx.TextRun("University College London").bold(),
var dateText = new docx.TextRun("5th Dec 2015").tab().bold();
**paragraph.addText(institutionText);
paragraph.addText(dateText);**

doc.addParagraph(paragraph);
var exporter = new docx.LocalPacker(doc);
exporter.pack('My Document');


var doc = new docx.Document();

var paragraph = new docx.Paragraph("Hello World");
var institutionText = new docx.TextRun("University College London").bold(),
var dateText = new docx.TextRun("5th Dec 2015").tab().bold();
**paragraph.addText(institutionText);
paragraph.addText(dateText);**

var exporter = new docx.ExpressPacker(doc, res);
exporter.pack('My Document');

thanks again!

**Comment by dolanmiu** [comment]
Thank you! All done
