### ISSUE TITLE
Outdated examples

### ISSUE THREAD

**Issue by hannojg** [dolanmiu/docx#487]
Hey,

just following the given examples I can't run any of them. I think this is due to the change to declarative since version 5 (all the examples use version 4).
E.g. the numbering example gives me the following error:
```
TypeError: Cannot read property 'config' of undefined
```

**Comment by dolanmiu** [comment]
All the examples under the /demo folder are up to date

**Comment by hannojg** [comment]
Okay, that's true, thank you!
But the examples in the readme https://github.com/dolanmiu/docx#node still seem to be somehow outdated.

**Comment by dolanmiu** [comment]
Yeah those ones are very outdated

Will update after I update all the documentation on https://docx.js.org

**Comment by dolanmiu** [comment]
All examples are updated on runkit
