### ISSUE TITLE
How to set the PageMargin

### ISSUE THREAD

**Issue by cchetan1993** [dolanmiu/docx#488]
Hi,
Could any one help me to set the PageMargin for whole Document.
Currently i am not able to find any example for the same and didn't get any api for it.

Regards,
Chetan.

**Comment by Sornelo** [comment]
You can set the margins for each section with
`doc.addSection({
  properties: {
    right: 1000,
    left: 1000
  },
  children: [...]
})`

**Comment by dolanmiu** [comment]
Check this demo out:

https://github.com/dolanmiu/docx/blob/master/demo/6-page-borders.ts
