### ISSUE TITLE
catching errors with exporter.pack

### ISSUE THREAD

**Issue by thiagorova** [dolanmiu/docx#49]
Hi again!
I looked around the wiki and tested with this:
try {
    exporter.pack(path.join(file_path, title));
} catch(e) {
    console.log(e);
}

and

exporter.pack(path.join(file_path, title), err => {
  if (err) {
    console.log(err);
  }
});
so, heres the thing... if writing the file doesn't work for some reason (e.g.. Uncaught Error: EISDIR: illegal operation on a directory, open),  Is there any way to catch the error?
thanks again!!!!

**Comment by dolanmiu** [comment]
Errors are now caught, I wrote tests to support this:

https://github.com/dolanmiu/docx/blob/master/src/export/packer/local.spec.ts#L35-L43

https://github.com/dolanmiu/docx/blob/master/src/export/packer/express.spec.ts#L35-L41

Thanks again!
