### ISSUE TITLE
Unable to build using latest version 5.0.1

### ISSUE THREAD

**Issue by LorediBega** [dolanmiu/docx#492]
![image](https://user-images.githubusercontent.com/24267938/72421681-41a71800-3781-11ea-84bc-d696582dba74.png)

Does anyone else face the same issue ? Thanks in advance

**Comment by rvergar7** [comment]
Same here. Thanks in advance.

<img width="1708" alt="Screen Shot 2020-01-15 at 1 09 23 PM" src="https://user-images.githubusercontent.com/38929128/72471895-5f33ac00-3798-11ea-9226-a984b417d4b4.png">

**Comment by dolanmiu** [comment]
ah yes I found the issue for the styles-options bug, will create a new release

It's actually a bug in webpack:

https://github.com/s-panferov/awesome-typescript-loader/issues/432

**Comment by dolanmiu** [comment]
The @types/node issue i am having trouble with atm

**Comment by dolanmiu** [comment]
So I've sort of fixed it

Realised the problem is due to the type definitions, without type definitions, it works totally fine

I may need some help on this issue from people

**Comment by dolanmiu** [comment]
I fixed it!

Version 5.0.2 Released!

Be sure to add "node" to types in Angular's `tsconfig.app.json`, to fix the `Buffer` issue:

![image](https://user-images.githubusercontent.com/2917613/72489895-7b256500-380d-11ea-892d-dde717e576d2.png)

**Comment by dolanmiu** [comment]
Some evidence of it working:

![image](https://user-images.githubusercontent.com/2917613/72490003-cc355900-380d-11ea-9abb-8b76b5335436.png)

**Comment by tahseen0amin** [comment]
Didn't work for me. I have to manually copy the style-options.js file from **docx/src/file/styles** to **docx/build/file/styles** in the node_mdules folder.

**Comment by dolanmiu** [comment]
I used 5.0.2 to make the picture to work:

> Some evidence of it working:
> 
> ![image](https://user-images.githubusercontent.com/2917613/72490003-cc355900-380d-11ea-9abb-8b76b5335436.png)

Are you using 5.0.2?

**Comment by dolanmiu** [comment]
It's fully working in Angular

Here is it working:

https://stackblitz.com/edit/angular-afvxtz
