### ISSUE TITLE
Word 2010 support for images

### ISSUE THREAD

**Issue by apsavin** [dolanmiu/docx#499]
Does `docx` support old `Word` versions?
It seems that new versions of `Word` and `Google docs` can open the result of [this](https://github.com/dolanmiu/docx/blob/master/demo/18-image-from-buffer.ts) example, but not `Word 2010` on Windows nor `Word 2008` on Mac OS.

**Comment by dolanmiu** [comment]
Yes, currently old versions of word aren't supported

If you can figure out why and can make a PR, that would be very much appreciated!

**Comment by dolanmiu** [comment]
duplicate of : https://github.com/dolanmiu/docx/issues/394
