### ISSUE TITLE
Page margins

### ISSUE THREAD

**Issue by andreafeccomandi** [dolanmiu/docx#50]
Hello and thank you very much for your great library!

I'm integrating it in my project (www.bibisco.com).

I have a question: how can I programmatically set page margins? Could you provide an example?

Thank you!

**Comment by dolanmiu** [comment]
Thank you for your interest

At the moment, theres no support for Page Margins. Good news is, its easy to add

I will add it in soon, I think its quite an important feature.

At the moment I am busy adding image support

**Comment by dolanmiu** [comment]
Done!

Will be released in `4.0.0`

This is how to use, it is the second argument. setting all to 0s will mean no margin, default is the word default:

https://github.com/dolanmiu/docx/blob/master/demo/demo6.js

**Comment by dolanmiu** [comment]
The unit is "20ths of a point":

https://startbigthinksmall.wordpress.com/2010/01/04/points-inches-and-emus-measuring-units-in-office-open-xml/
