### ISSUE TITLE
rowSpan is not working on first column

### ISSUE THREAD

**Issue by napanda** [dolanmiu/docx#501]
I m trying to merge all cells in column 1, here is my code,

```
new Table({
        alignment: AlignmentType.LEFT,
        rows: [
            new TableRow({
                children: [
                    new TableCell({
                        children: [new Paragraph("0,0")],
                        rowSpan:3
                    }),
                    new TableCell({
                        children: [new Paragraph("0,1")],
                        
                    })
                ],
            }),
            new TableRow({
                children: [
                    new TableCell({
                        children: [new Paragraph("1,0")],
                        
                    }),
                   
                ],
            }),
            new TableRow({
                children: [
                    new TableCell({
                        children: [new Paragraph("2,0")],
                    })
                ],
            }),
        ],
        width: {
            size: 100,
            type: WidthType.AUTO,
        },
        columnWidths: [6000, 4000],
    });
```

the result is 
-----------
| 0,0 | 0,1 |
----------
| 1,0 |       |
-----
| 2,0 |       | 
-----------

if I put the "rowSpan" in the second column,
it is working as expected, all second column cells merged
----------
| 0,0 |      |
-----
| 1,0 |       |
-----
| 2,0 |       | 
-----------

**Comment by napanda** [comment]
using `verticalMerge` is ok, but rowspan is not working

```
new TableCell({ children:[], verticalMerge: VerticalMergeType.RESTART}), 

new TableCell({ children: [], verticalMerge: VerticalMergeType.CONTINUE }), 
```

**Comment by henry132109** [comment]
> 
> 
> using `verticalMerge` is ok, but rowspan is not working
> 
> ```
> new TableCell({ children:[], verticalMerge: VerticalMergeType.RESTART}), 
> 
> new TableCell({ children: [], verticalMerge: VerticalMergeType.CONTINUE }), 
> ```

Will this go well for cells with rowSpan 2 since it's **BOTH** the CONTINUE and RESTART?

If the rowSpan isn't working, could the package provider provide some instructions on the use of `verticalMerge`?

**Comment by henry132109** [comment]
Update:
I found out the solution.
When using verticalMerge, **one needs to declare the merged cell in the markup as well**.

Hope this helps anyone moving from rowSpan to verticalMerge.
