### ISSUE TITLE
Why was 'StreamPacker' object removed from the library?

### ISSUE THREAD

**Issue by siarhei-murkou** [dolanmiu/docx#502]
P.S. Do we have an alternative way to create `Node.js` readable stream based on created `docx` object?

**Comment by dolanmiu** [comment]
Because now the library sends out plain data in Buffer/Base64 etc

It is now down to you, your implementation detail, and how you would like to handle it.

Better separation of concerns

> P.S. Do we have an alternative way to create Node.js readable stream based on created docx object?

Yes.
