### ISSUE TITLE
How to add style or modify the style of hyperlinks in version 5

### ISSUE THREAD

**Issue by marcelorodcla** [dolanmiu/docx#503]
How to add style or modify the style of hyperlinks in version 5? I followed this example: https://github.com/dolanmiu/docx/blob/master/demo/35-hyperlinks.ts

Thanks so much @dolanmiu

**Comment by dolanmiu** [comment]
This might not be a feature yet

You can style the paragraph though:

https://github.com/dolanmiu/docx/blob/master/demo/11-declaritive-styles-2.ts

I would like to make it so you can style it like so:

https://github.com/dolanmiu/docx/blob/master/demo/46-shading-text.ts

**Comment by billreynolds007** [comment]
Here is how I achieved hyperlink text styling,

I modified the Hyperlink constructor to accept an optional runTextOptions argument.
The argument is used in place of the current argument to the TextRun constructor call.
This is shown below,

```
class Hyperlink extends xml_components_1.XmlComponent {
	 // Added textRunOptions override. It MUST include style: 'Hyperlink'
	constructor(text, relationshipId, anchor, textRunOptions) {
		...
		// Use any optional textRunOptions. Otherwise use the default argument.
       		this.textRun = new run_1.TextRun( textRunOptions != null ? textRunOptions : 
        		{
            			text: text,
            			style: "Hyperlink",
        		});

```
In my generation code I have regular text run options and then the target hyperlink URL,

```
	var hyperlinkUrl = 'www.google.com';
	textRunOptions.style = 'Hyperlink';
	var relationshipId = 'myHyperloop1';
	elementDocx = new docx.Hyperlink(textRunOptions.text, 
			relationshipId, hyperlinkUrl, textRunOptions);

```
The styled hyperlink is then added to the paragraph as usual.
Shading should work as well. I did not try that though.

Thanks so much @dolanmiu for a super useful library!

**Comment by dolanmiu** [comment]
Now hyperlinks are entirely fully customizable, you can change it to whatever style you want.

Hyperlinks now take a `child` component, which means hyperlinks can be anything you want, go wild. It can even be images etc!

Will be fixed by:

#784
