### ISSUE TITLE
stylesWithLevels on Table of Contents Not Working

### ISSUE THREAD

**Issue by CamronCapps** [dolanmiu/docx#504]
From the documentation, it states "Uses paragraphs formatted with styles other than the built-in heading styles."

Whenever I add StyleLevels to my Table-of-Contents, nothing appears. Am I missing a step? My styles are NOT based on any other pre-built HeadingX style.

**Comment by CamronCapps** [comment]
Figured it out - the example uses the style's ID rather than the Name. 

StyleLevels are constructed by Name, not ID.

**Comment by FlorianChampin** [comment]
@ccapps0 Ok I feel dumb to miss this, thanks cap
