### ISSUE TITLE
Is declarative syntax the only way ??

### ISSUE THREAD

**Issue by GautierBlondel** [dolanmiu/docx#505]
Hello there, I'm trying to create a table and I would like to factor it. I wonder what is the closest from this syntax that was possible in the latest version.

const tabCreation = (doc, rows, columns, width, height, horAnchor, vertAnchor) => {
	const table = doc.createTable({
		rows,
		columns,
		width,
		height,
		float: {
			horizontalAnchor: horAnchor,
			verticalAnchor: vertAnchor,
			relativeHorizontalPosition: RelativeHorizontalPosition.CENTER,
		},
		widthUnitType: WidthType.DXA,
		margins: {
			top: 10,
			bottom: 10,
		},
	});

Cheers,
Walter

**Comment by dolanmiu** [comment]
Yes

Declarative is the only way
