### ISSUE TITLE
Table Positioning - Distance from surrounding text

### ISSUE THREAD

**Issue by ElDubsNZ** [dolanmiu/docx#506]
Hi! Would like a feature request.

We can set paragraph spacing (before, after, left, right). I'd like to be able to set the Table Positioning "Distance from surrounding text" (top, bottom, left right) fields. Which applies spacing to the table itself, rather than the cells in the table. This is preferable to adding "before" spacing to the first paragraph after a table for consistency.

In Word this is done via Table Properties > Text Wrapping = Around > Positioning > Distance from surrounding text (Top, Bottom, Left, Right).

So when I'm generating a letter, and my styling says I have spacing after every paragraph of 240 DXA, I want to be able to set this to tables as well, so there is a space of 240 DXA after the table.

**Comment by dolanmiu** [comment]
This is already a feature which can be used today, its called floating table:

Along with float, you can also specify the distance from surrounding text

https://github.com/dolanmiu/docx/blob/master/demo/34-floating-tables.ts
