### ISSUE TITLE
Multiple Numbered Lists

### ISSUE THREAD

**Issue by mmdonaldson** [dolanmiu/docx#508]
With the new declarative way of doing lists, is the only way to create multiple numbered lists in a document via the numbering config creating a new list. E.g.

```
 numbering: {
                config: [
                    {
                        reference: 'list1',
                        levels: [
                           ...etc
                        ],
                    },
                    {
                        reference: 'list2',
                        levels: [
                           ...etc
                        ],
                    },
                ],
```

I can't reuse the list1 configuration for multiple lists?

Desired outcome:
1. First item
2. Second item

1. First item again
2. Second item again

Current outcome:
1. First item
2. Second item

3. First item again
4. Second item again

**Comment by henry132109** [comment]
I'm also not sure about the new 
```
{
   custom: true
}
```
part, what effect does it have?

**Comment by henry132109** [comment]
> With the new declarative way of doing lists, is the only way to create multiple numbered lists in a document via the numbering config creating a new list. E.g.
> 
> ```
>  numbering: {
>                 config: [
>                     {
>                         reference: 'list1',
>                         levels: [
>                            ...etc
>                         ],
>                     },
>                     {
>                         reference: 'list2',
>                         levels: [
>                            ...etc
>                         ],
>                     },
>                 ],
> ```
> 
> I can't reuse the list1 configuration for multiple lists?

This is important, because the number of lists can be dynamic, namely we can't easily declare styles for the lists beforehand easily.

**Comment by henry132109** [comment]
Isn't the desired outcome the same as the current outcome?

**Comment by FilipRafaj** [comment]
> Isn't the desired outcome the same as the current outcome?

I think @mmdonaldson ment:

Desired outcome:

```
1. First item
2. Second item
1. First item again
2. Second item again
```

Current outcome:

```
1. First item
2. Second item
3. First item again
4. Second item again
```
I'd also like to know how that can be done.

**Comment by dijam** [comment]
I have the exact same problem when I upgraded to the latest version.

**Comment by dolanmiu** [comment]
This will be included in: https://github.com/dolanmiu/docx/pull/816

A demo will be included to demonstrate its usage

Thanks!
