### ISSUE TITLE
Floating image on top of another floating image

### ISSUE THREAD

**Issue by gytisgreitai** [dolanmiu/docx#510]
How are floating images ordered? At first I thought that adding order matters, but afaik the bigger one always sits on the smaller one when they overlap?

**Comment by dolanmiu** [comment]
AFAIK it should be the order of which you add them in the children list, but I am not sure, needs investigation

**Comment by dolanmiu** [comment]
Correct, it was previously set based on how big the image was, but now this is corrected in:

https://github.com/dolanmiu/docx/compare/feat/convenience-functions?expand=1
