### ISSUE TITLE
Bullet points - forced to use default bullet style

### ISSUE THREAD

**Issue by ElDubsNZ** [dolanmiu/docx#512]
I've set up custom styles in my document. Such as:

```
paragraphStyles: [
{
    id: "standard",
    name: "Standard",
    run: {
        font: 'Arial',
        size: 22
    },
    paragraph: {
        alignment: docx.AlignmentType.JUSTIFIED
    }
},
]
```

however, if I use bullet points, the style is overwritten by the default bullet point style because the Style "ListParagraph" is being pushed.

```
if (options.bullet) {
    this.properties.push(new Style("ListParagraph"));
    this.properties.push(new NumberProperties(1, options.bullet.level));
}
```

This means when I do this:

```
new docx.Paragraph({
    style: 'standard',
    bullet: {level: 0},
    children: [new docx.TextRun("Hello World!")]
})
```

It ignores my custom "standard" style and forces the "ListParagraph" style.

I've tested just removing that line, and the bullet point functionality seems to work just fine. Wouldn't it be preferable to separate these and not force style on bullet points? When I do this, it retains the style I set otherwise.

```
if (options.bullet) {
    this.properties.push(new NumberProperties(1, options.bullet.level));
}
```

With this, whatever style I've set to the Paragraph is now retained.

**Comment by rickgrana** [comment]
Hello, 

I resolved this by styling the ListParagraph style, and then my style is 'basedOn' the 'ListParagraph'.

**Comment by SeakeyCode** [comment]
`
new Paragraph({
    children: [
        new TextRun({
            text: "Bullet points",
            size: 34
        })
    ],
    bullet: {
        level: 0
    }
})
`

**Comment by dolanmiu** [comment]
You can define an entirely new numbering system with whatever bullet point icons you want

I have updated the example here:

https://github.com/dolanmiu/docx/blob/master/demo/3-numbering-and-bullet-points.ts
