### ISSUE TITLE
Can we create "Hyperlink" at the paragraph level?

### ISSUE THREAD

**Issue by ElDubsNZ** [dolanmiu/docx#513]
I know there are two ways of creating hyperlinks, either with `hyperlinkRef(id)` or `doc.createHyperlink(link, text)` but there are a couple things with that.

For the first, I have to have pre-defined all my hyperlinks, which I don't necessarily want to do.
For the second, I have to have pre-defined "doc", which I've found storing a big table of text in another sheet breaks if it initialises before I've defined doc.

I'd like to have something like:

```
paragraph = new Paragraph({
    children: [
        new docx.TextRun("you need to provide a "),
        new docx.HyperlinkRef("linkhere", text.content),
        new docs.TextRun(" if you wish to be considered for this job.")
    ]
})
```

In this example, the link stays the same, but the text is variable, and code-wise, hyperlinks would "flow" more nicely with TextRuns.

**Comment by tomswork** [comment]
Hey @ElDubsNZ - I was stuck on this problem too,
The solution is to use `doc.createHyperlink(HREF, LINKTEXT);` switching out for your href string and link text string - then add as a child to a paragraph element. For example;

```javascript
const HREF = "https://www.google.com";
const LINKTEXT = "Example link to google";

new Paragraph({
  children: [
    doc.createHyperlink(HREF, LINKTEXT)
  ] 
})
```

It should render as an inline hyperlink in your document

**Comment by ElDubsNZ** [comment]
Hey @tomswork 

Unfortunately this doesn't help with the second issue I raised, where I must have pre-defined "doc", but I'm storing all this text in a completely different file that breaks because I haven't defined "doc" in that file. Textruns work fine because no variable declaration is required.

**Comment by supervanya** [comment]
Has there been any planning on creating hyperlinks without having to define them in the constructor of the doc? Could I add them after I added all the sections? I have a dynamic document that has hundreds of hyperlinks and creating them upfront is very difficult.

**Comment by dolanmiu** [comment]
Great question @supervanya, and the answer to that is yes

Now hyperlinks are entirely fully customizable, you can change it to whatever style you want.

Hyperlinks now take a child component, which means hyperlinks can even be images etc!

Will be done in:

#784

**Comment by supervanya** [comment]
@dolanmiu thank you so much for this fix! 

What is the timeline for a new release? Hyperlinks, alongside with compatibility mode improvements, are two huge features my team would really like to take advantage as soon as possible.

Also, if you want you can add our [logo](https://res-4.cloudinary.com/crunchbase-production/image/upload/c_lpad,f_auto,q_auto:eco/inrnjpsuvyayv73r9vkc) and [website](http://circadianrisk.com/) to the `used by` section on the repo readme! We have been using the library quite a bit and it is such a lifesaver!

**Comment by dolanmiu** [comment]
@supervanya 

I aim to release it in a month or so, give or take. I want to close as much tickets and PRs as I can, and introduce all the breaking changes I've been planning on doing for v6

Thanks for this, I will add the logo and company on the used by section
