### ISSUE TITLE
Update Tab documentation

### ISSUE THREAD

**Issue by jacwright** [dolanmiu/docx#515]
This is a reminder to update the documentation on tabs. No longer `.tab()` but `\t` in the text.

**Comment by dolanmiu** [comment]
Can you tell me where in the documentation it says that?

I just did a find all, and cant see

Is it in the Wiki by any chance? if so, that is deprecated

**Comment by thuctd** [comment]
I see "  Property 'tab' does not exist on type 'TextRun'.  " in my angular app. It not visible before.

**Comment by dolanmiu** [comment]
https://github.com/dolanmiu/docx/wiki/Tab-Stops

Done

Deprecated the Wiki

**Comment by jacwright** [comment]
See https://docx.js.org/#/usage/tab-stops

> Simply call the relevant methods on the paragraph listed below. Then just add a tab() method call to a text object. Adding multiple tabStops will mean you would have to chain tab() until the desired tabStop is selected. Example is shown below.
