### ISSUE TITLE
Table columnWidths property setting is useless

### ISSUE THREAD

**Issue by boomsi** [dolanmiu/docx#517]
Table columnWidths property setting is useless,The Document Usage.
So how do I set the table width?
Thank you.
Vesion v5.0.2.

**Comment by henry132109** [comment]
I'm not sure about your code, but you can try setting layout to TableLayoutType.FIXED and see if that helps.

**Comment by damian-garrido** [comment]
@boomsi 
hi, im use this feature in this way

```
new TableCell({
  verticalAlign: VerticalAlign.CENTER,
  shading: {
    fill: '#DDDDDD'
  },
  width: {
    size: '5%',
    type: WidthType.PERCENTAGE
  },
  children: []
}),
```

i use the size with '%' because if not this not work
hope this help

**Comment by frankvm04** [comment]
Agree with Damian. Here is altering the property syntax:
cell.properties.setWidth("50%", WidthType.PERCENTAGE);

**Comment by boomsi** [comment]
> @boomsi
> hi, im use this feature in this way
> 
> ```
> new TableCell({
>   verticalAlign: VerticalAlign.CENTER,
>   shading: {
>     fill: '#DDDDDD'
>   },
>   width: {
>     size: '5%',
>     type: WidthType.PERCENTAGE
>   },
>   children: []
> }),
> ```
> 
> i use the size with '%' because if not this not work
> hope this help

Think you,I think I have solved it.

**Comment by boomsi** [comment]
> Agree with Damian. Here is altering the property syntax:
> 
> ```js
> cell.properties.setWidth("50%", WidthType.PERCENTAGE);
> ```

Think you,I think I have solved it.
