### ISSUE TITLE
Numbering in the format of [000X] with leading zeros

### ISSUE THREAD

**Issue by douglance** [dolanmiu/docx#518]
I am trying to build a numbering format that uses up to three leading zeros, which is possible in the Word GUI.

I have gotten close with this format: 

```js
	{
      reference: 'numbering',
      levels: [
        {
          level: 0,
          format: 'decimalZero',
          text: '[00%1]',
          alignment: AlignmentType.LEFT,
          suffix: LevelSuffix.NOTHING
        }
      ]
    }
```
But it fails at 100+ going to `[00100]` rather than `[0100]`

I found in [the spec](http://officeopenxml.com/WPnumbering-numFmt.php) that it says there is a `format` attribute that:
 
Specifies a custom format using the XSLT format attribute. For example, a value of &#x30A2 indicates that Katakana numbering should be used.

Does docx allow for custom formats? Is there another method that I'm missing?

**Comment by douglance** [comment]
Or is there a way to inject an XML definition?

**Comment by dolanmiu** [comment]
I have managed to create an example with one leading zero. It seems that is the max word supports:

http://officeopenxml.com/WPnumbering-numFmt.php

> decimalZero - decimal number but with a zero added to numbers 1 through 9

PR is here: https://github.com/dolanmiu/docx/pull/736

**Comment by f3ve** [comment]
@douglance were you able to find a solution for this? `decimalZero` only supports 1 leading zero and the method suggested by HTrayford results in more zeros than I need on larger numbers.

**Comment by f3ve** [comment]
I think what it might be doing is taking the length of string `'%1'` and basing the padding around that. So it thinks it already has 2 characters and adds 3 more no matter what the actually value of `%1` is.

**Comment by f3ve** [comment]
Exactly. Thanks so much for your help though! I appreciate you reaching out 😄

**Comment by VCNinc** [comment]
@douglance how did you end up solving this issue?

**Comment by VCNinc** [comment]
@f3ve Did you end up finding a solution?

**Comment by f3ve** [comment]
@VCNinc I was unable to find a solution with this library. I was able to do what I needed with [docxtemplater](https://github.com/open-xml-templating/docxtemplater) instead.
