### ISSUE TITLE
Take Headers into account when generating Table of Contents

### ISSUE THREAD

**Issue by hendrikgaffo** [dolanmiu/docx#521]
I actually don't know if this is intended behavior, so I am raising this issue.

I am using `docx@5.0.2` in the backend with NodeJS 12.16.1.

I am creating headers for each section of my document. Each header contains a paragraph with `heading` set to `HeadingLevel.HEADING_1` like this:

```typescript
new Header({
  children: [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      children: [
        new TextRun({
          text: headline,
          size: 44,
          font: style.font.type,
        }),
      ],
      alignment: AlignmentType.LEFT,
    }),
  ],
});
```

Each section of the document than has paragraphs with `heading` set to `HeadingLevel.HEADING_2` (kind of sub-headlines).

What I am trying to do now, is generating a Table of Contents. As specified in the documentation, I am using this code:

```typescript
new TableOfContents('Summary', {
  hyperlink: true,
  headingStyleRange: '1-5',
});
```

The Table of Contents is generated, but unfortunately none of the paragraphs with `HeadingLevel.HEADING_1` created in headers are taken into account, which basically messes up the structure of the Table of Contents, because it only contains the sub-headlines mentioned above.

Is there a way to include paragraphs from headers into the Table of Contents?

If there is any more information I can provide to clarify the problem, please let me know.

**Comment by ccocker** [comment]
Hi Why are you putting the heading 1 in a header, if you want them on a new page just put :

`
this.createHeading("Commercial Offer"),

public createHeading(text: string): Paragraph {
        return new Paragraph({
            text: text,
            heading: HeadingLevel.HEADING_1,
            thematicBreak: true,
            pageBreakBefore: true,
        });
    }`

**Comment by hendrikgaffo** [comment]
@ccocker Thanks for commenting on this issue! That is pretty much what I was doing, but since the returned Paragraph still is inside of the `Header` class in the example I mentioned above, it is not added to the TOC. Or am I misunderstanding your point?

In the meantime I have worked around the problem by ditching the idea of putting `Paragraph`s that should appear in the TOC inside of the `Header` class.
I am now using a standard Headline in the `Header` and putting all the `Paragraph`s that I want to appear in the TOC with `heading` set to `HeadingLevel.HEADING_1` in the `Section`, instead of putting them in the `Header`.

That is not exactly the solution I wanted, but at least the TOC is generated correctly now.

**Comment by ccocker** [comment]
Great glad you have something working, sometimes we have to do things in a different way to get the result we want.
