### ISSUE TITLE
Office365 is not showing the table of contents

### ISSUE THREAD

**Issue by joby-kurian** [dolanmiu/docx#524]
Dear Team,

I have referred the link "https://github.com/dolanmiu/docx/blob/master/demo/28-table-of-contents.ts" for generationg docx file with TOC. But unfortunately TOC is not showing in Office 365's MS Word. Whether this will work in O365 word as well ? Please find attached image with issue.

Version: 5.0.2
Environment: Windows 10 + Office 365
![imag](https://user-images.githubusercontent.com/48939865/78869610-5d465580-7a34-11ea-8c7b-75d9f2635499.png)

**Comment by 0xheret1c** [comment]
Can confirm, the ToC feauture is not working for me either. Copy-Pasting the ToC-Example does not show the ToC.

**Comment by dolanmiu** [comment]
Closing as it's related to general office365 compatibility issues:

https://github.com/dolanmiu/docx/issues/496

**Comment by 0xheret1c** [comment]
Its not just Office365. I'm experiencing this issue on LibreOffice.

**Comment by joby-kurian** [comment]
I am able to see the TOC using OpenOffice software. Currently I am facing issue with O365

**Comment by 0xheret1c** [comment]
> 
> 
> I am able to see the TOC using OpenOffice software. Currently I am facing issue with O365

I'll try switching to OpenOffice. Thanks!
