### ISSUE TITLE
Is it possible to create vertical text

### ISSUE THREAD

**Issue by bschwarz** [dolanmiu/docx#526]
Is it possible to set the direction of the text in a table cell, for example, if I want to have the text vertical (rotated 90 degrees)? Something like this: https://word.tips.net/T001781_Changing_Table_Cell_Text_Direction.html

**Comment by dolanmiu** [comment]
Not yet

This needs the Text Box feature first

**Comment by bschwarz** [comment]
So, I was able to patch the source, and to get vertical text working in a table cell. I believe I did it correctly, but I am not too familiar with TS and not too familiar with word xml. How would you like me to submit the patches (they span multiple files)?

**Comment by dolanmiu** [comment]
Great! Can u make a Pull request into this repo?

**Comment by bschwarz** [comment]
Ok, it's passing the tests and the table demo works, but when I try to commit to my fork, it fails with a pre-commit hook 'style'. Any hints on where to look to fix this?

Also, I modified the following files:
        modified:   demo/31-tables.ts
        modified:   src/file/table/table-cell/table-cell-components.ts
        modified:   src/file/table/table-cell/table-cell-properties.ts
        modified:   src/file/table/table-cell/table-cell.spec.ts
        modified:   src/file/table/table-cell/table-cell.ts

Do I need to modify any other files? Paragraph or Section files?

Thanks!

**Comment by dolanmiu** [comment]
run:

```
npm run style.fix
```

to fix all the stylistic issues

**Comment by dolanmiu** [comment]
Now possible to create vertical text in tables as of 5.1.1
