### ISSUE TITLE
The cell widths are incorrect under LibreOffice.

### ISSUE THREAD

**Issue by aaf0171** [dolanmiu/docx#528]
Hi,

First of all, thank you for you wonderful library. It works perfectly under Word. But, i have a problem with rendering in LibreOffice.

Take a look at this code below. It displays correctly under Word (two columns : 20% width for the first and 80% width for the second column). But under LibreOffice, it displays two columns with the same width (50%).

Am I doing it wrong?

Best regards

``
			new docx.Table({
				rows: [
					new docx.TableRow({
						children: [
							new docx.TableCell({ 
								children: [ new docx.Paragraph( { text: "Description du contexte/Mise en situation professionnelle", style: 'tableauHeader' } ) ],
								shading: { fill: '00595b' }, 
								width: { size: 20, type: docx.WidthType.PERCENTAGE },							
							}),
							new docx.TableCell({ 
								children: [ new docx.Paragraph( { text: "Secteurs d'activité", style: 'tableauHeader' } ) ], 
								shading: { fill: '00595b' }, 
								width: { size: 80, type: docx.WidthType.PERCENTAGE },	
							})							
						]
					}), 								
				],
				width: { size: 100, type: docx.WidthType.PERCENTAGE },					
				layout: docx.TableLayoutType.FIXED
			})``

**Comment by aaf0171** [comment]
Ok, i've found the solution. If it helps anyone :
`
new docx.Table({ 
           rows: [ 
              new docx.TableRow({ 
                children: [ 
                     new docx.TableCell({ 
                      children: [ 
                         new docx.Paragraph( { text: "Colonne1"} ) 
                       ], 
                       width: { size: 20, type: docx.WidthType.PERCENTAGE }, }),
                    new docx.TableCell({ 
                      children: [ 
                        new docx.Paragraph( { text: "Colonne2" } ) 
                      ], 
                      width: { size: 80, type: docx.WidthType.PERCENTAGE }
                    })
                  ] 
                }), 
            ], 
            width: { size: 100, type: docx.WidthType.PERCENTAGE }, 
            columnWidths: [ 20, 80 ],
            layout: docx.TableLayoutType.FIXED })
`

**Comment by avlapeto** [comment]
For those who are looking into the same issue:
LibreOffice expect `columnWidths: [20, 80] ` for correct representation. 
Thanks much, @aaf0171 !

**Comment by zeelmodi-simform** [comment]
> Ok, i've found the solution. If it helps anyone : `new docx.Table({ rows: [ new docx.TableRow({ children: [ new docx.TableCell({ children: [ new docx.Paragraph( { text: "Colonne1"} ) ], width: { size: 20, type: docx.WidthType.PERCENTAGE }, }), new docx.TableCell({ children: [ new docx.Paragraph( { text: "Colonne2" } ) ], width: { size: 80, type: docx.WidthType.PERCENTAGE } }) ] }), ], width: { size: 100, type: docx.WidthType.PERCENTAGE }, columnWidths: [ 20, 80 ], layout: docx.TableLayoutType.FIXED })`

Thanks @aaf0171 for solution.
