### ISSUE TITLE
Insert new line character (\n) within the same paragraph

### ISSUE THREAD

**Issue by mrtsniper** [dolanmiu/docx#529]
Hi
i'm trying to add text  containing new line characters to a paragraph. but it seems to be ignored and the generated document does not contains the line breaks.
tried with '\n' and "\r\n" without success

could you please help how to add line breaks to a paragraph text ?

Thanks

**Comment by dolanmiu** [comment]
These example here uses \n:

https://github.com/dolanmiu/docx/blob/master/demo/10-my-cv.ts
https://github.com/dolanmiu/docx/blob/master/demo/21-bookmarks.ts

**Comment by lukeburns** [comment]
Does docx currently ignore new lines / carriage returns? If so, why?

**Comment by nikolaioak** [comment]
Hi, also following up on this. I have an electron application that is feeding text areas submitted by a user into the docx creator, but even capturing carriage returns and line feeds and replacing them with \n within the string does re-create the new line within the word document. These are usually in the middle of a string being inserted into a single text run, so trying to do something with .break() does not seem feasible.

**Comment by dolanmiu** [comment]
@nikolaioak It seems that the text you are passing into docx must be escaped, because it is indeed possible.

The proof is in the pudding:

https://github.com/dolanmiu/docx/blob/master/demo/10-my-cv.ts

**Comment by guushoekman** [comment]
@dolanmiu in your link I see that you have this function:

```
public splitParagraphIntoBullets(text: string): string[] {
  return text.split("\n\n");
}
```

Is that necessary to make `/n` work as a new line? A new line isn't showing up for me either even though I think I'm doing the right thing:

```
new docx.TableRow({
  children: [new docx.TableCell({
    children: [new docx.Paragraph({
      text: "Methodology"
    })],
  }), new docx.TableCell({
    children: [new docx.Paragraph({
      text: "1. Identify stakeholder activity \n\n 2. Describe process and when stakeholders are involved \n\n 3. Identify dialogue methods used \n\n 4. Number of people involved"
    })],
  })]
}),
```

Am I doing something wrong?

**Comment by nikolaioak** [comment]
Just to follow up, I escaped the text in the input, used RegEx to replace line breaks/carriage feeds from the user's text area, then unescaped before passing my text into the document function. All good on my end. Thanks!

**Comment by guushoekman** [comment]
@nikolaioak thanks for the info. What was the string you ended up with in the end that worked? Was it similar to:

`text: "1. Identify stakeholder activity \n\n 2. Describe process and when stakeholders are involved \n\n 3. Identify dialogue methods used \n\n 4. Number of people involved"`

This is what I currently have, but the output in the docx document is just a single whitespace ` `, not a new line.

**Comment by nikolaioak** [comment]
Since I was passing in values from a text area on an html page, I did character replaces like this:
```
// replace all carriage returns and line feeds in text for passing to word document
let chgRisk = escape(changeRisk.value)
chgRisk = chgRisk.replace(/%0D%0A/g,'\\n')
chgRisk = chgRisk.replace(/%0A/g,'\\n')
chgRisk = chgRisk.replace(/%0D/g,'\\n')
chgRisk = unescape(chgRisk)
```

In this example, `changeRisk` is associated with `document.getElementById('changeRisk')` 

But to your point, I only replaced it with a single \n for each line break needed. I would assume two \n\n would be two line breaks. The function included in the template is what breaks apart the input text, but I handled it differently and passed all my variables straight into a table cell (using the function `createValueFour` for formatting) rather than a text object:

```
new TableRow({
     children: [
          createValueFour(`${chgRisk}`),
     ],
}),
```

I assume you can do the same in a text object, but it may be better if you pass your text into a variable, then call the variable in the text object.

**Comment by guushoekman** [comment]
Thanks for your help @nikolaioak. I still haven't been able to make this work unfortunately. @dolanmiu previously said:

> @nikolaioak It seems that the text you are passing into docx must be escaped, because it is indeed possible.
> 
> The proof is in the pudding:
> 
> https://github.com/dolanmiu/docx/blob/master/demo/10-my-cv.ts

To keep things extremely simple, I took the fiddle that is in the documentation: https://jsfiddle.net/dolanmiu/kqxrj35u/1/

Then I took the string that contains `\n` from @dolanmiu's link I quoted above.

Unfortunately, this does not work either. Here's a fiddle: https://jsfiddle.net/v6o4nujc/

Should I be doing something else to make this work? In the example I saw this:

```
public splitParagraphIntoBullets(text: string): string[] {
    return text.split("\n\n");
}
```

and later:

```
const bulletPoints = this.splitParagraphIntoBullets(position.summary);
```

@nikolaioak what is this `createValueFour` function you run? What does that do?

**Comment by nikolaioak** [comment]
@guushoekman This is my function - I do map the input text to an array that is then fed into a separate function that creates text runs with breaks to split the new lines:

```
let createValueFour = (text) => { 
    let arr = text.split('\\n')
    return new TableCell({
        children: [
            new Paragraph({
                children: textRunMap(arr),
                style: "Normal",
            }),
        ],
        columnSpan: 4,
    })
}
```

Then the textRunMap function is as follows:

```
let textRunMap = (arr) => {
    let run = []
    arr.map((a,i) => {
        if (arr.length === 1 || i === 0) {
            run.push(new TextRun(`${a}`))
        } else {
            run.push(new TextRun(`${a}`).break())
        }
    })
    return run
}
```

This shouldn't be specific to tables, let me know if this helps. Apologies in my previous comment I was under the impression that the function only had table related formatting but I was mistaken, it's been a while since I put this together.

**Comment by guushoekman** [comment]
Thank you so much @nikolaioak!
