### ISSUE TITLE
can this library be used to open existing docx files and save them as pdf?

### ISSUE THREAD

**Issue by russgove** [dolanmiu/docx#53]

**Comment by dolanmiu** [comment]
Sorry, it cannot

maybe in future versions, but not right now

**Comment by plutext** [comment]
For anyone who stumbles across this, there is now https://www.npmjs.com/package/@nativedocuments/docx-wasm which performs the conversion locally.  Freemium model.

**Comment by batatop** [comment]
> can this library be used to open existing `.docx` files and save them as `.pdf`?

If it is possible now, it would be a great help if it could be added. This library provides great control over `.docx` files.
