### ISSUE TITLE
Set Shading Property on Paragraph

### ISSUE THREAD

**Issue by jamesdefant** [dolanmiu/docx#531]
As far as I can tell, within docx,  shading is only supported on a TextRun. Within word we can apply shading to a paragraph as well as a segment of text. The difference in XML looks like this:

**Generated** (docx Version 5.0.2):

		<w:p>
			<w:r>
				<w:rPr>
					<w:shd w:fill="E5E5FF" w:color="auto"/>
					<w:shdCs w:fill="E5E5FF" w:color="auto"/>
				</w:rPr>
				<w:t xml:space="preserve">Technical Skills:</w:t>
			</w:r>
		</w:p>

**Written in Word** (365 - Version 1908):

		<w:p w:rsidR="00E003E9" w:rsidRPr="00E003E9" w:rsidRDefault="00E003E9" w:rsidP="00E003E9">
			<w:pPr>
				<w:shd w:val="clear" w:color="auto" w:fill="D9D9D9" w:themeFill="background1" w:themeFillShade="D9"/>
			</w:pPr>
			<w:r>
				<w:t>Technical Skills:</w:t>
			</w:r>
		</w:p>

It seems like the paragraph itself has a property (I assume that's what pPr - paragraphProperty, is) that sets the shading. 

It is my understanding that this is how shading is most commonly used

**Comment by vijayarun** [comment]
Any update on this issue.

**Comment by dolanmiu** [comment]
Shading is possible, example is here:

https://github.com/dolanmiu/docx/blob/master/demo/46-shading-text.ts
https://github.com/dolanmiu/docx/blob/master/demo/45-highlighting-text.ts

**Comment by vijayarun** [comment]
@dolanmiu shading text allows us to draw background colors on text width. But what if we want it based on the document width.

in Libreoffice v6.4 under paragraph styling, we have an option called area to set the paragraph width shading.

**Comment by dolanmiu** [comment]
Could you show me this option in Microsoft Word? Thats the word processor I use

**Comment by jamesdefant** [comment]
Here - I've made a simple react app to show the usage:
https://github.com/jamesdefant/docx-test

I've included your (altered) sample script, MSWord created document, and some notes

**Comment by dolanmiu** [comment]
Thanks for this

A PR is made to add this feature in: 

https://github.com/dolanmiu/docx/pull/669

**Comment by jamesdefant** [comment]
For sure. Glad I can help
