### ISSUE TITLE
Cannot perform Japanese characters

### ISSUE THREAD

**Issue by ALPhaHoai** [dolanmiu/docx#535]
I try to generate a word file with Japanese characters, but the result is not accurate.
The word 'ハロー・ワールド' is displayed like this

![Alt][1]

[1]: https://i.imgur.com/8k7SwGp.png

Here is my source code.
~~~~
const doc = new docx.Document();

doc.addSection({
    children: [
        new docx.Paragraph({
            children: [
                new docx.TextRun('ハロー・ワールド'),
            ],
        }),
    ],
});

docx.Packer.toBlob(doc).then(blob => {
    saveAs(blob, 'example.docx');
});
~~~~

**Comment by dolanmiu** [comment]
You need to use a japanese font such as MS Gothic:

I have written an example for you:

https://github.com/dolanmiu/docx/blob/master/demo/52-japanese.ts
