### ISSUE TITLE
How can I insert text as is, with newlines respected. For example inserting a code snippet

### ISSUE THREAD

**Issue by bschwarz** [dolanmiu/docx#537]
I am generating a doc, and some parts of it I am trying to insert json samples into a table cell (I am using table cell for formatting purposes). However, the json samples in the word doc are not "pretty" formatted anymore. Is there a way to make docx insert text as is, so that the json sample remains "pretty" in the docx file?

**Comment by dolanmiu** [comment]
This is not possible I'm afraid as essentially this library would need to translate the text into the word XML stuff with the line breaks

If you can find a way, a PR would be nice
