### ISSUE TITLE
Document created in compatibility mode.

### ISSUE THREAD

**Issue by prv123** [dolanmiu/docx#544]
Each time when i create a document using docx.js then it's always created in compatibility mode which gives error in further processing of docx file through other languages like python. On the other hand when i generate file with other library like docxtemplater things works like a charm...

**Comment by dolanmiu** [comment]
Known issue:

https://github.com/dolanmiu/docx/issues/332

If you can do some research into why it happens, would be appreciated

**Comment by dolanmiu** [comment]
Fixed in:

https://github.com/dolanmiu/docx/pull/783
