### ISSUE TITLE
How to restart Numbering?

### ISSUE THREAD

**Issue by adamnator92** [dolanmiu/docx#548]
I'm using version 5.1.1,  currently, the numbering didn't restart the sequence when there is some text/paragraph between it

**Current behavior:**
1. 
2.
3.
Some Text
4.
5.

**Expect behavior** 
1. 
2.
3.
Some Text
1.
2.

**Comment by henry132109** [comment]
We are really desperate for some documentation, or at least a simple example for the resetting numbering for the declarative approach.
This would help immensely for generating dynamic lists because apparently the old non-declarative method doesn't work out either.

**Comment by carole-lavillonniere** [comment]
You need to give each paragraph of your list a unique `numId` that identifies the list it belongs to so that the numbering restarts:
```
new DocXParagraph({
  children: ...,
  numbering: {
      reference: "standardNumbering",
      level: 1,
      num: { numId: uniqueListId },
  },
})
```

In your example the first 3 paragraphs would have the same `numId` and the last two would have another `numId`:
```
Expect behavior
1.
2.
3.
Some Text
1.
2.
```

**Comment by dolanmiu** [comment]
Will be added as part of: https://github.com/dolanmiu/docx/pull/816

Thanks!
