### ISSUE TITLE
Documentation inconsistency regarding cantSplit

### ISSUE THREAD

**Issue by marcohamersma** [dolanmiu/docx#552]
Heya, 
[The readme](https://docx.js.org/#/usage/tables?id=prevent-row-pagination) seems to suggest that you can add the `cantSplit` option to `Table`'s constructor, but according to [the types](https://github.com/dolanmiu/docx/blob/af461f841882644a8142fb6d518a4f42655ac80e/src/file/table/table.ts#L21-L39), this option is not available, and a quick scan through the source code makes me think this indeed is not an option for Tables, but I'm not sure.

**Comment by damian-garrido** [comment]
Hi @marcohamersma 
i'm not sure, but the cantSplit is not a property of Table but TableRow and its a boolean.

**Comment by BeanSampa** [comment]
Hi guys, i'm very noobs but persistent.
The documentation treats cantSplit as a Tables property, in the code, canSplit is treated as a TableRow property. It's confused.

You do not need to use canSplit. You can only use keepNext and keepLines in each paragraph within a TableCell
```
            new TableRow({
                children: [
                    new TableCell({
                        children: [
                            new Paragraph({
                                children:[
                                    new TextRun({
                                        children: ["Column 1"], 
                                    }),
                                ], 
                                keepNext: true,
                                keepLines: true, 
                            }),
                        ],
                    }),
                    new TableCell({
                        children: [
                            new Paragraph({
                                children:[
                                    new TextRun({
                                        children: ["Column 2"], 
                                    }),
                                ], 
                                keepNext: true,
                                keepLines: true, 
                            }),
                        ],
                    }),
                    new TableCell({
                        children: [
                            new Paragraph({
                                children:[
                                    new TextRun({
                                        children: ["Column 3"], 
                                    }),
                                ], 
                                keepNext: true,
                                keepLines: true, 
                            }),
                        ],
                    }),
                ], 
            }),
```
It worked for me. I hope it helps.

I found this solution at:
https://stackoverflow.com/questions/24530954/prevent-tables-from-breaking-over-a-page-if-possible

**Comment by dolanmiu** [comment]
Documentation is now fixed

Thanks for reporting
