### ISSUE TITLE
Dinamic hyperLinks

### ISSUE THREAD

**Issue by retanarivas** [dolanmiu/docx#554]
I have an array with multiple files and I need to create a hyperlink for each file, how I can do that?
I try the following code but doesn't work
this.additionalAttachmentsArray.forEach(element => {
              new Paragraph({
                text: element
              })
            })

**Comment by dolanmiu** [comment]
instead of forEach, use map:

```ts
const paragraphs = this.additionalAttachmentsArray.forEach(element => {
    return new Paragraph({
        text: element
    });
});
```
