### ISSUE TITLE
question: ParagraphProperties & RunProperties goes in various place

### ISSUE THREAD

**Issue by wangfengming** [dolanmiu/docx#560]
We can saw `ParagraphProperties & RunProperties` in the blow files.
```
src/file/paragraph/paragraph.ts
src/file/paragraph/run/run.ts
src/file/styles/style/paragraph-style.ts
src/file/styles/style/character-style.ts
src/file/numbering/level.ts
```
They have very similar options to setup the Properties. Why don't we move all the option definition & setup to the single place in ParagraphProperties & RunProperties

---

Besides, user can't setup options for document defaults styles
```
src/file/styles/defaults/index.ts
src/file/styles/defaults/paragraph-properties.ts
src/file/styles/defaults/run-properties.ts
```
Should change the below code
```typescript
export class ParagraphPropertiesDefaults extends XmlComponent {
    constructor() {
        super("w:pPrDefault");
        this.root.push(new ParagraphProperties({}));
    }
}
```
to 
```typescript
export class ParagraphPropertiesDefaults extends XmlComponent {
    constructor(options?: IParagraphPropertiesOptions) {
        super("w:pPrDefault");
        this.root.push(new ParagraphProperties(options));
    }
}
```
and `ParagraphProperties` should receive the options(alignment/indent/spacing... ).

**Comment by wangfengming** [comment]
If I may, I'll make a pr to modify the code as below:

```typescript
export interface IRunPropertiesOptions {
    readonly bold?: boolean;
    readonly italics?: boolean;
    readonly underline?: {
        readonly color?: string;
        readonly type?: UnderlineType;
    };
    readonly emphasisMark?: {
        readonly type?: EmphasisMarkType;
    };
    readonly color?: string;
    readonly size?: number;
    readonly rightToLeft?: boolean;
    readonly smallCaps?: boolean;
    readonly allCaps?: boolean;
    readonly strike?: boolean;
    readonly doubleStrike?: boolean;
    readonly subScript?: boolean;
    readonly superScript?: boolean;
    readonly style?: string;
    readonly font?: string | IFontOptions | IFontAttributesProperties;
    readonly highlight?: string;
    readonly characterSpacing?: number;
    readonly shading?: {
        readonly type: ShadingType;
        readonly fill: string;
        readonly color: string;
    };
    readonly shadow?: {  // need backward compatibility? shadow alias for shading.
        readonly type: ShadingType;
        readonly fill: string;
        readonly color: string;
    };
}
```

```typescript
export class RunProperties extends IgnoreIfEmptyXmlComponent {
    constructor(options?: IRunPropertiesOptions) {
        super("w:rPr");

        if (!options) {
            return;
        }

        if (options.bold) {
            this.push(new Bold());
            this.push(new BoldComplexScript());
        }

        // ... setup other options
}
```

**Comment by wangfengming** [comment]
And wonder why `xxxComplexScript` is such various.

- `src/file/styles/style/paragraph-style.ts` and `src/file/styles/style/character-style.ts` have only `SizeComplexScript`
- `src/file/numbering/level.ts` has no `xxxComplexScript`
- `src/file/paragraph/run/run.ts` has all `BoldComplexScript` `HighlightComplexScript` `ItalicsComplexScript` `ShadowComplexScript` `SizeComplexScript`

**Comment by wangfengming** [comment]
More question: 
Why have def `SmallCaps & Caps` in two file: `src/file/paragraph/run/caps.ts` and `src/file/paragraph/run/formatting.ts`. What's the diff?

**Comment by dolanmiu** [comment]
> src/file/numbering/level.ts has no xxxComplexScript
Probably an error

> Why have def SmallCaps & Caps in two files: src/file/paragraph/run/caps.ts and src/file/paragraph/run/formatting.ts. What's the diff?

Probably no difference, good to make 1 source of truth

> If I may, I'll make a pr to modify the code as below:

Sure, sounds good!

> They have very similar options to setup the Properties. Why don't we move all the option definition & setup to the single place in ParagraphProperties & RunProperties

They are very similar, but not *equal* right? Something which looks similar not necessarily is equal. But maybe good to have a BaseProperties of some sort

**Comment by dolanmiu** [comment]
> We can saw ParagraphProperties & RunProperties in the blow files.

> src/file/paragraph/paragraph.ts
src/file/paragraph/run/run.ts
src/file/styles/style/paragraph-style.ts
src/file/styles/style/character-style.ts
src/file/numbering/level.ts

Yes lots of duplication, will need fixing

**Comment by wangfengming** [comment]
#562
Close this?
