### ISSUE TITLE
Does this plugin render html ?

### ISSUE THREAD

**Issue by uzairkhan7729** [dolanmiu/docx#563]
I just wonder if this plugin render html like following:
new TextRun ({
                        text: " <h 1 >This is a bold run< / h1>",
                        bold: true,
                    }),
Can we insert any Html into Text ?

**Comment by dolanmiu** [comment]
nope, this is not possible and out of scope

**Comment by cksachdev** [comment]
@uzairkhan7729 I have a similar need, have you figured out an alternative?

**Comment by uzairkhan7729** [comment]
@cksachdev  Nope ! I was not able to do that. Basically in my scenario, I needed to create Docx same as i was creating  PDF( through JsPdf. 
So what i did i just create a microservice which converts pdf into docx. And that's how i achieved the requirement.
