### ISSUE TITLE
[Bug] Chrome is blocking docx downloads as malware

### ISSUE THREAD

**Issue by noahsw** [dolanmiu/docx#576]
This only started happening in the last few days.

![image](https://user-images.githubusercontent.com/2034879/87811765-04950e80-c814-11ea-8113-d782942fdd91.png)

Possibly related to https://www.theverge.com/2020/2/10/21132099/google-chrome-users-block-insecure-downloads-https-android-ios but I'm only on Chrome 83

**Comment by dolanmiu** [comment]
If thats the case, theres not much we can do?

Chrome security rules is definitely out of scope of this library at the very least
