### ISSUE TITLE
Orientation always flips when Width is longer than height

### ISSUE THREAD

**Issue by nguyen-bao** [dolanmiu/docx#587]
If the width and height that I pass into the docx module are such that the width is longer than the height, the orientation will flip and the width and height will flip. I can think of many ways around this, but I think this behavior is unintuitive and unexpected.

For example, if I add a section with these properties:
- width: 19192
- height: 10800,
- orientation: 'portrait'
then docx produces a section that looks like it has these properties:
- width: 10800
- height: 19192,
- orientation: 'landscape'

And for example, if I add a section with these properties:
- width: 19192
- height: 10800,
- orientation: 'landscape'
then docx produces a section that looks like it has these properties:
- width: 10800
- height: 19192,
- orientation: 'portrait'

I believe the expected behavior would be to maintain the 'portrait' or 'landscape' orientation. Perhaps the width and height may have to flip within the document, but the orientation passed in should not change.

**Comment by dolanmiu** [comment]
I think this must be a word processor specific issue

To my knowledge, I do not think this library flips pages automatically
