### ISSUE TITLE
the docx not working when i uploaded in google driver

### ISSUE THREAD

**Issue by nicholasess** [dolanmiu/docx#59]
When i try to open file in driver, show the message: "Could not convert document."
I used the complete or basic example

```
const docx = require('docx');

var doc = new docx.Document();

var paragraph = new docx.Paragraph("Hello World");
var institutionText = new docx.TextRun("University College London").bold();
var dateText = new docx.TextRun("5th Dec 2015").tab().bold();
paragraph.addRun(institutionText);
paragraph.addRun(dateText);

doc.addParagraph(paragraph);

var exporter = new docx.LocalPacker(doc);
exporter.pack('My Document');

console.log('Document created successfully at project root!');

```

**Comment by WorksOfLiam** [comment]
Hi

I can confirm that `docx@3.2.0` is not working and any files generated are corrupted. Downgrading to `3.1.0` fixes the issue for me.

**Comment by dolanmiu** [comment]
Is this not working in general? Or just for Google Drive?

**Comment by WorksOfLiam** [comment]
Just in general. The code I have generates a document and uses `ExpressPacker` to serve it up.

When opening the file with Word, it errors with this: 
![image](https://user-images.githubusercontent.com/3708366/36105024-80616c5c-100b-11e8-9b6a-327133634d61.png)

**Comment by dolanmiu** [comment]
I will investigate tonight

**Comment by dolanmiu** [comment]
It works for me using ExpressPacker and with Express

Can you send me the word document u generated?

And if you can, the code used to generate the document

**Comment by dolanmiu** [comment]
Works on `runkit`:

https://runkit.com/dolanmiu/docx-demo1

Click on "endpoint"

**Comment by dolanmiu** [comment]
I added most of the demos on the `README`, so you can test this package on the browser, it's very convinient:

https://github.com/dolanmiu/docx/blob/master/README.md

They all seem to work!

**Comment by Chintanvanpariya** [comment]
I am having some issues, can somone please help me.
1. the doc file when made using Localpacker, generates the file but the first page is empty by default. 
2. when i use packPdf and use  docx.ExpressPacker(doc, res) ,    it gives me an error stating- TypeError: exporter.packPdf is not a function.

**Comment by dolanmiu** [comment]
Deprecated.

LocalPacker and Express packer are deprecated and removed

There is only one `Packer` class now which exports it to Buffer, Blob or base64 strings.

It is now up to you to write to disk, or attach to `res.attachment` etc.
