### ISSUE TITLE
can docx dynamically generate directories?

### ISSUE THREAD

**Issue by 2456844450** [dolanmiu/docx#597]
of course the first question I learned for myself was how do I get the page number for each title.
your official document cannot open the contents of the page number section.

**Comment by dolanmiu** [comment]
Page number section of the documentation works for me:

https://docx.js.org/#/usage/page-numbers?id=total-number-of-pages

**Comment by 2456844450** [comment]
the page doesn't seem to open.

**Comment by dolanmiu** [comment]
This link will work: https://github.com/dolanmiu/docx/blob/master/docs/usage/page-numbers.md

**Comment by 2456844450** [comment]
Thanks, this is very useful!
I tried to read your source code , but it didn't seem easy,and I couldn't find a way to debug the code.
