### ISSUE TITLE
Request footnotes

### ISSUE THREAD

**Issue by i-n-g-m-a-r** [dolanmiu/docx#61]
Are you planning on implementing footnotes?
Congrats on very nice work. Awesome api!

**Comment by dolanmiu** [comment]
Yes, I can add footnotes

No ETA, but it requires a lot of work from what I can see! Expect it in the next version

**Comment by i-n-g-m-a-r** [comment]
would be a great feature, tnx!

**Comment by dolanmiu** [comment]
Footnotes are now supported

Will be released in the next version
