### ISSUE TITLE
First header and even header doesn't  work

### ISSUE THREAD

**Issue by hjj1227** [dolanmiu/docx#613]
I 'm using version 5.3.0, when I set first header and even header for a document, The produced docx file has no header,could you please have a check? 

 eg:
 doc.addSection({
    	headers: {
		first: new Header({ 
		children: [new Paragraph("first text")],,
	        }),
	even: new Header({ // The footer on every other page
	children: [new Paragraph("even text")],
	         }),
         },
    	children:documentData,
  });

**Comment by meta-akshita-agrawal** [comment]
Same

**Comment by lbragile** [comment]
I had the same issue, but a work-around that might be suitable for you is to have two different sections:

1. First header which includes the page content under this header.
2. Second header for rest of content.

Something like:
```
doc.addSection({
  headers: {
    default: new Header({
      children: [new Paragraph("first header")],,
    }),
  },
  children: documentDataWithFirstHeader,
});

// Here your data will have a different header
doc.addSection({
  headers: {
    default: new Header({
      children: [new Paragraph("second header")],,
    }),
  },
  children: documentDataWithSecondHeader,
});
```

Of course, this (adding sections) can be repeated to have many different headers.

**Comment by thojansen** [comment]
Not sure if it helps, but the first header is only used when you set the `titlePage` property on the section.
https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.wordprocessing.titlepage?view=openxml-2.8.1
```
properties: {
  titlePage: true
}
```

**Comment by BrentFarese** [comment]
Adding `titlePage: true` will work for first-page header, but I have not yet figured out how to turn on an even footer.  You can create 1 using DOCX, but it doesn't show up.  Per the [OOXML spec](http://officeopenxml.com/WPSectionFooterReference.php):

```
even - the footer should be applied to every even page of the section (counting from the first page, not the section numbering). The actual appearance is dependent upon the setting of the evenAndOddHeaders element in settings.
```

However, I don't see `evenAndOddHeaders` setting available in DOCX.  cc @dolanmiu.

**Comment by dolanmiu** [comment]
Did some research, and it seems like `evenAndOddHeaders` needs to be under a `w:settings` tag:

https://c-rex.net/projects/samples/ooxml/e1/Part4/OOXML_P4_DOCX_evenAndOddHeaders_topic_ID0ET1WU.html

**Comment by dolanmiu** [comment]
This will be fixed in: https://github.com/dolanmiu/docx/pull/828
