### ISSUE TITLE
Documentation site is down

### ISSUE THREAD

**Issue by matthova** [dolanmiu/docx#62]
Awesome project.
I noticed that the documentation site listed isn't working.
http://dolanmiu.github.io/docx

**Comment by dolanmiu** [comment]
Oh yeah, seems like it is

From checking the logs, it keeps skipping the docs by going on this line:

https://github.com/dolanmiu/docx/blob/master/deploy-docs.sh#L13

Will fix soon

**Comment by dolanmiu** [comment]
Fixed:

http://dolanmiu.github.io/docx/index.html
