### ISSUE TITLE
styline in table

### ISSUE THREAD

**Issue by holzfelix** [dolanmiu/docx#623]
Hi together,

I want to style the text in a table, but it dosn't work like in docu mentioned. 

I tried this:

` const table = new Table({
            rows: [
                new TableRow({
                    children: [
                        new TableCell({
                            children: [new Paragraph({
                                bold: true,
                                font: "Calibri",
                                text: "Author"
                            })],
                        }),`

**Comment by holzfelix** [comment]
Worked for me. do you also have an hint for cell background for me? that would be amazing thanks.

**Comment by HTrayford** [comment]
to change the background of a table cell you adjust it's shading property:

`new TableCell({
    children: [new Paragraph({...}),
    shading: { fill: '000066', color: 'FFFFFF' }
})`

this shading will give you a dark blue ('000066') background with white ('FFFFFF') text

**Comment by holzfelix** [comment]
> to change the background of a table cell you adjust it's shading property:
> 
> `new TableCell({ children: [new Paragraph({...}), shading: { fill: '000066', color: 'FFFFFF' } })`
> 
> this shading will give you a dark blue ('000066') background with white ('FFFFFF') text

Thanks already found it in the docs but thanks.
