### ISSUE TITLE
Is it possible to add a HyperLinkRef to a footnote? - example inside

### ISSUE THREAD

**Issue by RayBB** [dolanmiu/docx#627]
Seems related to: https://github.com/dolanmiu/docx/issues/513

I would like to have a footnote with a hyperlink inside of it.
The problem seems to be that `footnotes` must be defined upon doc creation.
However, a `HyperLinkRef` can be defined at doc creation or with `doc.createHyperlink` later.

So if I want a hyperlink in a footnote it doesn't seem possible. But if I'm missing something please let me know.

Thanks!

Example code (not working):
```javascript
// https://github.com/dolanmiu/docx/blob/master/demo/35-hyperlinks.ts
// https://github.com/dolanmiu/docx/blob/master/demo/17-footnotes.ts
let fs = require("fs");
const { Document, HyperlinkRef, HyperlinkType, Packer, Paragraph, Media, FootnoteReferenceRun } = require("docx");

const doc = new Document({
    hyperlinks: {
        myCoolLink: {
            link: "http://www.example.com",
            text: "Hyperlink",
            type: HyperlinkType.EXTERNAL,
        },
    },
    footnotes: [
        new Paragraph("Foo"),
        //new Paragraph("Foo2"),
        new Paragraph({children: [new HyperlinkRef("myCoolLink")]})
    ]
});

doc.addSection({
    children: [
        new Paragraph({
            children: [new HyperlinkRef("myCoolLink"), new FootnoteReferenceRun(1), new FootnoteReferenceRun(2)
        ],
        })
    ],
});

Packer.toBuffer(doc).then((buffer) => {
    fs.writeFileSync("My Document.docx", buffer);
});
doc.createHyperlink
```

**Comment by dolanmiu** [comment]
This is now fixed in https://github.com/dolanmiu/docx/pull/789

Problem was there wasn't a footnotes relationship file, so when adding a hyperlink, `docx` didn't know where to add the relationship
