### ISSUE TITLE
Document or Section Background-color support?

### ISSUE THREAD

**Issue by dkipp** [dolanmiu/docx#628]
In microsoft word it is posible to set background colors other than white.
Is it posible with this library too?

Buy the way, there is a non working example in the docs: In 'Styling with JS -> Declaritive Styles (similar to external CSS)'

```javascript
color: "999999",
{
  type: UnderlineType.DOUBLE,
  color: "FF0000",
},
```

maybee with underline?
```javascript
color: "999999",
underline: 
{
  type: UnderlineType.DOUBLE,
  color: "FF0000",
},
```

**Comment by v-bondarenko364** [comment]
@dkipp Yes it's possible to set background color for words, see example here:
https://github.com/dolanmiu/docx/blob/master/demo/45-highlighting-text.ts

**Comment by dkipp** [comment]
Sorry for being not explicit enough, I'd like to change the background of the whole document or a section, not just a single word. Like it is possible with "Microsoft word"

**Comment by silinca18** [comment]
> Sorry for being not explicit enough, I'd like to change the background of the whole document or a section, not just a single word. Like it is possible with "Microsoft word"

This will be a nice feature. ( I'm also looking for this functionality )

**Comment by dolanmiu** [comment]
This is coming soon here:

https://github.com/dolanmiu/docx/pull/667

**Comment by dkipp** [comment]
awesome.
There is a typo in:  docs/usage/document.md

hax => hex

**Comment by dolanmiu** [comment]
Thanks

Typo fixed
