### ISSUE TITLE
How to force table cell no-wrap?

### ISSUE THREAD

**Issue by elementalPRESS** [dolanmiu/docx#629]
Is it possible or how is it possible to specify a TableCell where the content is **not** wrapped to a new line?

**Comment by HTrayford** [comment]
The TextWrappingType enum has a `NONE` option, I haven't tried it to see if that works, have you?

**Comment by dolanmiu** [comment]
From doing some research, it seems the only way is to set the correct widths of your document:

https://support.microsoft.com/en-us/office/set-table-cells-to-expand-with-contents-in-word-eab1b881-07bc-4877-8a83-6199f037435f?ui=en-us&rs=en-us&ad=us
