### ISSUE TITLE
How to maintain header distance from top

### ISSUE THREAD

**Issue by zeco2309** [dolanmiu/docx#638]
The default header distance from top is 1.25cm. My task requires it to be tinier. I couldn't find anything in manual nor in templates. Does such function exist?

**Comment by rohit4799** [comment]
We can change header and footer distance in addSection
doc.addSection({
        margins: {
          header: 400, //header distance from top
          footer: 400, //footer distance
        },
      });

**Comment by ehdwns980416** [comment]
+1

**Comment by thojansen** [comment]
Side Remark: I think it would be cool to include these "convenience functions". Likely everyone is implementing them 😆 at some point.

<img width="404" alt="Screenshot 2020-11-23 at 12 15 28" src="https://user-images.githubusercontent.com/5912220/99956014-95ad6080-2d85-11eb-965d-d18118e90a3a.png">

**Comment by dolanmiu** [comment]
Great idea @thojansen! Created a PR to add Convenience functions into `docx`

**Comment by thojansen** [comment]
super cool !!!
