### ISSUE TITLE
Fix highlighting with custom colors

### ISSUE THREAD

**Issue by bre7** [dolanmiu/docx#647]
highlight is currently broken, custom colors don't work.

2 possible solutions:

1. Re-implement using shading instead (`<w:shd w:fill="FF6D6D" w:val="clear"/>`)
    -> Named colors not supported, need to be converted to hex
2. Use `<shd>`/`<highlight>` depending on `highlight`'s `color` parameter 👈

Works:
```xml
<w:shd w:fill="FF6D6D" w:val="clear"/>
<w:highlight w:val="yellow"/>
```

Doesn't work:
```xml
<w:highlight w:val="FF6D6D"/>
<w:shd w:fill="yellow" w:val="clear"/>
```

Highlight only accepts the following `val`ues (http://officeopenxml.com/WPtextShading.php):
> black, blue, cyan, darkBlue, darkCyan, darkGray, darkGreen, darkMagenta, darkRed, darkYellow, green, lightGray, magenta, none, red, white, yellow

**Comment by dolanmiu** [comment]
> Highlight only accepts the following values

This is correct, highlight indeed does support only a fixed set of values, and we should respect this
