### ISSUE TITLE
How to check if a section is broken by page break

### ISSUE THREAD

**Issue by xeiaaa** [dolanmiu/docx#649]
I'm currently creating an app that generates a docx file with a signature block at the last part. The other parts before the signature block is dynamic, so there are some cases that the signature block is broken by page break (see the first picture). If ever it was broken, I'd like to move the whole signature block to the next page (see second image). Does anyone know how can I do it? The details on the top of the document varies so much, so it's a little hard to check when it will generate something like on the first image. 

![image](https://user-images.githubusercontent.com/23055744/95030932-8561f900-06e5-11eb-9a2b-cfc0f48c90a7.png)
![image](https://user-images.githubusercontent.com/23055744/95030961-b3473d80-06e5-11eb-8f33-f0352d644166.png)

**Comment by dolanmiu** [comment]
I do not think there is a way I am afraid, maybe create a function which calculates the length of the body of the text?

**Comment by vasslehel** [comment]
Can't this be achieved by using `keepNext`?

**Comment by dolanmiu** [comment]
Yes, this can be achieved with `keepNext`

I misunderstood the issue. I thought he wanted a `boolean` value returned weather or not a paragraph was broken by a page break
