### ISSUE TITLE
Uncaught ReferenceError: Table is not defined

### ISSUE THREAD

**Issue by volhardend** [dolanmiu/docx#656]
First of all, I want to apologize for my bad English, it's not my native language.

I'm trying to use this plugin without installing it with npm (we don't have it on our project). So I tried using the "cdn" version (https://cdn.jsdelivr.net/npm/docx@5.3.0/build/index.min.js) and it works, but when i want to create a table, it trows me the message in the title, I tried using import, didn´t work either, so I don't know what to do, I search all over the internet but didn't find anything useful, I hope you can help me and thank you so much in advance for your response.

**Comment by dolanmiu** [comment]
Can you show me your code?

perhaps you need to prefix it is `docx.`

**Comment by dolanmiu** [comment]
Closing as theres no follow up
