### ISSUE TITLE
Removing underline from hyperlink & modifying style of TOC

### ISSUE THREAD

**Issue by lbragile** [dolanmiu/docx#659]
I have two questions which I asked on StackOverflow but so far have not gotten a response.

1. https://stackoverflow.com/questions/64381067/how-to-remove-the-underline-from-docx-js-hyperlink
   
  **Question:**
  To add a hyperlink, I used this example (modified for my needs and gave MWE below):
   https://github.com/dolanmiu/docx/blob/master/demo/35-hyperlinks.ts

```
const doc = new Document({
  styles: {
    paragraphStyles: [
      {
        id: "link",
        name: "link",
        basedOn: "Heading2",
        next: "Heading2",
        quickFormat: true,
        run: {
          italics: false,
          color: "000000",
          underline: { color: "FFFFFF" }
        },
      },
    ]
  }

  hyperlinks: {
    myCoolLink: {
        link: "http://www.google.com",
        text: "Google",
        type: HyperlinkType.EXTERNAL,
    },
  },
});

doc.addSection({
  children: [
    new Paragraph({
        children: [new HyperlinkRef("myCoolLink")],
        style: "link",
    }),
  ],
});
```
However, this gives a link with letters that are somewhat "hidden", like the tail of `g`, `y`, `p`, etc.

Is there a way to override this? Maybe adding a margin between the link and underline?

2. https://stackoverflow.com/questions/64383132/modifying-style-of-docx-toc-using-javascript-docx-js

**Question:**
Following this tutorial, https://docx.js.org/#/usage/table-of-contents, I would like to do the following two things:

- Change the font & size of entries in the table as the default `Times New Roman - 10` is too small.
- Remove the "leading dots" from entries to page numbers: `a.......1` to `a       1`

**What I tried (with no success):**

- All my entries are based on Heading1 so their level is 1. `stylesWithLevels: [new StyleLevel("Style", 1)]`. This produces no change whatsoever.
- `entryAndPageNumberSeparator: "\t"` gives leading dots (`a.......1`), while `entryAndPageNumberSeparator: " "` gives `a 1`. I tried other combinations like `entryAndPageNumberSeparator: " \t"` to no avail. It seems like only the first character is taken into consideration.

Both of these were tested individually with a working TOC (modified from the above tutorial):
```
new TableOfContents("Example", {
  hyperlink: true,
  headingStyleRange: "1-1",
}),
```

Thank you in advance for taking the time to respond!

**Comment by dolanmiu** [comment]
Hyperlinks are now fully customisable, all styles can be changed!

Hyperlinks now take a child component, which means hyperlinks can be anything you want, go wild. It can even be images etc!

https://github.com/dolanmiu/docx/pull/784
