### ISSUE TITLE
Issue when adding image from base64

### ISSUE THREAD

**Issue by DASoftware** [dolanmiu/docx#660]
Trying to add an image to the document, converting it to a base64, i copied over the string generated and tested out that the image is correctly generated. but when i add it to the document i get a placeholder with the text "The picture cant be displayed".

const logo = Media.addImage(doc, Buffer.from(this.base64Image, 'base64'), 500, 160);

and using it as, new Paragraph(logo).
Using Angular 8.

Thanks in advance.

**Comment by ErikYu** [comment]
Try remove the "data:image......;base64" prefix from base64 string.

**Comment by DASoftware** [comment]
Thanks for the quick response, but i have already tried that.

**Comment by dolanmiu** [comment]
Check out the example here:

https://github.com/dolanmiu/docx/blob/master/demo/23-base64-images.ts

**Comment by fpaupier** [comment]
In browser, the following snippet worked for me
```js
const base64String = b64Img.replace(/^data:image\/(png|jpg);base64,/, ''); // Remove data URL prefix and only keep the base64-encoded string
const imageData = Uint8Array.from(atob(base64String.replace(/[^A-Za-z0-9+/]/g, '')), c => c.charCodeAt(0)); // Convert base64-encoded string to Uint8Array
return new docx.ImageRun({
    data: imageData,
    transformation: {
        width: 10,
        height: 100,
    },
});
```
