### ISSUE TITLE
release new version

### ISSUE THREAD

**Issue by thojansen** [dolanmiu/docx#670]
@dolanmiu: I was wondering if it would be possible to release a new version to `npm`. The current verison `5.3.0` is already 3 months old and I cannot easily point directly to the latest commit on the master branch, since the build step is missing and if I try to build it in a postinstall step, I run into various typescript problems. So the only other option would be to also push it to npm under another name.

**Comment by dolanmiu** [comment]
Will do later this week!

Wanted to put in some extra changes before `5.4.0`

**Comment by dolanmiu** [comment]
Released!
