### ISSUE TITLE
Add comments part

### ISSUE THREAD

**Issue by BrentFarese** [dolanmiu/docx#675]
**_Feature Request:_**

[ECMA Office Open XML Part 1 - Section 11.3.2](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-376,%20Fifth%20Edition,%20Part%201%20-%20Fundamentals%20And%20Markup%20Language%20Reference.zip) specifies a Comments Part for Word documents.  Section 17.13 also outlines Annotations including Comments at Section 17.13.4.  I cannot find detailed reference to the comments part on [officeopenxml.com](http://officeopenxml.com/), which is somewhat weird.

In any case, it would be great if DOCX had comment support so we could build comments into a document.  Is this a highly-requested feature?  We might be able to dedicate some resources to trying to implement it.

Thanks!

Some snippets from the ECMA spec:

<img width="928" alt="Screen Shot 2020-11-02 at 9 34 26 PM" src="https://user-images.githubusercontent.com/25846953/97944699-54f89380-1d53-11eb-9d7f-372bc14cef9b.png">

<img width="944" alt="Screen Shot 2020-11-02 at 9 34 45 PM" src="https://user-images.githubusercontent.com/25846953/97944703-56c25700-1d53-11eb-98df-12ec493e6c91.png">

**Comment by thojansen** [comment]
Would love to have that feature, too. Here are the references from the Microsoft API References. They usually also provide a few examples. It seems that `commentReference`, `comments/ comment`, `commentRangeStart` and `commentRangeEnd` are needed.

https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.wordprocessing.comment?view=openxml-2.8.1
https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.wordprocessing.commentrangestart?view=openxml-2.8.1
https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.wordprocessing.commentrangeend?view=openxml-2.8.1
https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.wordprocessing.commentreference?view=openxml-2.8.1
