### ISSUE TITLE
missing Example and Doc: Styling with JS -> Document defaults

### ISSUE THREAD

**Issue by dkipp** [dolanmiu/docx#683]
The documentation for **Styling with JS -> Document defaults** is almost empty.
[https://docx.js.org/#/usage/styling-with-js?id=document-defaults](url)
Is there an example how we can use that feature?

**Comment by dolanmiu** [comment]
Yes:

https://github.com/dolanmiu/docx/blob/master/demo/11-declaritive-styles-2.ts
