### ISSUE TITLE
How to style none declarative?

### ISSUE THREAD

**Issue by dkipp** [dolanmiu/docx#684]
How to style an existing (dolanmiu/docx) Document. lets take "demo/10-my-cv.ts" as an example.

    // line 340
    const doc = documentCreator.create([experiences, education, skills, achievements]);

    /* How to add a character style here that makes all bold elements red? or try a different Paragraph font */

    Packer.toBuffer ...

If I don't want to edit the document definition, but see how appealing it would be if all bold elements are in red.

**Comment by dolanmiu** [comment]
You are thinking of styles:

https://github.com/dolanmiu/docx/blob/master/demo/2-declaritive-styles.ts
https://github.com/dolanmiu/docx/blob/master/demo/11-declaritive-styles-2.ts
