### ISSUE TITLE
Basic functions like adding a Table or Media.addImage are not recognized by browser

### ISSUE THREAD

**Issue by aghosh03** [dolanmiu/docx#686]
I'm trying to export a table and image to MS Word using Docx.js in the browser but basic functions like Table or Media are not being recognized by the browser.  For some reason the exact code works in JsFiddle, but not in any other browser.  Has anyone experienced this issue and if so, is there a fix? 

I'm receiving the following error message in console: **"Uncaught ReferenceError: Table is not defined"**

Below is my sample code:

`
<html>

<head>
<script src="https://unpkg.com/docx@5.0.2/build/index.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.8/FileSaver.js"></script>

</head>

<body>

    <h1>DOCX browser Word document generation</h1>

    <button type="button" onclick="generate()">Click to generate document</button>

    <script>
        function generate() {
            const doc = new docx.Document();
            
            const table = new Table({
                rows: [
                    new TableRow({
                        children: [
                            new TableCell({
                                children: [new Paragraph("Hello")],
                            }),
                            new TableCell({
                                children: [new Paragraph("World!!!")],
                            }),
                        ],
                    }),
                    new TableRow({
                        children: [
                            new TableCell({
                                children: [new Paragraph("bla bla bla")],
                            }),
                            new TableCell({
                                children: [new Paragraph("bla bla bla")],
                            }),
                        ],
                    }),
                ],
            });

            doc.addSection({
                children: [table],
            });

            docx.Packer.toBlob(doc).then(blob => {
                console.log(blob);
                saveAs(blob, "example.docx");
                console.log("Document created successfully");
            });
        }
    </script>

</body>

</html>
`

**Comment by dkipp** [comment]
It works for me if you add "docx." I just tested it with the current version 5.4.0

new Table => new docx.Table
new TableRow => new docx.TableRow
new TableCell=> new docx.TableCell
new Paragraph=> new docx.Paragraph

that's it

**Comment by aghosh03** [comment]
Thank you so much!!!!  It worked! You're Awesome!
