### ISSUE TITLE
"export 'Document' was not found in 'docx'

### ISSUE THREAD

**Issue by dimitrisdovinos** [dolanmiu/docx#689]
Having trouble importing Document (or any other class) inside a React app.

Any idea why this is happening?

**Comment by dolanmiu** [comment]
check out this example written in React

https://stackblitz.com/edit/react-ts-qq25sp

Works for me fine

**Comment by seans84** [comment]
In case anyone stumbles upon this, I spent the better part of a day finding a solution. I believe this issue is isolated to using Rails with Webpacker. You have to specifically opt-out of using the default `nodeModules` loader like this:

```
const nodeModulesLoader = environment.loaders.get('nodeModules');
nodeModulesLoader.exclude.push(/docx/);
```
