### ISSUE TITLE
fs.readFileSync not recognized when adding image using html/js

### ISSUE THREAD

**Issue by aghosh03** [dolanmiu/docx#696]
I'm using html and js but "fs.readFileSync" doesn't seem to be recognized when trying to add an image.  I tried adding "docx" in front of "fs" and then it doesn't recognize readFileSync.  Below is my code:

`let image = docx.Media.addImage(doc, fs.readFileSync("Image.png"), 200, 200, {
            floating: {horizontalPosition: {offset: 1014400,},verticalPosition: {offset: 1014400,},},
        });`

 Any advice is much appreciated.   Thanks.

**Comment by dolanmiu** [comment]
`fs` does not exist in a browser environment

Please use an alternative. There are examples in the demo folder to show how to add images without `fs`
