### ISSUE TITLE
Table support

### ISSUE THREAD

**Issue by felipeochoa** [dolanmiu/docx#7]
Hey @dolanmiu -- I've started working on a table implementation for `docx`. You can see the initial work at felipeochoa/docx@04c489fed798cf. If you have the time, I have a couple of questions I want to check with you and discuss the preliminary API:

* `XmlComponent#clearVariables` is there to make sure that JSON-ifying the components results in something that `xml` will understand, correct? Does it have any other uses? Did you consider implementing it generically (similar to `XmlComponent#replaceKey`) at the base class?
* The initial implementation does not offer any way of modifying the structure of a table; only its cell contents (a paragraph) can be edited. This is in some ways similar to the way a paragraph style can only be applied once. Not sure if you'd like to eventually have all of these be proper getters and setters or if write-once is good enough. The way you use the current version is:

    ```js
    var table = new docx.Table(numRows, numCols);
    var contentParagraph = table.getRow(x).getCell(y).content;
    // contentParagraph is a regular paragraph which you can modify as you please
    table.properties.setWidth('pct', 50 * 100);  // measured in .02%
    // In theory you could add more properties to table.properties...
    doc.addTable(table);
    ```

* Is there any opportunity for sharing code across components? I ask because writing this much of the table felt very boiler-platish, but I don't know since I'm not as familiar with the spec and the other components.

**Comment by dolanmiu** [comment]
I am having a look at `clearVariables` now, and it seems like it literally doesn't do anything. I think I remember adding it, then realising it was probably not a good idea, but left it in there, for derp reasons.

But yes, you are correct, it was originally to **_"clense"_** the JSON, so `xml` can understand and parse correctly.

I would need to go through and delete this at some point.

Yes, I am a huge fan of getters and setters

I like how it is at the moment, but I think this would be nicer:
```ts
table.properties.setWidth(Unit.Percent, 50 * 100);
```

Or force the user to only use one type of Unit to keep it simple...
```ts
table.properties.width = 100 // In pixels.
```

But I don't know, what do you think? Or maybe have both for flexibilty

For styling, I envision one day for there to be a "style-generator" Angular2 website, with a nice GUI. You could pick colours, font, size, padding, then press "Generate" and it will create some JSON config. You plug this config into the docx document, and **BAM** styled.

It depends if the spec is the same. I will have a look at the spec too. I am quite against having a `common` folder to cram all the common stuff in. That folder will get messy quite fast

**Comment by dolanmiu** [comment]
I see paragraph it in the table. We should make the table use the Paragraph class, so there is only **one** Paragraph class.

**Comment by dolanmiu** [comment]
@felipeochoa 
Not sure if too late, but this may help:

https://github.com/dolanmiu/Office-Open-XML-Reference/wiki/Table-Structure

**Comment by felipeochoa** [comment]
Thanks! The table effort is paused ATM. I'm doing some work on
styles---similar to what I did with numbering---that will make it much
easier to define and use custom styles! After that, I think it will be
tables :)

**Comment by dolanmiu** [comment]
Can this be closed now as tables are done? 😀

**Comment by felipeochoa** [comment]
Yes! I eventually want to add support for table styles, but I think that's a separate issue
