### ISSUE TITLE
Missing: TextRun declarative break

### ISSUE THREAD

**Issue by devoidfury** [dolanmiu/docx#704]
In the docs here, it shows passing a `break: true` option.
https://docx.js.org/#/usage/text?id=break

However this is not implemented, and requires calling the `break()` method:
https://github.com/dolanmiu/docx/blob/master/src/file/paragraph/run/run.ts

**Comment by dolanmiu** [comment]
Good find

Will make a fix shortly

**Comment by devoidfury** [comment]
Something to consider - passing a number as a parameter there for more than one line break. I wrote a wrapper function to do this, which currently just calls `.break()` some number of times.

**Comment by dolanmiu** [comment]
> Something to consider - passing a number as a parameter 

Great suggestion! added it in this PR:

https://github.com/dolanmiu/docx/pull/734
