### ISSUE TITLE
Table width is not working

### ISSUE THREAD

**Issue by jaguarsiva** [dolanmiu/docx#706]
I tried giving width to the table, it is not working. I tried giving width to the table cell also, it does not work there also. I'm getting a very thin table. I want a table of full width. Someone help me fix this.

**Comment by HTrayford** [comment]
`const wideTable = new Table({
    rows: [
        new TableRow({
            children: [
                new TableCell({
                    width: { size: 66, type: WidthType.PERCENTAGE },
                    children: [
                        new Paragraph({
                            children:[
                                new TextRun({
                                    text: 'Some wide text for first cell in first row'
                                })
                            ]
                        })
                    ]
                }),
                new TableCell({
                    width: { size: 33, type: WidthType.PERCENTAGE },
                    children: [
                        new Paragraph({
                            children:[
                                new TextRun({
                                    text: 'Some wide text for second cell in first row'
                                })
                            ]
                        })
                    ]
                })
            ]
        }),
        new TableRow({
            children: [
                new TableCell({
                    width: { size: 66, type: WidthType.PERCENTAGE },
                    children: [
                        new Paragraph({
                            children:[
                                new TextRun({
                                    text: 'Some wide text for first cell in second row'
                                })
                            ]
                        })
                    ]
                }),
                new TableCell({
                    width: { size: 33, type: WidthType.PERCENTAGE },
                    children: [
                        new Paragraph({
                            children:[
                                new TextRun({
                                    text: 'Some wide text for second cell in second row'
                                })
                            ]
                        })
                    ]
                })
            ]
        })
    ]
})

const narrowTable = new Table({
    width: {
        size: 4525,
        type: WidthType.DXA
    },
    rows: [
        new TableRow({
            children: [
                new TableCell({
                    width: { size: 33, type: WidthType.PERCENTAGE },
                    children: [
                        new Paragraph({
                            children:[
                                new TextRun({
                                    text: 'Some text for first cell in first row'
                                })
                            ]
                        })
                    ]
                }),
                new TableCell({
                    width: { size: 66, type: WidthType.PERCENTAGE },
                    children: [
                        new Paragraph({
                            children:[
                                new TextRun({
                                    text: 'Some text for second cell in first row'
                                })
                            ]
                        })
                    ]
                })
            ]
        }),
        new TableRow({
            children: [
                new TableCell({
                    width: { size: 33, type: WidthType.PERCENTAGE },
                    children: [
                        new Paragraph({
                            children:[
                                new TextRun({
                                    text: 'Some text for first cell in second row'
                                })
                            ]
                        })
                    ]
                }),
                new TableCell({
                    width: { size: 66, type: WidthType.PERCENTAGE },
                    children: [
                        new Paragraph({
                            children:[
                                new TextRun({
                                    text: 'Some text for second cell in second row'
                                })
                            ]
                        })
                    ]
                })
            ]
        })
    ]
})

doc.addSection({
    children: [wideTable],
});

doc.addSection({
    children: [narrowTable]
})

![Table With Width](https://user-images.githubusercontent.com/35882155/101507325-ac31eb00-3933-11eb-91cf-395dc5575700.png)
`
