### ISSUE TITLE
Numbering for nested lists

### ISSUE THREAD

**Issue by bkmalan** [dolanmiu/docx#707]
Hi,
First of all, this is an amazing library and I would like to thank all the contributors for doing an amazing job!

My issue is that , I want nested numbering for nested lists meaning this is the current behavior,
![image](https://user-images.githubusercontent.com/55806149/101451659-7f410080-3952-11eb-9805-d6b2e2cb7677.png)

Expected behavior is
![image](https://user-images.githubusercontent.com/55806149/101451588-63d5f580-3952-11eb-80fe-91972b8de861.png)

Kindly let me know if there's a way around to achieve this.

Cheers,

**Comment by HTrayford** [comment]
The key is add this: `text: '%1.%2'`

{
              level: 1,
              format: 'decimal',
              text: '%1.%2',
              alignment: AlignmentType.START,
              style: {
                paragraph: {
                  indent: { left: 1.25 * leftIndent, hanging: 1.25 * hangingIndent }
                },
                run: {
                  bold: true,
                  size: subSectionFontSize * 2,
                  font: primaryFont
                }
              }
            },

**Comment by dolanmiu** [comment]
Thanks @HTrayford 

I have created a demo to showcase this using your example provided:

https://github.com/dolanmiu/docx/blob/master/demo/57-add-parent-numbered-lists.ts
