### ISSUE TITLE
Is there a way to dynamically create table rows depending on how much data I have?

### ISSUE THREAD

**Issue by 15ahl1** [dolanmiu/docx#709]
I want to create a table in the word document but the number of rows in the table won't be known until Run-Time. I want to know if I can somehow use a for-loop to add as many table rows as I need.

**Comment by HTrayford** [comment]
@15ahl1 Create an array and inside your for loop, create a TableRow and push it into the array.  After creating as many rows as you desire, pass the array to the "rows" option when creating your Table.

const rows = [];
for (let i = 0; i < rowChildren.length; i++) {
  rows.push(new TableRow({
    children: rowChildren[i], //each entry is an array of TableCell that make up this row
    cantSplit: true,
    tableHeader: false
  }))
}

const table = new Table({
  rows: rows,
  alignment: AlignmentType.CENTER
})

**Comment by dolanmiu** [comment]
Or even better:

```ts
const table = new Table({
  rows: rowChildren.map((r) => new TableRow({
    children: r, //each entry is an array of TableCell that make up this row
    cantSplit: true,
    tableHeader: false
  })),
  alignment: AlignmentType.CENTER
});
```
