### ISSUE TITLE
Error header, children is not iterable

### ISSUE THREAD

**Issue by ACDR-Programming** [dolanmiu/docx#712]
When I create the header I get the following error, I would appreciate your help.
![Error](https://user-images.githubusercontent.com/65685487/101691910-65c8b300-3a3d-11eb-8be1-403a312f190a.png)
![Codigo](https://user-images.githubusercontent.com/65685487/101691887-59445a80-3a3d-11eb-8e41-8d51cfd1d07f.png)

**Comment by adriNooo** [comment]
Have the same issue here. Getting `Uncaught (in promise) TypeError: s is not iterable
    at e.File.addSection...`,
```
doc.addSection({
                                
                                    headers: {
                                
                                        default: new docx.Header({
                                            children: [new docx.Paragraph('fdfdf')],
                                        }),
                                        children: [new docx.Paragraph("Header text")],
                                
                                    },
                                
                                
                                
                                });
```

**Comment by ACDR-Programming** [comment]
Try adding a "children" element outside the "headers".
`doc.addSection({
  headers: {
    default: new docx.Header({
      children: [new docx.Paragraph('Text Header')],
    })
  },
  children:[new.docx.Paragraph("text")]
});`

**Comment by TheDarkStrix** [comment]
@dolanmiu  
```
headers: {
          default: new Header({
            children: [new Paragraph("Text Header")],
          }),
        },
```

I am trying to add header to the page : 
```
Unhandled Runtime Error
TypeError: children is not iterable
```

any help is very much appreciated

**Comment by dolanmiu** [comment]
What is your full code? Have you checked the examples? they work

**Comment by acdrDev** [comment]
@TheDarkStrix 
try this:
`New Document({
    headers: {
        default: new Header({
            children: [new Paragraph("Text Header")],
        }),
    },
    children:[new docx.Paragraph("text")]
});`

Adding that last "children" will allow iteration of the object.

**Comment by dolanmiu** [comment]
Right, so it seems children is required for a document to be valid, it should have a default value

**Comment by dolanmiu** [comment]
This is a non-issue, the TypeScript interface specfies that it needs a children array

TypeScript should warn you about this
