### ISSUE TITLE
Cannot find name 'Buffer'

### ISSUE THREAD

**Issue by piyushdp333** [dolanmiu/docx#721]
Hello, 
Greetings,
after installing and configuring this package I got below error message. can any one help me to resolve this issue?

Error:
Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i @types/node` and then add `node` to the types field in your tsconfig.

**Comment by dolanmiu** [comment]
Yes do try that. If you are in a browser environment, there is no such thing as `Buffer`.

This issue is out of scope of this package, will close

**Comment by piyushdp333** [comment]
I have resolved this issue. We need to add node type in tsconfig.app.json file.
compilerOptions:{
"type":["node"]
}
