### ISSUE TITLE
How to set no borders on table?

### ISSUE THREAD

**Issue by ehdwns980416** [dolanmiu/docx#725]
I want to set my table with no borders. But, I can't find any document about it.
When I look at the module, borders are set as default. So I have to code like below to remove borders.

```javascript
new Table({
    ...,
    borders: {
        top: {
            style: BorderStyle.SINGLE,
            size: 0,
            color: 'white',
        },
        bottom: {
            style: BorderStyle.SINGLE,
            size: 0,
            color: 'white',
        },
        left: {
            style: BorderStyle.SINGLE,
            size: 0,
            color: 'white',
        },
        right: {
            style: BorderStyle.SINGLE,
            size: 0,
            color: 'white',
        },
    },
})
```

Is there any other way?

**Comment by dolanmiu** [comment]
Nope, this is the only way

It is a bit tedious, I am aware

Perhaps I can add a "short hand" way in the next release

**Comment by dolanmiu** [comment]
Made a PR here to add a convenience object for no borders:

https://github.com/dolanmiu/docx/pull/729
