### ISSUE TITLE
Not downloading with GET request

### ISSUE THREAD

**Issue by ericoSoares** [dolanmiu/docx#73]
What I am trying to acocomplish is the same as you have in your website, the user clicks a button, which accesses the endpoint, generates and downloads the DOCX. 
When I access the endpoint directly from the route ("localhost:3000/api"), the DOC is generated as expected, but when I make an AJAX get request to the endpoint, the messages are logged to the console but the DOC is not generated/downloaded.
This is the code for the endpoint:

```
app.get("/api", (req, res) => {

    var doc = new docx.Document();
    const table = doc.createTable(4, 4);
    table.getCell(2, 2).addContent(new docx.Paragraph('Hello'));
    const expressPacker = new docx.ExpressPacker(doc, res);
    expressPacker.pack("Document");
    console.log("ENDPOINT REACHED");

});
```

And this is the code for the AJAX request using jQuery:
```
<script>
    $('button').click(() => {
        $.get("http://localhost:3000/api", (data) => {
            console.log("works");
        });
    });
</script>
```

I imagine it is some kind of problem due to conflits with the express response object, but I am not so sure.
I am using:
docx: 3.4.0
express: 4.16.3
Running on Windows 10, using Chrome.

Any ideas on what could be the problem?

**Comment by dolanmiu** [comment]
Is it because you need to set the content type? I am guessing because the computer doesn't know what file it is:

https://www.designedbyaturtle.co.uk/2016/how-to-force-the-download-of-a-file-with-http-headers-and-php/

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type

**Comment by ericoSoares** [comment]
I tried both and still didn't work, this is the request reported in the network tab of chrome dev tools:
### General:
Request URL: http://localhost:3000/api
Request Method: GET
Status Code: 200 OK
Remote Address: [::1]:3000
Referrer Policy: no-referrer-when-downgrade
### Response Headers:
Connection: keep-alive
Content-Disposition: attachment; filename="Document.docx"
Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document
Date: Tue, 08 May 2018 12:22:13 GMT
Transfer-Encoding: chunked
X-Powered-By: Express
### Request Headers:
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7
Connection: keep-alive
Host: localhost:3000
Referer: http://localhost:3000/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
X-Requested-With: XMLHttpRequest

Do you have any working examples on how to do this? Doesn't need to be with jQuery or anything specific, I just need to see what is the right way to do this.

Thanks for your time.

**Comment by ericoSoares** [comment]
Ok, I managed to find a solution:
```
$('button').click(() => {
        $.ajax({
            url: '/api',
            type: 'GET',
            success: function () {
                window.location = '/api';
            }
        });
    });
```
Forcing the browser to visit the route triggers the download. Thank you!

**Comment by dolanmiu** [comment]
No problem :)

I am glad you got the solution
