### ISSUE TITLE
How to shading TextRun including spaces

### ISSUE THREAD

**Issue by ehdwns980416** [dolanmiu/docx#730]
> Actually, I think this is not an issue, but I desperately need your ideas and experiences.
> Plz share your idea.

### What I want to do

- First, I want to make a little `number box`(?) like below.\

<img src="https://user-images.githubusercontent.com/26425092/102949752-5c931800-450c-11eb-959f-b1eff6477f57.png" width="40%">

- And this is what I coded.

```javascript
new TextRun({
    text: '  1  ',
    bold: false,
    color: '000000',
    size: 20,
    shading: {
        type: ShadingType.CLEAR,
        color: 'E5E5E5',
        fill: 'E5E5E5',
    },
});
```

- I thought I made it. But there was a problem.

### Problems
<img src="https://user-images.githubusercontent.com/26425092/102949801-7df40400-450c-11eb-9214-878ab49181b7.png" width="50%">
<img src="https://user-images.githubusercontent.com/26425092/102949814-85b3a880-450c-11eb-9c6b-8004bfcaff3d.png" width="50%">

- As shown in the pictures above,
when the box moved to the edge, I could see that the empty space disappeared.

- I tried putting a blank character instead spaces, but the problem is same.
- Is there any solution? Plz share your ideas. 🙏

**Comment by dolanmiu** [comment]
Try using a `blank character` instead of space:

https://www.compart.com/en/unicode/U+2800

**Comment by ehdwns980416** [comment]
Brilliant !!
