### ISSUE TITLE
Adding 'line between' to column

### ISSUE THREAD

**Issue by deathg0d** [dolanmiu/docx#732]
(Feature request) We are able to create columns using the following code, however we only have `space` and `count` input currently available. Could we also add the `line between` property?
```
doc.addSection({
    ...
        properties: {
          column: {
            space: ...,
            count: 2,
          }
        },
    ...
```

![image](https://user-images.githubusercontent.com/2324523/102991179-da711680-4540-11eb-84e5-b1d7f0c98a29.png)

**Comment by dolanmiu** [comment]
Will be added in https://github.com/dolanmiu/docx/pull/796

Thanks! :)
