### ISSUE TITLE
Adding headers/footers declaratively does not work

### ISSUE THREAD

**Issue by BrentFarese** [dolanmiu/docx#740]
Adding headers/footers declaratively using the `Document` constructor does not seem to work.  However, it **_does_** work just fine if you use `doc.addSection`.  Contrived example that does **_not_** work:

```
const document = new Document({}, {}, {children: [], footers: {
  default: new Footer({children: new Paragraph() })
}})
```

I believe it is because the addition of sections if you provide them declaratively using `new Document` is [different](https://github.com/dolanmiu/docx/blob/d41ef99c85e126fb8021eed47fb96c1e7f91bb9e/src/file/file.ts#L133-L145) than the [addition of sections](https://github.com/dolanmiu/docx/blob/d41ef99c85e126fb8021eed47fb96c1e7f91bb9e/src/file/file.ts#L181-L214) using `addSection`.  When using `addSection`, the proper headers/footers are created using `this.createHeader` and `this.createFooter`.

I would think that both methods of instantiating a `Document` should work the same.

**Comment by JovanKanevche** [comment]
Weirdly it only happens to the footers element.

**Comment by dolanmiu** [comment]
This now works in `6.0.0` as the only way to add headers and footers are declaratively!

The old imperative way is gone
