### ISSUE TITLE
Consider switching to a smaller ZIP library

### ISSUE THREAD

**Issue by 101arrowz** [dolanmiu/docx#742]
Over the past few months, I've developed [`fflate`](https://github.com/101arrowz/fflate). It's a ZIP library that would replace JSZip, but it's much faster and an order of magnitude smaller. You can check the [demo](https://101arrowz.github.io/fflate) and see the benchmarks within the library to see this for yourself. Let me know if you'd be interested in switching, and I'll draft a PR.

**Comment by dolanmiu** [comment]
Does it work on node and on the browser?

**Comment by 101arrowz** [comment]
Yes, that is true, it's quite a new library. But many major projects have already switched, and I usually fix issues within a day.
- [Three.js](https://github.com/mrdoob/three.js/issues/20941)
- [rrweb](https://github.com/rrweb-io/rrweb/pull/448)
- [PostHog](https://github.com/PostHog/posthog-js/pull/151) ([backend here](https://github.com/PostHog/posthog))
- SheetJS soon plans to switch [(listed in dependencies)](https://github.com/SheetJS/sheetjs/blob/master/package.json#L41)
- A few others, e.g. [Polkadot.js](https://github.com/polkadot-js/wasm/pull/159)

ZIP compression  is the most well-tested function in the library, and I haven't gotten any bugs related to it yet. ZIP decompression has had a few issues, but they weren't too hard to fix.

**Comment by dolanmiu** [comment]
I will re-open if in the future if need be. But at the moment, it's a no for now

Thanks very much for your contribution though to this lib and open source in general though, I appreciate it.
