### ISSUE TITLE
No error is thrown when an Array of Arrays is passed to TableCell.children

### ISSUE THREAD

**Issue by taraskuzyk** [dolanmiu/docx#746]
Environment: MacOS 11.1, Node 12

```
const docx = require("docx")
const fs = require("fs")
const doc = new docx.Document();
const paragraphs = [new docx.Paragraph("Foo Bar")]

doc.addSection({
    children: [
        new docx.Table({
            rows: [
                new docx.TableRow({
                    children: [
                        new docx.TableCell({
                            // ERRONEOUS LINE BELOW
                            children: [paragraphs] // because of nesting the file becomes corrupted
                            // However, this runs without throwing any errors and produces a file
                        })
                    ]
                })
            ]
        })
    ]
})

docx.Packer.toBuffer(doc).then(buffer => {
    fs.writeFileSync("doc.docx", buffer)
});

```

Behaviour: The above code corrupts the resulting file. The issue is fixed by passing an array of DOCX objects instead of a nested array.

Expected behaviour: Some sort of type checking throws an error to the user when a wrong type of object is passed.

**Comment by dolanmiu** [comment]
There is type checking, this project uses TypeScript

It works fine for me. Gives me errors as intended.

![Screenshot 2021-01-06 at 18 11 30](https://user-images.githubusercontent.com/2917613/103804867-a6bae400-504a-11eb-9f29-a5574def61bb.png)

![Screenshot 2021-01-06 at 18 11 40](https://user-images.githubusercontent.com/2917613/103804873-a884a780-504a-11eb-9b16-270dcb1e4ca1.png)
