### ISSUE TITLE
Widow/Orphan Control

### ISSUE THREAD

**Issue by deathg0d** [dolanmiu/docx#750]
This issue is related to https://github.com/dolanmiu/docx/pull/32

## 1. Keep Lines
This commit doesn't seem to be working for me. I am using the following code:
```
let paragraph = new Paragraph({
  style: HeadingLevel.HEADING_3,
  children: ...,
  keepLines: false
});
```

This is the resulting file:
![image](https://user-images.githubusercontent.com/2324523/104441698-205b5080-55bc-11eb-8c9a-433dce645ef4.png)

Which should instead look like the following with the "keep lines together" disabled in word:
![image](https://user-images.githubusercontent.com/2324523/104441770-3a952e80-55bc-11eb-91d7-4b14290f16d1.png)

## 2. Widow/Orphan control
This commit mentions widow/orphan control, but it doesn't seem to be implemented
![image](https://user-images.githubusercontent.com/2324523/104442024-98c21180-55bc-11eb-8a50-7e1446a98263.png)
As you can see, `widow/orphan control` is a separate function from `keep lines together` and `keep with next`. It would be great if this can be implemented too ([more info](https://support.microsoft.com/en-us/office/control-pagination-e9b3b005-cf62-41d0-afa2-24cfb223ab42)).

**Comment by dolanmiu** [comment]
I found the related documentation:

http://www.datypic.com/sc/ooxml/e-w_widowControl-1.html

It seems as if widow control is always turned on by default though

> By default, Word prevents the last line of a paragraph from appearing at the top or bottom of a page.

But it would be great to be able to toggle it i suppose

**Comment by dolanmiu** [comment]
Feature will be included in: https://github.com/dolanmiu/docx/pull/819
