### ISSUE TITLE
Add BidiVisual to change a table's direction

### ISSUE THREAD

**Issue by LironMat** [dolanmiu/docx#751]
In Word, there is an option too choose direction for a table: ltr/rtl.

![image](https://user-images.githubusercontent.com/34262761/104509041-caa19b00-55f1-11eb-8723-bc1de45b468e.png)

This feature is currently missing from docx.js

Its very easy to implement, needing only an empty element in TableProperties named BidiVisual to make a table go from right to left

**Comment by dolanmiu** [comment]
Sure, it sounds simple, will add

I have found the documentation for it:

https://c-rex.net/projects/samples/ooxml/e1/Part4/OOXML_P4_DOCX_bidiVisual_topic_ID0EOXIQ.html

**Comment by dolanmiu** [comment]
Will be included in:

https://github.com/dolanmiu/docx/pull/795

**Comment by typeoo** [comment]
Hi you work is very appreciated.
But it seems there is a problem with a paragraph that contains RTL and LTR words.  

see this screen: 

![Annotation 2024-06-03 230946](https://github.com/dolanmiu/docx/assets/66176156/75e7abe5-4fd9-4e4f-9ee4-a1809c539928)

The English word was flipped.

``
