### ISSUE TITLE
Basic example not working

### ISSUE THREAD

**Issue by tommykjensen** [dolanmiu/docx#754]
I cannot get the basic example

https://docx.js.org/#/?id=basic-usage

to work.

Can someone detail out how I should setup nodejs in order to be able to run this simple example as I get this error when trying to run the example exactly as on that page.

ERROR: 
 node index.js
(node:18640) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
D:\GitRepos\Angular\cv-creator\index.js:1
import * as fs from "fs";
^^^^^^

SyntaxError: Cannot use import statement outside a module

My package.json looks like this:

{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",

  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "docx": "^5.4.1"
  }
}

Node version: v12.19.0

**Comment by dolanmiu** [comment]
fs does not exist in a browser or Angular environment

Check out this Angular example:

https://stackblitz.com/edit/angular-afvxtz

**Comment by tommykjensen** [comment]
I was hoping for guidance regarding use of docx in nodejs not in Angular :-(

I ask about nodejs and you respond with an Angular example :-(

**Comment by dolanmiu** [comment]
Node example here:

https://runkit.com/dolanmiu/docx-demo1
