### ISSUE TITLE
[BUG] Creating dynamic hyperlinks causes 'Word found unreadable content'

### ISSUE THREAD

**Issue by FatmaAkram** [dolanmiu/docx#758]
when I create a dynamic hyperlink as following:
`new Paragraph({
  children: [
    new Hyperlink("www.test.com")
  ],
})`
and open the .docx file with word 
I get the error 
`Word found unreadable content . Do you want to recover the contents of this document? If you trust the source of this document, click Yes.`

**Comment by dolanmiu** [comment]
Follow this example, the syntax is wrong

Hyperlinks need to be defined at the very start, then word "eferences them, like a sort of "shortcut" per say:

https://github.com/dolanmiu/docx/blob/master/demo/35-hyperlinks.ts
