### ISSUE TITLE
integration big fix in index.js at line 2515

### ISSUE THREAD

**Issue by dlengenfelder** [dolanmiu/docx#761]
When integrating docx with hasura and svelte, there is an error that appears when hosting a webpage that uses docx.

If you change line 2515...

from
process.browser = true

to
process["browser"] = true

...the problem resolves itself.

We recommend this change to be made for the sake of our development and any future user's development with docx, svelte and hasura.

Thank you.

**Comment by dolanmiu** [comment]
Svelte is not supported

**Comment by dlengenfelder** [comment]
You do not have to support svelte.  We just need you to make a functionally equivalent, one-line modification that results in an easier development process on our end.

**Comment by dolanmiu** [comment]
Can you make a PR for this?

I am not sure what you mean by changing that particular line

`process.browser = true` is actually identical to `process["browser"] = true`
