### ISSUE TITLE
docx v5.5 breaks installation

### ISSUE THREAD

**Issue by elementalPRESS** [dolanmiu/docx#768]
Hi,

I really love docx and of course I was happy when I saw the update. So I tried to update from v5.4.1 to v5.5 but it gives me a huge list of error messages. It seems that interfaces have been changed. For example: `new TextRun('').break()`- the `break` seems to be new.

	protected numberConfig = {
		config: [
			{
				levels: [
					{
						level: 0,
						format: 'decimal',
						text: '%1',
						alignment: AlignmentType.START,
						style: {
							paragraph: {
								indent: { left: 720, hanging: 260 },
							},
						},
					},
					{
						level: 1,
						format: 'decimal',
						text: '%2',
						alignment: AlignmentType.START,
						style: {
							paragraph: {
								indent: { left: 1440, hanging: 260 },
							},
						},
					},
					{
						level: 2,
						format: 'decimal',
						text: '%3',
						alignment: AlignmentType.START,
						style: {
							paragraph: {
								indent: { left: 2160, hanging: 260 },
							},
						},
					},
				],
				reference: 'decimal-numbering-reference',
			},
		],
	};

	this.doc = new Document(
			{
				title: pageSettings.title || '',
				creator: pageSettings.creator || '',
				description: pageSettings.description || '',
				subject: pageSettings.subject || '',
				keywords: pageSettings.keywords || '',
				lastModifiedBy: pageSettings.lastModifiedBy || '',
				numbering: this.numberConfig,
			},
			{
				template: templateDocument,
			}
	);

It gives following error `The expected type comes from property 'numbering' which is declared here on type 'IPropertiesOptions'` Is there anywhere a documentation how it should look in the new version?

Is there anywhere a documentation about the changes? I'm a bit surprised, but I've learned (long time ago) that breaking changes will only be part of full versions, e.g. 6.xx. Maybe I'm wrong... However, a documentation on how to upgrade (migrate) would be very helpful.

Thx and best regards
Lars

**Comment by dolanmiu** [comment]
Yes, break() was actually an error, and wasn't migrated to the new declarative way. This addresses https://github.com/dolanmiu/docx/issues/704.

The way it was documented in the documentation is the correct way to do so:

https://docx.js.org/#/usage/text?id=break

**Comment by henry132109** [comment]
I guess it'll be more user-friendly to warn the user that 5.5 is not backward compatible with 5.x due to the change in .break()
Many of us don't expect a breaking change in a minor version update.

**Comment by dolanmiu** [comment]
@henry132109 sorry my mistake

I assumed since `.break()` was never documented in the documentation, people wouldn't use it

I will consider these things in future

**Comment by wodka** [comment]
this change also broke the rendering for us. :( updated now to have break passed in the constructor)
