### ISSUE TITLE
Test suggestion?

### ISSUE THREAD

**Issue by LorhanSohaky** [dolanmiu/docx#771]
I'm creating a wrapper for your project. To ensure its functioning, I am writing some tests. At the moment what I'm have problem is with image testing.

It seems to be generating different paths for the same image. Do you have any suggestions on how I can test?

![image](https://user-images.githubusercontent.com/16273730/107696771-20b93b00-6c91-11eb-89ac-5af49f809367.png)

For the tests I'm creating directly from your library and creating with my wrapper and comparing the base64 of each.

**Comment by dolanmiu** [comment]
You can try ignore the ID of the image, modify the ID before assertion, or find a way to spy + mock the ID response somehow

**Comment by LorhanSohaky** [comment]
I could not do it, but thanks
