### ISSUE TITLE
Hyperlinked Images

### ISSUE THREAD

**Issue by ashapir0** [dolanmiu/docx#773]
I can't seem to find any documentation or issues regarding attaching a hyperlink to an image. Has anyone had luck with that? Any help is much appreciated.

**Comment by dolanmiu** [comment]
To a url of an image? Or embedding an image into a document? 

What does this mean exactly

**Comment by ashapir0** [comment]
When you click on an image, it links you somewhere

**Comment by dolanmiu** [comment]
Thanks @ashapir0 

This feature is included in https://github.com/dolanmiu/docx/pull/784
