### ISSUE TITLE
header2 references in header-wrapper need to be removed.

### ISSUE THREAD

**Issue by formatically** [dolanmiu/docx#78]
In the header-wrapper file there are two classes, FirstPageHeaderWrapper and HeaderWrapper.  I added a "header2" property to the HeaderWrapper class that should be removed.  There is also a "get Header2() method that should be removed.  I added those when I was testing ways to add the "differentFirstPageHeader" feature but they are not used.   I forgot the clean that up before merging. 

Sorry about that!

**Comment by dolanmiu** [comment]
Can you make a PR to fix this before I release?

Thanks!

**Comment by formatically** [comment]
Yes!

**Comment by dolanmiu** [comment]
Merged
