### ISSUE TITLE
SectionType undefined

### ISSUE THREAD

**Issue by davidroettger** [dolanmiu/docx#790]
I try to set the SectionType of a section but always get „Cannot read property 'CONTINUOUS' of undefined“
Any ideas?

Imported it like:
`const { SectionType, Media, Document, Packer, Paragraph, TextRun } = docx;`

And set it like:
`  doc.addSection({
    properties: { type: SectionType.CONTINUOUS },
    children: [
      new Paragraph(image1),
      new Paragraph({
        children: [new TextRun(lotArtistName)],
      }),
    ],
  });`
  
  Thanks! 
  David

**Comment by dolanmiu** [comment]
Not released yet im afraid:

Roadmap for the next release: 

https://github.com/dolanmiu/docx/releases/tag/untagged-a895173c15b0d2fe14b5
