### ISSUE TITLE
TabStops, how to use .tab()? 

### ISSUE THREAD

**Issue by PatriciaJacob** [dolanmiu/docx#799]
Whenever I try to implement TabStops I can't get the .tab() to be recognised, how should I implement this? Example below of how I attempted. Has this been deprecated if so is there another way to accomplish this without using tables? 

new Paragraph({
            children: [new TextRun("Hey everyone"), new TextRun("11th November 1999").tab()],
            tabStops: [
                {
                    type: TabStopType.RIGHT,
                    position: TabStopPosition.MAX,
                },
            ],
        })

Thank you for all the great work on the library, it is really useful!

**Comment by dolanmiu** [comment]
Thank you for your kind words!

tab() is no longer supported, where did you see this example?

It should be like so:

https://docx.js.org/#/usage/tab-stops

An example of it being used is here:

https://github.com/dolanmiu/docx/blob/master/demo/10-my-cv.ts
