### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined when trying to use docx on Ionic3

### ISSUE THREAD

**Issue by ehammo** [dolanmiu/docx#80]
TypeError: Cannot read property 'prototype' of undefined when trying to use docx on Ionic3

```
import * as docx from 'docx';
let doc: any = new docx.Document();

```

**Comment by dolanmiu** [comment]
I need to look into this, I haven’t used ionic before

**Comment by dolanmiu** [comment]
As of 4.0.0, this should be fixed

**Comment by ehammo** [comment]
Updated to 4.0.0  but the issue remains.

**Comment by ehammo** [comment]
please re open it.
