### ISSUE TITLE
Modifying document layout header and footer

### ISSUE THREAD

**Issue by Vrx8** [dolanmiu/docx#801]
I am sure this is possible, I've read the source and documentation but cannot figure it out.
```javascript
doc.addSection({
	margins : {top: 0.42*cm, right: 0.97*cm, bottom: 0.46*cm, left: 0.32*cm},
	size: {width: 21.6*cm, height: 13.75*cm},
	children: docChild,
});			
```
In microsoft word, usually we can change it through Page Layout > Margins > Layout > Headers and footers > From edge > header and footer and I want to set both to zero. So far I managed to change the section size and margin but no luck with setting the header and footer height that takes up space. Thanks in advance.

**Comment by dolanmiu** [comment]
Yes, setting margins on header and footer arent supported yet

Will add to to-do!

**Comment by dolanmiu** [comment]
Discovered that it is possible with the current version, I have created an example:

https://github.com/dolanmiu/docx/blob/master/demo/59-header-footer-margins.ts
