### ISSUE TITLE
How to use in Lambda?

### ISSUE THREAD

**Issue by bishbashbosh123** [dolanmiu/docx#81]
Hi,
Just a question.
I'm porting some electron client side code over to Lambda cloud functions, but the two packers for docx seem to be to write out to a file (Lambda has a readonly file-system) or attach the doc to an Express response object. Is there any way to get the document as a Buffer? I can return it from my API if I can get it as a base64 string. 
I'm currently playing around with a mock Express response object and seeing if I can get the data back out of it. I might try a 'fs' mock next, but presumably the best thing to do would be to write my own packer?
Cheers!

**Comment by dolanmiu** [comment]
Never thought of that use case before, I can add that feature in, or you can make a PR.

Yes I would imagine it would be a Base64Packer or something which returns a base64 string

**Comment by dolanmiu** [comment]
This is done now and will be released in the next version

Now there is a `BufferPacker` which returns a `Buffer`, you can then do whatever you want with this buffer, including turning it to a string, sending it across, or even write that buffer into a file

**Comment by bishbashbosh123** [comment]
Sounds great! Thanks
