### ISSUE TITLE
Is it possible to read docx file as a 'Document'?

### ISSUE THREAD

**Issue by hydra1983** [dolanmiu/docx#811]
something like,

```typescript
import * as fs from "fs";
import { Reader, Document, Packer, Paragraph, TextRun } from "docx";

// Read document
const doc:Document = Reader.read('docx_file_path');
...
```

**Comment by dolanmiu** [comment]
Not possible no sorry

Currently out of scope for this project

The problem to tackle would be what would you do with the data after it is opened? How would the code look like? I have not got an answer for that
