### ISSUE TITLE
Rotate images

### ISSUE THREAD

**Issue by supervanya** [dolanmiu/docx#815]
I am embedding images into the document but I am noticing if the orientation of the jpeg image isn't correct. It is due to the EXIF metadata for orientation being something other than 1. 

Would it be possible to specify rotation when creating the media object within `drawingOptions`:

```js
const drawingOptions = {
  transformation: {
    rotate: {
      type: IMediaRotateType.Clockwise,
      value: 90,
    }
  }
}
Media.addImage(document, fileBuffer, actualWidth, actualHeight, drawingOptions)
```

**Comment by dolanmiu** [comment]
Gladly

Could you provide the associated documentation for this

Thanks

**Comment by dolanmiu** [comment]
Will be included in: https://github.com/dolanmiu/docx/pull/822

Thanks

**Comment by ivschukin** [comment]
small question: did you publish this change to npm? I'm not getting the updated code of #822.

**Comment by supervanya** [comment]
@ivschukin I don't think there was a release yet but if you really need this functionality you could try pointing your `package.json` to a specific commit instead:

```js
...
  "dependencies": {
    "docx": "https://github.com/dolanmiu/docx.git#9557015c6cef7bcae6e7d61b8b20dd0ac44c5b8d",
   }
...
```

You will also need to build the `docx` manually. I added a `postinstall` script to `package.json`:
```json
...
"scripts": {
  "postinstall": "cd ./node_modules/docx && yarn install && yarn build || rm -rf node_modules/ && cd ../..",
},
...
```

**Comment by dolanmiu** [comment]
i did not publish yet, its coming very soon though
