### ISSUE TITLE
Table of Figures

### ISSUE THREAD

**Issue by tduval** [dolanmiu/docx#818]
Hi,

I've tried to create a table of figures but I struggle with the caption text required.
Basically, I've done the following to declare the Table of Figure:
`new TableOfContents("Figure", {
            hyperlink: true,
            captionLabelIncludingNumbers: "FIGURE",
            stylesWithLevels: ["Legend"],
}),`

This TOC works well if I generate a document then manually create a figure caption with word after that.

My issue is how to create those caption figure fields in docxjs, I've seen something with SEQ fields required but I am unable to find anything related to the docxjs documentation on how to do it.

**Comment by rickgrana** [comment]
please refer to https://github.com/dolanmiu/docx/blob/master/demo/33-sequential-captions.ts

**Comment by tduval** [comment]
Thanks, it's exactly what I needed.
It might be good to include it to the documentation, I'll look on how to propose it.

**Comment by dolanmiu** [comment]
Thank you for the reply

If someone can make a PR to update the documentation, that would be great
