### ISSUE TITLE
[FR?] adding support to HTML input

### ISSUE THREAD

**Issue by mkikets99** [dolanmiu/docx#820]
I think than it can be hard to actually implement this...
Is there any option to insert html formatted string to document without getting tags (DOM-elements) as text, but as styles?

For example:
```html
<p>Test Question</p>
```
must be rendered as normal `Test Question` thing

or 
```html
<p><strong>Test&nbsp;</strong><u>Question&nbsp;</u><em>crear&nbsp;</em><em><u><strong>test</strong></u></em></p>
```
must be rendered as 
**Test** <ins>Question</ins> _crear_ <ins>_**test**_</ins>

**[Edit 1]:** btw `FR` here means `Feature Request`

**Comment by dolanmiu** [comment]
Sorry this is not possible with this library unfortunately and out of scope

There is already a library out there which does this:

https://github.com/nitin42/redocx

**Comment by mkikets99** [comment]
The problem with `redocx` is that it's can't be rendered in Browser, while this can. And there is even an issue about this.
Can you provide me some examples of rendering `redocx` in Browser?

**Comment by dolanmiu** [comment]
`redocx` is React right? And React works in the browser?

Sorry I am not familiar with `redocx` to help

**Comment by mkikets99** [comment]
> `redocx` is React right? And React works in the browser?

yes, but `redocx` use separate render method which blocks the stock React render method... in [this issue](https://github.com/nitin42/redocx/issues/23) everything is showed. this problem persist until 2017 :(
Here you have Packer which works even in browser variant with React, but i can't insert html inside of this document
