### ISSUE TITLE
style.xml is not applied to the table

### ISSUE THREAD

**Issue by tadmi** [dolanmiu/docx#823]
I try to apply styles.xml (extracted from docx) to a table generated by docxJS. My custom style is present in a final docx file, but not linked with target table.

I tested the demo example 25-table-xml-styles with ...assets/custom-styles.xml - and got a similar situation.
![image](https://user-images.githubusercontent.com/63556979/111120439-6614a500-857c-11eb-8357-356a128c3305.png)
![image](https://user-images.githubusercontent.com/63556979/111120766-d4f1fe00-857c-11eb-906c-e9fc72250c30.png)

Applied the style manually:
![image](https://user-images.githubusercontent.com/63556979/111121043-3619d180-857d-11eb-9cd7-9a5d74e2ba25.png)
![image](https://user-images.githubusercontent.com/63556979/111121129-5184dc80-857d-11eb-893e-6a9a79aa7853.png)

Although demo example 13-xml-styles works correctly (paragraph style).
![image](https://user-images.githubusercontent.com/63556979/111119922-c48d5380-857b-11eb-826e-6c3a59ebe449.png)
![image](https://user-images.githubusercontent.com/63556979/111120083-fbfc0000-857b-11eb-8e61-5d166cdd383d.png)

**Comment by dolanmiu** [comment]
Yes, this is currently not released yet, It will come in `6.0.0`
