### ISSUE TITLE
Overlaying a shape onto an image (missing Text Frame)

### ISSUE THREAD

**Issue by CathyCao-asus** [dolanmiu/docx#832]
Is there a way to draw a shape (ex. rectangle) on an image?

I was considering using the [Text Frame feature](https://docx.js.org/#/usage/text-frames) and overlapping the image behind the text, but it looks like this feature is not part of the most recent (5.5.0) release?

**Comment by dolanmiu** [comment]
yeah its not released yet, text frames will be part of `6.0.0`

**Comment by CathyCao-asus** [comment]
do you have a recommendation as to how to overlay a shape like a rectangle on top of an image with the existing functions?

**Comment by dolanmiu** [comment]
6.0.0 will be released soon, probably next week

docx cant make rectangles yet however, it will support Text Frames in 6.0.0, which is a rectangle
