### ISSUE TITLE
Edit metadata of an existing document

### ISSUE THREAD

**Issue by GreatEarl** [dolanmiu/docx#838]
Is it possible to edit metadata of an existing document? Or create a new document using docx package from the buffer?
For example:
1. In the Node env get the docx file content as a buffer
2. Find and edit some properties such as 'company', 'createdBy'
3. Save the document.
I need to change metadata on-the-fly. 
Thanks.

**Comment by dolanmiu** [comment]
Nope that is not possible im afraid, docx does not support reading existing documents
