### ISSUE TITLE
HEADING_4 has italics enabled by default

### ISSUE THREAD

**Issue by bkmalan** [dolanmiu/docx#839]
Hello,

This is an amazing library and thanks to the devs.

One problem i noticed is that `heading: HeadingLevel.HEADING_4` has italics enabled even though it is not specified.

**Comment by dolanmiu** [comment]
Hi, thanks for your compliments

It is not specified, that's true, but it is deliberate:

https://github.com/dolanmiu/docx/blob/master/src/file/styles/factory.ts#L84
