### ISSUE TITLE
docx v.6.0.0 -- using the table options and style.xml simultaneously

### ISSUE THREAD

**Issue by tadmi** [dolanmiu/docx#842]
Thank's for the release of DOCX v.6.

There is a problem when I apply together options and custom-style.xml to the table.
![2021-03-21_200849](https://user-images.githubusercontent.com/63556979/111919456-1a418e80-8a9b-11eb-87d1-741b0ef91509.jpg)

Word removes options on first launch.
In the image before and after the first run of the created file:
![2021-03-21_201105](https://user-images.githubusercontent.com/63556979/111919514-70aecd00-8a9b-11eb-8720-5d0ab569391a.jpg)

If you manually move the "w:tblStyle" tag to the first place before the first file launch, the options are not removed:
![2021-03-21_201427](https://user-images.githubusercontent.com/63556979/111919669-3c87dc00-8a9c-11eb-97ec-959ab074ab92.jpg)

Please change the order of adding tags to document.xml: 

let the tag "w:tblStyle" be the first one when using the table options and style.xml simultaneously.

**Comment by dolanmiu** [comment]
I will make this fix, but it works fine on my version of Word (MacOS)

Demo 25:

<img width="1192" alt="Screenshot 2021-03-22 at 05 42 02" src="https://user-images.githubusercontent.com/2917613/111945292-5bed2c00-8ad1-11eb-8325-6c2dc1888ae0.png">

If Word does indeed alter the Word document, when I try to close it, it should surely prompt me with a "Unsaved changes dialog"? But it does not do so

**Comment by dolanmiu** [comment]
I have made a PR, can you confirm if this branch fixes the issue?

Then I will release `6.0.1`

https://github.com/dolanmiu/docx/pull/844

**Comment by tadmi** [comment]
Yes, after the fix it works correctly:

applied to the table options and style from custom-style.xml are saved after the first opening of the file generated by docx.js.

**Comment by tadmi** [comment]
MS Word significantly transforms the internals of a docx file (generated by DOCX.JS) when first opened. And It does not offer to save the changes. 

It is possible to track changes using the extension for VS Code - [OOXML Viewer](https://marketplace.visualstudio.com/items?itemName=yuenm18.ooxml-viewer).

The image shows a fragment document.xml:
![2021-03-22_105941](https://user-images.githubusercontent.com/63556979/111959099-134c6780-8aff-11eb-8243-f01a18147017.jpg)

**Comment by dolanmiu** [comment]
I have applied the fix, will release `6.0.1` later today

Thanks for working with me through this
