### ISSUE TITLE
Module reference errors - docx v6.x

### ISSUE THREAD

**Issue by askoufis** [dolanmiu/docx#843]
Hi. When compiling my typescript project I get these two errors: 

```
node_modules/docx/build/file/document-wrapper.d.ts:2:24 - error TS2307: Cannot find module './footer' or its corresponding type declarations.

import { Footer } from "./footer";

------

node_modules/docx/build/file/paragraph/run/image-run.d.ts:5:42 - error TS2307: Cannot find module '/file/xml-components' or its corresponding type declarations.

5 import { IContext, IXmlableObject } from "/file/xml-components";
```

The first error is referring to [this](https://github.com/dolanmiu/docx/blob/master/src/file/document-wrapper.ts#L2). The `footer` file no longer exists.

The second error is referring to [this](https://github.com/dolanmiu/docx/blob/master/src/file/paragraph/run/image-run.ts#L7). Updating that line to `import { IContext, IXmlableObject } from "../../../file/xml-components";` seems to fix it.

It might help to run `tsc` as part of your lint step in order to catch these errors before release.

**Comment by dolanmiu** [comment]
Hi

This is fixed now

It seems like the demos still work even before the release (on my end anyway), so perhaps this does not require a patch release

**Comment by askoufis** [comment]
I don't think the issue is fixed with the first error. Your `build` step isn't generating a `index.d.ts` in the `file/footer` folder.

**Comment by askoufis** [comment]
Your demos most likely didn't pick up the footer thing because none of your demos import the `FooterWrapper` class, only the `Footer` type. I'm guessing it's an internal class.

**Comment by dolanmiu** [comment]
Correct, Footer is an internal type, only the FooterWrapper is (and should be) exposed

**Comment by askoufis** [comment]
Ah ok. I still think [this line](https://github.com/dolanmiu/docx/blob/master/src/file/document-wrapper.ts#L2) needs to be changed to [this](https://github.com/dolanmiu/docx/blob/master/src/file/footer-wrapper.ts#L5). Regardless of whether types are internal or not, running `tsc` resolves all the types, and so if something can't be resolved it fails.
