### ISSUE TITLE
Problem with options in docx v.6.0.0.

### ISSUE THREAD

**Issue by maximys781** [dolanmiu/docx#847]
In Mozilla I get error: **Uncaught TypeError: options is undefined**
If I add to  **const doc = new docx.Document();** this block:
`{
            creator: "Creator",
            title: "Title",
            subject: "Subject",
            description: "Description"
        },
        // No file properties
        {},
        // No sections
        [],
        [{
                name: "Subtitle",
                value: "Subtitle"
            },
            {
                name: "Address",
                value: "Address"
            },
        ]`
then I get this error: **Uncaught TypeError: options.sections is undefined**
_______________________________________________________________________________________________
In Google Chrome I get error: **Uncaught TypeError: Cannot read property 'creator' of undefined**
If I add to  **const doc = new docx.Document();** this block:
`{
            creator: "Creator",
            title: "Title",
            subject: "Subject",
            description: "Description"
        },
        // No file properties
        {},
        // No sections
        [],
        [{
                name: "Subtitle",
                value: "Subtitle"
            },
            {
                name: "Address",
                value: "Address"
            },
        ]`
then I get this error: **Uncaught TypeError: options.sections is not iterable**

on 5.5.0 there were no such problems

**Comment by dolanmiu** [comment]
Yes, `6.0.0` introduced a lot of breaking changes and features, including changing the way sections is added, now it is fully declarative

Please check the demos for examples how.

It now needs a `sections: []` array in document, rather than calling `.addSection`
