### ISSUE TITLE
Is it a joke?

### ISSUE THREAD

**Issue by crespowang** [dolanmiu/docx#848]
Found this on the site https://docx.js.org/#/?id=welcome. Not sure if it's a joke or something else? 
![image](https://user-images.githubusercontent.com/25573589/111973364-859a6780-8b52-11eb-8fc6-1f55244b32c8.png)

**Comment by dolanmiu** [comment]
Yes it is a joke

Do you like it?

Next time, if it is not an issue, please don't raise an issue, but rather open a ticket under discussions
