### ISSUE TITLE
Table with zero rows issue

### ISSUE THREAD

**Issue by anti-the-social** [dolanmiu/docx#856]
Hello, Dolan :) 

There is another thing that seems to be a bug.
About all element can be created with zero children and then filled with .addChildElement method, but the table is the only exception. 
1) Table does have "rows" which is interesting, while TableRow has children instead of cells (should we have children for Table as well?)
2) Table cannot be created with zero rows. The following code would give an error while I would think that it should not

p.s. according to deep documentation there is .addChildElement method on Table
https://docx.js.org/api/classes/table.html

```
const fs = require('fs');
const { Document, Packer, TextRun, TableCell, Paragraph, TableRow, Table} = require('docx');

const text = new TextRun({ text: 'Lovely text for lovely paragraph'})
const paragraph = new Paragraph({ children: [] })
const cell = new TableCell({children:[]})
const row = new TableRow({ children: [] })
const table = new Table({ rows: [] })

table.addChildElement(row)
row.addChildElement(cell)
cell.addChildElement(paragraph)
paragraph.addChildElement(text)

const doc = new Document({
  sections: [{
    children: [table]
  }],
});

// Used to export the file into a .docx file
Packer.toBuffer(doc).then((buffer) => {
    fs.writeFileSync("table.docx", buffer);
});
```

**Comment by dolanmiu** [comment]
Those methods will be deprecated soon, this was the old way of creating tables, refer to the demos on how to create declarative tables from v5 onwards

Regarding the table with zero rows, why would anyone want such table?

**Comment by anti-the-social** [comment]
First of all I'd count this as an inconsistency since other elements can be created with zero children.
Secondly, in my case, that is about recursive parsing of somewhat random html. 
I think, for such a recursive parsing solutions, methods that you are planning to depreciate are very clear and nice to keep. When you meet a table - you add a table and save a reference to it where you would add children if there are any. Similar approach kept for paragraphs/rows/cells. And ofc sections would be nice to be in the same way too.

**Comment by dolanmiu** [comment]
Closing as this no longer applies anymore
