### ISSUE TITLE
Empty file created.

### ISSUE THREAD

**Issue by ee0jmt** [dolanmiu/docx#88]
I am a first time user of docx.

I am using the simple usage example to create a docx fie.
Everything seems to run fine, no errors and the document is created, however it is empty.

I have also tried to create a pdf using the same example code, but no file is created.

Any idea whats going on

OS: Mint
Node: 8.10.0

**Comment by dolanmiu** [comment]
Can you show me your code?

**Comment by ee0jmt** [comment]
Hi, thanks for the response.

Other than wrapping it in a function, the code as been taken from the WiKi:

`const docx = require("docx");

internals.createDoc = function () {

    // Create document
    var doc = new docx.Document();

    // Add some content in the document
    var paragraph = new docx.Paragraph("Some cool text here.");
    // Add more text into the paragraph if you wish
    paragraph.addRun(new docx.TextRun("Lorem Ipsum Foo Bar"));
    doc.addParagraph(paragraph);

    // Used to export the file into a .docx file
    var exporter = new docx.LocalPacker(doc);

    // Or use the express packer to make the file downloadable.
    // res is express' Response object
    //var exporter = new docx.ExpressPacker(doc, res);

    exporter.pack("My First Document");
    // If you want to export it as a .pdf file instead
    //exporter.packPdf("My First Document");

    // done! A file called 'My First Document.docx'
    // will be in your file system if you used LocalPacker
    // Or it will start downloading if you are using Express

};
`

**Comment by dolanmiu** [comment]
Ok,

I suppose the example is pretty bad, I will update

Take a look at the demos here:

https://github.com/dolanmiu/docx/tree/master/demo

Demo 1 is a good starting point

**Comment by ee0jmt** [comment]
Hi dolanmiu. Sorry its taken a while to get back to you. I have it all working now thanks! I updated to the demo code, but I still had the same issue.

The problem was that I was calling process.exit(0) after creating the document. What I couldn't understand is that the docx file was being created, but it was empty. I'm not really sure what the problem is, but its working.

**Comment by dolanmiu** [comment]
Readme is much more improved

And Documentation is now finally available at http://docx.js.org
