### ISSUE TITLE
How to add an image from a buffer into a document?

### ISSUE THREAD

**Issue by madarche** [dolanmiu/docx#91]
Hello,

I'm using docx@3.6.0.

The code below returns `doc.createDrawing is not a function` : 

```javascript
const doc = new docx.Document();
const paragraph = new docx.Paragraph('Some text.');
paragraph.addRun(new docx.TextRun('Some text run.'));
doc.addParagraph(paragraph);
const buff = fs.readFileSync('/tmp/w3c_home.png');
const image_data = doc.createImageData('Dummy dummy', buff);
doc.createDrawing(image_data);
```

What am I doing wrong?

**Comment by madarche** [comment]
Maybe related to #89

**Comment by dolanmiu** [comment]
Can you try this?

https://github.com/dolanmiu/docx/blob/feat/base64-image/demo/demo18.js

**Comment by dolanmiu** [comment]
Yes, I am in the process of remaking the API, i agree it is a bit convoluted

**Comment by madarche** [comment]
Thanks a lot for your answer and your package!
