### ISSUE TITLE
how to edit w:overflowPunct element?

### ISSUE THREAD

**Issue by zackzergzeng** [dolanmiu/docx#916]
hello,

i need this to forbidden hanging punctuation
![image](https://user-images.githubusercontent.com/42129897/116343298-bedf8a80-a816-11eb-826e-07830b340787.png)

**Comment by dolanmiu** [comment]
Documentation:

http://www.datypic.com/sc/ooxml/e-w_overflowPunct-1.html
https://c-rex.net/projects/samples/ooxml/e1/Part4/OOXML_P4_DOCX_overflowPunct_topic_ID0E51CM.html

Will add
