### ISSUE TITLE
Numbering start from number doesn't work

### ISSUE THREAD

**Issue by anti-the-social** [dolanmiu/docx#925]
My greetings :) 
This list men to to start from 50, but it does not. Do I do something wrong or feature got corrupted?
Tested on 6.0.1, 6.0.3
Based on: https://github.com/dolanmiu/docx/blob/7acd9e1/src/file/numbering/level.ts#L89
![image](https://user-images.githubusercontent.com/69673750/116698936-a665a080-a9cd-11eb-8d4d-05168c046e95.png)

```
const fs = require('fs');
const { Document, Packer, Paragraph, PageNumberFormat} = require('docx');

const doc = new Document({
  numbering:{
    config:[{
      reference: 'ref1',
      levels: [
        {
          level: 0,
          format: PageNumberFormat.DECIMAL,
          text: '%1)',
          start: 50,
        }
      ],
    }]
  },
  sections: [{
    children: [
      new Paragraph({
        text: "REF1 - inst:0 - lvl:0",
        numbering : {
          reference: 'ref1',
          instance: 0,
          level: 0,
        }
      }),
      new Paragraph({
        text: "REF1 - inst:0 - lvl:0",
        numbering : {
          reference: 'ref1',
          instance: 0,
          level: 0,
        }
      }),
      new Paragraph({
        text: "REF1 - inst:0 - lvl:0",
        numbering : {
          reference: 'ref1',
          instance: 0,
          level: 0,
        }
      }),
    ],
  }]
});

// Used to export the file into a .docx file
Packer.toBuffer(doc).then((buffer) => {
    fs.writeFileSync("start_numbering.docx", buffer);
});
```

**Comment by tiejunhu** [comment]
I encountered same issue. I dig some and found the w:start is properly set but got overrided by this : https://github.com/dolanmiu/docx/blob/9048f8f2713a88c96a49a477e89051ae27724079/src/file/numbering/numbering.ts#L201

The generated docx file reflected the same obversation.

it seems not reasonable to override the numbering.

@dolanmiu would you check why there's an override ?

**Comment by tiejunhu** [comment]
I tried a hack way to remove the overrideLevel section from Numbering.concreteNumberingMap before export the generated docx to Parker. The exported docx now has proper list numbering. I also compared it with a docx file created by Microsoft Word, the numbering.xml are identical.

**Comment by dolanmiu** [comment]
Thanks for all this research

Looking into it now

@tiejunhu could you explain what this does? Does it simply re-create the concrete numbering without the override?

**Comment by dolanmiu** [comment]
@tiejunhu I added the overrides otherwise Restarting numbering wouldn't work:

https://github.com/dolanmiu/docx/pull/816

**Comment by dolanmiu** [comment]
so it seems to me that overrides must be conditional, and is required when the user wants to restart numbered lists, but shouldn't be included by default

**Comment by tiejunhu** [comment]
> Thanks for all this research
> 
> Looking into it now
> 
> @tiejunhu could you explain what this does? Does it simply re-create the concrete numbering without the override?

Because you call the createConcreteNumberingInstance during prepForXml here:  

https://github.com/dolanmiu/docx/blob/0f55d70a19b2ea3fc761c3854d0d95e9e1f27284/src/file/paragraph/properties.ts#L177

Which leads to create overriding numbering from 1.

So what I did is pre-create all the concreteNumberingInstances (to concreteNumberingMap) without the number overriding. Then when the prepForXml runs, it's already in the map and won't be created again.

**Comment by tiejunhu** [comment]
> so it seems to me that overrides must be conditional, and is required when the user wants to restart numbered lists, but shouldn't be included by default

I believe that would be a proper fix.

**Comment by tiejunhu** [comment]
I found another issue regarding this. The generated Docx won't restart the numbering when two ConcreteNumbering instances are sharing same AbstractNumbering even with the overrideLevel instruction. 

I have to create two abstract numbering for the two numbering list regardless they have the same style settings.

**Comment by dolanmiu** [comment]
interesting.

How would you suggest to fix this?

**Comment by tiejunhu** [comment]
> interesting.
> 
> How would you suggest to fix this?

Currently, I create different abstractNumbering for all numbering that's not started from 1

**Comment by anti-the-social** [comment]
I believe taking level.start for overrideLevel.start, when possible, would work well as a fix:
https://github.com/dolanmiu/docx/pull/1057

**Comment by anti-the-social** [comment]
While thinking of implementing testing of that case, came into conclusion that .spec.ts way is not applicable (unfortunately) since the numbering happens on the Word side. I've added some demo into pull request instead.

**Comment by anti-the-social** [comment]
I would close the issue, since the first stated problem solved by merged https://github.com/dolanmiu/docx/pull/1057 
@tiejunhu I think it worth opening new issue if your problem persists. Or you can reopen if you like..

**Comment by TheDarkStrix** [comment]
@anti-the-social @dolanmiu 
I was hoping you guys could help me out with this.
``` javascript 

 new Paragraph({
                  children: [
                    new TextRun({
                      text: sanitizeData(array[j]),
                    }),
                  ],
                  numbering: {
                    reference: "questionNumbers",
                    level: 0,
                    instance: totalQuestions,
                  },
                })
```
The for loop (loops for 3 times) : its values are 10 , 5 , 5 respectively.
Note : Instance value will change (depending of the iteration - for loop )

Current Output:
Section A
1. text
2. text
...
10. text
Section B
1. text  // <-- the number was reset 
2. text
...
5. text
Section C
6. text // <-- this number is not reset here (i want this start from 1)
7. text
8. text
9. text
10. text

Any help is very much appreciated

**Comment by anti-the-social** [comment]
@TheDarkStrix Can you create some easy example for me to run to illustrate the problem? (Just like I did in the issue description)
This way it would be a little easier to understand what exactly doesn't work.
