### ISSUE TITLE
table - set border width, style, color

### ISSUE THREAD

**Issue by qyloxe** [dolanmiu/docx#93]
Excellent library!

Is this possible to set those attributes for the whole table (or individual cells)?

I haven't found anything in the demos, but in library source code, those attributes are handled but only as defaults. I wonder if I could change them after table creation. And if yes, then how?

**Comment by Michael-Huang-9001** [comment]
You can probably do something like this:

table.getCell(x, y).cellProperties.setWidth(20000);
table.getCell(x, y).addContent(new docx.Paragraph().style({whatever you want `here}));`

You can also add a TextRun to that paragraph instead if you want stuff like font, bold, etc.

**Comment by qyloxe** [comment]
Hmm, I meant border styles, sorry...

So instead of this:

![obraz](https://user-images.githubusercontent.com/467508/42468423-34f31662-83b5-11e8-8d62-c2dfe4ac3517.png)

I would like to generate something like this:

![obraz](https://user-images.githubusercontent.com/467508/42468499-62a9259c-83b5-11e8-9684-1b27fafa5bd7.png)

**Comment by qyloxe** [comment]
OK, it is possible - thanks @Michael-Huang-9001 for inspiration.

For example, if somebody wants to clear borders here is the code:

```
  setClearBorder (table, x, y) {
    var cc = table.getCell(x, y)
    var cp = cc.cellProperties
    cp.borders.addBottomBorder('none',0,'FFFFFF')
    cp.borders.addEndBorder('none',0,'FFFFFF')
    cp.borders.addStartBorder('none',0,'FFFFFF')
    cp.borders.addTopBorder('none',0,'FFFFFF')
  }


```

**Comment by dolanmiu** [comment]
Ah @qyloxe! I did not see your comment so I also wrote an example:

```
var doc = new docx.Document();

const table = doc.createTable(4, 4);
table
    .getCell(2, 2)
    .addContent(new docx.Paragraph("Hello"))
    .cellProperties.borders.addTopBorder(docx.BorderStyle.DASH_DOT_STROKED, 3, "red")
    .addBottomBorder(docx.BorderStyle.DOUBLE, 3, "blue")
    .addStartBorder(docx.BorderStyle.DOT_DOT_DASH, 3, "green")
    .addEndBorder(docx.BorderStyle.DOT_DOT_DASH, 3, "#ff8000");

var exporter = new docx.LocalPacker(doc);
exporter.pack("My Document");
```

I will most likely change the API to conform to how the rest of the library is like in the next major version

```
cell.Properties
```

rather than:

```
cell.cellProperties
```

etc.

**Comment by dolanmiu** [comment]
This is now a feature!

Check out: https://github.com/dolanmiu/docx/blob/master/demo/demo20.ts
