### ISSUE TITLE
readFileSync is not a function

### ISSUE THREAD

**Issue by hugoebarboza** [dolanmiu/docx#945]
When I am trying to use data: fs.readFileSync("./demo/images/pizza.gif") in Angular I get error message "readFileSync is not a function"

# Thank you for raising an issue to `docx`

Please do not raise an issue unless it is an **issue**.

-   Is your issue a feature request? Are you giving ideas to the community? Are you asking for help? Please raise a ticket in the `Discussions` section:

    https://github.com/dolanmiu/docx/discussions

-   Is your issue a previously asked? Please respond to that thread instead

**Comment by devoidfury** [comment]
`fs.readFileSync` is a nodejs function. It doesn't work in the browser.

If you're trying to load an image in the browser, one way to do it is:

```js
export async function urlToBlob(url) {
  return (await fetch(url)).blob();
}

async function generate() {
  // ...
  new ImageRun({
    data: await urlToBlob(url_of_image),
    // ...
  })
  //
}
```

**Comment by dolanmiu** [comment]
Try the browser demos

Here is one for Angular:

https://stackblitz.com/edit/angular-docx

**Comment by hugoebarboza** [comment]
Hi @dolanmiu in stackblitz will be useful a demo with image implementation.

**Comment by hugoebarboza** [comment]
Hello @devoidfury and @dolanmiu, I have another issue in line  data: await urlToBlob(url_of_image),

"Promise is not assignable to type string Buffer ArrayBuffer"

![image](https://user-images.githubusercontent.com/39523704/119023778-5a749e80-b970-11eb-9f20-df9f2f580ec6.png)

Sincerely,
Hugo

**Comment by dolanmiu** [comment]
docx in stackblitz with images in React:

https://stackblitz.com/edit/react-docx-images

In angular, it would be similar

**Comment by dolanmiu** [comment]
Show me your full code with `urlToBlob`, 

I cant figure out what you are trying to do

**Comment by hugoebarboza** [comment]
Thank you all, the react example helped me a lot.

**Comment by hugoebarboza** [comment]
Hello @dolanmiu, Is there a way to use this library to export Excel and PDF docs ?

**Comment by devoidfury** [comment]
No, it only does docx.

**Comment by hugoebarboza** [comment]
Hi, is there a way to make an array of TableRow ? 

I have this, but it doesn't work. 

Variable imageRows = it is array of TableCell.

 const row = new TableRow({ children: imageRows });
 tablerow.push(row);
 return new Table({rows: [tablerow]});
