### ISSUE TITLE
Table left indentation feature request

### ISSUE THREAD

**Issue by anti-the-social** [dolanmiu/docx#954]
Hello!

I tried to create left indentation for the table via docx library, but didn't manage too. I think feature is missing, but tell me if I am wrong.
This is how word implements this kind of indentation ("Indent from left"):
![image](https://user-images.githubusercontent.com/69673750/119102749-0bd40c80-ba23-11eb-81f3-b307e8ffd10a.png)
![image](https://user-images.githubusercontent.com/69673750/119102645-eb0bb700-ba22-11eb-8ed3-a1eb493319af.png)
I used to try to implement some kind indentation using float table parameter, but then table overlapping and such kind of things does break page's outlook.

**Comment by dolanmiu** [comment]
I believe this is a feature yes

there is an alignment property on the table, just set that to `LEFT`:

```ts
const table = new Table({
    columnWidths: [3505, 5505],
    alignment: AlignmentType.LEFT,
    rows: [],
```

**Comment by devoidfury** [comment]
These margins options are for adding cell margins to the entire table. There's a separate element to add inside `w:tblPr` named `w:tblInd` for this feature. It's been added to my v7 prep branch, in commit dd6d1bc.
