### ISSUE TITLE
Is it possible to import docx not only dotx?

### ISSUE THREAD

**Issue by hydra1983** [dolanmiu/docx#969]
As I want to manipulate the imported docx file, such as insert new content, so better to import an existing docx file directly.

**Comment by dolanmiu** [comment]
Sorry, not possible im afraid

There is a library here called docx templater which is maybe what you need:
https://github.com/open-xml-templating/docxtemplater

**Comment by abubelinha** [comment]
@dolanmiu would you have a _dotx_ example of multiple labels being filled in [like described here](https://github.com/open-xml-templating/docxtemplater/issues/708)?

Thanks
@abubelinha

**Comment by dolanmiu** [comment]
> @dolanmiu would you have a _dotx_ example of multiple labels being filled in [like described here](https://github.com/open-xml-templating/docxtemplater/issues/708)?
> 
> Thanks @abubelinha

`docx` now has this feature out of the box! As of `v8.0.0`:

https://github.com/dolanmiu/docx/blob/master/demo/85-template-document.ts

This library can now read and write docx files.
