### ISSUE TITLE
Can't adjust document's size in Properties in document's secsion

### ISSUE THREAD

**Issue by biggywk** [dolanmiu/docx#973]
const doc = new Document({
    sections: [{
        properties: { page: { size: { width: 100, orientation: PageOrientation.LANDSCAPE } } },
        children: <....>
    }]
});

**### can't set width and height but orientation work nicely**

# Thank you for raising an issue to `docx`

Please do not raise an issue unless it is an **issue**.

-   Is your issue a feature request? Are you giving ideas to the community? Are you asking for help? Please raise a ticket in the `Discussions` section:

    https://github.com/dolanmiu/docx/discussions

-   Is your issue a previously asked? Please respond to that thread instead

**Comment by dolanmiu** [comment]
100 is too small, it uses TWIP as units, try something bigger
